/**
 * words/tier5-expansion.ts
 *
 * Tier 5 expansion: additional competition-level words (difficulty 9-10).
 * All definitions verified against Free Dictionary API (Wiktionary, CC-BY-SA).
 * Etymology, pronunciation guides, distractors, and themes enriched by AI.
 *
 * Attribution: Definitions reference Wiktionary (CC-BY-SA 3.0).
 */
import type { SpellingWord } from './types';

export const TIER_5_EXPANSION_WORDS: SpellingWord[] = [
    // ── Greek-origin competition words ────────────────────────────────────
    {
        word: 'epistaxis',
        definition: 'Bleeding from the nose; a nosebleed.',
        exampleSentence: 'The dry winter air caused frequent epistaxis among the students.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'ep-ih-STAK-sis',
        etymology: 'Greek: epistazein (to drip upon), from epi (upon) + stazein (to drip)',
        distractors: ['epistaxes', 'epistaxsis', 'episitaxis'],
        theme: 'health',
    },
    {
        word: 'heterodox',
        definition: 'Not conforming to accepted or orthodox standards or beliefs.',
        exampleSentence: 'His heterodox views on economics challenged the established theories.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'HET-er-uh-doks',
        etymology: 'Greek: heterodoxos (of another opinion), from heteros (other) + doxa (opinion)',
        distractors: ['heterodocks', 'heteradox', 'hetrodox'],
        theme: 'mind',
    },
    {
        word: 'homoeopathy',
        definition: 'A system of alternative medicine based on the principle of treating like with like.',
        exampleSentence: 'She explored homoeopathy as a complementary approach to her treatment.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'hoh-mee-OP-uh-thee',
        etymology: 'Greek: homoios (like, similar) + pathos (suffering, disease)',
        distractors: ['homoepathy', 'homeopothy', 'homoeopathey'],
        theme: 'health',
    },
    {
        word: 'ichthyology',
        definition: 'The branch of zoology that studies fish.',
        exampleSentence: 'Her passion for ichthyology led her to study coral reef ecosystems.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'ik-thee-OL-uh-jee',
        etymology: 'Greek: ichthys (fish) + logos (study)',
        distractors: ['icthyology', 'ichthiology', 'ichthyollogy'],
        theme: 'academic',
    },
    {
        word: 'lycanthropy',
        definition: 'The mythical transformation of a person into a wolf; werewolfism.',
        exampleSentence: 'Tales of lycanthropy have appeared in folklore across many cultures.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'ly-KAN-thruh-pee',
        etymology: 'Greek: lykanthropos (wolf-man), from lykos (wolf) + anthropos (human)',
        distractors: ['lycanthrapy', 'licanthropy', 'lycanthropi'],
        theme: 'nature',
    },
    {
        word: 'mycelium',
        definition: 'The mass of branching, thread-like filaments that form the main body of a fungus.',
        exampleSentence: 'The mycelium spread beneath the forest floor, connecting the tree roots.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'my-SEE-lee-um',
        etymology: 'Greek: mykes (fungus) + helos (nail, stud)',
        distractors: ['myceleum', 'mycellium', 'myscelium'],
        theme: 'plants',
    },
    {
        word: 'necropolis',
        definition: 'A large, elaborate ancient cemetery or burial ground.',
        exampleSentence: 'Archaeologists discovered a vast necropolis beneath the modern city.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'neh-KROP-uh-lis',
        etymology: 'Greek: nekropolis (city of the dead), from nekros (dead) + polis (city)',
        distractors: ['necropoles', 'necrapolis', 'necropilis'],
        theme: 'earth',
    },
    {
        word: 'pharmacopoeia',
        definition: 'An official publication listing medicinal drugs with their effects and directions for use.',
        exampleSentence: 'The pharmacopoeia was updated to include newly approved medications.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'far-muh-kuh-PEE-uh',
        etymology: 'Greek: pharmakopoiia (drug-making), from pharmakon (drug) + poiein (to make)',
        distractors: ['pharmacopeia', 'pharmacopea', 'pharmacopoea'],
        theme: 'health',
    },
    {
        word: 'prosthesis',
        definition: 'An artificial body part, such as a limb, tooth, or eye.',
        exampleSentence: 'The advanced prosthesis allowed the athlete to compete again.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'PROS-thee-sis',
        etymology: 'Greek: prosthesis (addition), from pros (to) + tithenai (to place)',
        distractors: ['prosthisis', 'prosthecis', 'prosthasis'],
        theme: 'body',
    },
    {
        word: 'pseudepigrapha',
        definition: 'Writings falsely attributed to notable authors, especially biblical texts.',
        exampleSentence: 'The pseudepigrapha were excluded from the official biblical canon.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'soo-deh-PIG-ruh-fuh',
        etymology: 'Greek: pseudepigraphos (falsely inscribed), from pseudos (false) + epigraphein (to inscribe)',
        distractors: ['pseudopigrapha', 'pseudepegrapha', 'psuedepigrapha'],
        theme: 'language',
    },
    {
        word: 'ptarmigan',
        definition: 'A northern grouse with feathered feet and plumage that turns white in winter.',
        exampleSentence: 'The ptarmigan turned white to blend in with the snowy landscape.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'irregular',
        pronunciation: 'TAR-mih-gun',
        etymology: 'Scottish Gaelic: tarmachan; silent P added by false association with Greek pteron (wing)',
        distractors: ['tarmigan', 'ptarmagen', 'ptarmigon'],
        theme: 'animals',
    },
    {
        word: 'rheumatism',
        definition: 'A condition causing inflammation and pain in the joints, muscles, or connective tissue.',
        exampleSentence: 'Cold, damp weather often worsened her rheumatism.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'ROO-muh-tiz-um',
        etymology: 'Greek: rheuma (stream, flow), from rhein (to flow)',
        distractors: ['rhumatism', 'rheumatizm', 'rhuematism'],
        theme: 'health',
    },
    {
        word: 'schizophrenia',
        definition: 'A chronic mental disorder involving distorted thinking, hallucinations, and withdrawal from reality.',
        exampleSentence: 'Advances in treatment have greatly improved outcomes for people with schizophrenia.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'skit-soh-FREN-ee-uh',
        etymology: 'Greek: skhizein (to split) + phren (mind)',
        distractors: ['schizofrenia', 'schitzophrenia', 'skizophrenia'],
        theme: 'health',
    },
    {
        word: 'anemone',
        definition: 'A plant of the buttercup family with brightly colored flowers, or a sea creature resembling one.',
        exampleSentence: 'The garden was filled with purple and white anemones in early spring.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'uh-NEM-uh-nee',
        etymology: 'Greek: anemone (windflower), from anemos (wind)',
        distractors: ['anenome', 'anemonie', 'annemone'],
        theme: 'plants',
    },
    {
        word: 'archetype',
        definition: 'A very typical example of a certain person or thing; an original model.',
        exampleSentence: 'The hero is one of the most common archetypes in world literature.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'AR-kih-type',
        etymology: 'Greek: arkhetypon (original pattern), from arkhe (beginning) + typos (stamp, model)',
        distractors: ['archytype', 'archatype', 'architype'],
        theme: 'academic',
    },
    {
        word: 'blasphemy',
        definition: 'The act of speaking disrespectfully about God or sacred things.',
        exampleSentence: 'In many historical societies, blasphemy was punishable by law.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'BLAS-fuh-mee',
        etymology: 'Greek: blasphemia (evil-speaking), from blaptein (to injure) + pheme (speech)',
        distractors: ['blasfemy', 'blashpemy', 'blasphamy'],
        theme: 'society',
    },
    {
        word: 'dialectic',
        definition: 'The art of investigating the truth through logical discussion and reasoning.',
        exampleSentence: 'Socrates used dialectic to challenge his students\' assumptions.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'dy-uh-LEK-tik',
        etymology: 'Greek: dialektike (the art of debate), from dialegesthai (to converse)',
        distractors: ['dialectik', 'dialecic', 'dielactic'],
        theme: 'academic',
    },
    {
        word: 'heresy',
        definition: 'A belief or opinion that goes against established religious or political doctrine.',
        exampleSentence: 'Galileo was accused of heresy for supporting the heliocentric model.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'HER-uh-see',
        etymology: 'Greek: hairesis (choice, sect), from hairein (to choose)',
        distractors: ['herasy', 'heressy', 'heresey'],
        theme: 'society',
    },
    {
        word: 'onyx',
        definition: 'A semiprecious gemstone with bands of alternating colors, typically black and white.',
        exampleSentence: 'The ring featured a polished onyx stone set in silver.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'ON-iks',
        etymology: 'Greek: onyx (claw, nail), from the stone\'s resemblance to a fingernail',
        distractors: ['onix', 'onnyx', 'onycks'],
        theme: 'earth',
    },
    {
        word: 'pariah',
        definition: 'A person who is rejected or avoided by others; an outcast.',
        exampleSentence: 'After the scandal, the politician became a pariah in his own party.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'irregular',
        pronunciation: 'puh-RY-uh',
        etymology: 'Tamil: paraiyar (hereditary drummers), a social group in southern India',
        distractors: ['parria', 'paria', 'pareah'],
        theme: 'people',
    },
    {
        word: 'polemic',
        definition: 'A strong verbal or written attack on someone or something; a controversial argument.',
        exampleSentence: 'The editorial was a fierce polemic against government corruption.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'puh-LEM-ik',
        etymology: 'Greek: polemikos (warlike), from polemos (war)',
        distractors: ['polemick', 'poleimc', 'pollemic'],
        theme: 'communication',
    },
    {
        word: 'talisman',
        definition: 'An object believed to have magical powers and bring good luck.',
        exampleSentence: 'The explorer carried a talisman for protection on dangerous journeys.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'irregular',
        pronunciation: 'TAL-is-mun',
        etymology: 'Arabic: tilsam (magical image), from Greek: telesma (consecrated object)',
        distractors: ['talismon', 'tallisman', 'talismen'],
        theme: 'everyday',
    },
    {
        word: 'catechism',
        definition: 'A summary of religious doctrine in the form of questions and answers, used for teaching.',
        exampleSentence: 'The children studied the catechism every Sunday morning.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'KAT-uh-kiz-um',
        etymology: 'Greek: katechismos (instruction), from katechein (to teach orally)',
        distractors: ['catechizm', 'catachism', 'catechesm'],
        theme: 'academic',
    },
    {
        word: 'dichotomy',
        definition: 'A division or contrast between two things that are presented as opposites.',
        exampleSentence: 'There is a clear dichotomy between the rich and poor in that city.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'dy-KOT-uh-mee',
        etymology: 'Greek: dikhotomia (cutting in two), from dikha (in two) + temnein (to cut)',
        distractors: ['dichotamy', 'dicotomy', 'dichotomey'],
        theme: 'academic',
    },
    {
        word: 'idolatry',
        definition: 'The worship of idols or excessive devotion to something.',
        exampleSentence: 'The ancient civilization practiced idolatry, building shrines to stone figures.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'eye-DOL-uh-tree',
        etymology: 'Greek: eidololatria (worship of idols), from eidolon (image) + latreia (worship)',
        distractors: ['idolatrey', 'idolitry', 'idolatri'],
        theme: 'society',
    },
    {
        word: 'panacea',
        definition: 'A solution or remedy for all difficulties or diseases.',
        exampleSentence: 'There is no panacea for the complex problems facing education today.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'pan-uh-SEE-uh',
        etymology: 'Greek: panakeia (cure-all), from pan (all) + akos (cure)',
        distractors: ['panacaea', 'panaciea', 'panncea'],
        theme: 'health',
    },
    {
        word: 'plethysmograph',
        definition: 'An instrument for measuring changes in volume in a body part, usually reflecting blood flow.',
        exampleSentence: 'The doctor used a plethysmograph to measure blood flow in the patient\'s finger.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'pluh-THIZ-muh-graf',
        etymology: 'Greek: plethysmos (increase) + graphein (to write)',
        distractors: ['plethismograph', 'plethysmograf', 'plethesmograph'],
        theme: 'health',
    },
    {
        word: 'pyrrhic',
        definition: 'Won at too great a cost to have been worthwhile for the victor.',
        exampleSentence: 'The battle was a pyrrhic victory, as the army lost most of its soldiers.',
        partOfSpeech: 'adjective',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'PIR-ik',
        etymology: 'Greek: Pyrrhikos, after King Pyrrhus of Epirus, whose costly victories inspired the term',
        distractors: ['pyrric', 'pirhic', 'pyrhic'],
        theme: 'society',
    },
    {
        word: 'aphorism',
        definition: 'A pithy observation that contains a general truth, like a proverb.',
        exampleSentence: '"Actions speak louder than words" is a well-known aphorism.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'AF-uh-riz-um',
        etymology: 'Greek: aphorismos (definition), from aphorizein (to define)',
        distractors: ['aphoriszm', 'aphorisim', 'aforism'],
        theme: 'language',
    },
    {
        word: 'dystopia',
        definition: 'An imagined place or state where everything is unpleasant or oppressive.',
        exampleSentence: 'The novel portrayed a dystopia where citizens had no freedom of speech.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'dis-TOH-pee-uh',
        etymology: 'Greek: dys (bad) + topos (place), coined as opposite of utopia',
        distractors: ['distopia', 'dystopea', 'disttopia'],
        theme: 'society',
    },
    {
        word: 'gnosis',
        definition: 'Knowledge of spiritual mysteries; esoteric or intuitive knowledge.',
        exampleSentence: 'The ancient sect believed gnosis was the path to enlightenment.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'NOH-sis',
        etymology: 'Greek: gnosis (knowledge, inquiry), from gignoskein (to know)',
        distractors: ['nosis', 'gnoesis', 'gnoses'],
        theme: 'mind',
    },
    {
        word: 'miasma',
        definition: 'An unpleasant or unhealthy smell or atmosphere; a pervasive influence.',
        exampleSentence: 'A miasma of decay hung over the abandoned building.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'my-AZ-muh',
        etymology: 'Greek: miasma (pollution, defilement), from miainein (to pollute)',
        distractors: ['miazma', 'miasama', 'maisma'],
        theme: 'sensory',
    },
    {
        word: 'ostracism',
        definition: 'Exclusion from a society or group; banishment.',
        exampleSentence: 'Social ostracism can be as painful as physical punishment.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'OS-truh-siz-um',
        etymology: 'Greek: ostrakismos (banishment by vote), from ostrakon (potsherd used as ballot)',
        distractors: ['ostracizm', 'ostrasism', 'ostrecism'],
        theme: 'society',
    },
    {
        word: 'pathos',
        definition: 'A quality that evokes pity, sadness, or compassion.',
        exampleSentence: 'The film\'s final scene was filled with genuine pathos.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'PAY-thos',
        etymology: 'Greek: pathos (suffering, experience, emotion)',
        distractors: ['pathoss', 'paythos', 'pathoes'],
        theme: 'feelings',
    },
    {
        word: 'plinth',
        definition: 'A heavy base supporting a statue, vase, or column.',
        exampleSentence: 'The marble statue stood on a granite plinth in the museum lobby.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'PLINTH',
        etymology: 'Greek: plinthos (brick, squared stone)',
        distractors: ['plynth', 'plinnth', 'plith'],
        theme: 'art',
    },
    {
        word: 'rhapsody',
        definition: 'An enthusiastic or ecstatic expression of feeling, or an instrumental composition of irregular form.',
        exampleSentence: 'The pianist performed Gershwin\'s Rhapsody in Blue to a standing ovation.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'RAP-suh-dee',
        etymology: 'Greek: rhapsodia (recitation of epic poetry), from rhaptein (to stitch) + oide (song)',
        distractors: ['rapsody', 'rhapsodi', 'rhapsodey'],
        theme: 'art',
    },
    {
        word: 'theorem',
        definition: 'A general proposition that can be proved by a chain of reasoning; a mathematical truth.',
        exampleSentence: 'The Pythagorean theorem relates the sides of a right triangle.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'THEER-um',
        etymology: 'Greek: theorema (a sight, speculation), from theorein (to look at)',
        distractors: ['theorum', 'theoremm', 'thearem'],
        theme: 'academic',
    },
    // ── Latin-origin competition words ────────────────────────────────────
    {
        word: 'contiguous',
        definition: 'Sharing a common border; next to or touching.',
        exampleSentence: 'The two states are contiguous, sharing a border along the river.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'kun-TIG-yoo-us',
        etymology: 'Latin: contiguus (touching), from contingere (to touch on all sides)',
        distractors: ['contigueous', 'contigous', 'contigious'],
        theme: 'earth',
    },
    {
        word: 'supernumerary',
        definition: 'Present in excess of the normal or required number; an extra person.',
        exampleSentence: 'Supernumerary actors filled the crowd scenes in the film.',
        partOfSpeech: 'adjective',
        difficulty: 10,
        pattern: 'latin-roots',
        pronunciation: 'soo-per-NOO-muh-rer-ee',
        etymology: 'Latin: supernumerarius (excess), from super (above) + numerus (number)',
        distractors: ['supernumary', 'supernumerery', 'supernumerairy'],
        theme: 'quantity',
    },
    {
        word: 'cogent',
        definition: 'Clear, logical, and convincing.',
        exampleSentence: 'She presented a cogent argument that persuaded the entire jury.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'KOH-junt',
        etymology: 'Latin: cogent- (compelling), from cogere (to drive together)',
        distractors: ['cogant', 'cojent', 'cogient'],
        theme: 'communication',
    },
    {
        word: 'exonerate',
        definition: 'To absolve someone from blame or wrongdoing; to clear.',
        exampleSentence: 'New DNA evidence helped exonerate the wrongfully convicted man.',
        partOfSpeech: 'verb',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'ig-ZON-uh-rayt',
        etymology: 'Latin: exonerare (to free from a burden), from ex (out) + onus (burden)',
        distractors: ['exonnerate', 'exonorate', 'exonarate'],
        theme: 'actions',
    },
    {
        word: 'repudiate',
        definition: 'To refuse to accept or be associated with; to deny the truth of.',
        exampleSentence: 'The senator repudiated the controversial comments made by his aide.',
        partOfSpeech: 'verb',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'rih-PYOO-dee-ayt',
        etymology: 'Latin: repudiare (to reject), from repudium (divorce)',
        distractors: ['repudeate', 'repudiete', 'repuddiate'],
        theme: 'actions',
    },
    {
        word: 'cadaverous',
        definition: 'Very pale, thin, or bony; resembling a corpse.',
        exampleSentence: 'His cadaverous appearance alarmed his friends.',
        partOfSpeech: 'adjective',
        difficulty: 10,
        pattern: 'latin-roots',
        pronunciation: 'kuh-DAV-er-us',
        etymology: 'Latin: cadaverosus (corpse-like), from cadaver (dead body)',
        distractors: ['cadavorus', 'cadaverus', 'caddaverous'],
        theme: 'body',
    },
    {
        word: 'effulgent',
        definition: 'Shining brightly; radiant.',
        exampleSentence: 'The effulgent sunset painted the sky in shades of gold and crimson.',
        partOfSpeech: 'adjective',
        difficulty: 10,
        pattern: 'latin-roots',
        pronunciation: 'ih-FUL-junt',
        etymology: 'Latin: effulgere (to shine out), from ex (out) + fulgere (to shine)',
        distractors: ['efulgent', 'effulgant', 'effulgient'],
        theme: 'sensory',
    },
    {
        word: 'equivocal',
        definition: 'Open to more than one interpretation; ambiguous.',
        exampleSentence: 'The politician gave an equivocal answer to avoid taking a clear position.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'ih-KWIV-uh-kul',
        etymology: 'Latin: aequivocus (of equal voice), from aequus (equal) + vocare (to call)',
        distractors: ['equivocle', 'equivical', 'equivacal'],
        theme: 'communication',
    },
    {
        word: 'incorrigible',
        definition: 'Not able to be corrected, improved, or reformed.',
        exampleSentence: 'The incorrigible prankster could not resist pulling one more joke.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'in-KOR-ij-uh-bul',
        etymology: 'Latin: incorrigibilis (not to be corrected), from in (not) + corrigere (to correct)',
        distractors: ['incorrigable', 'incorigible', 'incorriguble'],
        theme: 'character',
    },
    {
        word: 'sedulous',
        definition: 'Showing dedication and diligence; persistent and hardworking.',
        exampleSentence: 'Her sedulous preparation for the exam earned her the highest score.',
        partOfSpeech: 'adjective',
        difficulty: 10,
        pattern: 'latin-roots',
        pronunciation: 'SEJ-oo-lus',
        etymology: 'Latin: sedulus (diligent, attentive), from se (without) + dolus (guile)',
        distractors: ['seduluos', 'seddulous', 'sedualous'],
        theme: 'character',
    },
    // ── French-origin competition words ───────────────────────────────────
    {
        word: 'clairvoyance',
        definition: 'The supposed ability to perceive things beyond normal sensory experience.',
        exampleSentence: 'She claimed clairvoyance allowed her to sense events before they happened.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'french-origin',
        pronunciation: 'klair-VOY-uns',
        etymology: 'French: clairvoyance (clear-seeing), from clair (clear) + voir (to see)',
        distractors: ['clairvoyence', 'clairvoiance', 'clarevoyance'],
        theme: 'mind',
    },
    {
        word: 'nonchalance',
        definition: 'A casual lack of concern or worry; cool indifference.',
        exampleSentence: 'She accepted the award with an air of nonchalance that impressed everyone.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'french-origin',
        pronunciation: 'non-shuh-LAHNS',
        etymology: 'French: nonchalance (carelessness), from nonchaloir (to disregard)',
        distractors: ['nonchalanse', 'nonchilance', 'nonchalence'],
        theme: 'feelings',
    },
    {
        word: 'bijou',
        definition: 'A jewel or trinket; something small and elegant.',
        exampleSentence: 'They dined at a bijou restaurant tucked away on a side street.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'french-origin',
        pronunciation: 'BEE-zhoo',
        etymology: 'French: bijou (jewel), from Breton bizou (ring)',
        distractors: ['bijoo', 'bijeu', 'bejou'],
        theme: 'everyday',
    },
    {
        word: 'cachet',
        definition: 'Prestige or distinction; a distinguishing mark of quality.',
        exampleSentence: 'Graduating from that university carries a certain cachet in the industry.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'french-origin',
        pronunciation: 'ka-SHAY',
        etymology: 'French: cachet (seal, stamp), from cacher (to hide, press)',
        distractors: ['cashay', 'cachett', 'casheet'],
        theme: 'society',
    },
    {
        word: 'charlatan',
        definition: 'A person falsely claiming to have special knowledge or skill; a fraud.',
        exampleSentence: 'The so-called healer turned out to be a charlatan selling worthless remedies.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'french-origin',
        pronunciation: 'SHAR-luh-tun',
        etymology: 'French: charlatan, from Italian ciarlatano (quack), from ciarlare (to chatter)',
        distractors: ['charleton', 'charlatin', 'sharlatan'],
        theme: 'people',
    },
    {
        word: 'chatelaine',
        definition: 'The mistress of a large house; or a decorative clasp worn at the waist.',
        exampleSentence: 'The chatelaine managed the estate while her husband was away.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'french-origin',
        pronunciation: 'SHAT-uh-layn',
        etymology: 'French: chatelaine (mistress of a castle), from chateau (castle)',
        distractors: ['chattelaine', 'chatalaine', 'chatelain'],
        theme: 'people',
    },
    {
        word: 'coquette',
        definition: 'A woman who flirts or behaves in a playfully alluring way.',
        exampleSentence: 'In the novel, the coquette charmed every gentleman at the ball.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'french-origin',
        pronunciation: 'koh-KET',
        etymology: 'French: coquette (flirtatious woman), from coq (rooster)',
        distractors: ['coquet', 'coquete', 'coqutte'],
        theme: 'people',
    },
    {
        word: 'cortege',
        definition: 'A solemn procession, especially for a funeral.',
        exampleSentence: 'The funeral cortege wound slowly through the streets of the capital.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'french-origin',
        pronunciation: 'kor-TEZH',
        etymology: 'French: cortege (procession), from Italian corteggio, from corte (court)',
        distractors: ['cortage', 'corteje', 'cortedge'],
        theme: 'society',
    },
    {
        word: 'gaffe',
        definition: 'An embarrassing blunder or social mistake.',
        exampleSentence: 'The diplomat committed a gaffe by mispronouncing the president\'s name.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'french-origin',
        pronunciation: 'GAF',
        etymology: 'French: gaffe (blunder), originally a boathook',
        distractors: ['gaff', 'gafe', 'gaffee'],
        theme: 'actions',
    },
    {
        word: 'gauche',
        definition: 'Lacking ease or grace; unsophisticated and socially awkward.',
        exampleSentence: 'His gauche table manners made the other guests uncomfortable.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'french-origin',
        pronunciation: 'GOHSH',
        etymology: 'French: gauche (left, awkward), from gauchir (to turn aside)',
        distractors: ['gouch', 'gaush', 'gaushe'],
        theme: 'character',
    },
    {
        word: 'largesse',
        definition: 'Generosity in bestowing money or gifts; munificence.',
        exampleSentence: 'The billionaire\'s largesse funded scholarships for hundreds of students.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'french-origin',
        pronunciation: 'lar-ZHES',
        etymology: 'French: largesse (generosity), from large (generous)',
        distractors: ['largess', 'largese', 'larjesse'],
        theme: 'money',
    },
    {
        word: 'macabre',
        definition: 'Disturbing and horrifying because of involvement with death or injury.',
        exampleSentence: 'Edgar Allan Poe is famous for his macabre tales of mystery.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'french-origin',
        pronunciation: 'muh-KAH-bruh',
        etymology: 'French: macabre (gruesome), from danse macabre (dance of death)',
        distractors: ['macabra', 'macabar', 'maccabre'],
        theme: 'art',
    },
    {
        word: 'nuance',
        definition: 'A subtle difference in meaning, expression, or sound.',
        exampleSentence: 'Good actors capture every nuance of a character\'s personality.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'french-origin',
        pronunciation: 'NOO-ahns',
        etymology: 'French: nuance (shade, subtlety), from nuer (to shade), from nue (cloud)',
        distractors: ['nuanse', 'newance', 'nuence'],
        theme: 'language',
    },
    {
        word: 'penchant',
        definition: 'A strong or habitual liking for something; a tendency.',
        exampleSentence: 'She had a penchant for collecting rare books.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'french-origin',
        pronunciation: 'PEN-chunt',
        etymology: 'French: penchant (inclining), from pencher (to lean)',
        distractors: ['penchent', 'penchint', 'penchont'],
        theme: 'character',
    },
    {
        word: 'potpourri',
        definition: 'A mixture of dried petals and spices for fragrance; or a miscellaneous collection.',
        exampleSentence: 'A bowl of potpourri on the table filled the room with a pleasant scent.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'french-origin',
        pronunciation: 'poh-poo-REE',
        etymology: 'French: pot-pourri (rotten pot), a translation of Spanish olla podrida (mixed stew)',
        distractors: ['potpourrie', 'potporri', 'popourri'],
        theme: 'home',
    },
    // ── German-origin competition words ───────────────────────────────────
    {
        word: 'angst',
        definition: 'A feeling of deep anxiety, dread, or anguish about the human condition.',
        exampleSentence: 'The existentialist novel explored themes of angst and alienation.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'irregular',
        pronunciation: 'AHNGST',
        etymology: 'German: Angst (fear, anxiety), from Old High German angust (distress)',
        distractors: ['ankst', 'anxt', 'angzt'],
        theme: 'feelings',
    },
    {
        word: 'doppelganger',
        definition: 'An apparition or ghostly double of a living person.',
        exampleSentence: 'She was startled to meet her doppelganger at the conference.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'irregular',
        pronunciation: 'DOP-ul-gang-er',
        etymology: 'German: Doppelganger (double-goer), from doppel (double) + Ganger (goer)',
        distractors: ['doppleganger', 'doppelgenger', 'dopelganger'],
        theme: 'people',
    },
    {
        word: 'dachshund',
        definition: 'A small dog breed with a long body and short legs, originally bred for hunting badgers.',
        exampleSentence: 'The dachshund squeezed through the narrow tunnel with ease.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'irregular',
        pronunciation: 'DAHKS-hoont',
        etymology: 'German: Dachshund (badger dog), from Dachs (badger) + Hund (dog)',
        distractors: ['dachsund', 'dachshound', 'dashund'],
        theme: 'animals',
    },
    {
        word: 'flak',
        definition: 'Anti-aircraft fire; or strong criticism.',
        exampleSentence: 'The proposal received heavy flak from environmental groups.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'irregular',
        pronunciation: 'FLAK',
        etymology: 'German: Flak, abbreviation of Fliegerabwehrkanone (aircraft defense cannon)',
        distractors: ['flack', 'fflak', 'flac'],
        theme: 'society',
    },
    {
        word: 'gestalt',
        definition: 'An organized whole that is perceived as more than the sum of its parts.',
        exampleSentence: 'The gestalt of the painting was more powerful than any single element.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'irregular',
        pronunciation: 'geh-SHTALT',
        etymology: 'German: Gestalt (form, shape), from stellen (to place)',
        distractors: ['gestault', 'gestald', 'gestolt'],
        theme: 'mind',
    },
    {
        word: 'hinterland',
        definition: 'The remote areas of a country, away from the coast or major cities.',
        exampleSentence: 'The explorer ventured deep into the hinterland of the Amazon basin.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'irregular',
        pronunciation: 'HIN-ter-land',
        etymology: 'German: Hinterland (land behind), from hinter (behind) + Land (land)',
        distractors: ['hinterladn', 'hinterlan', 'hintreland'],
        theme: 'earth',
    },
    {
        word: 'kitsch',
        definition: 'Art, objects, or design considered to be in poor taste because of excessive showiness.',
        exampleSentence: 'The souvenir shop was full of kitsch, from plastic flamingos to glitter globes.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'irregular',
        pronunciation: 'KICH',
        etymology: 'German: Kitsch (cheap, gaudy), possibly from kitschen (to smear)',
        distractors: ['kitch', 'kitsh', 'kitchh'],
        theme: 'art',
    },
    {
        word: 'poltergeist',
        definition: 'A ghost or supernatural force believed to cause physical disturbances like noises and moving objects.',
        exampleSentence: 'The family blamed a poltergeist for the mysterious rattling of doors.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'irregular',
        pronunciation: 'POHL-ter-gyst',
        etymology: 'German: Poltergeist (noisy ghost), from poltern (to make noise) + Geist (ghost)',
        distractors: ['polterguist', 'poltergeest', 'polterghist'],
        theme: 'nature',
    },
    {
        word: 'rucksack',
        definition: 'A bag carried on the back with shoulder straps; a backpack.',
        exampleSentence: 'She packed her rucksack with supplies for the mountain hike.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'irregular',
        pronunciation: 'RUK-sak',
        etymology: 'German: Rucksack (back-bag), from Rucken (back) + Sack (bag)',
        distractors: ['rucksak', 'ruksack', 'rucksach'],
        theme: 'travel',
    },
    {
        word: 'verboten',
        definition: 'Forbidden, especially by an authority.',
        exampleSentence: 'Using cellphones in the exam hall was strictly verboten.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'irregular',
        pronunciation: 'fer-BOH-tun',
        etymology: 'German: verboten (forbidden), past participle of verbieten (to forbid)',
        distractors: ['varboten', 'verbotten', 'verboden'],
        theme: 'society',
    },
    // ── Spanish/Portuguese-origin competition words ───────────────────────
    {
        word: 'aficionado',
        definition: 'A person who is very enthusiastic and knowledgeable about an activity or subject.',
        exampleSentence: 'As an aficionado of jazz, he had a vast record collection.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'irregular',
        pronunciation: 'uh-fish-ee-uh-NAH-doh',
        etymology: 'Spanish: aficionado (amateur, fan), from aficion (affection)',
        distractors: ['afficionado', 'aficianado', 'aficianodo'],
        theme: 'people',
    },
    {
        word: 'incommunicado',
        definition: 'Not able to or allowed to communicate with other people.',
        exampleSentence: 'The prisoner was held incommunicado for three weeks.',
        partOfSpeech: 'adjective',
        difficulty: 10,
        pattern: 'irregular',
        pronunciation: 'in-kuh-myoo-nih-KAH-doh',
        etymology: 'Spanish: incomunicado (cut off from communication)',
        distractors: ['incomunicado', 'incommunicato', 'incommuncado'],
        theme: 'actions',
    },
    {
        word: 'bravado',
        definition: 'A bold manner or a show of boldness intended to impress or intimidate.',
        exampleSentence: 'His bravado masked a deep fear of public speaking.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'irregular',
        pronunciation: 'bruh-VAH-doh',
        etymology: 'Spanish: bravada (bravery, boasting), from bravo (brave, wild)',
        distractors: ['brovado', 'bravaddo', 'brevado'],
        theme: 'character',
    },
    {
        word: 'embargo',
        definition: 'An official ban on trade or other commercial activity with a particular country.',
        exampleSentence: 'The government imposed an embargo on oil imports from that nation.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'irregular',
        pronunciation: 'em-BAR-goh',
        etymology: 'Spanish: embargo (seizure), from embargar (to impede)',
        distractors: ['embargoe', 'imbargo', 'embbargo'],
        theme: 'society',
    },
    {
        word: 'machete',
        definition: 'A broad, heavy knife used as a tool for cutting vegetation or as a weapon.',
        exampleSentence: 'The farmer used a machete to clear a path through the dense jungle.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'irregular',
        pronunciation: 'muh-SHET-ee',
        etymology: 'Spanish: machete (chopping knife), from macho (sledgehammer)',
        distractors: ['machette', 'mashete', 'machetee'],
        theme: 'everyday',
    },
    {
        word: 'mosquito',
        definition: 'A small flying insect that bites and sucks blood, often spreading disease.',
        exampleSentence: 'The campers wore repellent to keep away the mosquitoes at dusk.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'irregular',
        pronunciation: 'muh-SKEE-toh',
        etymology: 'Spanish: mosquito (little fly), diminutive of mosca (fly), from Latin musca',
        distractors: ['mosquitto', 'musquito', 'mosqito'],
        theme: 'animals',
    },
    {
        word: 'renegade',
        definition: 'A person who deserts and betrays a group, cause, or principle; a rebel.',
        exampleSentence: 'The renegade soldier fled across the border under cover of darkness.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'irregular',
        pronunciation: 'REN-uh-gayd',
        etymology: 'Spanish: renegado (one who denies), from Latin renegare (to deny)',
        distractors: ['rennegade', 'renegaid', 'renagate'],
        theme: 'people',
    },
    {
        word: 'stampede',
        definition: 'A sudden panicked rush of a group of animals or people.',
        exampleSentence: 'The sound of thunder caused a stampede among the cattle.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'irregular',
        pronunciation: 'stam-PEED',
        etymology: 'Spanish: estampida (uproar, crash), from estampar (to stamp)',
        distractors: ['stampeed', 'stampeede', 'stampide'],
        theme: 'actions',
    },
    {
        word: 'vigilante',
        definition: 'A person who takes law enforcement into their own hands without legal authority.',
        exampleSentence: 'The town\'s vigilante justice was criticized as dangerous and unjust.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'irregular',
        pronunciation: 'vij-uh-LAN-tee',
        etymology: 'Spanish: vigilante (watchman), from Latin vigilare (to keep watch)',
        distractors: ['vigilanti', 'vigilente', 'vigalante'],
        theme: 'society',
    },
    // ── Italian-origin competition words ──────────────────────────────────
    {
        word: 'virtuoso',
        definition: 'A person highly skilled in music or another artistic pursuit.',
        exampleSentence: 'The violin virtuoso played with breathtaking precision.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'irregular',
        pronunciation: 'vur-choo-OH-soh',
        etymology: 'Italian: virtuoso (skilled), from virtu (virtue, excellence)',
        distractors: ['virtuosso', 'vertioso', 'virtouso'],
        theme: 'art',
    },
    {
        word: 'bravura',
        definition: 'Great technical skill and brilliance shown in a performance.',
        exampleSentence: 'The pianist\'s bravura performance earned a standing ovation.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'irregular',
        pronunciation: 'bruh-VYOOR-uh',
        etymology: 'Italian: bravura (bravery, skill), from bravo (brave)',
        distractors: ['bravurra', 'bravurha', 'brevura'],
        theme: 'art',
    },
    {
        word: 'cognoscenti',
        definition: 'People who are well-informed about a particular subject; connoisseurs.',
        exampleSentence: 'The wine was appreciated mainly by the cognoscenti.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'irregular',
        pronunciation: 'kon-yuh-SHEN-tee',
        etymology: 'Italian: cognoscenti (those who know), from cognoscere (to know)',
        distractors: ['cognocenti', 'cognoscente', 'conoscenti'],
        theme: 'people',
    },
    {
        word: 'fiasco',
        definition: 'A complete and humiliating failure.',
        exampleSentence: 'The product launch was a fiasco — nothing worked as planned.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'irregular',
        pronunciation: 'fee-AS-koh',
        etymology: 'Italian: fiasco (bottle, flask), used figuratively for a theatrical flop',
        distractors: ['fiassco', 'fiasko', 'fiascco'],
        theme: 'actions',
    },
    {
        word: 'graffiti',
        definition: 'Writing or drawings scribbled or sprayed on a wall or surface in a public place.',
        exampleSentence: 'The city launched a campaign to clean up graffiti on public buildings.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'irregular',
        pronunciation: 'gruh-FEE-tee',
        etymology: 'Italian: graffiti (scratched), plural of graffito, from graffiare (to scratch)',
        distractors: ['grafiti', 'graffitti', 'graffeti'],
        theme: 'art',
    },
    {
        word: 'influenza',
        definition: 'A highly contagious viral infection of the respiratory tract; the flu.',
        exampleSentence: 'The influenza outbreak forced many schools to close temporarily.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'irregular',
        pronunciation: 'in-floo-EN-zuh',
        etymology: 'Italian: influenza (influence), from the belief that epidemics were influenced by the stars',
        distractors: ['influensa', 'influenxa', 'enfluenza'],
        theme: 'health',
    },
    {
        word: 'libretto',
        definition: 'The text of an opera or other long vocal work.',
        exampleSentence: 'The composer wrote the libretto for the opera herself.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'irregular',
        pronunciation: 'lih-BRET-oh',
        etymology: 'Italian: libretto (little book), diminutive of libro (book)',
        distractors: ['librato', 'librettoe', 'libretoh'],
        theme: 'art',
    },
    {
        word: 'paparazzi',
        definition: 'Photographers who aggressively pursue celebrities to take candid pictures.',
        exampleSentence: 'The actress wore sunglasses to avoid being recognized by the paparazzi.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'irregular',
        pronunciation: 'pah-puh-RAT-see',
        etymology: 'Italian: Paparazzo, a character in Federico Fellini\'s film La Dolce Vita (1960)',
        distractors: ['paparazi', 'papparazzi', 'paparatzi'],
        theme: 'people',
    },
    {
        word: 'staccato',
        definition: 'Performed with each note sharply detached or separated; abrupt and disconnected.',
        exampleSentence: 'The drummer played a rapid staccato beat that energized the crowd.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'irregular',
        pronunciation: 'stuh-KAH-toh',
        etymology: 'Italian: staccato (detached), from staccare (to detach)',
        distractors: ['stacato', 'staccatto', 'staccatoe'],
        theme: 'art',
    },
    {
        word: 'vendetta',
        definition: 'A prolonged bitter feud or campaign of revenge.',
        exampleSentence: 'The two families carried on a vendetta that lasted for generations.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'irregular',
        pronunciation: 'ven-DET-uh',
        etymology: 'Italian: vendetta (revenge), from Latin vindicta (vengeance)',
        distractors: ['vendeta', 'vendettah', 'vindetta'],
        theme: 'society',
    },
    // ── Arabic/Persian/Hindi/Sanskrit-origin competition words ────────────
    {
        word: 'almanac',
        definition: 'An annual publication containing a calendar, weather forecasts, and other useful information.',
        exampleSentence: 'The farmer consulted the almanac to determine the best planting dates.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'irregular',
        pronunciation: 'AWL-muh-nak',
        etymology: 'Arabic: al-manakh (the climate), through Medieval Latin almanach',
        distractors: ['almanak', 'almenac', 'allmanac'],
        theme: 'academic',
    },
    {
        word: 'avatar',
        definition: 'A manifestation of a deity in bodily form; or an icon representing a person online.',
        exampleSentence: 'She designed a colorful avatar for her gaming profile.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'irregular',
        pronunciation: 'AV-uh-tar',
        etymology: 'Sanskrit: avatara (descent), from ava (down) + tarati (he crosses over)',
        distractors: ['avitar', 'avataar', 'avetar'],
        theme: 'academic',
    },
    {
        word: 'juggernaut',
        definition: 'A huge, powerful, and overwhelming force or institution.',
        exampleSentence: 'The tech company became a juggernaut dominating the industry.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'irregular',
        pronunciation: 'JUG-er-nawt',
        etymology: 'Hindi/Sanskrit: Jagannath (Lord of the World), a title of the Hindu god Krishna',
        distractors: ['juggernaught', 'jugernaut', 'juggernot'],
        theme: 'society',
    },
    {
        word: 'bazaar',
        definition: 'A market in a Middle Eastern country; or a sale of goods for charity.',
        exampleSentence: 'The colorful bazaar was filled with spices, fabrics, and handmade pottery.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'irregular',
        pronunciation: 'buh-ZAR',
        etymology: 'Persian: bazar (market), from Middle Persian wacar (commerce)',
        distractors: ['bazar', 'bazare', 'bazarr'],
        theme: 'travel',
    },
    {
        word: 'caravan',
        definition: 'A group of travelers journeying together across a desert or hostile region.',
        exampleSentence: 'A caravan of merchants crossed the Sahara loaded with gold and salt.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'irregular',
        pronunciation: 'KAR-uh-van',
        etymology: 'Persian: karwan (group of travelers)',
        distractors: ['caraven', 'caravaan', 'carravan'],
        theme: 'travel',
    },
    {
        word: 'elixir',
        definition: 'A magical or medicinal potion; a preparation believed to cure all diseases.',
        exampleSentence: 'The alchemist searched for an elixir that could grant eternal youth.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'irregular',
        pronunciation: 'ih-LIK-sur',
        etymology: 'Arabic: al-iksir (the philosopher\'s stone), from Greek xerion (drying powder)',
        distractors: ['elixer', 'elexir', 'elixur'],
        theme: 'health',
    },
    {
        word: 'ghoul',
        definition: 'An evil spirit or phantom that robs graves and feeds on the dead.',
        exampleSentence: 'The horror film featured a ghoul lurking in the abandoned cemetery.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'irregular',
        pronunciation: 'GOOL',
        etymology: 'Arabic: ghul (a desert demon that robs graves)',
        distractors: ['goul', 'ghool', 'ghowl'],
        theme: 'nature',
    },
    {
        word: 'jasmine',
        definition: 'A climbing plant with fragrant white or yellow flowers, used in perfumes and teas.',
        exampleSentence: 'The jasmine growing along the fence filled the garden with a sweet fragrance.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'irregular',
        pronunciation: 'JAZ-min',
        etymology: 'Arabic: yasmin, from Persian yasamin (the jasmine flower)',
        distractors: ['jasmin', 'jasimine', 'jasmyne'],
        theme: 'plants',
    },
    {
        word: 'monsoon',
        definition: 'A seasonal wind bringing heavy rainfall, especially in South Asia.',
        exampleSentence: 'The monsoon season brought much-needed rain to the parched farmland.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'irregular',
        pronunciation: 'mon-SOON',
        etymology: 'Arabic: mawsim (season), from wasama (to mark)',
        distractors: ['monsoone', 'moonsoon', 'monsune'],
        theme: 'weather',
    },
    {
        word: 'nadir',
        definition: 'The lowest point; the point of greatest adversity or despair.',
        exampleSentence: 'The economy reached its nadir during the worst months of the recession.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'irregular',
        pronunciation: 'NAY-deer',
        etymology: 'Arabic: nazir (opposite), from nazir as-samt (opposite the zenith)',
        distractors: ['nadeer', 'nader', 'nadire'],
        theme: 'quantity',
    },
    {
        word: 'safari',
        definition: 'An expedition to observe or hunt animals in their natural habitat, especially in Africa.',
        exampleSentence: 'They went on a safari in Kenya and saw elephants and lions up close.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'irregular',
        pronunciation: 'suh-FAR-ee',
        etymology: 'Swahili: safari (journey), from Arabic safar (to travel)',
        distractors: ['saffari', 'safarri', 'safarie'],
        theme: 'travel',
    },
    {
        word: 'zenith',
        definition: 'The highest point reached by something; the peak of achievement.',
        exampleSentence: 'The empire reached its zenith during the golden age of trade.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'irregular',
        pronunciation: 'ZEE-nith',
        etymology: 'Arabic: samt ar-ra\'s (direction of the head), corrupted through Old Spanish cenit',
        distractors: ['zeneth', 'zeenith', 'zennith'],
        theme: 'quantity',
    },
    // ── Other origins competition words ───────────────────────────────────
    {
        word: 'beleaguer',
        definition: 'To cause someone persistent problems or hardship; to besiege.',
        exampleSentence: 'The beleaguered company faced lawsuits from multiple directions.',
        partOfSpeech: 'verb',
        difficulty: 9,
        pattern: 'irregular',
        pronunciation: 'bih-LEE-gur',
        etymology: 'Dutch: belegeren (to besiege), from be (around) + leger (camp)',
        distractors: ['beleager', 'beleguer', 'beleagure'],
        theme: 'actions',
    },
    {
        word: 'fjord',
        definition: 'A long, narrow, deep inlet of the sea between high cliffs, formed by glaciers.',
        exampleSentence: 'The boat sailed through the stunning Norwegian fjord.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'irregular',
        pronunciation: 'FYORD',
        etymology: 'Norwegian: fjord (inlet), from Old Norse fjorthr (inlet)',
        distractors: ['fiord', 'fjored', 'fjurd'],
        theme: 'earth',
    },
    {
        word: 'ombudsman',
        definition: 'An official appointed to investigate complaints against organizations.',
        exampleSentence: 'Citizens can file complaints with the ombudsman when they feel unfairly treated.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'irregular',
        pronunciation: 'OM-budz-mun',
        etymology: 'Swedish: ombudsman (representative, agent), from ombud (commission)',
        distractors: ['ombudsmen', 'ombudman', 'ombundsman'],
        theme: 'society',
    },
    {
        word: 'smorgasbord',
        definition: 'A buffet offering a variety of dishes; or a wide range of something.',
        exampleSentence: 'The conference offered a smorgasbord of workshops and presentations.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'irregular',
        pronunciation: 'SMOR-gus-bord',
        etymology: 'Swedish: smorgasbord (sandwich table), from smorgas (open sandwich) + bord (table)',
        distractors: ['smorgasboard', 'smorgasbourg', 'shmorgasbord'],
        theme: 'food',
    },
    {
        word: 'typhoon',
        definition: 'A tropical storm with very high winds, especially in the western Pacific.',
        exampleSentence: 'The powerful typhoon forced thousands of residents to evacuate.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'irregular',
        pronunciation: 'ty-FOON',
        etymology: 'Chinese: tai fung (great wind), influenced by Greek typhon (whirlwind)',
        distractors: ['typhoone', 'tyhpoon', 'typhune'],
        theme: 'weather',
    },
    {
        word: 'ukulele',
        definition: 'A small four-stringed guitar of Hawaiian origin.',
        exampleSentence: 'She learned to play the ukulele during her vacation in Hawaii.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'irregular',
        pronunciation: 'yoo-kuh-LAY-lee',
        etymology: 'Hawaiian: ukulele (jumping flea), from uku (flea) + lele (jumping)',
        distractors: ['ukelele', 'ukuelele', 'ukulale'],
        theme: 'art',
    },
    {
        word: 'voodoo',
        definition: 'A religion practiced chiefly in Haiti and the southern US, involving spirit possession and sorcery.',
        exampleSentence: 'The museum exhibit explored the history and cultural significance of voodoo.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'irregular',
        pronunciation: 'VOO-doo',
        etymology: 'Louisiana French: voudou, from Fon (West African language) vodun (spirit)',
        distractors: ['voodou', 'voodo', 'vudoo'],
        theme: 'society',
    },
];
