/**
 * words/tier4.ts
 *
 * Tier 4 word bank: 6th-8th grade level (difficulty 7-8).
 * Covers Latin roots, Greek roots, irregular spellings, and French-origin words.
 * Etymology included for ALL words.
 * ~120 curated entries.
 */
import type { SpellingWord } from './types';

export const TIER_4_WORDS: SpellingWord[] = [
    // ── Latin Roots (difficulty 7) ─────────────────────────────────────
    {
        word: 'spectacle',
        definition: 'An impressive or remarkable sight or performance.',
        exampleSentence: 'The fireworks display was quite a spectacle.',
        partOfSpeech: 'noun',
        difficulty: 7,
        pattern: 'latin-roots',
        pronunciation: 'SPEK-tuh-kul',
        etymology: 'Latin: spectare (to look at)',
    },
    {
        word: 'portable',
        definition: 'Easy to carry or move from one place to another.',
        exampleSentence: 'She brought a portable speaker to the beach.',
        partOfSpeech: 'adjective',
        difficulty: 7,
        pattern: 'latin-roots',
        pronunciation: 'POR-tuh-bul',
        etymology: 'Latin: portare (to carry)',
    },
    {
        word: 'manuscript',
        definition: 'A handwritten or typed document, especially a draft of a book.',
        exampleSentence: 'The author submitted her manuscript to the publisher.',
        partOfSpeech: 'noun',
        difficulty: 7,
        pattern: 'latin-roots',
        pronunciation: 'MAN-yoo-skript',
        etymology: 'Latin: manu scriptus (written by hand)',
    },
    {
        word: 'describe',
        definition: 'To tell or write about the qualities or features of something.',
        exampleSentence: 'Can you describe what the suspect looked like?',
        partOfSpeech: 'verb',
        difficulty: 7,
        pattern: 'latin-roots',
        pronunciation: 'dih-SKRYB',
        etymology: 'Latin: describere (to write down)',
    },
    {
        word: 'interrupt',
        definition: 'To stop someone while they are speaking or doing something.',
        exampleSentence: 'Please do not interrupt the teacher during the lesson.',
        partOfSpeech: 'verb',
        difficulty: 7,
        pattern: 'latin-roots',
        pronunciation: 'in-tuh-RUPT',
        etymology: 'Latin: interrumpere (to break apart)',
    },
    {
        word: 'visible',
        definition: 'Able to be seen.',
        exampleSentence: 'The mountain was visible from miles away on a clear day.',
        partOfSpeech: 'adjective',
        difficulty: 7,
        pattern: 'latin-roots',
        pronunciation: 'VIZ-uh-bul',
        etymology: 'Latin: visibilis (that may be seen), from videre (to see)',
    },
    {
        word: 'conductor',
        definition: 'A person who directs an orchestra or leads a group.',
        exampleSentence: 'The conductor raised his baton to begin the symphony.',
        partOfSpeech: 'noun',
        difficulty: 7,
        pattern: 'latin-roots',
        pronunciation: 'kun-DUK-tur',
        etymology: 'Latin: conducere (to lead together)',
    },
    {
        word: 'construct',
        definition: 'To build or put together from parts.',
        exampleSentence: 'The workers will construct a new bridge over the river.',
        partOfSpeech: 'verb',
        difficulty: 7,
        pattern: 'latin-roots',
        pronunciation: 'kun-STRUKT',
        etymology: 'Latin: construere (to pile up, build)',
    },
    {
        word: 'dictator',
        definition: 'A ruler who has total power over a country.',
        exampleSentence: 'The dictator controlled every aspect of the government.',
        partOfSpeech: 'noun',
        difficulty: 7,
        pattern: 'latin-roots',
        pronunciation: 'DIK-tay-tur',
        etymology: 'Latin: dictare (to say repeatedly, prescribe)',
    },
    {
        word: 'transport',
        definition: 'To carry or move something from one place to another.',
        exampleSentence: 'Trucks transport goods across the country.',
        partOfSpeech: 'verb',
        difficulty: 7,
        pattern: 'latin-roots',
        pronunciation: 'trans-PORT',
        etymology: 'Latin: transportare (to carry across)',
    },
    {
        word: 'manufacture',
        definition: 'To make something on a large scale using machinery.',
        exampleSentence: 'The factory will manufacture one thousand cars this month.',
        partOfSpeech: 'verb',
        difficulty: 7,
        pattern: 'latin-roots',
        pronunciation: 'man-yoo-FAK-chur',
        etymology: 'Latin: manu factus (made by hand)',
    },
    {
        word: 'prediction',
        definition: 'A statement about what you think will happen in the future.',
        exampleSentence: 'Her prediction about the weather turned out to be correct.',
        partOfSpeech: 'noun',
        difficulty: 7,
        pattern: 'latin-roots',
        pronunciation: 'prih-DIK-shun',
        etymology: 'Latin: praedicere (to foretell)',
    },
    {
        word: 'subscription',
        definition: 'An arrangement to receive something regularly, often by paying.',
        exampleSentence: 'He renewed his subscription to the science magazine.',
        partOfSpeech: 'noun',
        difficulty: 7,
        pattern: 'latin-roots',
        pronunciation: 'sub-SKRIP-shun',
        etymology: 'Latin: subscribere (to write underneath)',
    },
    {
        word: 'inspector',
        definition: 'A person who examines something officially.',
        exampleSentence: 'The health inspector visited the restaurant to check its cleanliness.',
        partOfSpeech: 'noun',
        difficulty: 7,
        pattern: 'latin-roots',
        pronunciation: 'in-SPEK-tur',
        etymology: 'Latin: inspicere (to look into)',
    },
    {
        word: 'projection',
        definition: 'An image displayed on a surface, or an estimate of future results.',
        exampleSentence: 'The projection of the movie onto the big screen looked amazing.',
        partOfSpeech: 'noun',
        difficulty: 7,
        pattern: 'latin-roots',
        pronunciation: 'proh-JEK-shun',
        etymology: 'Latin: proicere (to throw forward)',
    },
    {
        word: 'annual',
        definition: 'Happening once every year.',
        exampleSentence: 'The annual school fair is held every spring.',
        partOfSpeech: 'adjective',
        difficulty: 7,
        pattern: 'latin-roots',
        pronunciation: 'AN-yoo-ul',
        etymology: 'Latin: annualis (yearly), from annus (year)',
    },
    {
        word: 'auditorium',
        definition: 'A large room or building used for performances or public gatherings.',
        exampleSentence: 'The entire school gathered in the auditorium for the assembly.',
        partOfSpeech: 'noun',
        difficulty: 7,
        pattern: 'latin-roots',
        pronunciation: 'aw-dih-TOR-ee-um',
        etymology: 'Latin: auditorium (a place for hearing), from audire (to hear)',
    },
    {
        word: 'rupture',
        definition: 'A break or burst, especially in a pipe or body tissue.',
        exampleSentence: 'The rupture in the water pipe caused flooding in the basement.',
        partOfSpeech: 'noun',
        difficulty: 7,
        pattern: 'latin-roots',
        pronunciation: 'RUP-chur',
        etymology: 'Latin: rumpere (to break)',
    },
    {
        word: 'attract',
        definition: 'To draw someone or something closer by appeal or force.',
        exampleSentence: 'The bright flowers attract bees and butterflies to the garden.',
        partOfSpeech: 'verb',
        difficulty: 7,
        pattern: 'latin-roots',
        pronunciation: 'uh-TRAKT',
        etymology: 'Latin: attrahere (to draw toward)',
    },
    {
        word: 'perspective',
        definition: 'A point of view or way of looking at something.',
        exampleSentence: 'Traveling to another country gave her a new perspective on life.',
        partOfSpeech: 'noun',
        difficulty: 7,
        pattern: 'latin-roots',
        pronunciation: 'pur-SPEK-tiv',
        etymology: 'Latin: perspicere (to look through)',
    },
    {
        word: 'concurrent',
        definition: 'Happening at the same time.',
        exampleSentence: 'The two concerts were concurrent, so we had to choose one.',
        partOfSpeech: 'adjective',
        difficulty: 7,
        pattern: 'latin-roots',
        pronunciation: 'kun-KUR-unt',
        etymology: 'Latin: concurrere (to run together)',
    },
    {
        word: 'inscription',
        definition: 'Words carved or written on a surface.',
        exampleSentence: 'The inscription on the statue read "In honor of the brave."',
        partOfSpeech: 'noun',
        difficulty: 7,
        pattern: 'latin-roots',
        pronunciation: 'in-SKRIP-shun',
        etymology: 'Latin: inscribere (to write upon)',
    },
    {
        word: 'invincible',
        definition: 'Too powerful to be defeated or overcome.',
        exampleSentence: 'The team felt invincible after winning ten games in a row.',
        partOfSpeech: 'adjective',
        difficulty: 7,
        pattern: 'latin-roots',
        pronunciation: 'in-VIN-suh-bul',
        etymology: 'Latin: invincibilis (unconquerable), from vincere (to conquer)',
    },
    {
        word: 'contradict',
        definition: 'To say the opposite of what someone else has said.',
        exampleSentence: 'The witness seemed to contradict her earlier statement.',
        partOfSpeech: 'verb',
        difficulty: 7,
        pattern: 'latin-roots',
        pronunciation: 'kon-truh-DIKT',
        etymology: 'Latin: contradicere (to speak against)',
    },
    {
        word: 'export',
        definition: 'To send goods to another country for sale.',
        exampleSentence: 'Brazil is known for its export of coffee beans worldwide.',
        partOfSpeech: 'verb',
        difficulty: 7,
        pattern: 'latin-roots',
        pronunciation: 'ek-SPORT',
        etymology: 'Latin: exportare (to carry out)',
    },
    {
        word: 'credentials',
        definition: 'Qualifications or documents proving a person\'s identity or abilities.',
        exampleSentence: 'The reporter showed her credentials to enter the press conference.',
        partOfSpeech: 'noun',
        difficulty: 7,
        pattern: 'latin-roots',
        pronunciation: 'krih-DEN-shulz',
        etymology: 'Latin: credere (to believe, trust)',
    },
    {
        word: 'beneficial',
        definition: 'Producing good or helpful results.',
        exampleSentence: 'Regular exercise is beneficial to your overall health.',
        partOfSpeech: 'adjective',
        difficulty: 7,
        pattern: 'latin-roots',
        pronunciation: 'ben-uh-FISH-ul',
        etymology: 'Latin: beneficium (kindness, favor), from bene (well) + facere (to do)',
    },
    {
        word: 'circumference',
        definition: 'The distance around the outside of a circle.',
        exampleSentence: 'We measured the circumference of the basketball for our math problem.',
        partOfSpeech: 'noun',
        difficulty: 7,
        pattern: 'latin-roots',
        pronunciation: 'sur-KUM-fur-unss',
        etymology: 'Latin: circumferre (to carry around)',
    },
    {
        word: 'terrestrial',
        definition: 'Relating to the earth or land rather than water or air.',
        exampleSentence: 'Frogs are terrestrial animals that also spend time in water.',
        partOfSpeech: 'adjective',
        difficulty: 7,
        pattern: 'latin-roots',
        pronunciation: 'tuh-RES-tree-ul',
        etymology: 'Latin: terrestris (of the earth), from terra (earth)',
    },
    {
        word: 'elaborate',
        definition: 'Detailed and carefully planned; to explain in more detail.',
        exampleSentence: 'The architect created an elaborate design for the new museum.',
        partOfSpeech: 'adjective',
        difficulty: 7,
        pattern: 'latin-roots',
        pronunciation: 'ih-LAB-ur-it',
        etymology: 'Latin: elaborare (to work out)',
    },
    {
        word: 'illuminate',
        definition: 'To light up or make brighter.',
        exampleSentence: 'Thousands of candles illuminate the cathedral during the ceremony.',
        partOfSpeech: 'verb',
        difficulty: 7,
        pattern: 'latin-roots',
        pronunciation: 'ih-LOO-mih-nayt',
        etymology: 'Latin: illuminare (to light up), from lumen (light)',
    },
    {
        word: 'sentiment',
        definition: 'A feeling or opinion about something.',
        exampleSentence: 'The card expressed a warm sentiment of gratitude.',
        partOfSpeech: 'noun',
        difficulty: 7,
        pattern: 'latin-roots',
        pronunciation: 'SEN-tih-ment',
        etymology: 'Latin: sentire (to feel)',
    },
    {
        word: 'peninsula',
        definition: 'A piece of land almost surrounded by water on three sides.',
        exampleSentence: 'Florida is a large peninsula in the southeastern United States.',
        partOfSpeech: 'noun',
        difficulty: 7,
        pattern: 'latin-roots',
        pronunciation: 'peh-NIN-suh-luh',
        etymology: 'Latin: paeninsula (almost an island), from paene (almost) + insula (island)',
    },
    {
        word: 'abbreviation',
        definition: 'A shortened form of a word or phrase.',
        exampleSentence: 'Dr. is the abbreviation for the word Doctor.',
        partOfSpeech: 'noun',
        difficulty: 7,
        pattern: 'latin-roots',
        pronunciation: 'uh-bree-vee-AY-shun',
        etymology: 'Latin: abbreviare (to shorten), from brevis (short)',
    },
    {
        word: 'magnify',
        definition: 'To make something appear larger than it really is.',
        exampleSentence: 'Use a magnifying glass to magnify the tiny print on the map.',
        partOfSpeech: 'verb',
        difficulty: 7,
        pattern: 'latin-roots',
        pronunciation: 'MAG-nuh-fy',
        etymology: 'Latin: magnificare (to make great), from magnus (great)',
    },
    {
        word: 'translucent',
        definition: 'Allowing light to pass through but not transparent.',
        exampleSentence: 'The translucent curtains let sunlight filter into the room.',
        partOfSpeech: 'adjective',
        difficulty: 7,
        pattern: 'latin-roots',
        pronunciation: 'trans-LOO-sunt',
        etymology: 'Latin: translucere (to shine through), from lux (light)',
    },
    {
        word: 'aquatic',
        definition: 'Relating to or living in water.',
        exampleSentence: 'Dolphins and whales are aquatic mammals.',
        partOfSpeech: 'adjective',
        difficulty: 7,
        pattern: 'latin-roots',
        pronunciation: 'uh-KWAT-ik',
        etymology: 'Latin: aquaticus (of water), from aqua (water)',
    },
    {
        word: 'captivate',
        definition: 'To hold someone\'s attention completely; to charm.',
        exampleSentence: 'The storyteller could captivate an audience for hours.',
        partOfSpeech: 'verb',
        difficulty: 7,
        pattern: 'latin-roots',
        pronunciation: 'KAP-tih-vayt',
        etymology: 'Latin: captivare (to take captive), from capere (to take)',
    },
    {
        word: 'proclaim',
        definition: 'To announce something publicly and officially.',
        exampleSentence: 'The mayor will proclaim next week as Community Service Week.',
        partOfSpeech: 'verb',
        difficulty: 7,
        pattern: 'latin-roots',
        pronunciation: 'proh-KLAYM',
        etymology: 'Latin: proclamare (to cry out)',
    },
    {
        word: 'resilient',
        definition: 'Able to recover quickly from difficulties.',
        exampleSentence: 'She proved to be resilient after overcoming many challenges.',
        partOfSpeech: 'adjective',
        difficulty: 7,
        pattern: 'latin-roots',
        pronunciation: 'rih-ZIL-yunt',
        etymology: 'Latin: resilire (to spring back)',
    },

    // ── Greek Roots (difficulty 7-8) ───────────────────────────────────
    {
        word: 'telephone',
        definition: 'A device used to talk to someone far away.',
        exampleSentence: 'Alexander Graham Bell invented the telephone in 1876.',
        partOfSpeech: 'noun',
        difficulty: 7,
        pattern: 'greek-roots',
        pronunciation: 'TEL-uh-fohn',
        etymology: 'Greek: tele (far) + phone (voice, sound)',
    },
    {
        word: 'autograph',
        definition: 'A person\'s own handwritten signature, especially a famous person\'s.',
        exampleSentence: 'The young fan asked the basketball star for an autograph.',
        partOfSpeech: 'noun',
        difficulty: 7,
        pattern: 'greek-roots',
        pronunciation: 'AW-toh-graf',
        etymology: 'Greek: autos (self) + graphein (to write)',
    },
    {
        word: 'biography',
        definition: 'A written account of someone\'s life by another person.',
        exampleSentence: 'She read a biography of Abraham Lincoln for her book report.',
        partOfSpeech: 'noun',
        difficulty: 7,
        pattern: 'greek-roots',
        pronunciation: 'by-OG-ruh-fee',
        etymology: 'Greek: bios (life) + graphein (to write)',
    },
    {
        word: 'photograph',
        definition: 'An image captured by a camera.',
        exampleSentence: 'The old photograph showed her grandparents on their wedding day.',
        partOfSpeech: 'noun',
        difficulty: 7,
        pattern: 'greek-roots',
        pronunciation: 'FOH-toh-graf',
        etymology: 'Greek: photos (light) + graphein (to write, draw)',
    },
    {
        word: 'microscope',
        definition: 'An instrument that magnifies tiny objects so they can be seen.',
        exampleSentence: 'We looked at plant cells through a microscope in science class.',
        partOfSpeech: 'noun',
        difficulty: 7,
        pattern: 'greek-roots',
        pronunciation: 'MY-kroh-skohp',
        etymology: 'Greek: mikros (small) + skopein (to look at)',
    },
    {
        word: 'geography',
        definition: 'The study of the earth\'s surface, features, and people.',
        exampleSentence: 'In geography class, we learned about the continents and oceans.',
        partOfSpeech: 'noun',
        difficulty: 7,
        pattern: 'greek-roots',
        pronunciation: 'jee-OG-ruh-fee',
        etymology: 'Greek: geo (earth) + graphein (to write, describe)',
    },
    {
        word: 'democracy',
        definition: 'A system of government in which people vote to choose leaders.',
        exampleSentence: 'In a democracy, every citizen has the right to vote.',
        partOfSpeech: 'noun',
        difficulty: 7,
        pattern: 'greek-roots',
        pronunciation: 'dih-MOK-ruh-see',
        etymology: 'Greek: demos (people) + kratos (rule, power)',
    },
    {
        word: 'synonym',
        definition: 'A word that has the same or nearly the same meaning as another word.',
        exampleSentence: '"Happy" and "joyful" are synonyms.',
        partOfSpeech: 'noun',
        difficulty: 7,
        pattern: 'greek-roots',
        pronunciation: 'SIN-uh-nim',
        etymology: 'Greek: syn (together) + onoma (name)',
    },
    {
        word: 'thermometer',
        definition: 'A device for measuring temperature.',
        exampleSentence: 'The thermometer showed that the temperature was ninety degrees.',
        partOfSpeech: 'noun',
        difficulty: 7,
        pattern: 'greek-roots',
        pronunciation: 'thur-MOM-uh-tur',
        etymology: 'Greek: therme (heat) + metron (measure)',
    },
    {
        word: 'astronaut',
        definition: 'A person trained to travel in a spacecraft.',
        exampleSentence: 'The astronaut floated in zero gravity aboard the space station.',
        partOfSpeech: 'noun',
        difficulty: 7,
        pattern: 'greek-roots',
        pronunciation: 'AS-troh-nawt',
        etymology: 'Greek: astron (star) + nautes (sailor)',
    },
    {
        word: 'hydrate',
        definition: 'To supply water to the body or another substance.',
        exampleSentence: 'It is important to hydrate by drinking water during exercise.',
        partOfSpeech: 'verb',
        difficulty: 7,
        pattern: 'greek-roots',
        pronunciation: 'HY-drayt',
        etymology: 'Greek: hydor (water)',
    },
    {
        word: 'chronological',
        definition: 'Arranged in the order in which events happened.',
        exampleSentence: 'The history book presented events in chronological order.',
        partOfSpeech: 'adjective',
        difficulty: 7,
        pattern: 'greek-roots',
        pronunciation: 'kron-uh-LOJ-ih-kul',
        etymology: 'Greek: chronos (time) + logos (study)',
    },
    {
        word: 'mythology',
        definition: 'A collection of traditional stories about gods and heroes.',
        exampleSentence: 'Greek mythology includes tales of Zeus and Athena.',
        partOfSpeech: 'noun',
        difficulty: 7,
        pattern: 'greek-roots',
        pronunciation: 'mih-THOL-uh-jee',
        etymology: 'Greek: mythos (story) + logos (study, word)',
    },
    {
        word: 'technology',
        definition: 'The use of science to create tools, machines, and systems.',
        exampleSentence: 'New technology has changed how we communicate with each other.',
        partOfSpeech: 'noun',
        difficulty: 7,
        pattern: 'greek-roots',
        pronunciation: 'tek-NOL-uh-jee',
        etymology: 'Greek: techne (art, skill) + logos (study)',
    },
    {
        word: 'hypothesis',
        definition: 'An educated guess or proposed explanation to be tested.',
        exampleSentence: 'The scientist formed a hypothesis before starting the experiment.',
        partOfSpeech: 'noun',
        difficulty: 8,
        pattern: 'greek-roots',
        pronunciation: 'hy-POTH-uh-sis',
        etymology: 'Greek: hypo (under) + thesis (placing, proposition)',
    },
    {
        word: 'philanthropy',
        definition: 'The desire to help others, especially through donations.',
        exampleSentence: 'Her philanthropy helped build a new library for the community.',
        partOfSpeech: 'noun',
        difficulty: 8,
        pattern: 'greek-roots',
        pronunciation: 'fih-LAN-thruh-pee',
        etymology: 'Greek: philos (loving) + anthropos (human being)',
    },
    {
        word: 'phenomenon',
        definition: 'A remarkable event or fact that can be observed.',
        exampleSentence: 'A solar eclipse is a fascinating natural phenomenon.',
        partOfSpeech: 'noun',
        difficulty: 8,
        pattern: 'greek-roots',
        pronunciation: 'feh-NOM-uh-non',
        etymology: 'Greek: phainomenon (thing appearing), from phainein (to show)',
    },
    {
        word: 'catastrophe',
        definition: 'A sudden and widespread disaster.',
        exampleSentence: 'The flood was a catastrophe that affected thousands of families.',
        partOfSpeech: 'noun',
        difficulty: 8,
        pattern: 'greek-roots',
        pronunciation: 'kuh-TAS-truh-fee',
        etymology: 'Greek: katastrophe (overturning), from kata (down) + strephein (to turn)',
    },
    {
        word: 'anonymous',
        definition: 'Not identified by name; of unknown identity.',
        exampleSentence: 'The generous donation was made by an anonymous benefactor.',
        partOfSpeech: 'adjective',
        difficulty: 8,
        pattern: 'greek-roots',
        pronunciation: 'uh-NON-uh-mus',
        etymology: 'Greek: anonymos (nameless), from an (without) + onoma (name)',
    },
    {
        word: 'parallelogram',
        definition: 'A four-sided shape with opposite sides that are parallel and equal.',
        exampleSentence: 'We learned how to calculate the area of a parallelogram in geometry.',
        partOfSpeech: 'noun',
        difficulty: 8,
        pattern: 'greek-roots',
        pronunciation: 'pair-uh-LEL-oh-gram',
        etymology: 'Greek: parallelos (beside one another) + gramma (something written or drawn)',
    },
    {
        word: 'metamorphosis',
        definition: 'A major change in form or appearance, especially in biology.',
        exampleSentence: 'A caterpillar undergoes metamorphosis to become a butterfly.',
        partOfSpeech: 'noun',
        difficulty: 8,
        pattern: 'greek-roots',
        pronunciation: 'met-uh-MOR-fuh-sis',
        etymology: 'Greek: meta (change) + morphe (form)',
    },
    {
        word: 'bibliography',
        definition: 'A list of books and sources used in a research paper.',
        exampleSentence: 'The teacher required a bibliography at the end of every research paper.',
        partOfSpeech: 'noun',
        difficulty: 8,
        pattern: 'greek-roots',
        pronunciation: 'bib-lee-OG-ruh-fee',
        etymology: 'Greek: biblion (book) + graphein (to write)',
    },
    {
        word: 'philosophical',
        definition: 'Relating to the study of fundamental questions about life and knowledge.',
        exampleSentence: 'The students had a philosophical debate about the meaning of fairness.',
        partOfSpeech: 'adjective',
        difficulty: 8,
        pattern: 'greek-roots',
        pronunciation: 'fil-uh-SOF-ih-kul',
        etymology: 'Greek: philosophia (love of wisdom), from philos (loving) + sophia (wisdom)',
    },
    {
        word: 'archaeology',
        definition: 'The study of human history through the excavation of ancient sites.',
        exampleSentence: 'Archaeology helped us learn about how ancient Egyptians lived.',
        partOfSpeech: 'noun',
        difficulty: 8,
        pattern: 'greek-roots',
        pronunciation: 'ar-kee-OL-uh-jee',
        etymology: 'Greek: archaios (ancient) + logos (study)',
    },
    {
        word: 'atmosphere',
        definition: 'The layer of gases surrounding the earth.',
        exampleSentence: 'The atmosphere protects us from harmful radiation from the sun.',
        partOfSpeech: 'noun',
        difficulty: 7,
        pattern: 'greek-roots',
        pronunciation: 'AT-mus-feer',
        etymology: 'Greek: atmos (vapor) + sphaira (sphere)',
    },
    {
        word: 'polygon',
        definition: 'A flat shape with three or more straight sides.',
        exampleSentence: 'A hexagon is a polygon with six sides.',
        partOfSpeech: 'noun',
        difficulty: 7,
        pattern: 'greek-roots',
        pronunciation: 'POL-ee-gon',
        etymology: 'Greek: poly (many) + gonia (angle)',
    },
    {
        word: 'diagnosis',
        definition: 'The identification of a disease or problem through examination.',
        exampleSentence: 'The doctor made a diagnosis after reviewing the test results.',
        partOfSpeech: 'noun',
        difficulty: 8,
        pattern: 'greek-roots',
        pronunciation: 'dy-ug-NOH-sis',
        etymology: 'Greek: dia (through) + gnosis (knowledge)',
    },
    {
        word: 'therapeutic',
        definition: 'Relating to the treatment or healing of a disease or condition.',
        exampleSentence: 'Listening to music can be therapeutic after a stressful day.',
        partOfSpeech: 'adjective',
        difficulty: 8,
        pattern: 'greek-roots',
        pronunciation: 'thair-uh-PYOO-tik',
        etymology: 'Greek: therapeutikos (inclined to serve), from therapeuein (to heal)',
    },
    {
        word: 'symphony',
        definition: 'A long musical composition for an orchestra, usually in four movements.',
        exampleSentence: 'Beethoven composed his famous fifth symphony despite losing his hearing.',
        partOfSpeech: 'noun',
        difficulty: 7,
        pattern: 'greek-roots',
        pronunciation: 'SIM-fuh-nee',
        etymology: 'Greek: symphonia (agreement in sound), from syn (together) + phone (sound)',
    },
    {
        word: 'pseudonym',
        definition: 'A fictitious name used by an author instead of their real name.',
        exampleSentence: 'Mark Twain was the pseudonym of Samuel Clemens.',
        partOfSpeech: 'noun',
        difficulty: 8,
        pattern: 'greek-roots',
        pronunciation: 'SOO-doh-nim',
        etymology: 'Greek: pseudonymos (having a false name), from pseudo (false) + onoma (name)',
    },
    {
        word: 'photosynthesis',
        definition: 'The process by which plants use sunlight to make food from carbon dioxide and water.',
        exampleSentence: 'Photosynthesis is how plants convert sunlight into energy.',
        partOfSpeech: 'noun',
        difficulty: 8,
        pattern: 'greek-roots',
        pronunciation: 'foh-toh-SIN-thuh-sis',
        etymology: 'Greek: photos (light) + synthesis (putting together)',
    },
    {
        word: 'hemisphere',
        definition: 'One half of the earth, divided by the equator or a meridian.',
        exampleSentence: 'Australia is located in the Southern Hemisphere.',
        partOfSpeech: 'noun',
        difficulty: 7,
        pattern: 'greek-roots',
        pronunciation: 'HEM-ih-sfeer',
        etymology: 'Greek: hemi (half) + sphaira (sphere)',
    },
    {
        word: 'perimeter',
        definition: 'The total distance around the outside of a shape.',
        exampleSentence: 'We calculated the perimeter of the rectangular field.',
        partOfSpeech: 'noun',
        difficulty: 7,
        pattern: 'greek-roots',
        pronunciation: 'puh-RIM-uh-tur',
        etymology: 'Greek: peri (around) + metron (measure)',
    },
    {
        word: 'epidemic',
        definition: 'A widespread outbreak of disease in a community.',
        exampleSentence: 'The flu epidemic caused many schools to close for the week.',
        partOfSpeech: 'noun',
        difficulty: 8,
        pattern: 'greek-roots',
        pronunciation: 'ep-ih-DEM-ik',
        etymology: 'Greek: epidemia (prevalence of disease), from epi (upon) + demos (people)',
    },
    {
        word: 'aristocrat',
        definition: 'A member of the highest social class or nobility.',
        exampleSentence: 'The aristocrat lived in a grand mansion on the hill.',
        partOfSpeech: 'noun',
        difficulty: 8,
        pattern: 'greek-roots',
        pronunciation: 'uh-RIS-toh-krat',
        etymology: 'Greek: aristos (best) + kratos (rule, power)',
    },
    {
        word: 'monologue',
        definition: 'A long speech by one person, often in a play.',
        exampleSentence: 'The actor delivered a powerful monologue in the final act.',
        partOfSpeech: 'noun',
        difficulty: 8,
        pattern: 'greek-roots',
        pronunciation: 'MON-uh-log',
        etymology: 'Greek: monos (alone) + logos (speech, word)',
    },
    {
        word: 'protagonist',
        definition: 'The main character in a story, play, or movie.',
        exampleSentence: 'The protagonist of the novel overcame many challenges on her journey.',
        partOfSpeech: 'noun',
        difficulty: 8,
        pattern: 'greek-roots',
        pronunciation: 'proh-TAG-uh-nist',
        etymology: 'Greek: protos (first) + agonistes (actor, combatant)',
    },
    {
        word: 'eccentric',
        definition: 'Unconventional and slightly strange in behavior.',
        exampleSentence: 'The eccentric inventor filled his house with unusual gadgets.',
        partOfSpeech: 'adjective',
        difficulty: 8,
        pattern: 'greek-roots',
        pronunciation: 'ek-SEN-trik',
        etymology: 'Greek: ekkentros (out of center), from ek (out) + kentron (center)',
    },

    // ── Irregular (difficulty 7) ───────────────────────────────────────
    {
        word: 'colonel',
        definition: 'A high-ranking military officer.',
        exampleSentence: 'The colonel led his troops through the difficult terrain.',
        partOfSpeech: 'noun',
        difficulty: 7,
        pattern: 'irregular',
        pronunciation: 'KUR-nul',
        etymology: 'Italian: colonnello (commander of a column of soldiers)',
    },
    {
        word: 'tsunami',
        definition: 'A very large ocean wave caused by an underwater earthquake.',
        exampleSentence: 'The tsunami destroyed buildings along the coast.',
        partOfSpeech: 'noun',
        difficulty: 7,
        pattern: 'irregular',
        pronunciation: 'tsoo-NAH-mee',
        etymology: 'Japanese: tsu (harbor) + nami (wave)',
    },
    {
        word: 'pneumonia',
        definition: 'A serious lung infection that causes difficulty breathing.',
        exampleSentence: 'She was hospitalized with pneumonia during the winter.',
        partOfSpeech: 'noun',
        difficulty: 7,
        pattern: 'irregular',
        pronunciation: 'noo-MOHN-yuh',
        etymology: 'Greek: pneumon (lung)',
    },
    {
        word: 'psychology',
        definition: 'The scientific study of the mind and human behavior.',
        exampleSentence: 'She studied psychology to understand why people behave the way they do.',
        partOfSpeech: 'noun',
        difficulty: 7,
        pattern: 'irregular',
        pronunciation: 'sy-KOL-uh-jee',
        etymology: 'Greek: psyche (mind, soul) + logos (study)',
    },
    {
        word: 'rhythm',
        definition: 'A strong, regular repeated pattern of movement or sound.',
        exampleSentence: 'The drummer kept a steady rhythm throughout the song.',
        partOfSpeech: 'noun',
        difficulty: 7,
        pattern: 'irregular',
        pronunciation: 'RITH-um',
        etymology: 'Greek: rhythmos (measured flow, movement)',
    },
    {
        word: 'conscience',
        definition: 'An inner sense of right and wrong that guides behavior.',
        exampleSentence: 'His conscience told him to return the wallet he found.',
        partOfSpeech: 'noun',
        difficulty: 7,
        pattern: 'irregular',
        pronunciation: 'KON-shunss',
        etymology: 'Latin: conscientia (knowledge within oneself)',
    },
    {
        word: 'receipt',
        definition: 'A written record showing that a payment has been made.',
        exampleSentence: 'She kept the receipt in case she needed to return the shoes.',
        partOfSpeech: 'noun',
        difficulty: 7,
        pattern: 'irregular',
        pronunciation: 'rih-SEET',
        etymology: 'Old French: receite, from Latin recipere (to receive)',
    },
    {
        word: 'scissors',
        definition: 'A tool with two sharp blades used for cutting.',
        exampleSentence: 'She used scissors to cut out the paper snowflakes.',
        partOfSpeech: 'noun',
        difficulty: 7,
        pattern: 'irregular',
        pronunciation: 'SIZ-urz',
        etymology: 'Latin: cisorium (cutting instrument), from caedere (to cut)',
    },
    {
        word: 'mischievous',
        definition: 'Playfully causing trouble or annoyance.',
        exampleSentence: 'The mischievous raccoon knocked over the trash cans every night.',
        partOfSpeech: 'adjective',
        difficulty: 7,
        pattern: 'irregular',
        pronunciation: 'MIS-chuh-vus',
        etymology: 'Old French: meschief (misfortune, trouble)',
    },
    {
        word: 'guarantee',
        definition: 'A promise that something will meet certain standards or conditions.',
        exampleSentence: 'The store offered a money-back guarantee on all products.',
        partOfSpeech: 'noun',
        difficulty: 7,
        pattern: 'irregular',
        pronunciation: 'gair-un-TEE',
        etymology: 'Old French: garantie (protection, pledge)',
    },
    {
        word: 'queue',
        definition: 'A line of people or vehicles waiting for their turn.',
        exampleSentence: 'We waited in the queue for thirty minutes to enter the exhibit.',
        partOfSpeech: 'noun',
        difficulty: 7,
        pattern: 'irregular',
        pronunciation: 'KYOO',
        etymology: 'French: queue (tail), from Latin cauda (tail)',
    },
    {
        word: 'mortgage',
        definition: 'A loan used to buy property, paid back over many years.',
        exampleSentence: 'My parents finally paid off the mortgage on our house.',
        partOfSpeech: 'noun',
        difficulty: 7,
        pattern: 'irregular',
        pronunciation: 'MOR-gij',
        etymology: 'Old French: mort gage (dead pledge)',
    },
    {
        word: 'thoroughly',
        definition: 'In a complete and careful way.',
        exampleSentence: 'She thoroughly cleaned the kitchen before the guests arrived.',
        partOfSpeech: 'adverb',
        difficulty: 7,
        pattern: 'irregular',
        pronunciation: 'THUR-oh-lee',
        etymology: 'Old English: thuruh (through)',
    },
    {
        word: 'accommodate',
        definition: 'To provide space or make adjustments for someone.',
        exampleSentence: 'The hotel can accommodate up to two hundred guests.',
        partOfSpeech: 'verb',
        difficulty: 7,
        pattern: 'irregular',
        pronunciation: 'uh-KOM-uh-dayt',
        etymology: 'Latin: accommodare (to make fitting), from commodus (suitable)',
    },
    {
        word: 'occurrence',
        definition: 'An event or instance of something happening.',
        exampleSentence: 'Seeing a shooting star is a rare occurrence.',
        partOfSpeech: 'noun',
        difficulty: 7,
        pattern: 'irregular',
        pronunciation: 'uh-KUR-unss',
        etymology: 'Latin: occurrere (to run to meet, present itself)',
    },
    {
        word: 'lieutenant',
        definition: 'A military officer of middle rank, below a captain.',
        exampleSentence: 'The lieutenant received orders from the captain.',
        partOfSpeech: 'noun',
        difficulty: 7,
        pattern: 'irregular',
        pronunciation: 'loo-TEN-unt',
        etymology: 'French: lieu (place) + tenant (holding)',
    },
    {
        word: 'February',
        definition: 'The second month of the year.',
        exampleSentence: 'Valentine\'s Day is celebrated on the fourteenth of February.',
        partOfSpeech: 'noun',
        difficulty: 7,
        pattern: 'irregular',
        pronunciation: 'FEB-roo-air-ee',
        etymology: 'Latin: Februarius (month of purification), from februa (purification rites)',
    },
    {
        word: 'Wednesday',
        definition: 'The day of the week between Tuesday and Thursday.',
        exampleSentence: 'Our piano lessons are every Wednesday afternoon.',
        partOfSpeech: 'noun',
        difficulty: 7,
        pattern: 'irregular',
        pronunciation: 'WENZ-day',
        etymology: 'Old English: Wodnesdaeg (day of Woden, a Norse god)',
    },
    {
        word: 'necessary',
        definition: 'Needed; required for a purpose.',
        exampleSentence: 'It is necessary to study if you want to pass the exam.',
        partOfSpeech: 'adjective',
        difficulty: 7,
        pattern: 'irregular',
        pronunciation: 'NES-uh-sair-ee',
        etymology: 'Latin: necessarius (unavoidable, indispensable)',
    },
    {
        word: 'amateur',
        definition: 'A person who does an activity for enjoyment, not as a profession.',
        exampleSentence: 'The amateur photographer took surprisingly beautiful pictures.',
        partOfSpeech: 'noun',
        difficulty: 7,
        pattern: 'irregular',
        pronunciation: 'AM-uh-chur',
        etymology: 'French: amateur (lover of), from Latin amare (to love)',
    },

    // ── French Origin (difficulty 8) ───────────────────────────────────
    {
        word: 'restaurant',
        definition: 'A place where meals are prepared and served to customers.',
        exampleSentence: 'We had dinner at an Italian restaurant downtown.',
        partOfSpeech: 'noun',
        difficulty: 8,
        pattern: 'french-origin',
        pronunciation: 'RES-tuh-rawnt',
        etymology: 'French: restaurant (restoring), from restaurer (to restore)',
    },
    {
        word: 'ballet',
        definition: 'A graceful style of dance performed on stage.',
        exampleSentence: 'She practiced ballet for years before performing in her first recital.',
        partOfSpeech: 'noun',
        difficulty: 8,
        pattern: 'french-origin',
        pronunciation: 'ba-LAY',
        etymology: 'French: ballet (a dance), from Italian balletto (little dance)',
    },
    {
        word: 'boutique',
        definition: 'A small shop that sells fashionable clothes or accessories.',
        exampleSentence: 'She found a unique dress at the boutique on Main Street.',
        partOfSpeech: 'noun',
        difficulty: 8,
        pattern: 'french-origin',
        pronunciation: 'boo-TEEK',
        etymology: 'French: boutique (small shop)',
    },
    {
        word: 'champagne',
        definition: 'A sparkling white wine from the Champagne region of France.',
        exampleSentence: 'They raised glasses of champagne to toast the New Year.',
        partOfSpeech: 'noun',
        difficulty: 8,
        pattern: 'french-origin',
        pronunciation: 'sham-PAYN',
        etymology: 'French: Champagne (region in France where it originated)',
    },
    {
        word: 'entrepreneur',
        definition: 'A person who starts and runs their own business.',
        exampleSentence: 'The young entrepreneur launched a successful app before graduating college.',
        partOfSpeech: 'noun',
        difficulty: 8,
        pattern: 'french-origin',
        pronunciation: 'on-truh-pruh-NUR',
        etymology: 'French: entrepreneur (one who undertakes), from entreprendre (to undertake)',
    },
    {
        word: 'chauffeur',
        definition: 'A person employed to drive a private car.',
        exampleSentence: 'The chauffeur opened the car door for the ambassador.',
        partOfSpeech: 'noun',
        difficulty: 8,
        pattern: 'french-origin',
        pronunciation: 'SHOH-fur',
        etymology: 'French: chauffeur (stoker, driver), from chauffer (to heat)',
    },
    {
        word: 'souvenir',
        definition: 'A small item kept as a reminder of a place or event.',
        exampleSentence: 'She bought a snow globe as a souvenir from her trip to Paris.',
        partOfSpeech: 'noun',
        difficulty: 8,
        pattern: 'french-origin',
        pronunciation: 'soo-vuh-NEER',
        etymology: 'French: souvenir (to remember), from Latin subvenire (to come to mind)',
    },
    {
        word: 'silhouette',
        definition: 'A dark outline or shadow of something seen against a lighter background.',
        exampleSentence: 'The silhouette of the mountain was visible against the orange sky.',
        partOfSpeech: 'noun',
        difficulty: 8,
        pattern: 'french-origin',
        pronunciation: 'sil-oo-ET',
        etymology: 'French: named after Etienne de Silhouette, a French finance minister',
    },
    {
        word: 'brochure',
        definition: 'A small booklet with information about a product or place.',
        exampleSentence: 'We picked up a brochure about the national park at the visitor center.',
        partOfSpeech: 'noun',
        difficulty: 8,
        pattern: 'french-origin',
        pronunciation: 'broh-SHUR',
        etymology: 'French: brochure (stitched work), from brocher (to stitch)',
    },
    {
        word: 'fiancee',
        definition: 'A woman who is engaged to be married.',
        exampleSentence: 'He introduced his fiancee to the rest of the family at dinner.',
        partOfSpeech: 'noun',
        difficulty: 8,
        pattern: 'french-origin',
        pronunciation: 'fee-on-SAY',
        etymology: 'French: fiancee (betrothed woman), from fiancer (to betroth)',
    },
    {
        word: 'plateau',
        definition: 'A large flat area of land higher than the surrounding area.',
        exampleSentence: 'The hikers reached a plateau with a stunning view of the valley below.',
        partOfSpeech: 'noun',
        difficulty: 8,
        pattern: 'french-origin',
        pronunciation: 'pla-TOH',
        etymology: 'French: plateau (flat surface), from plat (flat)',
    },
    {
        word: 'rendezvous',
        definition: 'A meeting at an agreed time and place.',
        exampleSentence: 'The two ships had a rendezvous at the port before sailing together.',
        partOfSpeech: 'noun',
        difficulty: 8,
        pattern: 'french-origin',
        pronunciation: 'RON-day-voo',
        etymology: 'French: rendez-vous (present yourselves)',
    },
    {
        word: 'lingerie',
        definition: 'Lightweight undergarments or sleepwear for women.',
        exampleSentence: 'The department store had a large lingerie section on the second floor.',
        partOfSpeech: 'noun',
        difficulty: 8,
        pattern: 'french-origin',
        pronunciation: 'lon-zhuh-RAY',
        etymology: 'French: lingerie (linen goods), from linge (linen)',
    },
    {
        word: 'gourmet',
        definition: 'Relating to high-quality, finely prepared food.',
        exampleSentence: 'The gourmet chef prepared a five-course meal for the guests.',
        partOfSpeech: 'adjective',
        difficulty: 8,
        pattern: 'french-origin',
        pronunciation: 'gor-MAY',
        etymology: 'French: gourmet (wine taster, refined palate)',
    },
    {
        word: 'surveillance',
        definition: 'Close observation, especially of a suspected person.',
        exampleSentence: 'Security cameras provide surveillance of the building at all times.',
        partOfSpeech: 'noun',
        difficulty: 8,
        pattern: 'french-origin',
        pronunciation: 'sur-VAY-lunss',
        etymology: 'French: surveillance (watching over), from surveiller (to watch over)',
    },
    {
        word: 'debris',
        definition: 'Scattered pieces of rubbish or remains of something destroyed.',
        exampleSentence: 'The storm left debris scattered across the streets.',
        partOfSpeech: 'noun',
        difficulty: 8,
        pattern: 'french-origin',
        pronunciation: 'duh-BREE',
        etymology: 'French: debris (broken pieces), from debriser (to break down)',
    },
    {
        word: 'liaison',
        definition: 'A close connection or link between groups or people.',
        exampleSentence: 'She served as the liaison between the school and the parent committee.',
        partOfSpeech: 'noun',
        difficulty: 8,
        pattern: 'french-origin',
        pronunciation: 'lee-AY-zon',
        etymology: 'French: liaison (connection), from lier (to bind)',
    },
    {
        word: 'critique',
        definition: 'A detailed evaluation or analysis of something.',
        exampleSentence: 'The art teacher gave a thoughtful critique of each student\'s painting.',
        partOfSpeech: 'noun',
        difficulty: 8,
        pattern: 'french-origin',
        pronunciation: 'krih-TEEK',
        etymology: 'French: critique (critical analysis), from Greek kritike (art of judgment)',
    },
    {
        word: 'technique',
        definition: 'A particular way of doing something skillfully.',
        exampleSentence: 'The pianist practiced her technique for hours every day.',
        partOfSpeech: 'noun',
        difficulty: 8,
        pattern: 'french-origin',
        pronunciation: 'tek-NEEK',
        etymology: 'French: technique (method of performance), from Greek techne (art, skill)',
    },
    {
        word: 'reservoir',
        definition: 'A large natural or artificial lake used to store water.',
        exampleSentence: 'The city built a new reservoir to store drinking water.',
        partOfSpeech: 'noun',
        difficulty: 8,
        pattern: 'french-origin',
        pronunciation: 'REZ-ur-vwahr',
        etymology: 'French: reservoir (storehouse), from reserver (to reserve)',
    },
];
