/**
 * words/tier2.ts
 *
 * ~200 curated words for 2nd-3rd grade (difficulty 3-4).
 * Covers silent-e, vowel-teams, r-controlled vowels, and diphthongs.
 */

import type { SpellingWord } from './types';

export const TIER_2_WORDS: SpellingWord[] = [
    // ─────────────────────────────────────────────
    // SILENT-E  (~50 words, difficulty 3)
    // ─────────────────────────────────────────────
    {
        word: 'cake',
        definition: 'A sweet baked dessert, often with frosting.',
        exampleSentence: 'We made a chocolate cake for her birthday.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'silent-e',
        pronunciation: 'kayk',
    },
    {
        word: 'bike',
        definition: 'A two-wheeled vehicle you pedal with your feet.',
        exampleSentence: 'I ride my bike to school every morning.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'silent-e',
        pronunciation: 'byke',
    },
    {
        word: 'note',
        definition: 'A short written message or a single musical sound.',
        exampleSentence: 'She left a note on the kitchen table.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'silent-e',
        pronunciation: 'noht',
    },
    {
        word: 'hope',
        definition: 'A feeling of wanting something good to happen.',
        exampleSentence: 'I hope we can go to the park today.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'silent-e',
        pronunciation: 'hohp',
    },
    {
        word: 'tune',
        definition: 'A melody or series of musical notes.',
        exampleSentence: 'He hummed a cheerful tune while he walked.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'silent-e',
        pronunciation: 'toon',
    },
    {
        word: 'make',
        definition: 'To create or build something.',
        exampleSentence: 'Let us make a card for Grandma.',
        partOfSpeech: 'verb',
        difficulty: 3,
        pattern: 'silent-e',
        pronunciation: 'mayk',
    },
    {
        word: 'like',
        definition: 'To enjoy or feel good about something.',
        exampleSentence: 'I like reading books before bed.',
        partOfSpeech: 'verb',
        difficulty: 3,
        pattern: 'silent-e',
        pronunciation: 'lyke',
    },
    {
        word: 'home',
        definition: 'The place where a person lives.',
        exampleSentence: 'We walked home after school.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'silent-e',
        pronunciation: 'hohm',
    },
    {
        word: 'name',
        definition: 'What a person or thing is called.',
        exampleSentence: 'Please write your name at the top of the page.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'silent-e',
        pronunciation: 'naym',
    },
    {
        word: 'time',
        definition: 'The ongoing sequence of hours, minutes, and seconds.',
        exampleSentence: 'What time does the movie start?',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'silent-e',
        pronunciation: 'tyme',
    },
    {
        word: 'ride',
        definition: 'To sit on and move along on something, like a bike or horse.',
        exampleSentence: 'Can I ride the horse at the farm?',
        partOfSpeech: 'verb',
        difficulty: 3,
        pattern: 'silent-e',
        pronunciation: 'ryde',
    },
    {
        word: 'late',
        definition: 'After the expected or usual time.',
        exampleSentence: 'We were late because of the traffic.',
        partOfSpeech: 'adjective',
        difficulty: 3,
        pattern: 'silent-e',
        pronunciation: 'layt',
    },
    {
        word: 'shine',
        definition: 'To give off a bright light.',
        exampleSentence: 'The stars shine brightly at night.',
        partOfSpeech: 'verb',
        difficulty: 3,
        pattern: 'silent-e',
        pronunciation: 'shyne',
    },
    {
        word: 'bone',
        definition: 'A hard, white part inside the body that makes up the skeleton.',
        exampleSentence: 'The dog buried a bone in the yard.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'silent-e',
        pronunciation: 'bohn',
    },
    {
        word: 'grape',
        definition: 'A small, round fruit that grows in bunches on a vine.',
        exampleSentence: 'She packed a bunch of grapes in her lunch.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'silent-e',
        pronunciation: 'grayp',
    },
    {
        word: 'rose',
        definition: 'A flower with thorns and a sweet smell.',
        exampleSentence: 'He gave his mom a red rose.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'silent-e',
        pronunciation: 'rohz',
        etymology: 'From Latin "rosa," meaning a type of flower.',
    },
    {
        word: 'wave',
        definition: 'A moving ridge of water, or to move your hand back and forth.',
        exampleSentence: 'A big wave crashed on the shore.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'silent-e',
        pronunciation: 'wayv',
    },
    {
        word: 'plane',
        definition: 'A vehicle with wings that flies through the air.',
        exampleSentence: 'The plane flew high above the clouds.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'silent-e',
        pronunciation: 'playn',
    },
    {
        word: 'smoke',
        definition: 'The gray or black cloud that comes from something burning.',
        exampleSentence: 'Smoke rose from the campfire.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'silent-e',
        pronunciation: 'smohk',
    },
    {
        word: 'flute',
        definition: 'A musical instrument you blow across to play.',
        exampleSentence: 'She plays the flute in the school band.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'silent-e',
        pronunciation: 'floot',
        etymology: 'From Old French "flaute," a wind instrument.',
    },
    {
        word: 'smile',
        definition: 'A happy expression made by turning up the corners of the mouth.',
        exampleSentence: 'Her smile made everyone feel welcome.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'silent-e',
        pronunciation: 'smyle',
    },
    {
        word: 'stone',
        definition: 'A small piece of rock.',
        exampleSentence: 'He skipped a stone across the lake.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'silent-e',
        pronunciation: 'stohn',
    },
    {
        word: 'broke',
        definition: 'Past tense of break; damaged or separated into pieces.',
        exampleSentence: 'The vase broke when it fell off the shelf.',
        partOfSpeech: 'verb',
        difficulty: 3,
        pattern: 'silent-e',
        pronunciation: 'brohk',
    },
    {
        word: 'trade',
        definition: 'To exchange one thing for another.',
        exampleSentence: 'I will trade my apple for your orange.',
        partOfSpeech: 'verb',
        difficulty: 3,
        pattern: 'silent-e',
        pronunciation: 'trayd',
    },
    {
        word: 'flame',
        definition: 'The bright, hot part of a fire.',
        exampleSentence: 'The candle flame flickered in the wind.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'silent-e',
        pronunciation: 'flaym',
    },
    {
        word: 'drove',
        definition: 'Past tense of drive; operated a car or vehicle.',
        exampleSentence: 'Dad drove us to the beach.',
        partOfSpeech: 'verb',
        difficulty: 3,
        pattern: 'silent-e',
        pronunciation: 'drohv',
    },
    {
        word: 'prize',
        definition: 'A reward given to a winner.',
        exampleSentence: 'She won first prize at the science fair.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'silent-e',
        pronunciation: 'pryz',
    },
    {
        word: 'froze',
        definition: 'Past tense of freeze; became solid from cold.',
        exampleSentence: 'The pond froze over during the winter.',
        partOfSpeech: 'verb',
        difficulty: 3,
        pattern: 'silent-e',
        pronunciation: 'frohz',
    },
    {
        word: 'scale',
        definition: 'A device used for weighing things, or a set of ordered steps.',
        exampleSentence: 'She placed the fruit on the scale.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'silent-e',
        pronunciation: 'skayl',
    },
    {
        word: 'spine',
        definition: 'The column of bones running down the middle of the back.',
        exampleSentence: 'Your spine helps you stand up straight.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'silent-e',
        pronunciation: 'spyne',
    },
    {
        word: 'whale',
        definition: 'A very large sea mammal that breathes air.',
        exampleSentence: 'We saw a whale jump out of the water.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'silent-e',
        pronunciation: 'wayl',
    },
    {
        word: 'shade',
        definition: 'A cool area out of direct sunlight.',
        exampleSentence: 'We sat in the shade under the big tree.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'silent-e',
        pronunciation: 'shayd',
    },
    {
        word: 'slope',
        definition: 'Ground that slants upward or downward.',
        exampleSentence: 'The sled zoomed down the snowy slope.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'silent-e',
        pronunciation: 'slohp',
    },
    {
        word: 'stove',
        definition: 'An appliance used for cooking food.',
        exampleSentence: 'Mom heated the soup on the stove.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'silent-e',
        pronunciation: 'stohv',
    },
    {
        word: 'taste',
        definition: 'The flavor of food or drink sensed by the tongue.',
        exampleSentence: 'This lemonade has a sweet taste.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'silent-e',
        pronunciation: 'tayst',
    },
    {
        word: 'glide',
        definition: 'To move smoothly and quietly.',
        exampleSentence: 'The swan seemed to glide across the lake.',
        partOfSpeech: 'verb',
        difficulty: 3,
        pattern: 'silent-e',
        pronunciation: 'glyde',
    },
    {
        word: 'quote',
        definition: 'The exact words someone has said or written.',
        exampleSentence: 'The teacher read a famous quote to the class.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'silent-e',
        pronunciation: 'kwoht',
    },
    {
        word: 'solve',
        definition: 'To find the answer to a problem.',
        exampleSentence: 'She tried to solve the math puzzle.',
        partOfSpeech: 'verb',
        difficulty: 3,
        pattern: 'silent-e',
        pronunciation: 'sahlv',
    },
    {
        word: 'close',
        definition: 'To shut something, or nearby.',
        exampleSentence: 'Please close the door when you leave.',
        partOfSpeech: 'verb',
        difficulty: 3,
        pattern: 'silent-e',
        pronunciation: 'klohz',
    },
    {
        word: 'globe',
        definition: 'A round model of the Earth.',
        exampleSentence: 'She found Australia on the globe.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'silent-e',
        pronunciation: 'glohb',
        etymology: 'From Latin "globus," meaning a round ball.',
    },
    {
        word: 'brave',
        definition: 'Willing to face danger or difficulty without fear.',
        exampleSentence: 'The brave firefighter ran into the building.',
        partOfSpeech: 'adjective',
        difficulty: 3,
        pattern: 'silent-e',
        pronunciation: 'brayv',
    },
    {
        word: 'stripe',
        definition: 'A long, narrow band of color.',
        exampleSentence: 'The tiger has an orange coat with black stripes.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'silent-e',
        pronunciation: 'strype',
    },
    {
        word: 'stare',
        definition: 'To look at something for a long time.',
        exampleSentence: 'Do not stare at the sun; it can hurt your eyes.',
        partOfSpeech: 'verb',
        difficulty: 3,
        pattern: 'silent-e',
        pronunciation: 'stair',
    },
    {
        word: 'space',
        definition: 'An empty area, or the area beyond the Earth where stars are.',
        exampleSentence: 'Astronauts travel into outer space.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'silent-e',
        pronunciation: 'spays',
    },
    {
        word: 'place',
        definition: 'A particular area or location.',
        exampleSentence: 'The library is my favorite place to read.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'silent-e',
        pronunciation: 'plays',
    },
    {
        word: 'quite',
        definition: 'To a large degree; very.',
        exampleSentence: 'The test was quite easy.',
        partOfSpeech: 'adverb',
        difficulty: 3,
        pattern: 'silent-e',
        pronunciation: 'kwyte',
    },
    {
        word: 'pride',
        definition: 'A feeling of happiness about something you did well.',
        exampleSentence: 'She felt pride when she finished the race.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'silent-e',
        pronunciation: 'pryde',
    },
    {
        word: 'scene',
        definition: 'A part of a play or movie, or a view of a place.',
        exampleSentence: 'The mountain scene was beautiful.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'silent-e',
        pronunciation: 'seen',
        etymology: 'From Greek "skene," meaning a tent or stage.',
    },
    {
        word: 'cube',
        definition: 'A solid shape with six equal square sides.',
        exampleSentence: 'She dropped an ice cube into her glass.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'silent-e',
        pronunciation: 'kyoob',
    },
    {
        word: 'chase',
        definition: 'To run after someone or something to catch them.',
        exampleSentence: 'The puppy loves to chase squirrels.',
        partOfSpeech: 'verb',
        difficulty: 3,
        pattern: 'silent-e',
        pronunciation: 'chays',
    },

    // ─────────────────────────────────────────────
    // VOWEL TEAMS  (~50 words, difficulty 3)
    // ─────────────────────────────────────────────
    {
        word: 'rain',
        definition: 'Water that falls from clouds in the sky.',
        exampleSentence: 'The rain made puddles on the sidewalk.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'vowel-teams',
        pronunciation: 'rayn',
    },
    {
        word: 'boat',
        definition: 'A small vessel used for traveling on water.',
        exampleSentence: 'We took a boat ride across the lake.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'vowel-teams',
        pronunciation: 'boht',
    },
    {
        word: 'moon',
        definition: 'The round object in the sky that shines at night.',
        exampleSentence: 'The moon was full and bright last night.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'vowel-teams',
        pronunciation: 'moon',
    },
    {
        word: 'dream',
        definition: 'Pictures and stories your mind creates while you sleep.',
        exampleSentence: 'I had a dream about flying over the ocean.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'vowel-teams',
        pronunciation: 'dreem',
    },
    {
        word: 'seed',
        definition: 'A tiny part of a plant from which a new plant can grow.',
        exampleSentence: 'She planted a seed in the garden.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'vowel-teams',
        pronunciation: 'seed',
    },
    {
        word: 'team',
        definition: 'A group of people who work or play together.',
        exampleSentence: 'Our soccer team won the game.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'vowel-teams',
        pronunciation: 'teem',
    },
    {
        word: 'road',
        definition: 'A path for cars and trucks to drive on.',
        exampleSentence: 'The road through the mountains was winding.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'vowel-teams',
        pronunciation: 'rohd',
    },
    {
        word: 'tail',
        definition: 'The part at the back end of an animal.',
        exampleSentence: 'The happy dog wagged its tail.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'vowel-teams',
        pronunciation: 'tayl',
    },
    {
        word: 'leaf',
        definition: 'A flat, green part of a plant that grows from a branch.',
        exampleSentence: 'A yellow leaf fell from the tree.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'vowel-teams',
        pronunciation: 'leef',
    },
    {
        word: 'goat',
        definition: 'A farm animal with horns and a short tail.',
        exampleSentence: 'The goat nibbled on the grass.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'vowel-teams',
        pronunciation: 'goht',
    },
    {
        word: 'bead',
        definition: 'A small, round object with a hole, often strung on thread.',
        exampleSentence: 'She threaded a bead onto the necklace.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'vowel-teams',
        pronunciation: 'beed',
    },
    {
        word: 'pain',
        definition: 'An unpleasant feeling when part of the body hurts.',
        exampleSentence: 'He felt pain in his knee after the fall.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'vowel-teams',
        pronunciation: 'payn',
    },
    {
        word: 'coat',
        definition: 'A warm outer garment worn over other clothes.',
        exampleSentence: 'Put on your coat before you go outside.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'vowel-teams',
        pronunciation: 'koht',
    },
    {
        word: 'food',
        definition: 'Things that people and animals eat.',
        exampleSentence: 'We brought food for the picnic.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'vowel-teams',
        pronunciation: 'food',
    },
    {
        word: 'cool',
        definition: 'Slightly cold, or very good and impressive.',
        exampleSentence: 'The cool breeze felt nice on a hot day.',
        partOfSpeech: 'adjective',
        difficulty: 3,
        pattern: 'vowel-teams',
        pronunciation: 'kool',
    },
    {
        word: 'cream',
        definition: 'The thick, white part of milk, or a smooth spread.',
        exampleSentence: 'She put cream in her hot chocolate.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'vowel-teams',
        pronunciation: 'kreem',
    },
    {
        word: 'pool',
        definition: 'A body of water for swimming.',
        exampleSentence: 'We jumped into the pool to cool off.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'vowel-teams',
        pronunciation: 'pool',
    },
    {
        word: 'train',
        definition: 'A line of connected rail cars that moves on tracks.',
        exampleSentence: 'The train rumbled through the tunnel.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'vowel-teams',
        pronunciation: 'trayn',
        etymology: 'From Old French "trahiner," meaning to pull or drag.',
    },
    {
        word: 'toad',
        definition: 'An animal like a frog but with dry, bumpy skin.',
        exampleSentence: 'A toad sat on the rock near the pond.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'vowel-teams',
        pronunciation: 'tohd',
    },
    {
        word: 'snail',
        definition: 'A small, slow-moving animal that carries a shell on its back.',
        exampleSentence: 'The snail left a shiny trail on the leaf.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'vowel-teams',
        pronunciation: 'snayl',
    },
    {
        word: 'float',
        definition: 'To stay on the surface of water without sinking.',
        exampleSentence: 'Wood can float on water.',
        partOfSpeech: 'verb',
        difficulty: 3,
        pattern: 'vowel-teams',
        pronunciation: 'floht',
    },
    {
        word: 'spoon',
        definition: 'A tool with a shallow bowl used for eating or stirring.',
        exampleSentence: 'He stirred the soup with a spoon.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'vowel-teams',
        pronunciation: 'spoon',
    },
    {
        word: 'beach',
        definition: 'A sandy area next to the ocean or a lake.',
        exampleSentence: 'We built a sandcastle at the beach.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'vowel-teams',
        pronunciation: 'beech',
    },
    {
        word: 'clean',
        definition: 'Free from dirt; not dirty.',
        exampleSentence: 'Please keep your room clean.',
        partOfSpeech: 'adjective',
        difficulty: 3,
        pattern: 'vowel-teams',
        pronunciation: 'kleen',
    },
    {
        word: 'broom',
        definition: 'A tool with a long handle and bristles used for sweeping.',
        exampleSentence: 'She swept the floor with a broom.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'vowel-teams',
        pronunciation: 'broom',
    },
    {
        word: 'toast',
        definition: 'Bread that has been browned by heat.',
        exampleSentence: 'I like toast with butter for breakfast.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'vowel-teams',
        pronunciation: 'tohst',
    },
    {
        word: 'stain',
        definition: 'A dirty mark that is hard to remove.',
        exampleSentence: 'The juice left a stain on my shirt.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'vowel-teams',
        pronunciation: 'stayn',
    },
    {
        word: 'speed',
        definition: 'How fast something moves.',
        exampleSentence: 'The car was traveling at a high speed.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'vowel-teams',
        pronunciation: 'speed',
    },
    {
        word: 'sleep',
        definition: 'A natural state of rest when your eyes are closed.',
        exampleSentence: 'You need plenty of sleep to stay healthy.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'vowel-teams',
        pronunciation: 'sleep',
    },
    {
        word: 'feet',
        definition: 'The body parts at the end of your legs that you stand on.',
        exampleSentence: 'My feet were sore after the long hike.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'vowel-teams',
        pronunciation: 'feet',
    },
    {
        word: 'street',
        definition: 'A public road in a city or town.',
        exampleSentence: 'Look both ways before crossing the street.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'vowel-teams',
        pronunciation: 'street',
    },
    {
        word: 'bloom',
        definition: 'A flower, or the act of a flower opening up.',
        exampleSentence: 'The roses bloom every spring.',
        partOfSpeech: 'verb',
        difficulty: 3,
        pattern: 'vowel-teams',
        pronunciation: 'bloom',
    },
    {
        word: 'chain',
        definition: 'A series of metal rings linked together.',
        exampleSentence: 'The gate was held shut with a chain.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'vowel-teams',
        pronunciation: 'chayn',
    },
    {
        word: 'teach',
        definition: 'To help someone learn something new.',
        exampleSentence: 'Our teacher will teach us about planets today.',
        partOfSpeech: 'verb',
        difficulty: 3,
        pattern: 'vowel-teams',
        pronunciation: 'teech',
    },
    {
        word: 'plain',
        definition: 'Simple, without decoration; or a large flat area of land.',
        exampleSentence: 'She wore a plain white T-shirt.',
        partOfSpeech: 'adjective',
        difficulty: 3,
        pattern: 'vowel-teams',
        pronunciation: 'playn',
    },
    {
        word: 'roast',
        definition: 'To cook food in an oven or over a fire.',
        exampleSentence: 'We roast marshmallows over the campfire.',
        partOfSpeech: 'verb',
        difficulty: 3,
        pattern: 'vowel-teams',
        pronunciation: 'rohst',
    },
    {
        word: 'proof',
        definition: 'Evidence or facts that show something is true.',
        exampleSentence: 'The muddy footprints were proof the dog got out.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'vowel-teams',
        pronunciation: 'proof',
        etymology: 'From Old French "proeve," meaning a test or trial.',
    },
    {
        word: 'throat',
        definition: 'The front part of the neck, or the passage inside it.',
        exampleSentence: 'She drank warm tea because her throat was sore.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'vowel-teams',
        pronunciation: 'throht',
    },
    {
        word: 'stool',
        definition: 'A seat without a back, usually on legs.',
        exampleSentence: 'He sat on a stool at the kitchen counter.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'vowel-teams',
        pronunciation: 'stool',
    },
    {
        word: 'creek',
        definition: 'A small, narrow stream of water.',
        exampleSentence: 'We waded through the shallow creek.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'vowel-teams',
        pronunciation: 'kreek',
    },
    {
        word: 'brain',
        definition: 'The organ inside your head that controls thinking.',
        exampleSentence: 'Your brain helps you think and learn.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'vowel-teams',
        pronunciation: 'brayn',
    },
    {
        word: 'moan',
        definition: 'A low sound of pain or sadness.',
        exampleSentence: 'The wind seemed to moan through the trees.',
        partOfSpeech: 'verb',
        difficulty: 3,
        pattern: 'vowel-teams',
        pronunciation: 'mohn',
    },
    {
        word: 'troop',
        definition: 'A group of soldiers, scouts, or other people.',
        exampleSentence: 'Her scout troop went on a camping trip.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'vowel-teams',
        pronunciation: 'troop',
        etymology: 'From French "troupe," meaning a group or band.',
    },
    {
        word: 'cloak',
        definition: 'A loose outer garment like a cape.',
        exampleSentence: 'The wizard wore a long dark cloak.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'vowel-teams',
        pronunciation: 'klohk',
    },
    {
        word: 'steam',
        definition: 'The hot gas that rises from boiling water.',
        exampleSentence: 'Steam rose from the pot of boiling water.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'vowel-teams',
        pronunciation: 'steem',
    },
    {
        word: 'reach',
        definition: 'To stretch out your arm to touch or grab something.',
        exampleSentence: 'I can reach the top shelf if I stand on my toes.',
        partOfSpeech: 'verb',
        difficulty: 3,
        pattern: 'vowel-teams',
        pronunciation: 'reech',
    },
    {
        word: 'groan',
        definition: 'A deep, unhappy sound made when in pain or annoyed.',
        exampleSentence: 'He let out a groan when he saw all the homework.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'vowel-teams',
        pronunciation: 'grohn',
    },
    {
        word: 'peach',
        definition: 'A soft, round fruit with fuzzy skin and a pit inside.',
        exampleSentence: 'The ripe peach was sweet and juicy.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'vowel-teams',
        pronunciation: 'peech',
    },
    {
        word: 'scoop',
        definition: 'A deep spoon or shovel shape, or to pick something up.',
        exampleSentence: 'She asked for one scoop of vanilla ice cream.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'vowel-teams',
        pronunciation: 'skoop',
    },
    {
        word: 'wheat',
        definition: 'A grain plant used to make flour and bread.',
        exampleSentence: 'The farmer grew wheat in the large field.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'vowel-teams',
        pronunciation: 'weet',
    },

    // ─────────────────────────────────────────────
    // R-CONTROLLED  (~50 words, difficulty 3-4)
    // ─────────────────────────────────────────────
    {
        word: 'car',
        definition: 'A vehicle with four wheels powered by an engine.',
        exampleSentence: 'Dad parked the car in the driveway.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'r-controlled',
        pronunciation: 'kar',
    },
    {
        word: 'bird',
        definition: 'A warm-blooded animal with feathers and wings.',
        exampleSentence: 'A little bird sat on the windowsill.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'r-controlled',
        pronunciation: 'burd',
    },
    {
        word: 'turn',
        definition: 'To move in a circle or change direction.',
        exampleSentence: 'Turn left at the next corner.',
        partOfSpeech: 'verb',
        difficulty: 3,
        pattern: 'r-controlled',
        pronunciation: 'turn',
    },
    {
        word: 'care',
        definition: 'To feel concern or to look after someone.',
        exampleSentence: 'I care about keeping our classroom tidy.',
        partOfSpeech: 'verb',
        difficulty: 3,
        pattern: 'r-controlled',
        pronunciation: 'kair',
    },
    {
        word: 'store',
        definition: 'A shop where you can buy things.',
        exampleSentence: 'We went to the store to buy groceries.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'r-controlled',
        pronunciation: 'stor',
    },
    {
        word: 'star',
        definition: 'A bright point of light in the night sky.',
        exampleSentence: 'She wished upon the first star she saw.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'r-controlled',
        pronunciation: 'star',
    },
    {
        word: 'hurt',
        definition: 'To feel pain or to cause pain to someone.',
        exampleSentence: 'Be careful so you do not hurt yourself.',
        partOfSpeech: 'verb',
        difficulty: 3,
        pattern: 'r-controlled',
        pronunciation: 'hurt',
    },
    {
        word: 'farm',
        definition: 'A place where crops are grown and animals are raised.',
        exampleSentence: 'We visited a farm and fed the chickens.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'r-controlled',
        pronunciation: 'farm',
    },
    {
        word: 'girl',
        definition: 'A young female person.',
        exampleSentence: 'The girl scored the winning goal.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'r-controlled',
        pronunciation: 'gurl',
    },
    {
        word: 'burn',
        definition: 'To be on fire or to damage with heat.',
        exampleSentence: 'Be careful not to burn the cookies.',
        partOfSpeech: 'verb',
        difficulty: 3,
        pattern: 'r-controlled',
        pronunciation: 'burn',
    },
    {
        word: 'horn',
        definition: 'A hard, pointed growth on the head of some animals, or a musical instrument.',
        exampleSentence: 'The goat had a curved horn on each side of its head.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'r-controlled',
        pronunciation: 'horn',
    },
    {
        word: 'dark',
        definition: 'Having little or no light.',
        exampleSentence: 'The room was dark until she turned on the lamp.',
        partOfSpeech: 'adjective',
        difficulty: 3,
        pattern: 'r-controlled',
        pronunciation: 'dark',
    },
    {
        word: 'dirt',
        definition: 'Loose earth or soil.',
        exampleSentence: 'His shoes were covered in dirt after playing outside.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'r-controlled',
        pronunciation: 'durt',
    },
    {
        word: 'porch',
        definition: 'A covered area at the entrance of a building.',
        exampleSentence: 'We sat on the porch and watched the sunset.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'r-controlled',
        pronunciation: 'porch',
    },
    {
        word: 'shirt',
        definition: 'A piece of clothing worn on the upper body.',
        exampleSentence: 'He put on a clean shirt for school.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'r-controlled',
        pronunciation: 'shurt',
    },
    {
        word: 'corn',
        definition: 'A tall plant with yellow kernels that you can eat.',
        exampleSentence: 'We had corn on the cob for dinner.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'r-controlled',
        pronunciation: 'korn',
    },
    {
        word: 'shark',
        definition: 'A large fish with sharp teeth that lives in the ocean.',
        exampleSentence: 'We saw a shark at the aquarium.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'r-controlled',
        pronunciation: 'shark',
    },
    {
        word: 'fork',
        definition: 'A tool with prongs used for eating food.',
        exampleSentence: 'She picked up her fork and started eating.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'r-controlled',
        pronunciation: 'fork',
    },
    {
        word: 'storm',
        definition: 'Bad weather with strong wind, rain, or snow.',
        exampleSentence: 'The storm knocked down a tree in our yard.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'r-controlled',
        pronunciation: 'storm',
    },
    {
        word: 'yarn',
        definition: 'A thick thread used for knitting or weaving.',
        exampleSentence: 'Grandma used red yarn to knit a scarf.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'r-controlled',
        pronunciation: 'yarn',
    },
    {
        word: 'nurse',
        definition: 'A person who takes care of sick or injured people.',
        exampleSentence: 'The nurse put a bandage on my cut.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'r-controlled',
        pronunciation: 'nurs',
        etymology: 'From Latin "nutrire," meaning to nourish.',
    },
    {
        word: 'curb',
        definition: 'The raised edge where the sidewalk meets the street.',
        exampleSentence: 'Be careful stepping off the curb.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'r-controlled',
        pronunciation: 'kurb',
    },
    {
        word: 'clerk',
        definition: 'A person who works at a counter or in an office.',
        exampleSentence: 'The clerk at the store helped us find what we needed.',
        partOfSpeech: 'noun',
        difficulty: 4,
        pattern: 'r-controlled',
        pronunciation: 'klurk',
    },
    {
        word: 'chart',
        definition: 'A drawing that shows information, like a graph or map.',
        exampleSentence: 'We made a chart to track the weather each day.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'r-controlled',
        pronunciation: 'chart',
    },
    {
        word: 'perch',
        definition: 'A place where a bird sits, or to sit on a high spot.',
        exampleSentence: 'The parrot sat on its perch inside the cage.',
        partOfSpeech: 'noun',
        difficulty: 4,
        pattern: 'r-controlled',
        pronunciation: 'purch',
    },
    {
        word: 'swirl',
        definition: 'To move in a spinning, twisting pattern.',
        exampleSentence: 'The leaves began to swirl in the wind.',
        partOfSpeech: 'verb',
        difficulty: 4,
        pattern: 'r-controlled',
        pronunciation: 'swurl',
    },
    {
        word: 'scarf',
        definition: 'A piece of fabric worn around the neck for warmth.',
        exampleSentence: 'She wrapped a warm scarf around her neck.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'r-controlled',
        pronunciation: 'skarf',
    },
    {
        word: 'stork',
        definition: 'A large bird with long legs and a long beak.',
        exampleSentence: 'A stork stood at the edge of the pond.',
        partOfSpeech: 'noun',
        difficulty: 4,
        pattern: 'r-controlled',
        pronunciation: 'stork',
    },
    {
        word: 'skirt',
        definition: 'A piece of clothing that hangs from the waist.',
        exampleSentence: 'She wore a blue skirt to the party.',
        partOfSpeech: 'noun',
        difficulty: 4,
        pattern: 'r-controlled',
        pronunciation: 'skurt',
    },
    {
        word: 'harsh',
        definition: 'Rough, unpleasant, or severe.',
        exampleSentence: 'The harsh winter winds made everyone shiver.',
        partOfSpeech: 'adjective',
        difficulty: 4,
        pattern: 'r-controlled',
        pronunciation: 'harsh',
    },
    {
        word: 'smart',
        definition: 'Having or showing a quick mind; clever.',
        exampleSentence: 'She is smart and always gets good grades.',
        partOfSpeech: 'adjective',
        difficulty: 3,
        pattern: 'r-controlled',
        pronunciation: 'smart',
    },
    {
        word: 'earth',
        definition: 'The planet we live on, or the soil on the ground.',
        exampleSentence: 'The earth travels around the sun.',
        partOfSpeech: 'noun',
        difficulty: 4,
        pattern: 'r-controlled',
        pronunciation: 'urth',
        etymology: 'From Old English "eorthe," meaning the ground or world.',
    },
    {
        word: 'sport',
        definition: 'A game or activity that involves physical exercise.',
        exampleSentence: 'Soccer is my favorite sport.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'r-controlled',
        pronunciation: 'sport',
    },
    {
        word: 'stir',
        definition: 'To move something around with a spoon or stick.',
        exampleSentence: 'Please stir the paint before using it.',
        partOfSpeech: 'verb',
        difficulty: 3,
        pattern: 'r-controlled',
        pronunciation: 'stur',
    },
    {
        word: 'purse',
        definition: 'A small bag used for carrying money and personal items.',
        exampleSentence: 'She found her keys inside her purse.',
        partOfSpeech: 'noun',
        difficulty: 4,
        pattern: 'r-controlled',
        pronunciation: 'purs',
    },
    {
        word: 'north',
        definition: 'The direction toward the top of a map.',
        exampleSentence: 'The compass needle points north.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'r-controlled',
        pronunciation: 'north',
    },
    {
        word: 'church',
        definition: 'A building where people go to worship.',
        exampleSentence: 'The old church had a tall steeple.',
        partOfSpeech: 'noun',
        difficulty: 4,
        pattern: 'r-controlled',
        pronunciation: 'church',
        etymology: 'From Greek "kuriakon," meaning house of the Lord.',
    },
    {
        word: 'marsh',
        definition: 'An area of soft, wet land.',
        exampleSentence: 'Frogs live in the marsh near the river.',
        partOfSpeech: 'noun',
        difficulty: 4,
        pattern: 'r-controlled',
        pronunciation: 'marsh',
    },
    {
        word: 'further',
        definition: 'To a greater distance or degree.',
        exampleSentence: 'We walked further down the trail.',
        partOfSpeech: 'adverb',
        difficulty: 4,
        pattern: 'r-controlled',
        pronunciation: 'fur-thur',
    },
    {
        word: 'carpet',
        definition: 'A thick fabric covering for a floor.',
        exampleSentence: 'The soft carpet felt warm under our feet.',
        partOfSpeech: 'noun',
        difficulty: 4,
        pattern: 'r-controlled',
        pronunciation: 'kar-pit',
    },
    {
        word: 'market',
        definition: 'A place where people buy and sell food or goods.',
        exampleSentence: 'We bought fresh fruit at the farmers market.',
        partOfSpeech: 'noun',
        difficulty: 4,
        pattern: 'r-controlled',
        pronunciation: 'mar-kit',
    },
    {
        word: 'corner',
        definition: 'The point where two lines, edges, or streets meet.',
        exampleSentence: 'The bakery is on the corner of Main Street.',
        partOfSpeech: 'noun',
        difficulty: 4,
        pattern: 'r-controlled',
        pronunciation: 'kor-nur',
    },
    {
        word: 'garden',
        definition: 'A piece of land used for growing flowers or vegetables.',
        exampleSentence: 'We planted tomatoes in the garden.',
        partOfSpeech: 'noun',
        difficulty: 4,
        pattern: 'r-controlled',
        pronunciation: 'gar-din',
        etymology: 'From Old French "gardin," meaning an enclosed yard.',
    },
    {
        word: 'turtle',
        definition: 'A slow-moving reptile with a hard shell on its back.',
        exampleSentence: 'The turtle slowly crossed the path.',
        partOfSpeech: 'noun',
        difficulty: 4,
        pattern: 'r-controlled',
        pronunciation: 'tur-tul',
    },
    {
        word: 'party',
        definition: 'A social gathering for celebration or fun.',
        exampleSentence: 'We had a great time at the birthday party.',
        partOfSpeech: 'noun',
        difficulty: 3,
        pattern: 'r-controlled',
        pronunciation: 'par-tee',
    },
    {
        word: 'circle',
        definition: 'A perfectly round shape.',
        exampleSentence: 'Draw a circle with your compass.',
        partOfSpeech: 'noun',
        difficulty: 4,
        pattern: 'r-controlled',
        pronunciation: 'sur-kul',
        etymology: 'From Latin "circulus," meaning a small ring.',
    },
    {
        word: 'harbor',
        definition: 'A sheltered area of water where boats can dock.',
        exampleSentence: 'The fishing boats returned to the harbor.',
        partOfSpeech: 'noun',
        difficulty: 4,
        pattern: 'r-controlled',
        pronunciation: 'har-bur',
    },
    {
        word: 'perfect',
        definition: 'Having no mistakes; as good as it can be.',
        exampleSentence: 'She got a perfect score on the test.',
        partOfSpeech: 'adjective',
        difficulty: 4,
        pattern: 'r-controlled',
        pronunciation: 'pur-fikt',
    },
    {
        word: 'nerve',
        definition: 'A fiber in the body that carries signals to and from the brain.',
        exampleSentence: 'A tiny nerve in his tooth was causing the pain.',
        partOfSpeech: 'noun',
        difficulty: 4,
        pattern: 'r-controlled',
        pronunciation: 'nurv',
        etymology: 'From Latin "nervus," meaning a sinew or tendon.',
    },
    {
        word: 'thermometer',
        definition: 'A tool used to measure temperature.',
        exampleSentence: 'The thermometer showed it was ninety degrees outside.',
        partOfSpeech: 'noun',
        difficulty: 4,
        pattern: 'r-controlled',
        pronunciation: 'thur-mom-uh-tur',
    },

    // ─────────────────────────────────────────────
    // DIPHTHONGS  (~50 words, difficulty 4)
    // ─────────────────────────────────────────────
    {
        word: 'coin',
        definition: 'A small, flat piece of metal used as money.',
        exampleSentence: 'She found a shiny coin on the ground.',
        partOfSpeech: 'noun',
        difficulty: 4,
        pattern: 'diphthongs',
        pronunciation: 'koyn',
    },
    {
        word: 'boy',
        definition: 'A young male person.',
        exampleSentence: 'The boy threw the ball to his friend.',
        partOfSpeech: 'noun',
        difficulty: 4,
        pattern: 'diphthongs',
        pronunciation: 'boy',
    },
    {
        word: 'house',
        definition: 'A building where people live.',
        exampleSentence: 'Their house has a big front yard.',
        partOfSpeech: 'noun',
        difficulty: 4,
        pattern: 'diphthongs',
        pronunciation: 'hows',
    },
    {
        word: 'brown',
        definition: 'A dark color like chocolate or wood.',
        exampleSentence: 'The puppy has soft brown fur.',
        partOfSpeech: 'adjective',
        difficulty: 4,
        pattern: 'diphthongs',
        pronunciation: 'brown',
    },
    {
        word: 'choice',
        definition: 'The act of picking between two or more things.',
        exampleSentence: 'You have a choice between pizza and pasta.',
        partOfSpeech: 'noun',
        difficulty: 4,
        pattern: 'diphthongs',
        pronunciation: 'choys',
    },
    {
        word: 'cloud',
        definition: 'A white or gray mass of tiny water drops floating in the sky.',
        exampleSentence: 'A big cloud covered the sun.',
        partOfSpeech: 'noun',
        difficulty: 4,
        pattern: 'diphthongs',
        pronunciation: 'klowd',
    },
    {
        word: 'town',
        definition: 'A place where people live that is smaller than a city.',
        exampleSentence: 'Our town has a library and a park.',
        partOfSpeech: 'noun',
        difficulty: 4,
        pattern: 'diphthongs',
        pronunciation: 'town',
    },
    {
        word: 'join',
        definition: 'To become part of a group or connect things together.',
        exampleSentence: 'Would you like to join our team?',
        partOfSpeech: 'verb',
        difficulty: 4,
        pattern: 'diphthongs',
        pronunciation: 'joyn',
    },
    {
        word: 'mouse',
        definition: 'A small furry animal with a long tail.',
        exampleSentence: 'The mouse nibbled on a piece of cheese.',
        partOfSpeech: 'noun',
        difficulty: 4,
        pattern: 'diphthongs',
        pronunciation: 'mows',
    },
    {
        word: 'crowd',
        definition: 'A large group of people gathered together.',
        exampleSentence: 'A big crowd watched the parade.',
        partOfSpeech: 'noun',
        difficulty: 4,
        pattern: 'diphthongs',
        pronunciation: 'krowd',
    },
    {
        word: 'noise',
        definition: 'A sound, especially one that is loud or unpleasant.',
        exampleSentence: 'The loud noise scared the cat.',
        partOfSpeech: 'noun',
        difficulty: 4,
        pattern: 'diphthongs',
        pronunciation: 'noyz',
    },
    {
        word: 'point',
        definition: 'The sharp end of something, or to direct a finger toward something.',
        exampleSentence: 'She used her finger to point at the map.',
        partOfSpeech: 'verb',
        difficulty: 4,
        pattern: 'diphthongs',
        pronunciation: 'poynt',
    },
    {
        word: 'found',
        definition: 'Past tense of find; discovered something.',
        exampleSentence: 'He found his lost toy under the bed.',
        partOfSpeech: 'verb',
        difficulty: 4,
        pattern: 'diphthongs',
        pronunciation: 'fownd',
    },
    {
        word: 'joy',
        definition: 'A feeling of great happiness.',
        exampleSentence: 'Opening presents brought her great joy.',
        partOfSpeech: 'noun',
        difficulty: 4,
        pattern: 'diphthongs',
        pronunciation: 'joy',
        etymology: 'From Old French "joie," meaning gladness.',
    },
    {
        word: 'ground',
        definition: 'The surface of the earth.',
        exampleSentence: 'The ball rolled along the ground.',
        partOfSpeech: 'noun',
        difficulty: 4,
        pattern: 'diphthongs',
        pronunciation: 'grownd',
    },
    {
        word: 'soil',
        definition: 'The top layer of earth in which plants grow.',
        exampleSentence: 'She dug into the soil to plant the seeds.',
        partOfSpeech: 'noun',
        difficulty: 4,
        pattern: 'diphthongs',
        pronunciation: 'soyl',
    },
    {
        word: 'tower',
        definition: 'A tall, narrow building or structure.',
        exampleSentence: 'We climbed to the top of the tower.',
        partOfSpeech: 'noun',
        difficulty: 4,
        pattern: 'diphthongs',
        pronunciation: 'tow-ur',
    },
    {
        word: 'spoil',
        definition: 'To ruin or damage something.',
        exampleSentence: 'Do not spoil the surprise for your sister.',
        partOfSpeech: 'verb',
        difficulty: 4,
        pattern: 'diphthongs',
        pronunciation: 'spoyl',
    },
    {
        word: 'south',
        definition: 'The direction opposite of north.',
        exampleSentence: 'Birds fly south for the winter.',
        partOfSpeech: 'noun',
        difficulty: 4,
        pattern: 'diphthongs',
        pronunciation: 'sowth',
    },
    {
        word: 'loyal',
        definition: 'Faithful and devoted to someone or something.',
        exampleSentence: 'A dog is a loyal friend.',
        partOfSpeech: 'adjective',
        difficulty: 4,
        pattern: 'diphthongs',
        pronunciation: 'loy-ul',
        etymology: 'From Old French "loial," meaning faithful to the law.',
    },
    {
        word: 'shout',
        definition: 'To call out in a loud voice.',
        exampleSentence: 'Do not shout in the library.',
        partOfSpeech: 'verb',
        difficulty: 4,
        pattern: 'diphthongs',
        pronunciation: 'showt',
    },
    {
        word: 'power',
        definition: 'The ability to do something or make things happen.',
        exampleSentence: 'The storm knocked out the power.',
        partOfSpeech: 'noun',
        difficulty: 4,
        pattern: 'diphthongs',
        pronunciation: 'pow-ur',
    },
    {
        word: 'enjoy',
        definition: 'To take pleasure in something.',
        exampleSentence: 'I enjoy reading adventure stories.',
        partOfSpeech: 'verb',
        difficulty: 4,
        pattern: 'diphthongs',
        pronunciation: 'en-joy',
    },
    {
        word: 'round',
        definition: 'Shaped like a circle or ball.',
        exampleSentence: 'The pizza was perfectly round.',
        partOfSpeech: 'adjective',
        difficulty: 4,
        pattern: 'diphthongs',
        pronunciation: 'rownd',
    },
    {
        word: 'voice',
        definition: 'The sound made when a person speaks or sings.',
        exampleSentence: 'She has a beautiful singing voice.',
        partOfSpeech: 'noun',
        difficulty: 4,
        pattern: 'diphthongs',
        pronunciation: 'voys',
        etymology: 'From Latin "vox," meaning sound or voice.',
    },
    {
        word: 'bounce',
        definition: 'To spring back after hitting a surface.',
        exampleSentence: 'Watch the ball bounce off the wall.',
        partOfSpeech: 'verb',
        difficulty: 4,
        pattern: 'diphthongs',
        pronunciation: 'bowns',
    },
    {
        word: 'mount',
        definition: 'To climb up on something, or a large hill.',
        exampleSentence: 'She tried to mount the horse carefully.',
        partOfSpeech: 'verb',
        difficulty: 4,
        pattern: 'diphthongs',
        pronunciation: 'mownt',
    },
    {
        word: 'royal',
        definition: 'Having to do with a king or queen.',
        exampleSentence: 'The royal palace was huge and grand.',
        partOfSpeech: 'adjective',
        difficulty: 4,
        pattern: 'diphthongs',
        pronunciation: 'roy-ul',
    },
    {
        word: 'proud',
        definition: 'Feeling pleased about something you or someone else has done.',
        exampleSentence: 'Her parents were proud of her hard work.',
        partOfSpeech: 'adjective',
        difficulty: 4,
        pattern: 'diphthongs',
        pronunciation: 'prowd',
    },
    {
        word: 'frown',
        definition: 'An unhappy expression made by pulling the eyebrows together.',
        exampleSentence: 'The frown on his face showed he was upset.',
        partOfSpeech: 'noun',
        difficulty: 4,
        pattern: 'diphthongs',
        pronunciation: 'frown',
    },
    {
        word: 'moist',
        definition: 'Slightly wet; damp.',
        exampleSentence: 'The soil was moist after the rain.',
        partOfSpeech: 'adjective',
        difficulty: 4,
        pattern: 'diphthongs',
        pronunciation: 'moyst',
    },
    {
        word: 'plow',
        definition: 'A tool used to turn over soil, or to push through something.',
        exampleSentence: 'The farmer used a plow to prepare the field.',
        partOfSpeech: 'noun',
        difficulty: 4,
        pattern: 'diphthongs',
        pronunciation: 'plow',
    },
    {
        word: 'allow',
        definition: 'To let someone do something; to permit.',
        exampleSentence: 'Our teacher will allow extra time for the test.',
        partOfSpeech: 'verb',
        difficulty: 4,
        pattern: 'diphthongs',
        pronunciation: 'uh-low',
    },
    {
        word: 'couch',
        definition: 'A long, soft seat for two or more people.',
        exampleSentence: 'We sat on the couch to watch a movie.',
        partOfSpeech: 'noun',
        difficulty: 4,
        pattern: 'diphthongs',
        pronunciation: 'kowch',
    },
    {
        word: 'poison',
        definition: 'A substance that can cause sickness or death.',
        exampleSentence: 'Never touch or eat a wild plant because it could be poison.',
        partOfSpeech: 'noun',
        difficulty: 4,
        pattern: 'diphthongs',
        pronunciation: 'poy-zun',
        etymology: 'From Latin "potio," meaning a drink or potion.',
    },
    {
        word: 'drown',
        definition: 'To sink in water and be unable to breathe.',
        exampleSentence: 'Always wear a life jacket so you do not drown.',
        partOfSpeech: 'verb',
        difficulty: 4,
        pattern: 'diphthongs',
        pronunciation: 'drown',
    },
    {
        word: 'amount',
        definition: 'How much of something there is.',
        exampleSentence: 'She used a small amount of glue for her project.',
        partOfSpeech: 'noun',
        difficulty: 4,
        pattern: 'diphthongs',
        pronunciation: 'uh-mownt',
    },
    {
        word: 'annoy',
        definition: 'To bother or irritate someone.',
        exampleSentence: 'Loud chewing can annoy the people around you.',
        partOfSpeech: 'verb',
        difficulty: 4,
        pattern: 'diphthongs',
        pronunciation: 'uh-noy',
    },
    {
        word: 'voyage',
        definition: 'A long journey, especially by sea or through space.',
        exampleSentence: 'The sailors set out on a long voyage across the ocean.',
        partOfSpeech: 'noun',
        difficulty: 4,
        pattern: 'diphthongs',
        pronunciation: 'voy-ij',
        etymology: 'From Old French "voiage," meaning a journey.',
    },
    {
        word: 'growl',
        definition: 'A low, angry sound, often made by a dog.',
        exampleSentence: 'The dog let out a growl when it saw a stranger.',
        partOfSpeech: 'noun',
        difficulty: 4,
        pattern: 'diphthongs',
        pronunciation: 'growl',
    },
    {
        word: 'count',
        definition: 'To say numbers in order, or to figure out how many.',
        exampleSentence: 'Can you count to one hundred?',
        partOfSpeech: 'verb',
        difficulty: 4,
        pattern: 'diphthongs',
        pronunciation: 'kownt',
    },
    {
        word: 'doubt',
        definition: 'A feeling of not being sure about something.',
        exampleSentence: 'I have no doubt she will pass the test.',
        partOfSpeech: 'noun',
        difficulty: 4,
        pattern: 'diphthongs',
        pronunciation: 'dowt',
        etymology: 'From Latin "dubitare," meaning to hesitate or question.',
    },
    {
        word: 'scout',
        definition: 'A person sent out to gather information, or a member of a youth group.',
        exampleSentence: 'She earned a new badge as a scout.',
        partOfSpeech: 'noun',
        difficulty: 4,
        pattern: 'diphthongs',
        pronunciation: 'skowt',
    },
    {
        word: 'flour',
        definition: 'A white powder made from grain, used in baking.',
        exampleSentence: 'We need flour to make the bread.',
        partOfSpeech: 'noun',
        difficulty: 4,
        pattern: 'diphthongs',
        pronunciation: 'flowr',
    },
    {
        word: 'oyster',
        definition: 'A sea creature with a shell that sometimes makes pearls.',
        exampleSentence: 'We found an oyster shell on the beach.',
        partOfSpeech: 'noun',
        difficulty: 4,
        pattern: 'diphthongs',
        pronunciation: 'oy-stur',
    },
    {
        word: 'towel',
        definition: 'A piece of cloth or paper used for drying things.',
        exampleSentence: 'She grabbed a towel to dry her hands.',
        partOfSpeech: 'noun',
        difficulty: 4,
        pattern: 'diphthongs',
        pronunciation: 'tow-ul',
    },
    {
        word: 'flower',
        definition: 'The colorful part of a plant that produces seeds.',
        exampleSentence: 'A bright yellow flower grew in the garden.',
        partOfSpeech: 'noun',
        difficulty: 4,
        pattern: 'diphthongs',
        pronunciation: 'flow-ur',
    },
    {
        word: 'joyful',
        definition: 'Full of happiness.',
        exampleSentence: 'The children were joyful on the last day of school.',
        partOfSpeech: 'adjective',
        difficulty: 4,
        pattern: 'diphthongs',
        pronunciation: 'joy-ful',
    },
    {
        word: 'powder',
        definition: 'A dry substance made of very tiny pieces.',
        exampleSentence: 'She sprinkled cocoa powder on the cookies.',
        partOfSpeech: 'noun',
        difficulty: 4,
        pattern: 'diphthongs',
        pronunciation: 'pow-dur',
    },
    {
        word: 'destroy',
        definition: 'To damage something so badly that it no longer exists.',
        exampleSentence: 'The strong winds can destroy weak buildings.',
        partOfSpeech: 'verb',
        difficulty: 4,
        pattern: 'diphthongs',
        pronunciation: 'dih-stroy',
        etymology: 'From Latin "destruere," meaning to tear down.',
    },
];
