/**
 * words/tier5.ts
 *
 * Tier 5 word bank: Competition level (difficulty 9-10).
 * National Spelling Bee caliber words with full etymology.
 * Mixed patterns. ~80 curated entries.
 */
import type { SpellingWord } from './types';

export const TIER_5_WORDS: SpellingWord[] = [
    {
        word: 'bureaucracy',
        definition: 'A system of government with many complicated rules and processes.',
        exampleSentence: 'Navigating the bureaucracy to get a building permit took months.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'french-origin',
        pronunciation: 'byoo-ROK-ruh-see',
        etymology: 'French: bureau (desk, office) + Greek: kratos (rule, power)',
    },
    {
        word: 'onomatopoeia',
        definition: 'A word that imitates the natural sound it describes, like "buzz" or "hiss."',
        exampleSentence: 'The poet used onomatopoeia to bring the sounds of the forest to life.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'on-uh-mat-uh-PEE-uh',
        etymology: 'Greek: onomatopoiia (word-making), from onoma (name) + poiein (to make)',
    },
    {
        word: 'hemorrhage',
        definition: 'A severe or uncontrollable loss of blood from a blood vessel.',
        exampleSentence: 'The surgeon worked quickly to stop the hemorrhage during the operation.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'HEM-uh-rij',
        etymology: 'Greek: haimorrhagia (bleeding), from haima (blood) + rhegnynai (to burst)',
    },
    {
        word: 'chrysanthemum',
        definition: 'A garden plant with brightly colored ornamental flowers.',
        exampleSentence: 'She planted chrysanthemum bushes that bloomed every autumn.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'krih-SAN-thuh-mum',
        etymology: 'Greek: chrysos (gold) + anthemon (flower)',
    },
    {
        word: 'supercilious',
        definition: 'Behaving as though one is superior to others; haughty.',
        exampleSentence: 'His supercilious attitude made it difficult for others to work with him.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'soo-pur-SIL-ee-us',
        etymology: 'Latin: supercilium (eyebrow, haughtiness), from super (above) + cilium (eyelid)',
    },
    {
        word: 'acquiesce',
        definition: 'To accept something reluctantly without protest.',
        exampleSentence: 'After much debate, she decided to acquiesce to the committee\'s decision.',
        partOfSpeech: 'verb',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'ak-wee-ESS',
        etymology: 'Latin: acquiescere (to find rest in), from ad (to) + quiescere (to rest)',
    },
    {
        word: 'bourgeoisie',
        definition: 'The middle class, especially those regarded as materialistic.',
        exampleSentence: 'The revolution was driven by the frustrations of the bourgeoisie.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'french-origin',
        pronunciation: 'boor-zhwah-ZEE',
        etymology: 'French: bourgeoisie (middle class), from bourgeois (citizen of a town)',
    },
    {
        word: 'conscientious',
        definition: 'Wishing to do what is right; careful and thorough.',
        exampleSentence: 'The conscientious student always double-checked her answers before turning in the exam.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'kon-shee-EN-shus',
        etymology: 'Latin: conscientia (moral awareness), from conscire (to be aware)',
    },
    {
        word: 'sacrilegious',
        definition: 'Showing disrespect toward something considered sacred.',
        exampleSentence: 'Many considered it sacrilegious to demolish the historic chapel.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'sak-rih-LIJ-us',
        etymology: 'Latin: sacrilegium (temple robbery), from sacer (sacred) + legere (to steal)',
    },
    {
        word: 'pharmaceutical',
        definition: 'Relating to the preparation and dispensing of medicinal drugs.',
        exampleSentence: 'The pharmaceutical company developed a new treatment for the disease.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'far-muh-SOO-tih-kul',
        etymology: 'Greek: pharmakeutikos (of drugs), from pharmakon (drug, medicine)',
    },
    {
        word: 'idiosyncrasy',
        definition: 'A distinctive or peculiar feature of a person\'s character.',
        exampleSentence: 'One of his many idiosyncrasies was always wearing mismatched socks.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'id-ee-oh-SING-kruh-see',
        etymology: 'Greek: idiosynkrasia (a peculiar temperament), from idios (own, private) + synkrasis (mixture)',
    },
    {
        word: 'insouciance',
        definition: 'Casual lack of concern; indifference.',
        exampleSentence: 'She faced the mounting problems with an air of insouciance that unnerved her colleagues.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'french-origin',
        pronunciation: 'in-SOO-see-unss',
        etymology: 'French: insouciance (carelessness), from in (not) + soucier (to care)',
    },
    {
        word: 'mnemonic',
        definition: 'A device or pattern that helps one remember something.',
        exampleSentence: 'She used a mnemonic to remember the order of the planets.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'nih-MON-ik',
        etymology: 'Greek: mnemonikos (of or relating to memory), from mnemon (mindful)',
    },
    {
        word: 'connoisseur',
        definition: 'An expert, especially in matters of fine art or taste.',
        exampleSentence: 'As a connoisseur of fine art, she could identify paintings from across the room.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'french-origin',
        pronunciation: 'kon-uh-SUR',
        etymology: 'French: connoisseur (one who knows), from connaitre (to know)',
    },
    {
        word: 'perspicacious',
        definition: 'Having a keen mental perception and understanding; shrewd.',
        exampleSentence: 'The perspicacious detective noticed the tiny clue everyone else had missed.',
        partOfSpeech: 'adjective',
        difficulty: 10,
        pattern: 'latin-roots',
        pronunciation: 'pur-spih-KAY-shus',
        etymology: 'Latin: perspicax (sharp-sighted), from perspicere (to look through)',
    },
    {
        word: 'staphylococcus',
        definition: 'A type of bacteria that can cause infections in humans.',
        exampleSentence: 'The lab test confirmed the presence of staphylococcus in the wound.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'staf-ih-loh-KOK-us',
        etymology: 'Greek: staphyle (bunch of grapes) + kokkos (berry, grain)',
    },
    {
        word: 'antidisestablishmentarianism',
        definition: 'Opposition to the withdrawal of government support from a state church.',
        exampleSentence: 'Antidisestablishmentarianism was a political movement in 19th-century Britain.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'latin-roots',
        pronunciation: 'an-tee-dis-es-TAB-lish-men-TAIR-ee-un-iz-um',
        etymology: 'English: anti (against) + dis (reversal) + establish + ment + arian + ism',
    },
    {
        word: 'surreptitious',
        definition: 'Done secretly because it would not be approved of.',
        exampleSentence: 'She took a surreptitious glance at the answers on the board.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'sur-up-TISH-us',
        etymology: 'Latin: surrepticius (stolen, secret), from surripere (to snatch secretly)',
    },
    {
        word: 'gubernatorial',
        definition: 'Relating to a governor or the office of governor.',
        exampleSentence: 'The gubernatorial election drew voters from across the state.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'goo-bur-nuh-TOR-ee-ul',
        etymology: 'Latin: gubernator (governor), from gubernare (to steer, govern)',
    },
    {
        word: 'xylophone',
        definition: 'A musical instrument with wooden bars struck by small mallets.',
        exampleSentence: 'The child played a simple melody on the xylophone.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'ZY-luh-fohn',
        etymology: 'Greek: xylon (wood) + phone (sound, voice)',
    },
    {
        word: 'diphtheria',
        definition: 'A serious bacterial infection affecting the throat and airways.',
        exampleSentence: 'Vaccines have greatly reduced the occurrence of diphtheria worldwide.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'dif-THEER-ee-uh',
        etymology: 'Greek: diphthera (leather, membrane), referring to the membrane that forms in the throat',
    },
    {
        word: 'millennium',
        definition: 'A period of one thousand years.',
        exampleSentence: 'The turn of the millennium in the year 2000 was celebrated worldwide.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'mih-LEN-ee-um',
        etymology: 'Latin: mille (thousand) + annus (year)',
    },
    {
        word: 'denouement',
        definition: 'The final resolution or outcome of a story or complex situation.',
        exampleSentence: 'The denouement of the mystery novel revealed an unexpected twist.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'french-origin',
        pronunciation: 'day-noo-MAH',
        etymology: 'French: denouement (untying), from denouer (to untie)',
    },
    {
        word: 'eczema',
        definition: 'A medical condition causing the skin to become inflamed, itchy, and cracked.',
        exampleSentence: 'The dermatologist prescribed a cream to treat her eczema.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'EK-suh-muh',
        etymology: 'Greek: ekzema (eruption), from ekzein (to boil over)',
    },
    {
        word: 'psychedelic',
        definition: 'Relating to vivid colors, patterns, or altered states of consciousness.',
        exampleSentence: 'The museum exhibit featured psychedelic artwork from the 1960s.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'sy-kuh-DEL-ik',
        etymology: 'Greek: psyche (mind, soul) + delos (clear, manifest)',
    },
    {
        word: 'pterodactyl',
        definition: 'A large flying reptile that lived during the time of the dinosaurs.',
        exampleSentence: 'The pterodactyl had a wingspan that could reach over thirty feet.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'tair-uh-DAK-til',
        etymology: 'Greek: pteron (wing) + daktylos (finger)',
    },
    {
        word: 'Machiavellian',
        definition: 'Cunning, scheming, and unscrupulous, especially in politics.',
        exampleSentence: 'The character\'s Machiavellian tactics eventually led to his downfall.',
        partOfSpeech: 'adjective',
        difficulty: 10,
        pattern: 'irregular',
        pronunciation: 'mak-ee-uh-VEL-ee-un',
        etymology: 'Italian: named after Niccolo Machiavelli, Renaissance political philosopher',
    },
    {
        word: 'unequivocally',
        definition: 'In a way that is clear and without any doubt.',
        exampleSentence: 'The jury unequivocally agreed that the defendant was innocent.',
        partOfSpeech: 'adverb',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'un-ih-KWIV-uh-kul-ee',
        etymology: 'Latin: aequivocus (ambiguous), from aequus (equal) + vox (voice); with un- (not)',
    },
    {
        word: 'verisimilitude',
        definition: 'The appearance of being true or real.',
        exampleSentence: 'The historical novel was praised for its verisimilitude.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'latin-roots',
        pronunciation: 'vair-ih-sih-MIL-ih-tood',
        etymology: 'Latin: verisimilitudo (likeness to truth), from verus (true) + similis (similar)',
    },
    {
        word: 'labyrinthine',
        definition: 'Resembling a complex maze; intricate and confusing.',
        exampleSentence: 'The labyrinthine streets of the old city confused many tourists.',
        partOfSpeech: 'adjective',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'lab-uh-RIN-theen',
        etymology: 'Greek: labyrinthos (maze), from the mythical labyrinth of King Minos',
    },
    {
        word: 'effervescent',
        definition: 'Giving off bubbles; vivacious and enthusiastic.',
        exampleSentence: 'Her effervescent personality lit up every room she entered.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'ef-ur-VES-unt',
        etymology: 'Latin: effervescere (to boil up), from ex (out) + fervescere (to begin to boil)',
    },
    {
        word: 'ubiquitous',
        definition: 'Present, appearing, or found everywhere.',
        exampleSentence: 'Smartphones have become ubiquitous in modern society.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'yoo-BIK-wih-tus',
        etymology: 'Latin: ubique (everywhere), from ubi (where)',
    },
    {
        word: 'ephemeral',
        definition: 'Lasting for a very short time.',
        exampleSentence: 'The beauty of cherry blossoms is ephemeral, lasting only a few days.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'ih-FEM-ur-ul',
        etymology: 'Greek: ephemeros (lasting only a day), from epi (on) + hemera (day)',
    },
    {
        word: 'serendipity',
        definition: 'The occurrence of fortunate events by happy chance.',
        exampleSentence: 'It was pure serendipity that they met on that train to London.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'irregular',
        pronunciation: 'sair-un-DIP-ih-tee',
        etymology: 'English: coined by Horace Walpole in 1754, from the fairy tale The Three Princes of Serendip',
    },
    {
        word: 'sesquipedalian',
        definition: 'Characterized by long words; tending to use long words.',
        exampleSentence: 'The professor\'s sesquipedalian lectures were hard for freshmen to follow.',
        partOfSpeech: 'adjective',
        difficulty: 10,
        pattern: 'latin-roots',
        pronunciation: 'ses-kwih-puh-DAY-lee-un',
        etymology: 'Latin: sesquipedalis (a foot and a half long), from sesqui (one and a half) + pes (foot)',
    },
    {
        word: 'schadenfreude',
        definition: 'Pleasure derived from another person\'s misfortune.',
        exampleSentence: 'He felt a twinge of schadenfreude when his rival tripped on stage.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'irregular',
        pronunciation: 'SHAH-dun-froy-duh',
        etymology: 'German: Schaden (damage) + Freude (joy)',
    },
    {
        word: 'loquacious',
        definition: 'Very talkative; fond of talking.',
        exampleSentence: 'The loquacious tour guide kept the group entertained for hours.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'loh-KWAY-shus',
        etymology: 'Latin: loquax (talkative), from loqui (to speak)',
    },
    {
        word: 'juxtaposition',
        definition: 'Placing two things close together to show contrast or comparison.',
        exampleSentence: 'The artist created a striking juxtaposition of light and shadow.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'juk-stuh-puh-ZIH-shun',
        etymology: 'Latin: juxta (beside, near) + French: position (placement)',
    },
    {
        word: 'indefatigable',
        definition: 'Persisting tirelessly; showing sustained enthusiasm.',
        exampleSentence: 'The indefatigable volunteer worked around the clock to help disaster victims.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'in-dih-FAT-ih-guh-bul',
        etymology: 'Latin: indefatigabilis (that cannot be wearied), from in (not) + defatigare (to tire out)',
    },
    {
        word: 'pneumonoultramicroscopicsilicovolcanoconiosis',
        definition: 'A lung disease caused by inhaling very fine silica dust from volcanoes.',
        exampleSentence: 'Pneumonoultramicroscopicsilicovolcanoconiosis is one of the longest words in English.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'noo-mon-oh-ul-truh-my-kroh-SKOP-ik-sil-ih-koh-vol-kay-noh-koh-nee-OH-sis',
        etymology: 'Greek: pneumon (lung) + Latin: ultra (beyond) + Greek: mikros (small) + skopein (to view) + Latin: silico (silica) + volcano + Greek: konis (dust) + -osis (condition)',
    },
    {
        word: 'triskaidekaphobia',
        definition: 'Extreme fear or superstition regarding the number thirteen.',
        exampleSentence: 'Her triskaidekaphobia meant she refused to sit in row thirteen on the airplane.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'tris-ky-dek-uh-FOH-bee-uh',
        etymology: 'Greek: triskaideka (thirteen) + phobos (fear)',
    },
    {
        word: 'eleemosynary',
        definition: 'Relating to or dependent on charity; charitable.',
        exampleSentence: 'The eleemosynary organization provided food to families in need.',
        partOfSpeech: 'adjective',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'el-ih-MOS-ih-nair-ee',
        etymology: 'Greek: eleemosyne (compassion, pity), from eleos (mercy)',
    },
    {
        word: 'floccinaucinihilipilification',
        definition: 'The act of estimating something as worthless.',
        exampleSentence: 'His floccinaucinihilipilification of modern art upset the gallery owner.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'latin-roots',
        pronunciation: 'flok-sih-naw-sih-ny-hil-ih-pil-ih-fih-KAY-shun',
        etymology: 'Latin: flocci + nauci + nihili + pili (all meaning "of little value") + -fication',
    },
    {
        word: 'pulchritudinous',
        definition: 'Having great physical beauty.',
        exampleSentence: 'The pulchritudinous landscape of the Swiss Alps took her breath away.',
        partOfSpeech: 'adjective',
        difficulty: 10,
        pattern: 'latin-roots',
        pronunciation: 'pul-krih-TOO-dih-nus',
        etymology: 'Latin: pulchritudo (beauty), from pulcher (beautiful)',
    },
    {
        word: 'syzygy',
        definition: 'An alignment of three celestial bodies, such as the sun, earth, and moon.',
        exampleSentence: 'A solar eclipse occurs during a syzygy of the sun, moon, and earth.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'SIZ-ih-jee',
        etymology: 'Greek: syzygia (conjunction, yoking together), from syn (together) + zygon (yoke)',
    },
    {
        word: 'legerdemain',
        definition: 'Skillful use of the hands when performing tricks; sleight of hand.',
        exampleSentence: 'The magician\'s legerdemain amazed the audience at the gala.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'french-origin',
        pronunciation: 'lej-ur-duh-MAYN',
        etymology: 'French: leger de main (light of hand)',
    },
    {
        word: 'sycophant',
        definition: 'A person who flatters someone important to gain an advantage.',
        exampleSentence: 'The king was surrounded by sycophants who only told him what he wanted to hear.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'SIK-uh-fant',
        etymology: 'Greek: sykophantes (informer, slanderer), from sykon (fig) + phainein (to show)',
    },
    {
        word: 'recalcitrant',
        definition: 'Stubbornly resistant to authority or control.',
        exampleSentence: 'The recalcitrant student refused to follow the school dress code.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'rih-KAL-sih-trunt',
        etymology: 'Latin: recalcitrare (to kick back), from re (back) + calcitrare (to kick)',
    },
    {
        word: 'obsequious',
        definition: 'Excessively compliant or eager to please.',
        exampleSentence: 'The obsequious waiter hovered over the table throughout dinner.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'ob-SEE-kwee-us',
        etymology: 'Latin: obsequiosus (compliant), from obsequi (to follow, comply)',
    },
    {
        word: 'pusillanimous',
        definition: 'Lacking courage; cowardly and timid.',
        exampleSentence: 'His pusillanimous response to the crisis disappointed his supporters.',
        partOfSpeech: 'adjective',
        difficulty: 10,
        pattern: 'latin-roots',
        pronunciation: 'pyoo-sih-LAN-ih-mus',
        etymology: 'Latin: pusillanimis (faint-hearted), from pusillus (very small) + animus (spirit)',
    },
    {
        word: 'grandiloquent',
        definition: 'Using pompous or extravagant language.',
        exampleSentence: 'The senator\'s grandiloquent speech impressed few of the audience members.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'gran-DIL-oh-kwent',
        etymology: 'Latin: grandis (great) + loqui (to speak)',
    },
    {
        word: 'flibbertigibbet',
        definition: 'A frivolous or excessively talkative person.',
        exampleSentence: 'The nuns described the lively young woman as a flibbertigibbet.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'irregular',
        pronunciation: 'FLIB-ur-tee-jib-it',
        etymology: 'Middle English: flepergebet (a gossip or chatterer), of imitative origin',
    },
    {
        word: 'machination',
        definition: 'A scheming or crafty plot intended to accomplish an evil end.',
        exampleSentence: 'The villain\'s machinations were finally exposed by the detective.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'mak-ih-NAY-shun',
        etymology: 'Latin: machinatio (device, contrivance), from machinari (to contrive)',
    },
    {
        word: 'soliloquy',
        definition: 'An act of speaking one\'s thoughts aloud, especially in a play.',
        exampleSentence: 'Hamlet\'s famous soliloquy begins with "To be, or not to be."',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'suh-LIL-uh-kwee',
        etymology: 'Latin: soliloquium (talking to oneself), from solus (alone) + loqui (to speak)',
    },
    {
        word: 'hors d\'oeuvre',
        definition: 'A small savory dish served as an appetizer before a meal.',
        exampleSentence: 'The caterer prepared an elegant tray of hors d\'oeuvres for the reception.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'french-origin',
        pronunciation: 'or-DURV',
        etymology: 'French: hors d\'oeuvre (outside the [main] work)',
    },
    {
        word: 'prestidigitation',
        definition: 'Magic tricks performed as entertainment; sleight of hand.',
        exampleSentence: 'The audience marveled at the performer\'s prestidigitation with playing cards.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'latin-roots',
        pronunciation: 'pres-tih-dij-ih-TAY-shun',
        etymology: 'French: prestidigitation, from preste (nimble) + Latin: digitus (finger)',
    },
    {
        word: 'anathema',
        definition: 'Something or someone that is greatly disliked or detested.',
        exampleSentence: 'The idea of cutting down the ancient forest was anathema to the conservationists.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'uh-NATH-uh-muh',
        etymology: 'Greek: anathema (thing devoted to evil), from anatithenai (to set up)',
    },
    {
        word: 'quintessential',
        definition: 'Representing the most perfect example of a quality or type.',
        exampleSentence: 'She was the quintessential student, always prepared and eager to learn.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'kwin-tuh-SEN-shul',
        etymology: 'Latin: quinta essentia (fifth essence), from the medieval concept of a fifth element',
    },
    {
        word: 'thoroughfare',
        definition: 'A main road or public highway.',
        exampleSentence: 'The city\'s main thoroughfare was closed for the annual parade.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'irregular',
        pronunciation: 'THUR-oh-fair',
        etymology: 'Old English: thuruh (through) + fare (a going, passage)',
    },
    {
        word: 'quixotic',
        definition: 'Extremely idealistic; impractical and unrealistic.',
        exampleSentence: 'His quixotic plan to sail around the world in a bathtub amused his friends.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'irregular',
        pronunciation: 'kwik-SOT-ik',
        etymology: 'Spanish: from Don Quixote, the idealistic hero of Cervantes\' novel',
    },
    {
        word: 'magnanimous',
        definition: 'Very generous or forgiving, especially toward a rival.',
        exampleSentence: 'The magnanimous winner congratulated her opponent with genuine warmth.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'mag-NAN-ih-mus',
        etymology: 'Latin: magnanimus (great-souled), from magnus (great) + animus (soul, spirit)',
    },
    {
        word: 'archipelago',
        definition: 'A group or chain of islands clustered together in a sea.',
        exampleSentence: 'Indonesia is a vast archipelago made up of thousands of islands.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'ar-kih-PEL-uh-goh',
        etymology: 'Greek: archi (chief) + pelagos (sea)',
    },
    {
        word: 'anachronism',
        definition: 'Something that is placed in the wrong historical time period.',
        exampleSentence: 'The wristwatch on the Roman soldier was a glaring anachronism in the film.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'uh-NAK-ruh-niz-um',
        etymology: 'Greek: anachronismos (wrong time reference), from ana (against) + chronos (time)',
    },
    {
        word: 'ignominious',
        definition: 'Deserving or causing public disgrace or shame.',
        exampleSentence: 'The team suffered an ignominious defeat in the championship game.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'ig-noh-MIN-ee-us',
        etymology: 'Latin: ignominiosus (disgraceful), from in (not) + nomen (name, reputation)',
    },
    {
        word: 'sanguine',
        definition: 'Optimistic or positive, especially in a difficult situation.',
        exampleSentence: 'Despite the setback, she remained sanguine about the project\'s success.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'SANG-gwin',
        etymology: 'Latin: sanguineus (of blood), from sanguis (blood); medieval belief linked blood to optimism',
    },
    {
        word: 'autochthonous',
        definition: 'Indigenous rather than imported; native to a place.',
        exampleSentence: 'The researchers studied the autochthonous plant species of the island.',
        partOfSpeech: 'adjective',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'aw-TOK-thuh-nus',
        etymology: 'Greek: autokhthon (sprung from the land itself), from autos (self) + khthon (earth)',
    },
    {
        word: 'abstemious',
        definition: 'Not self-indulgent, especially regarding food and drink.',
        exampleSentence: 'His abstemious habits kept him in excellent health into old age.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'ab-STEE-mee-us',
        etymology: 'Latin: abstemius (temperate), from abs (from) + temetum (strong drink)',
    },
    {
        word: 'lascivious',
        definition: 'Feeling or revealing an inappropriate desire.',
        exampleSentence: 'The censors objected to the lascivious content of the novel.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'luh-SIV-ee-us',
        etymology: 'Latin: lascivia (wantonness), from lascivus (playful, wanton)',
    },
    {
        word: 'otorhinolaryngology',
        definition: 'The study and treatment of diseases of the ear, nose, and throat.',
        exampleSentence: 'She decided to specialize in otorhinolaryngology after medical school.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'oh-toh-ry-noh-lair-in-GOL-uh-jee',
        etymology: 'Greek: oto (ear) + rhino (nose) + laryngo (throat) + logos (study)',
    },
    {
        word: 'querulous',
        definition: 'Complaining in a whiny or petulant way.',
        exampleSentence: 'The querulous customer demanded to speak with the manager.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'KWER-uh-lus',
        etymology: 'Latin: querulus (complaining), from queri (to complain)',
    },
    {
        word: 'phantasmagoria',
        definition: 'A sequence of dreamlike images, as seen in a dream or fever.',
        exampleSentence: 'The film was a phantasmagoria of surreal images and haunting music.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'fan-taz-muh-GOR-ee-uh',
        etymology: 'Greek: phantasma (image, phantom) + agora (assembly); coined in the 18th century',
    },
    {
        word: 'terpsichorean',
        definition: 'Relating to dancing.',
        exampleSentence: 'The terpsichorean display at the festival celebrated cultures from around the world.',
        partOfSpeech: 'adjective',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'turp-sih-koh-REE-un',
        etymology: 'Greek: Terpsichore (muse of dance), from terpein (to delight) + khoros (dance)',
    },
    {
        word: 'antediluvian',
        definition: 'Ridiculously old-fashioned; belonging to the time before the biblical flood.',
        exampleSentence: 'His antediluvian views on technology baffled his grandchildren.',
        partOfSpeech: 'adjective',
        difficulty: 10,
        pattern: 'latin-roots',
        pronunciation: 'an-tee-dih-LOO-vee-un',
        etymology: 'Latin: ante (before) + diluvium (flood, deluge)',
    },
    {
        word: 'callipygian',
        definition: 'Having well-shaped, attractive buttocks.',
        exampleSentence: 'The ancient Greek statue was noted for its callipygian proportions.',
        partOfSpeech: 'adjective',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'kal-ih-PIJ-ee-un',
        etymology: 'Greek: kallipygos (beautiful-buttocked), from kallos (beauty) + pyge (buttocks)',
    },
    {
        word: 'absquatulate',
        definition: 'To leave abruptly; to abscond.',
        exampleSentence: 'The suspect managed to absquatulate before the police arrived.',
        partOfSpeech: 'verb',
        difficulty: 10,
        pattern: 'latin-roots',
        pronunciation: 'ab-SKWOT-choo-layt',
        etymology: 'American English: humorous formation from ab (away) + squat + -ulate, a pseudo-Latin coinage',
    },
    {
        word: 'sisyphean',
        definition: 'Endlessly laborious or futile, like the task of Sisyphus.',
        exampleSentence: 'Organizing the cluttered attic felt like a sisyphean task.',
        partOfSpeech: 'adjective',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'sis-ih-FEE-un',
        etymology: 'Greek: from Sisyphos, the mythological king condemned to push a boulder uphill forever',
    },
    {
        word: 'obstreperous',
        definition: 'Noisy, unruly, and difficult to control.',
        exampleSentence: 'The obstreperous crowd made it impossible for the speaker to continue.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'ob-STREP-ur-us',
        etymology: 'Latin: obstreperus (noisy), from obstrepere (to make noise against)',
    },
    {
        word: 'synecdoche',
        definition: 'A figure of speech where a part represents the whole or vice versa.',
        exampleSentence: 'Saying "all hands on deck" is a synecdoche because hands refers to sailors.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'sih-NEK-duh-kee',
        etymology: 'Greek: synekdokhe (simultaneous understanding), from syn (with) + ekdekhesthai (to receive)',
    },
    {
        word: 'ameliorate',
        definition: 'To make a bad situation better or less severe.',
        exampleSentence: 'The charity worked tirelessly to ameliorate the living conditions of the refugees.',
        partOfSpeech: 'verb',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'uh-MEEL-yuh-rayt',
        etymology: 'Latin: ameliorare (to make better), from melior (better)',
    },
    {
        word: 'sangfroid',
        definition: 'Composure or coolness under strain; calmness in danger.',
        exampleSentence: 'The pilot showed remarkable sangfroid during the emergency landing.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'french-origin',
        pronunciation: 'sahn-FRWAH',
        etymology: 'French: sang-froid (cold blood), from sang (blood) + froid (cold)',
    },
    {
        word: 'perspicuous',
        definition: 'Clearly expressed and easily understood; lucid.',
        exampleSentence: 'The textbook was praised for its perspicuous explanation of quantum physics.',
        partOfSpeech: 'adjective',
        difficulty: 10,
        pattern: 'latin-roots',
        pronunciation: 'pur-SPIK-yoo-us',
        etymology: 'Latin: perspicuus (transparent, clear), from perspicere (to look through)',
    },
    {
        word: 'tintinnabulation',
        definition: 'A ringing or tinkling sound, as of bells.',
        exampleSentence: 'The tintinnabulation of the church bells echoed through the valley.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'latin-roots',
        pronunciation: 'tin-tin-ab-yoo-LAY-shun',
        etymology: 'Latin: tintinnabulum (small bell), from tintinnare (to ring, jingle)',
    },
    {
        word: 'magniloquent',
        definition: 'Using high-flown or bombastic language.',
        exampleSentence: 'The magniloquent speechwriter stuffed every paragraph with elaborate phrases.',
        partOfSpeech: 'adjective',
        difficulty: 10,
        pattern: 'latin-roots',
        pronunciation: 'mag-NIL-oh-kwent',
        etymology: 'Latin: magnus (great) + loqui (to speak)',
    },
    {
        word: 'defenestration',
        definition: 'The act of throwing someone out of a window.',
        exampleSentence: 'The Defenestration of Prague was a pivotal event in European history.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'latin-roots',
        pronunciation: 'dee-fen-uh-STRAY-shun',
        etymology: 'Latin: de (down from) + fenestra (window)',
    },
    {
        word: 'cataclysm',
        definition: 'A large-scale and violent event in the natural world; a disaster.',
        exampleSentence: 'The volcanic eruption was a cataclysm that reshaped the entire landscape.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'KAT-uh-kliz-um',
        etymology: 'Greek: kataklysmos (flood, deluge), from kata (down) + klyzein (to wash)',
    },
];
