/**
 * words/tier5-state.ts
 *
 * State-level spelling bee competition words (difficulty 8-10).
 * Words typical of state-level spelling bee competitions.
 * All entries include full etymology and source provenance.
 * ~100 curated entries.
 */
import type { SpellingWord } from './types';

export const TIER_5_STATE_WORDS: SpellingWord[] = [
    {
        word: 'abscission',
        definition: 'The natural separation of plant parts such as leaves or fruit.',
        exampleSentence: 'The abscission of autumn leaves creates a colorful display before winter.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'ab-SIZH-un',
        etymology: 'Latin: abscissio (a cutting off), from abscindere (to cut off), from ab (off) + scindere (to cut)',
        source: 'state-bee',
    },
    {
        word: 'accouterments',
        definition: 'Additional items of dress or equipment carried or worn.',
        exampleSentence: 'The hiker packed all the necessary accouterments for the week-long trail expedition.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'french-origin',
        pronunciation: 'uh-KOO-tur-munts',
        etymology: 'French: accoutrement (equipment), from accoutrer (to equip, dress)',
        source: 'state-bee',
    },
    {
        word: 'adjudicate',
        definition: 'To make a formal judgment or decision about a problem or disputed matter.',
        exampleSentence: 'The panel was asked to adjudicate the dispute between the two property owners.',
        partOfSpeech: 'verb',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'uh-JOO-dih-kayt',
        etymology: 'Latin: adjudicare (to award judicially), from ad (to) + judicare (to judge)',
        source: 'state-bee',
    },
    {
        word: 'ambidextrous',
        definition: 'Able to use the right and left hands equally well.',
        exampleSentence: 'The ambidextrous pitcher could throw with devastating accuracy from either arm.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'am-bih-DEK-strus',
        etymology: 'Latin: ambi (both) + dexter (right hand, skillful)',
        source: 'state-bee',
    },
    {
        word: 'antithesis',
        definition: 'A person or thing that is the direct opposite of someone or something else.',
        exampleSentence: 'His relaxed approach was the antithesis of his predecessor\'s rigid management style.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'an-TITH-uh-sis',
        etymology: 'Greek: antithesis (opposition), from anti (against) + thesis (a placing, proposition)',
        source: 'state-bee',
    },
    {
        word: 'archipelago',
        definition: 'A group or chain of islands clustered together in a body of water.',
        exampleSentence: 'The Philippine archipelago comprises over seven thousand islands.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'ar-kih-PEL-uh-goh',
        etymology: 'Greek: archi (chief) + pelagos (sea)',
        source: 'state-bee',
    },
    {
        word: 'bacchanalia',
        definition: 'Wild and drunken revelry; an orgiastic celebration.',
        exampleSentence: 'The historical novel described the bacchanalia of ancient Roman festivals.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'latin-roots',
        pronunciation: 'bak-uh-NAY-lee-uh',
        etymology: 'Latin: Bacchanalia (festival of Bacchus), from Bacchus (god of wine)',
        source: 'state-bee',
    },
    {
        word: 'bifurcate',
        definition: 'To divide into two branches or forks.',
        exampleSentence: 'The river bifurcates at the valley, creating two separate waterways.',
        partOfSpeech: 'verb',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'BY-fur-kayt',
        etymology: 'Latin: bifurcus (two-forked), from bi (two) + furca (fork)',
        source: 'state-bee',
    },
    {
        word: 'calligraphy',
        definition: 'The art of producing decorative handwriting or lettering.',
        exampleSentence: 'The wedding invitations featured exquisite calligraphy in gold and silver ink.',
        partOfSpeech: 'noun',
        difficulty: 8,
        pattern: 'greek-roots',
        pronunciation: 'kuh-LIG-ruh-fee',
        etymology: 'Greek: kalligraphia (beautiful writing), from kallos (beauty) + graphein (to write)',
        source: 'state-bee',
    },
    {
        word: 'cantaloupe',
        definition: 'A type of melon with orange flesh and a rough, netted rind.',
        exampleSentence: 'She sliced the ripe cantaloupe for the fruit salad at the picnic.',
        partOfSpeech: 'noun',
        difficulty: 8,
        pattern: 'french-origin',
        pronunciation: 'KAN-tuh-lohp',
        etymology: 'French: cantaloup, from Cantalupo, a papal estate near Rome where the melon was first cultivated',
        source: 'state-bee',
    },
    {
        word: 'chauvinism',
        definition: 'Exaggerated or aggressive patriotism; prejudiced support for one\'s own cause or group.',
        exampleSentence: 'The columnist criticized the chauvinism that prevented a fair assessment of other cultures.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'french-origin',
        pronunciation: 'SHOH-vin-iz-um',
        etymology: 'French: chauvinisme, from Nicolas Chauvin, a legendary soldier fanatically devoted to Napoleon',
        source: 'state-bee',
    },
    {
        word: 'coagulate',
        definition: 'To change from a liquid to a solid or semisolid state.',
        exampleSentence: 'The blood began to coagulate around the edges of the wound.',
        partOfSpeech: 'verb',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'koh-AG-yoo-layt',
        etymology: 'Latin: coagulare (to cause to curdle), from coagulum (rennet), from cogere (to drive together)',
        source: 'state-bee',
    },
    {
        word: 'corroboration',
        definition: 'Evidence that confirms or supports a statement or theory.',
        exampleSentence: 'The detective sought corroboration of the witness\'s account from security footage.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'kuh-rob-uh-RAY-shun',
        etymology: 'Latin: corroboratio (strengthening), from corroborare (to strengthen)',
        source: 'state-bee',
    },
    {
        word: 'daguerreotype',
        definition: 'An early type of photograph produced on a silver-coated copper plate.',
        exampleSentence: 'The museum displayed a rare daguerreotype of the city from the 1840s.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'french-origin',
        pronunciation: 'duh-GAIR-oh-typ',
        etymology: 'French: from Louis Daguerre, the French inventor who developed the process in 1839',
        source: 'state-bee',
    },
    {
        word: 'delineate',
        definition: 'To describe or portray precisely; to outline.',
        exampleSentence: 'The architect carefully delineated the floor plan for the new building.',
        partOfSpeech: 'verb',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'deh-LIN-ee-ayt',
        etymology: 'Latin: delineare (to sketch out), from de (completely) + lineare (to draw a line), from linea (line)',
        source: 'state-bee',
    },
    {
        word: 'desiccate',
        definition: 'To remove moisture from; to dry out thoroughly.',
        exampleSentence: 'The extreme heat desiccated the soil, leaving deep cracks across the field.',
        partOfSpeech: 'verb',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'DES-ih-kayt',
        etymology: 'Latin: desiccare (to dry up), from de (thoroughly) + siccare (to dry), from siccus (dry)',
        source: 'state-bee',
    },
    {
        word: 'discombobulate',
        definition: 'To confuse or disconcert; to upset or frustrate.',
        exampleSentence: 'The sudden change in schedule discombobulated the entire production team.',
        partOfSpeech: 'verb',
        difficulty: 9,
        pattern: 'irregular',
        pronunciation: 'dis-kum-BOB-yoo-layt',
        etymology: 'American English: humorous alteration of discompose or discomfit, of uncertain further origin',
        source: 'state-bee',
    },
    {
        word: 'efficacious',
        definition: 'Successful in producing a desired or intended result.',
        exampleSentence: 'The new treatment proved highly efficacious in clinical trials.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'ef-ih-KAY-shus',
        etymology: 'Latin: efficax (effective), from efficere (to accomplish), from ex (out) + facere (to make)',
        source: 'state-bee',
    },
    {
        word: 'eloquence',
        definition: 'Fluent or persuasive speaking or writing.',
        exampleSentence: 'The lawyer\'s eloquence in the courtroom swayed the jury to acquit the defendant.',
        partOfSpeech: 'noun',
        difficulty: 8,
        pattern: 'latin-roots',
        pronunciation: 'EL-oh-kwenss',
        etymology: 'Latin: eloquentia (fluency of speech), from eloqui (to speak out)',
        source: 'state-bee',
    },
    {
        word: 'embouchure',
        definition: 'The way in which a player applies the mouth to a wind or brass instrument.',
        exampleSentence: 'The trumpet teacher corrected the student\'s embouchure to improve her tone.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'french-origin',
        pronunciation: 'AHM-boo-shoor',
        etymology: 'French: embouchure (mouth of a river, mouthpiece), from emboucher (to put to the mouth)',
        source: 'state-bee',
    },
    {
        word: 'erysipelas',
        definition: 'An acute bacterial infection of the skin causing a painful red rash.',
        exampleSentence: 'The doctor prescribed antibiotics to treat the erysipelas on the patient\'s leg.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'er-ih-SIP-uh-lus',
        etymology: 'Greek: erysipelas (red skin), from erythros (red) + pella (skin)',
        source: 'state-bee',
    },
    {
        word: 'evanescent',
        definition: 'Soon passing out of sight, memory, or existence; quickly fading.',
        exampleSentence: 'The evanescent morning mist disappeared as soon as the sun rose above the hills.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'ev-uh-NES-unt',
        etymology: 'Latin: evanescere (to vanish), from e (out) + vanescere (to vanish), from vanus (empty)',
        source: 'state-bee',
    },
    {
        word: 'fluorescent',
        definition: 'Vividly bright; emitting light during exposure to radiation.',
        exampleSentence: 'The fluorescent lights in the office gave everything a slightly greenish tint.',
        partOfSpeech: 'adjective',
        difficulty: 8,
        pattern: 'latin-roots',
        pronunciation: 'floo-RES-unt',
        etymology: 'Latin: fluor (a flowing), from fluere (to flow); named after the mineral fluorite',
        source: 'state-bee',
    },
    {
        word: 'flocculent',
        definition: 'Having or resembling tufts of wool; downy.',
        exampleSentence: 'The flocculent clouds resembled cotton balls scattered across the blue sky.',
        partOfSpeech: 'adjective',
        difficulty: 10,
        pattern: 'latin-roots',
        pronunciation: 'FLOK-yoo-lunt',
        etymology: 'Latin: flocculus (small tuft), diminutive of floccus (tuft of wool)',
        source: 'state-bee',
    },
    {
        word: 'fuselage',
        definition: 'The main body of an aircraft.',
        exampleSentence: 'The engineers reinforced the fuselage to withstand higher cabin pressure.',
        partOfSpeech: 'noun',
        difficulty: 8,
        pattern: 'french-origin',
        pronunciation: 'FYOO-zuh-lahzh',
        etymology: 'French: fuselage (spindle-shaped), from fusele (shaped like a spindle), from fuseau (spindle)',
        source: 'state-bee',
    },
    {
        word: 'gargantuan',
        definition: 'Enormous; immense.',
        exampleSentence: 'The gargantuan feast featured dishes from twelve different cuisines.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'french-origin',
        pronunciation: 'gar-GAN-choo-un',
        etymology: 'French: from Gargantua, the giant king in Rabelais\' satirical novels',
        source: 'state-bee',
    },
    {
        word: 'hemorrhoid',
        definition: 'A swollen vein in the region of the anus.',
        exampleSentence: 'The doctor recommended a topical treatment for the hemorrhoid.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'HEM-uh-royd',
        etymology: 'Greek: haimorrhoides (bleeding veins), from haima (blood) + rhein (to flow)',
        source: 'state-bee',
    },
    {
        word: 'hyperbole',
        definition: 'Exaggerated statements not meant to be taken literally.',
        exampleSentence: 'Saying "I have a million things to do" is an example of hyperbole.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'hy-PUR-buh-lee',
        etymology: 'Greek: hyperbole (excess), from hyper (beyond) + ballein (to throw)',
        source: 'state-bee',
    },
    {
        word: 'imprimatur',
        definition: 'An official license to print or publish; official approval.',
        exampleSentence: 'The project received the imprimatur of the university\'s research ethics board.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'latin-roots',
        pronunciation: 'im-prih-MAH-tur',
        etymology: 'Latin: imprimatur (let it be printed), from imprimere (to impress, print)',
        source: 'state-bee',
    },
    {
        word: 'incandescent',
        definition: 'Emitting light as a result of being heated; brilliant or outstanding.',
        exampleSentence: 'The incandescent bulb cast a warm golden glow over the dining room.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'in-kan-DES-unt',
        etymology: 'Latin: incandescere (to become white hot), from in (intensive) + candescere (to glow)',
        source: 'state-bee',
    },
    {
        word: 'infinitesimal',
        definition: 'Extremely small; immeasurably minute.',
        exampleSentence: 'The probability of winning the lottery is infinitesimal.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'in-fin-ih-TES-ih-mul',
        etymology: 'Latin: infinitesimus (infinite in degree), from infinitus (unlimited)',
        source: 'state-bee',
    },
    {
        word: 'inoculate',
        definition: 'To treat with a vaccine to produce immunity against a disease.',
        exampleSentence: 'The clinic worked to inoculate every child in the village against measles.',
        partOfSpeech: 'verb',
        difficulty: 8,
        pattern: 'latin-roots',
        pronunciation: 'in-OK-yoo-layt',
        etymology: 'Latin: inoculare (to graft a bud), from in (into) + oculus (eye, bud)',
        source: 'state-bee',
    },
    {
        word: 'insatiable',
        definition: 'Impossible to satisfy; always wanting more.',
        exampleSentence: 'The child had an insatiable curiosity about how machines worked.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'in-SAY-shuh-bul',
        etymology: 'Latin: insatiabilis (that cannot be satisfied), from in (not) + satiare (to fill, satisfy)',
        source: 'state-bee',
    },
    {
        word: 'isosceles',
        definition: 'Having two sides of equal length, as in a triangle.',
        exampleSentence: 'The geometry teacher explained the properties of an isosceles triangle.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'eye-SOS-uh-leez',
        etymology: 'Greek: isoskeles (equal-legged), from isos (equal) + skelos (leg)',
        source: 'state-bee',
    },
    {
        word: 'kaleidoscope',
        definition: 'A toy with mirrors and colored glass producing changing patterns; a constantly shifting scene.',
        exampleSentence: 'The carnival was a kaleidoscope of colors, sounds, and movement.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'kuh-LY-duh-skohp',
        etymology: 'Greek: kalos (beautiful) + eidos (form) + skopein (to look at)',
        source: 'state-bee',
    },
    {
        word: 'knowledgeable',
        definition: 'Intelligent and well informed.',
        exampleSentence: 'The knowledgeable tour guide answered every question about the ancient ruins.',
        partOfSpeech: 'adjective',
        difficulty: 8,
        pattern: 'irregular',
        pronunciation: 'NOL-ij-uh-bul',
        etymology: 'Middle English: knowleche (knowledge), from know + -leche (suffix denoting action)',
        source: 'state-bee',
    },
    {
        word: 'labyrinth',
        definition: 'A complicated irregular network of passages or paths; a maze.',
        exampleSentence: 'The old city center was a labyrinth of narrow streets and hidden courtyards.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'LAB-uh-rinth',
        etymology: 'Greek: labyrinthos (maze), associated with the mythical maze built by Daedalus for King Minos',
        source: 'state-bee',
    },
    {
        word: 'legitimacy',
        definition: 'Conformity to the law or to rules; the quality of being reasonable.',
        exampleSentence: 'The court ruling established the legitimacy of the new government.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'leh-JIT-ih-muh-see',
        etymology: 'Latin: legitimus (lawful), from lex (law)',
        source: 'state-bee',
    },
    {
        word: 'liaison',
        definition: 'Communication or cooperation between groups; a person who ensures such communication.',
        exampleSentence: 'She served as the liaison between the research team and the government agency.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'french-origin',
        pronunciation: 'lee-AY-zon',
        etymology: 'French: liaison (connection, linking), from lier (to bind), from Latin: ligare',
        source: 'state-bee',
    },
    {
        word: 'malevolent',
        definition: 'Having or showing a wish to do evil to others.',
        exampleSentence: 'The malevolent villain plotted to overthrow the peaceful kingdom.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'muh-LEV-uh-lunt',
        etymology: 'Latin: malevolens (ill-disposed), from male (badly) + volens (wishing), from velle (to wish)',
        source: 'state-bee',
    },
    {
        word: 'masquerade',
        definition: 'A false show or pretense; a party where people wear masks and costumes.',
        exampleSentence: 'The charity hosted an elaborate masquerade ball at the historic mansion.',
        partOfSpeech: 'noun',
        difficulty: 8,
        pattern: 'french-origin',
        pronunciation: 'mas-kuh-RAYD',
        etymology: 'French: mascarade (masked ball), from Italian: mascherata, from maschera (mask)',
        source: 'state-bee',
    },
    {
        word: 'meringue',
        definition: 'A confection made from whipped egg whites and sugar, typically baked.',
        exampleSentence: 'The lemon meringue pie was topped with perfectly golden peaks.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'french-origin',
        pronunciation: 'muh-RANG',
        etymology: 'French: meringue, of uncertain origin; possibly from German: Meringer (a cake from Mehringen)',
        source: 'state-bee',
    },
    {
        word: 'miscellaneous',
        definition: 'Of various types or from various sources.',
        exampleSentence: 'The drawer was filled with miscellaneous items accumulated over the years.',
        partOfSpeech: 'adjective',
        difficulty: 8,
        pattern: 'latin-roots',
        pronunciation: 'mis-uh-LAY-nee-us',
        etymology: 'Latin: miscellaneus (mixed), from miscere (to mix)',
        source: 'state-bee',
    },
    {
        word: 'mischievous',
        definition: 'Causing or showing a fondness for causing trouble in a playful way.',
        exampleSentence: 'The mischievous puppy chewed every shoe it could find.',
        partOfSpeech: 'adjective',
        difficulty: 8,
        pattern: 'french-origin',
        pronunciation: 'MIS-chuh-vus',
        etymology: 'Old French: meschever (to come to grief), from mes (wrongly) + chever (to come to an end)',
        source: 'state-bee',
    },
    {
        word: 'mosaic',
        definition: 'A picture or pattern produced by arranging small colored pieces of stone or glass.',
        exampleSentence: 'The ancient mosaic on the villa floor depicted scenes from Greek mythology.',
        partOfSpeech: 'noun',
        difficulty: 8,
        pattern: 'greek-roots',
        pronunciation: 'moh-ZAY-ik',
        etymology: 'Greek: mouseion (place of the Muses), via Latin: musaicum (artistic work inspired by the Muses)',
        source: 'state-bee',
    },
    {
        word: 'nonchalant',
        definition: 'Feeling or appearing casually calm and relaxed.',
        exampleSentence: 'She tried to look nonchalant, but her trembling hands betrayed her nervousness.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'french-origin',
        pronunciation: 'non-shuh-LAHNT',
        etymology: 'French: nonchalant (careless), from non (not) + chaloir (to be concerned), from Latin: calere (to be warm)',
        source: 'state-bee',
    },
    {
        word: 'opalescent',
        definition: 'Showing varying colors as an opal does; iridescent.',
        exampleSentence: 'The opalescent surface of the pearl shimmered with pink and blue hues.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'oh-puh-LES-unt',
        etymology: 'Latin: opalus (opal) + -escent (becoming, displaying)',
        source: 'state-bee',
    },
    {
        word: 'oscillate',
        definition: 'To move or swing back and forth at a regular speed.',
        exampleSentence: 'The pendulum continued to oscillate long after the clock was wound.',
        partOfSpeech: 'verb',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'OS-ih-layt',
        etymology: 'Latin: oscillare (to swing), from oscillum (a swing)',
        source: 'state-bee',
    },
    {
        word: 'outrageous',
        definition: 'Shockingly bad or excessive; wildly exaggerated.',
        exampleSentence: 'The outrageous prices at the resort discouraged budget-conscious travelers.',
        partOfSpeech: 'adjective',
        difficulty: 8,
        pattern: 'french-origin',
        pronunciation: 'owt-RAY-jus',
        etymology: 'Old French: outrage (excess), from outre (beyond), from Latin: ultra',
        source: 'state-bee',
    },
    {
        word: 'paraphernalia',
        definition: 'Miscellaneous articles, especially the equipment needed for a particular activity.',
        exampleSentence: 'The photographer carried all her paraphernalia in a large equipment bag.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'par-uh-fur-NAY-lee-uh',
        etymology: 'Greek: parapherna (property beyond a dowry), from para (beyond) + pherne (dowry)',
        source: 'state-bee',
    },
    {
        word: 'pasteurize',
        definition: 'To heat food or drink to kill harmful bacteria.',
        exampleSentence: 'Dairies pasteurize milk to make it safe for consumption.',
        partOfSpeech: 'verb',
        difficulty: 9,
        pattern: 'french-origin',
        pronunciation: 'PAS-chur-yz',
        etymology: 'French: from Louis Pasteur, the French microbiologist who developed the process',
        source: 'state-bee',
    },
    {
        word: 'peccadillo',
        definition: 'A small, relatively unimportant offense or sin.',
        exampleSentence: 'The voters forgave the candidate\'s peccadillo and reelected her by a wide margin.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'latin-roots',
        pronunciation: 'pek-uh-DIL-oh',
        etymology: 'Spanish: pecadillo (small sin), diminutive of pecado (sin), from Latin: peccatum (sin)',
        source: 'state-bee',
    },
    {
        word: 'penicillin',
        definition: 'An antibiotic produced from Penicillium molds.',
        exampleSentence: 'The discovery of penicillin revolutionized the treatment of bacterial infections.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'pen-ih-SIL-in',
        etymology: 'Latin: penicillum (paintbrush, tuft of hair), describing the brush-like shape of the mold',
        source: 'state-bee',
    },
    {
        word: 'perennial',
        definition: 'Lasting for an indefinitely long time; recurring year after year.',
        exampleSentence: 'Lavender is a perennial plant that returns each spring with fragrant blooms.',
        partOfSpeech: 'adjective',
        difficulty: 8,
        pattern: 'latin-roots',
        pronunciation: 'puh-REN-ee-ul',
        etymology: 'Latin: perennis (lasting through the year), from per (through) + annus (year)',
        source: 'state-bee',
    },
    {
        word: 'plausible',
        definition: 'Seeming reasonable or probable; convincing.',
        exampleSentence: 'The detective found his alibi plausible but continued investigating.',
        partOfSpeech: 'adjective',
        difficulty: 8,
        pattern: 'latin-roots',
        pronunciation: 'PLAW-zih-bul',
        etymology: 'Latin: plausibilis (worthy of applause), from plaudere (to applaud)',
        source: 'state-bee',
    },
    {
        word: 'predecessor',
        definition: 'A person who held a job or office before the current holder.',
        exampleSentence: 'The new principal introduced several changes that her predecessor had resisted.',
        partOfSpeech: 'noun',
        difficulty: 8,
        pattern: 'latin-roots',
        pronunciation: 'PRED-uh-ses-ur',
        etymology: 'Latin: praedecessor (one who retires from office), from prae (before) + decessor (retiring officer)',
        source: 'state-bee',
    },
    {
        word: 'reconnaissance',
        definition: 'Military observation of a region to locate an enemy or determine strategic features.',
        exampleSentence: 'The troops conducted reconnaissance of the area before advancing.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'french-origin',
        pronunciation: 'reh-KON-uh-sunss',
        etymology: 'French: reconnaissance (recognition, exploration), from reconnaitre (to recognize)',
        source: 'state-bee',
    },
    {
        word: 'rendezvous',
        definition: 'A meeting at an agreed time and place.',
        exampleSentence: 'The spies arranged a clandestine rendezvous at the abandoned warehouse.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'french-origin',
        pronunciation: 'RON-day-voo',
        etymology: 'French: rendez-vous (present yourselves), from se rendre (to present oneself)',
        source: 'state-bee',
    },
    {
        word: 'resuscitate',
        definition: 'To revive from unconsciousness or apparent death.',
        exampleSentence: 'The paramedics worked quickly to resuscitate the drowning victim.',
        partOfSpeech: 'verb',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'reh-SUS-ih-tayt',
        etymology: 'Latin: resuscitare (to raise up again), from re (again) + suscitare (to raise)',
        source: 'state-bee',
    },
    {
        word: 'rhododendron',
        definition: 'A shrub or small tree with large clusters of bell-shaped flowers.',
        exampleSentence: 'The garden was ablaze with pink and purple rhododendron blooms in May.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'roh-duh-DEN-drun',
        etymology: 'Greek: rhododendron (rose tree), from rhodon (rose) + dendron (tree)',
        source: 'state-bee',
    },
    {
        word: 'sacrosanct',
        definition: 'Regarded as too important or valuable to be interfered with.',
        exampleSentence: 'In many families, the Sunday dinner tradition was considered sacrosanct.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'SAK-roh-sankt',
        etymology: 'Latin: sacrosanctus (consecrated with religious ceremonies), from sacer (sacred) + sanctus (holy)',
        source: 'state-bee',
    },
    {
        word: 'schmaltz',
        definition: 'Excessive sentimentality; rendered chicken fat used in cooking.',
        exampleSentence: 'The holiday movie was full of schmaltz that made audiences both laugh and cry.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'irregular',
        pronunciation: 'SHMAHLTS',
        etymology: 'Yiddish: shmalts (rendered fat), from German: Schmalz (grease, lard)',
        source: 'state-bee',
    },
    {
        word: 'silhouette',
        definition: 'The dark shape and outline of someone or something visible against a lighter background.',
        exampleSentence: 'The silhouette of the mountain range was stunning against the sunset.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'french-origin',
        pronunciation: 'sil-oo-ET',
        etymology: 'French: from Etienne de Silhouette, a French finance minister whose austerity policies were mocked',
        source: 'state-bee',
    },
    {
        word: 'solemnity',
        definition: 'The state or quality of being serious and dignified.',
        exampleSentence: 'The solemnity of the memorial ceremony moved everyone in attendance.',
        partOfSpeech: 'noun',
        difficulty: 8,
        pattern: 'latin-roots',
        pronunciation: 'suh-LEM-nih-tee',
        etymology: 'Latin: solemnitas (ceremony, completeness), from sollemnis (established, ceremonial)',
        source: 'state-bee',
    },
    {
        word: 'sovereignty',
        definition: 'Supreme power or authority; the authority of a state to govern itself.',
        exampleSentence: 'The nation fought for its sovereignty against the colonial power.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'french-origin',
        pronunciation: 'SOV-run-tee',
        etymology: 'Old French: souverainete (authority), from souverain (sovereign), from Latin: superanus (chief)',
        source: 'state-bee',
    },
    {
        word: 'spontaneity',
        definition: 'The condition of being spontaneous; unplanned or impulsive behavior.',
        exampleSentence: 'The spontaneity of the street performers delighted the tourists.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'spon-tuh-NEE-ih-tee',
        etymology: 'Latin: spontaneus (voluntary, of one\'s own accord), from sponte (of one\'s free will)',
        source: 'state-bee',
    },
    {
        word: 'strenuous',
        definition: 'Requiring or using great exertion.',
        exampleSentence: 'The strenuous hike up the mountain left everyone gasping for breath.',
        partOfSpeech: 'adjective',
        difficulty: 8,
        pattern: 'latin-roots',
        pronunciation: 'STREN-yoo-us',
        etymology: 'Latin: strenuus (active, vigorous)',
        source: 'state-bee',
    },
    {
        word: 'subterranean',
        definition: 'Existing, occurring, or done under the earth\'s surface.',
        exampleSentence: 'The subterranean cave system extended for miles beneath the limestone plateau.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'sub-tuh-RAY-nee-un',
        etymology: 'Latin: subterraneus (underground), from sub (under) + terra (earth)',
        source: 'state-bee',
    },
    {
        word: 'surveillance',
        definition: 'Close observation, especially of a suspected person.',
        exampleSentence: 'The police maintained surveillance on the building for several weeks.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'french-origin',
        pronunciation: 'sur-VAY-lunss',
        etymology: 'French: surveillance (oversight, watching), from surveiller (to watch over), from sur (over) + veiller (to watch)',
        source: 'state-bee',
    },
    {
        word: 'therapeutic',
        definition: 'Relating to the healing of disease; having a good effect on the body or mind.',
        exampleSentence: 'The therapeutic benefits of massage are well documented in medical literature.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'thair-uh-PYOO-tik',
        etymology: 'Greek: therapeutikos (inclined to serve), from therapeuein (to heal, attend)',
        source: 'state-bee',
    },
    {
        word: 'topography',
        definition: 'The arrangement of the natural and artificial physical features of an area.',
        exampleSentence: 'The topography of the region made road construction extremely challenging.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'toh-POG-ruh-fee',
        etymology: 'Greek: topographia (description of a place), from topos (place) + graphein (to write)',
        source: 'state-bee',
    },
    {
        word: 'translucent',
        definition: 'Allowing light to pass through partially; semitransparent.',
        exampleSentence: 'The translucent curtains softened the harsh afternoon sunlight.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'trans-LOO-sunt',
        etymology: 'Latin: translucere (to shine through), from trans (through) + lucere (to shine)',
        source: 'state-bee',
    },
    {
        word: 'tyrannical',
        definition: 'Exercising power in a cruel or arbitrary way.',
        exampleSentence: 'The people rose up against the tyrannical regime and demanded democratic elections.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'tih-RAN-ih-kul',
        etymology: 'Greek: tyrannikos (of a tyrant), from tyrannos (absolute ruler)',
        source: 'state-bee',
    },
    {
        word: 'unconscionable',
        definition: 'Not right or reasonable; unreasonably excessive.',
        exampleSentence: 'The unconscionable delay in delivering emergency supplies cost many lives.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'un-KON-shun-uh-bul',
        etymology: 'Latin: conscientia (moral awareness), with un- (not) and -able (capable of)',
        source: 'state-bee',
    },
    {
        word: 'ventriloquist',
        definition: 'A person who can speak without moving their lips, making the voice seem to come from elsewhere.',
        exampleSentence: 'The ventriloquist entertained the children with her talking puppet act.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'ven-TRIL-oh-kwist',
        etymology: 'Latin: ventriloquus (one who speaks from the belly), from venter (belly) + loqui (to speak)',
        source: 'state-bee',
    },
    {
        word: 'vicarious',
        definition: 'Experienced in the imagination through the feelings or actions of another.',
        exampleSentence: 'She lived vicariously through her daughter\'s adventures traveling the world.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'vy-KAIR-ee-us',
        etymology: 'Latin: vicarius (substituted, delegated), from vicis (change, alternation)',
        source: 'state-bee',
    },
    {
        word: 'wisteria',
        definition: 'A climbing shrub with hanging clusters of fragrant flowers.',
        exampleSentence: 'The pergola was draped with cascading purple wisteria.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'irregular',
        pronunciation: 'wis-TEER-ee-uh',
        etymology: 'Named after Caspar Wistar (1761-1818), American anatomist',
        source: 'state-bee',
    },
    {
        word: 'acquittal',
        definition: 'A judgment that a person is not guilty of the crime with which they have been charged.',
        exampleSentence: 'The jury\'s acquittal came as a surprise to both the prosecution and the media.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'french-origin',
        pronunciation: 'uh-KWIT-ul',
        etymology: 'Old French: acquiter (to discharge a debt), from a (to) + quiter (to set free)',
        source: 'state-bee',
    },
    {
        word: 'bourgeois',
        definition: 'Of or characteristic of the middle class; materialistic or conventional.',
        exampleSentence: 'The artist rejected bourgeois values in favor of a bohemian lifestyle.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'french-origin',
        pronunciation: 'boor-ZHWAH',
        etymology: 'French: bourgeois (citizen, middle class), from bourg (market town)',
        source: 'state-bee',
    },
    {
        word: 'claustrophobia',
        definition: 'Extreme or irrational fear of confined places.',
        exampleSentence: 'His claustrophobia made it impossible for him to ride in elevators.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'klaws-truh-FOH-bee-uh',
        etymology: 'Latin: claustrum (enclosed place) + Greek: phobos (fear)',
        source: 'state-bee',
    },
    {
        word: 'concatenate',
        definition: 'To link things together in a chain or series.',
        exampleSentence: 'The programmer used a function to concatenate the two strings of text.',
        partOfSpeech: 'verb',
        difficulty: 10,
        pattern: 'latin-roots',
        pronunciation: 'kon-KAT-uh-nayt',
        etymology: 'Latin: concatenare (to chain together), from con (together) + catena (chain)',
        source: 'state-bee',
    },
    {
        word: 'convalescence',
        definition: 'The time spent recovering from an illness or medical treatment.',
        exampleSentence: 'During her convalescence, she read dozens of novels and wrote in her journal.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'kon-vuh-LES-unss',
        etymology: 'Latin: convalescere (to grow strong), from con (intensive) + valescere (to grow strong)',
        source: 'state-bee',
    },
    {
        word: 'demitasse',
        definition: 'A small cup of strong black coffee; the cup itself.',
        exampleSentence: 'After dinner, the host offered each guest a demitasse of espresso.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'french-origin',
        pronunciation: 'DEM-ee-tass',
        etymology: 'French: demitasse (half cup), from demi (half) + tasse (cup)',
        source: 'state-bee',
    },
    {
        word: 'eccentricity',
        definition: 'The quality of being unconventional or slightly strange.',
        exampleSentence: 'The professor was known for her eccentricity, including wearing mismatched shoes.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'ek-sen-TRIS-ih-tee',
        etymology: 'Greek: ekkentros (out of center), from ek (out) + kentron (center)',
        source: 'state-bee',
    },
    {
        word: 'flamboyant',
        definition: 'Tending to attract attention because of exuberance, confidence, and stylishness.',
        exampleSentence: 'The flamboyant designer was famous for his bold use of color and pattern.',
        partOfSpeech: 'adjective',
        difficulty: 8,
        pattern: 'french-origin',
        pronunciation: 'flam-BOY-unt',
        etymology: 'French: flamboyant (flaming, blazing), from flamboyer (to flame), from flambe (flame)',
        source: 'state-bee',
    },
    {
        word: 'gesticulate',
        definition: 'To use gestures, especially dramatic ones, instead of or in addition to speaking.',
        exampleSentence: 'The excited tour guide gesticulated wildly as he described the ancient battle.',
        partOfSpeech: 'verb',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'jeh-STIK-yoo-layt',
        etymology: 'Latin: gesticulari (to make mimic gestures), from gesticulus (a mimic gesture), from gestus (gesture)',
        source: 'state-bee',
    },
    {
        word: 'heuristic',
        definition: 'Enabling a person to discover or learn something for themselves.',
        exampleSentence: 'The teacher used a heuristic approach that encouraged students to find answers independently.',
        partOfSpeech: 'adjective',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'hyoo-RIS-tik',
        etymology: 'Greek: heuriskein (to find, discover)',
        source: 'state-bee',
    },
    {
        word: 'hypotenuse',
        definition: 'The longest side of a right triangle, opposite the right angle.',
        exampleSentence: 'The Pythagorean theorem calculates the length of the hypotenuse.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'hy-POT-uh-nooss',
        etymology: 'Greek: hypoteinousa (subtending), from hypo (under) + teinein (to stretch)',
        source: 'state-bee',
    },
    {
        word: 'idiomatic',
        definition: 'Using expressions natural to a native speaker; peculiar to a particular language.',
        exampleSentence: 'The translator struggled with the idiomatic expressions that had no direct equivalent.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'id-ee-oh-MAT-ik',
        etymology: 'Greek: idiomatikos (peculiar), from idioma (peculiar phraseology), from idios (own, private)',
        source: 'state-bee',
    },
    {
        word: 'magnolia',
        definition: 'A tree or shrub with large, typically creamy-pink, waxy flowers.',
        exampleSentence: 'The magnificent magnolia tree bloomed every spring outside the courthouse.',
        partOfSpeech: 'noun',
        difficulty: 8,
        pattern: 'latin-roots',
        pronunciation: 'mag-NOH-lee-uh',
        etymology: 'Named after Pierre Magnol (1638-1715), French botanist',
        source: 'state-bee',
    },
    {
        word: 'neurology',
        definition: 'The branch of medicine dealing with the nervous system and its disorders.',
        exampleSentence: 'She specialized in neurology after witnessing her grandfather\'s struggle with Parkinson\'s.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'noo-ROL-uh-jee',
        etymology: 'Greek: neuron (nerve) + logos (study)',
        source: 'state-bee',
    },
    {
        word: 'nomenclature',
        definition: 'The devising or choosing of names for things in a particular field.',
        exampleSentence: 'Botanical nomenclature follows a strict set of internationally agreed rules.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'NOH-men-klay-chur',
        etymology: 'Latin: nomenclatura (calling by name), from nomen (name) + calare (to call)',
        source: 'state-bee',
    },
    {
        word: 'palindromic',
        definition: 'Of or relating to a palindrome; reading the same forwards and backwards.',
        exampleSentence: 'The date 02/02/2020 was palindromic when written in many date formats.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'pal-in-DROM-ik',
        etymology: 'Greek: palindromos (running back again), from palin (again) + dromos (running)',
        source: 'state-bee',
    },
    {
        word: 'parenthetical',
        definition: 'Relating to or inserted as a parenthesis; incidental.',
        exampleSentence: 'The author\'s parenthetical remark added humor to an otherwise serious passage.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'par-un-THEH-tih-kul',
        etymology: 'Greek: parenthesis (a putting in beside), from para (beside) + en (in) + tithenai (to place)',
        source: 'state-bee',
    },
    {
        word: 'prerequisite',
        definition: 'A thing that is required as a prior condition for something else to happen.',
        exampleSentence: 'Chemistry 101 is a prerequisite for all advanced science courses.',
        partOfSpeech: 'noun',
        difficulty: 8,
        pattern: 'latin-roots',
        pronunciation: 'pree-REK-wih-zit',
        etymology: 'Latin: prae (before) + requisitus (required), from requirere (to seek again)',
        source: 'state-bee',
    },
    {
        word: 'pseudonym',
        definition: 'A fictitious name, especially one used by an author.',
        exampleSentence: 'The famous author published several novels under a pseudonym to avoid attention.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'SOO-doh-nim',
        etymology: 'Greek: pseudonymon (having a false name), from pseudos (false) + onyma (name)',
        source: 'state-bee',
    },
    {
        word: 'quarantine',
        definition: 'A state of isolation imposed to prevent the spread of disease.',
        exampleSentence: 'The travelers were placed in quarantine for two weeks upon their arrival.',
        partOfSpeech: 'noun',
        difficulty: 8,
        pattern: 'latin-roots',
        pronunciation: 'KWOR-un-teen',
        etymology: 'Italian: quarantina (forty days), from quaranta (forty), from Latin: quadraginta',
        source: 'state-bee',
    },
    {
        word: 'sarsaparilla',
        definition: 'A tropical American plant whose roots are used in drinks and medicine.',
        exampleSentence: 'The old-fashioned soda fountain served sarsaparilla as one of its signature drinks.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'irregular',
        pronunciation: 'sar-suh-puh-RIL-uh',
        etymology: 'Spanish: zarzaparrilla, from zarza (bramble) + parrilla (small vine, diminutive of parra)',
        source: 'state-bee',
    },
    {
        word: 'soliloquize',
        definition: 'To talk to oneself; to speak a soliloquy.',
        exampleSentence: 'The actor soliloquized brilliantly in the opening scene of the play.',
        partOfSpeech: 'verb',
        difficulty: 10,
        pattern: 'latin-roots',
        pronunciation: 'suh-LIL-oh-kwyz',
        etymology: 'Latin: soliloquium (a talking to oneself), from solus (alone) + loqui (to speak)',
        source: 'state-bee',
    },
    {
        word: 'surreptitious',
        definition: 'Kept secret, especially because it would not be approved of.',
        exampleSentence: 'The surreptitious recording of the meeting violated company policy.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'sur-up-TISH-us',
        etymology: 'Latin: surrepticius (stolen, secret), from surripere (to snatch secretly)',
        source: 'state-bee',
    },
    {
        word: 'tautology',
        definition: 'The saying of the same thing twice in different words, generally as a fault of style.',
        exampleSentence: 'The phrase "free gift" is a tautology because gifts are inherently free.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'taw-TOL-uh-jee',
        etymology: 'Greek: tautologia (saying the same thing), from tauto (the same) + logos (word)',
        source: 'state-bee',
    },
    {
        word: 'temperamental',
        definition: 'Liable to unreasonable changes of mood; unpredictable.',
        exampleSentence: 'The temperamental artist refused to paint unless conditions were perfect.',
        partOfSpeech: 'adjective',
        difficulty: 8,
        pattern: 'latin-roots',
        pronunciation: 'tem-pruh-MEN-tul',
        etymology: 'Latin: temperamentum (proper mixture), from temperare (to mingle, regulate)',
        source: 'state-bee',
    },
    {
        word: 'verisimilitude',
        definition: 'The appearance of being true or real.',
        exampleSentence: 'The movie achieved verisimilitude through meticulous attention to period detail.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'latin-roots',
        pronunciation: 'vair-ih-sih-MIL-ih-tood',
        etymology: 'Latin: verisimilitudo (likeness to truth), from verus (true) + similis (similar)',
        source: 'state-bee',
    },
    {
        word: 'vituperative',
        definition: 'Bitter and abusive in criticism.',
        exampleSentence: 'The vituperative editorial attacked the governor\'s record on every front.',
        partOfSpeech: 'adjective',
        difficulty: 10,
        pattern: 'latin-roots',
        pronunciation: 'vy-TOO-pur-uh-tiv',
        etymology: 'Latin: vituperare (to blame, censure), from vitium (fault) + parare (to make)',
        source: 'state-bee',
    },
    {
        word: 'onomatopoeia',
        definition: 'The formation of a word from a sound associated with what is named.',
        exampleSentence: 'Words like "buzz" and "splash" are examples of onomatopoeia.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'on-uh-mat-uh-PEE-uh',
        etymology: 'Greek: onomatopoiia (word-making), from onoma (name) + poiein (to make)',
        source: 'state-bee',
    },
    {
        word: 'presumptuous',
        definition: 'Failing to observe the limits of what is permitted or appropriate.',
        exampleSentence: 'It would be presumptuous to assume you know what the committee will decide.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'prih-ZUMP-choo-us',
        etymology: 'Latin: praesumptuosus (full of presumption), from praesumere (to take beforehand)',
        source: 'state-bee',
    },
    {
        word: 'idiosyncrasy',
        definition: 'A distinctive or peculiar feature of a person.',
        exampleSentence: 'Each family has its own idiosyncrasies that make holiday gatherings unique.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'id-ee-oh-SING-kruh-see',
        etymology: 'Greek: idiosynkrasia (peculiar temperament), from idios (own) + synkrasis (mixture)',
        source: 'state-bee',
    },
    {
        word: 'bourgeoisie',
        definition: 'The middle class, typically with reference to its perceived materialistic values.',
        exampleSentence: 'The revolution was driven in part by the aspirations of the bourgeoisie.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'french-origin',
        pronunciation: 'boor-zhwah-ZEE',
        etymology: 'French: bourgeoisie (middle class), from bourgeois (citizen of a town)',
        source: 'state-bee',
    },
];
