/**
 * words/tier3.ts
 *
 * Tier 3 word bank: 4th-5th grade level (difficulty 5-6).
 * Covers prefixes, suffixes, compound words, and multisyllable words.
 * ~150 curated entries.
 */
import type { SpellingWord } from './types';

export const TIER_3_WORDS: SpellingWord[] = [
    // ── Prefixes (difficulty 5) ────────────────────────────────────────
    {
        word: 'unhappy',
        definition: 'Not happy; feeling sad or displeased.',
        exampleSentence: 'The dog looked unhappy when we left the house.',
        partOfSpeech: 'adjective',
        difficulty: 5,
        pattern: 'prefixes',
        pronunciation: 'un-HAP-ee',
    },
    {
        word: 'rebuild',
        definition: 'To build something again after it has been damaged or destroyed.',
        exampleSentence: 'The community worked together to rebuild the playground.',
        partOfSpeech: 'verb',
        difficulty: 5,
        pattern: 'prefixes',
        pronunciation: 'ree-BILD',
    },
    {
        word: 'disappear',
        definition: 'To go out of sight or become invisible.',
        exampleSentence: 'The magician made the rabbit disappear from the hat.',
        partOfSpeech: 'verb',
        difficulty: 5,
        pattern: 'prefixes',
        pronunciation: 'dis-uh-PEER',
    },
    {
        word: 'misplace',
        definition: 'To put something in the wrong spot and lose track of it.',
        exampleSentence: 'I always misplace my keys when I am in a hurry.',
        partOfSpeech: 'verb',
        difficulty: 5,
        pattern: 'prefixes',
        pronunciation: 'mis-PLAYSS',
    },
    {
        word: 'preview',
        definition: 'A showing or viewing of something before the main event.',
        exampleSentence: 'We watched a preview of the new movie before it opened in theaters.',
        partOfSpeech: 'noun',
        difficulty: 5,
        pattern: 'prefixes',
        pronunciation: 'PREE-vyoo',
    },
    {
        word: 'uncertain',
        definition: 'Not sure or confident about something.',
        exampleSentence: 'She felt uncertain about which answer to choose on the test.',
        partOfSpeech: 'adjective',
        difficulty: 5,
        pattern: 'prefixes',
        pronunciation: 'un-SUR-tin',
    },
    {
        word: 'disobey',
        definition: 'To refuse to follow rules or instructions.',
        exampleSentence: 'If you disobey the safety rules, someone could get hurt.',
        partOfSpeech: 'verb',
        difficulty: 5,
        pattern: 'prefixes',
        pronunciation: 'dis-oh-BAY',
    },
    {
        word: 'rewrite',
        definition: 'To write something again, usually to improve it.',
        exampleSentence: 'The teacher asked me to rewrite my essay with better details.',
        partOfSpeech: 'verb',
        difficulty: 5,
        pattern: 'prefixes',
        pronunciation: 'ree-RITE',
    },
    {
        word: 'impossible',
        definition: 'Not able to happen or be done.',
        exampleSentence: 'It seemed impossible to finish the puzzle in one hour.',
        partOfSpeech: 'adjective',
        difficulty: 5,
        pattern: 'prefixes',
        pronunciation: 'im-POSS-uh-bul',
    },
    {
        word: 'misbehave',
        definition: 'To act badly or not follow the expected behavior.',
        exampleSentence: 'The puppy would misbehave whenever guests came over.',
        partOfSpeech: 'verb',
        difficulty: 5,
        pattern: 'prefixes',
        pronunciation: 'mis-bee-HAYV',
    },
    {
        word: 'uncomfortable',
        definition: 'Not physically or mentally at ease.',
        exampleSentence: 'The wooden chair was uncomfortable to sit in for a long time.',
        partOfSpeech: 'adjective',
        difficulty: 5,
        pattern: 'prefixes',
        pronunciation: 'un-KUM-fur-tuh-bul',
    },
    {
        word: 'disagree',
        definition: 'To have a different opinion from someone else.',
        exampleSentence: 'It is okay to disagree as long as you are respectful.',
        partOfSpeech: 'verb',
        difficulty: 5,
        pattern: 'prefixes',
        pronunciation: 'dis-uh-GREE',
    },
    {
        word: 'recycle',
        definition: 'To process used materials so they can be used again.',
        exampleSentence: 'Our school collects cans and bottles to recycle every week.',
        partOfSpeech: 'verb',
        difficulty: 5,
        pattern: 'prefixes',
        pronunciation: 'ree-SY-kul',
    },
    {
        word: 'preschool',
        definition: 'A school for young children before they start kindergarten.',
        exampleSentence: 'My little sister goes to preschool three days a week.',
        partOfSpeech: 'noun',
        difficulty: 5,
        pattern: 'prefixes',
        pronunciation: 'PREE-skool',
    },
    {
        word: 'unkind',
        definition: 'Not kind; mean or thoughtless toward others.',
        exampleSentence: 'It is unkind to make fun of someone for making a mistake.',
        partOfSpeech: 'adjective',
        difficulty: 5,
        pattern: 'prefixes',
        pronunciation: 'un-KYND',
    },
    {
        word: 'replace',
        definition: 'To put something new in the place of something old or broken.',
        exampleSentence: 'We need to replace the broken light bulb in the kitchen.',
        partOfSpeech: 'verb',
        difficulty: 5,
        pattern: 'prefixes',
        pronunciation: 'ree-PLAYSS',
    },
    {
        word: 'disconnect',
        definition: 'To break the connection between two things.',
        exampleSentence: 'Remember to disconnect the charger when the battery is full.',
        partOfSpeech: 'verb',
        difficulty: 5,
        pattern: 'prefixes',
        pronunciation: 'dis-kuh-NEKT',
    },
    {
        word: 'misunderstand',
        definition: 'To fail to understand something correctly.',
        exampleSentence: 'It is easy to misunderstand a text message without hearing the tone.',
        partOfSpeech: 'verb',
        difficulty: 5,
        pattern: 'prefixes',
        pronunciation: 'mis-un-dur-STAND',
    },
    {
        word: 'impatient',
        definition: 'Not willing to wait calmly; wanting things to happen quickly.',
        exampleSentence: 'He grew impatient waiting in the long line at the store.',
        partOfSpeech: 'adjective',
        difficulty: 5,
        pattern: 'prefixes',
        pronunciation: 'im-PAY-shunt',
    },
    {
        word: 'unbelievable',
        definition: 'So amazing or surprising that it is hard to believe.',
        exampleSentence: 'The sunset over the ocean was unbelievable.',
        partOfSpeech: 'adjective',
        difficulty: 5,
        pattern: 'prefixes',
        pronunciation: 'un-buh-LEEV-uh-bul',
    },
    {
        word: 'replay',
        definition: 'To play something again, like a recording or a game.',
        exampleSentence: 'The referee asked to see the replay of the last goal.',
        partOfSpeech: 'verb',
        difficulty: 5,
        pattern: 'prefixes',
        pronunciation: 'ree-PLAY',
    },
    {
        word: 'dislike',
        definition: 'A feeling of not liking someone or something.',
        exampleSentence: 'She has a strong dislike for spicy food.',
        partOfSpeech: 'noun',
        difficulty: 5,
        pattern: 'prefixes',
        pronunciation: 'dis-LYKE',
    },
    {
        word: 'misspell',
        definition: 'To spell a word incorrectly.',
        exampleSentence: 'Be careful not to misspell words on your final report.',
        partOfSpeech: 'verb',
        difficulty: 5,
        pattern: 'prefixes',
        pronunciation: 'mis-SPEL',
    },
    {
        word: 'unable',
        definition: 'Not having the ability or means to do something.',
        exampleSentence: 'The kitten was unable to climb over the tall fence.',
        partOfSpeech: 'adjective',
        difficulty: 5,
        pattern: 'prefixes',
        pronunciation: 'un-AY-bul',
    },
    {
        word: 'overreact',
        definition: 'To respond more strongly than the situation calls for.',
        exampleSentence: 'Try not to overreact when you hear surprising news.',
        partOfSpeech: 'verb',
        difficulty: 5,
        pattern: 'prefixes',
        pronunciation: 'oh-vur-ree-AKT',
    },
    {
        word: 'incomplete',
        definition: 'Not finished or whole; missing parts.',
        exampleSentence: 'The puzzle was incomplete because several pieces were lost.',
        partOfSpeech: 'adjective',
        difficulty: 5,
        pattern: 'prefixes',
        pronunciation: 'in-kum-PLEET',
    },
    {
        word: 'transplant',
        definition: 'To move something from one place to another, often a plant or organ.',
        exampleSentence: 'We need to transplant the tomato seedlings into bigger pots.',
        partOfSpeech: 'verb',
        difficulty: 5,
        pattern: 'prefixes',
        pronunciation: 'trans-PLANT',
    },
    {
        word: 'nonprofit',
        definition: 'An organization that uses its money to help others, not to make a profit.',
        exampleSentence: 'The nonprofit raised money to build a new animal shelter.',
        partOfSpeech: 'noun',
        difficulty: 5,
        pattern: 'prefixes',
        pronunciation: 'non-PROF-it',
    },
    {
        word: 'uncover',
        definition: 'To remove a cover from something; to reveal.',
        exampleSentence: 'The archaeologists hoped to uncover ancient artifacts at the dig site.',
        partOfSpeech: 'verb',
        difficulty: 5,
        pattern: 'prefixes',
        pronunciation: 'un-KUV-ur',
    },
    {
        word: 'irregular',
        definition: 'Not following the usual pattern or rule.',
        exampleSentence: 'Some English verbs have irregular past tense forms.',
        partOfSpeech: 'adjective',
        difficulty: 5,
        pattern: 'prefixes',
        pronunciation: 'ih-REG-yoo-lur',
    },
    {
        word: 'superhero',
        definition: 'A fictional character with extraordinary powers who fights evil.',
        exampleSentence: 'Her favorite superhero can fly and lift heavy objects.',
        partOfSpeech: 'noun',
        difficulty: 5,
        pattern: 'prefixes',
        pronunciation: 'SOO-pur-heer-oh',
    },
    {
        word: 'discomfort',
        definition: 'A slight feeling of pain or unease.',
        exampleSentence: 'The tight shoes caused discomfort after walking all day.',
        partOfSpeech: 'noun',
        difficulty: 5,
        pattern: 'prefixes',
        pronunciation: 'dis-KUM-furt',
    },
    {
        word: 'misjudge',
        definition: 'To form a wrong or unfair opinion about something.',
        exampleSentence: 'Do not misjudge someone before you get to know them.',
        partOfSpeech: 'verb',
        difficulty: 5,
        pattern: 'prefixes',
        pronunciation: 'mis-JUJ',
    },
    {
        word: 'untangle',
        definition: 'To free something from knots or a confused state.',
        exampleSentence: 'It took ten minutes to untangle the knotted necklace.',
        partOfSpeech: 'verb',
        difficulty: 5,
        pattern: 'prefixes',
        pronunciation: 'un-TANG-gul',
    },
    {
        word: 'reunite',
        definition: 'To bring together again after being separated.',
        exampleSentence: 'The lost dog was finally reunited with its owner.',
        partOfSpeech: 'verb',
        difficulty: 5,
        pattern: 'prefixes',
        pronunciation: 'ree-yoo-NYTE',
    },
    {
        word: 'invisible',
        definition: 'Not able to be seen.',
        exampleSentence: 'The chameleon became nearly invisible against the green leaves.',
        partOfSpeech: 'adjective',
        difficulty: 5,
        pattern: 'prefixes',
        pronunciation: 'in-VIZ-uh-bul',
    },
    {
        word: 'overflow',
        definition: 'To flow over the edges of a container.',
        exampleSentence: 'The bathtub started to overflow because we forgot to turn off the water.',
        partOfSpeech: 'verb',
        difficulty: 5,
        pattern: 'prefixes',
        pronunciation: 'oh-vur-FLOH',
    },
    {
        word: 'disappoint',
        definition: 'To fail to meet someone\'s hopes or expectations.',
        exampleSentence: 'I did not want to disappoint my parents by skipping practice.',
        partOfSpeech: 'verb',
        difficulty: 5,
        pattern: 'prefixes',
        pronunciation: 'dis-uh-POINT',
    },
    {
        word: 'mismatch',
        definition: 'A combination of things that do not go well together.',
        exampleSentence: 'He wore a mismatch of one blue sock and one red sock.',
        partOfSpeech: 'noun',
        difficulty: 5,
        pattern: 'prefixes',
        pronunciation: 'MIS-match',
    },
    {
        word: 'unfamiliar',
        definition: 'Not known or recognized; strange.',
        exampleSentence: 'The unfamiliar street made her feel a little nervous.',
        partOfSpeech: 'adjective',
        difficulty: 5,
        pattern: 'prefixes',
        pronunciation: 'un-fuh-MIL-yur',
    },

    // ── Suffixes (difficulty 5) ────────────────────────────────────────
    {
        word: 'kindness',
        definition: 'The quality of being friendly, generous, and considerate.',
        exampleSentence: 'Her kindness toward the new student made everyone smile.',
        partOfSpeech: 'noun',
        difficulty: 5,
        pattern: 'suffixes',
        pronunciation: 'KYND-ness',
    },
    {
        word: 'careful',
        definition: 'Done with attention and thought to avoid mistakes or danger.',
        exampleSentence: 'Be careful when you cross the street.',
        partOfSpeech: 'adjective',
        difficulty: 5,
        pattern: 'suffixes',
        pronunciation: 'KAIR-ful',
    },
    {
        word: 'happily',
        definition: 'In a happy or joyful way.',
        exampleSentence: 'The children played happily in the park all afternoon.',
        partOfSpeech: 'adverb',
        difficulty: 5,
        pattern: 'suffixes',
        pronunciation: 'HAP-uh-lee',
    },
    {
        word: 'movement',
        definition: 'The act of changing position or location.',
        exampleSentence: 'The dancer\'s graceful movement across the stage amazed the audience.',
        partOfSpeech: 'noun',
        difficulty: 5,
        pattern: 'suffixes',
        pronunciation: 'MOOV-ment',
    },
    {
        word: 'darkness',
        definition: 'The absence of light.',
        exampleSentence: 'The darkness of the cave made it hard to see without a flashlight.',
        partOfSpeech: 'noun',
        difficulty: 5,
        pattern: 'suffixes',
        pronunciation: 'DARK-ness',
    },
    {
        word: 'peaceful',
        definition: 'Free from disturbance; calm and quiet.',
        exampleSentence: 'The garden was a peaceful place to read a book.',
        partOfSpeech: 'adjective',
        difficulty: 5,
        pattern: 'suffixes',
        pronunciation: 'PEESS-ful',
    },
    {
        word: 'quickly',
        definition: 'At a fast speed; in a short amount of time.',
        exampleSentence: 'She quickly finished her homework so she could go outside.',
        partOfSpeech: 'adverb',
        difficulty: 5,
        pattern: 'suffixes',
        pronunciation: 'KWIK-lee',
    },
    {
        word: 'statement',
        definition: 'A clear expression of a fact or opinion in words.',
        exampleSentence: 'The witness gave a statement to the police about what happened.',
        partOfSpeech: 'noun',
        difficulty: 5,
        pattern: 'suffixes',
        pronunciation: 'STAYT-ment',
    },
    {
        word: 'weakness',
        definition: 'A lack of strength or a fault in someone or something.',
        exampleSentence: 'His biggest weakness in soccer was his left foot.',
        partOfSpeech: 'noun',
        difficulty: 5,
        pattern: 'suffixes',
        pronunciation: 'WEEK-ness',
    },
    {
        word: 'wonderful',
        definition: 'Extremely good; causing delight or admiration.',
        exampleSentence: 'We had a wonderful time at the amusement park.',
        partOfSpeech: 'adjective',
        difficulty: 5,
        pattern: 'suffixes',
        pronunciation: 'WUN-dur-ful',
    },
    {
        word: 'quietly',
        definition: 'In a way that makes little or no noise.',
        exampleSentence: 'He quietly tiptoed past the sleeping baby.',
        partOfSpeech: 'adverb',
        difficulty: 5,
        pattern: 'suffixes',
        pronunciation: 'KWY-ut-lee',
    },
    {
        word: 'enjoyment',
        definition: 'The state of taking pleasure in something.',
        exampleSentence: 'Reading books gives her great enjoyment.',
        partOfSpeech: 'noun',
        difficulty: 5,
        pattern: 'suffixes',
        pronunciation: 'en-JOY-ment',
    },
    {
        word: 'sadness',
        definition: 'The feeling of being unhappy or sorrowful.',
        exampleSentence: 'There was sadness in his eyes when his best friend moved away.',
        partOfSpeech: 'noun',
        difficulty: 5,
        pattern: 'suffixes',
        pronunciation: 'SAD-ness',
    },
    {
        word: 'powerful',
        definition: 'Having great strength, force, or influence.',
        exampleSentence: 'The powerful storm knocked down several trees.',
        partOfSpeech: 'adjective',
        difficulty: 5,
        pattern: 'suffixes',
        pronunciation: 'POW-ur-ful',
    },
    {
        word: 'bravely',
        definition: 'In a way that shows courage.',
        exampleSentence: 'The firefighter bravely entered the burning building.',
        partOfSpeech: 'adverb',
        difficulty: 5,
        pattern: 'suffixes',
        pronunciation: 'BRAYV-lee',
    },
    {
        word: 'treatment',
        definition: 'The way someone or something is dealt with, or medical care.',
        exampleSentence: 'The doctor recommended a new treatment for her allergies.',
        partOfSpeech: 'noun',
        difficulty: 5,
        pattern: 'suffixes',
        pronunciation: 'TREET-ment',
    },
    {
        word: 'forgiveness',
        definition: 'The act of pardoning someone for a mistake or wrongdoing.',
        exampleSentence: 'Forgiveness is an important part of keeping friendships strong.',
        partOfSpeech: 'noun',
        difficulty: 5,
        pattern: 'suffixes',
        pronunciation: 'for-GIV-ness',
    },
    {
        word: 'thankful',
        definition: 'Feeling or showing gratitude.',
        exampleSentence: 'We are thankful for the food on our table.',
        partOfSpeech: 'adjective',
        difficulty: 5,
        pattern: 'suffixes',
        pronunciation: 'THANK-ful',
    },
    {
        word: 'honestly',
        definition: 'In a truthful and sincere way.',
        exampleSentence: 'She honestly admitted that she had made a mistake.',
        partOfSpeech: 'adverb',
        difficulty: 5,
        pattern: 'suffixes',
        pronunciation: 'ON-ist-lee',
    },
    {
        word: 'excitement',
        definition: 'A feeling of great enthusiasm and eagerness.',
        exampleSentence: 'The excitement in the crowd grew as the game went into overtime.',
        partOfSpeech: 'noun',
        difficulty: 5,
        pattern: 'suffixes',
        pronunciation: 'ek-SYTE-ment',
    },
    {
        word: 'foolish',
        definition: 'Lacking good sense or judgment; silly.',
        exampleSentence: 'It was foolish to go outside without a coat in the snowstorm.',
        partOfSpeech: 'adjective',
        difficulty: 5,
        pattern: 'suffixes',
        pronunciation: 'FOO-lish',
    },
    {
        word: 'cheerful',
        definition: 'Feeling or showing happiness and optimism.',
        exampleSentence: 'The cheerful greeting from the teacher made us feel welcome.',
        partOfSpeech: 'adjective',
        difficulty: 5,
        pattern: 'suffixes',
        pronunciation: 'CHEER-ful',
    },
    {
        word: 'proudly',
        definition: 'In a way that shows deep pleasure in achievements.',
        exampleSentence: 'She proudly displayed her science fair ribbon on the refrigerator.',
        partOfSpeech: 'adverb',
        difficulty: 5,
        pattern: 'suffixes',
        pronunciation: 'PROWD-lee',
    },
    {
        word: 'arrangement',
        definition: 'A plan or preparation for something, or a display of items.',
        exampleSentence: 'The flower arrangement on the table looked beautiful.',
        partOfSpeech: 'noun',
        difficulty: 5,
        pattern: 'suffixes',
        pronunciation: 'uh-RAYNJ-ment',
    },
    {
        word: 'loneliness',
        definition: 'The feeling of being sad because you are alone.',
        exampleSentence: 'Moving to a new city filled her with loneliness at first.',
        partOfSpeech: 'noun',
        difficulty: 5,
        pattern: 'suffixes',
        pronunciation: 'LONE-lee-ness',
    },
    {
        word: 'colorful',
        definition: 'Having many bright and varied colors.',
        exampleSentence: 'The colorful parrot perched on the branch in the rainforest.',
        partOfSpeech: 'adjective',
        difficulty: 5,
        pattern: 'suffixes',
        pronunciation: 'KUL-ur-ful',
    },
    {
        word: 'suddenly',
        definition: 'Happening quickly and unexpectedly.',
        exampleSentence: 'Suddenly, a deer leaped across the road in front of us.',
        partOfSpeech: 'adverb',
        difficulty: 5,
        pattern: 'suffixes',
        pronunciation: 'SUD-un-lee',
    },
    {
        word: 'agreement',
        definition: 'A shared understanding or arrangement between people.',
        exampleSentence: 'The two friends reached an agreement to share the toy.',
        partOfSpeech: 'noun',
        difficulty: 5,
        pattern: 'suffixes',
        pronunciation: 'uh-GREE-ment',
    },
    {
        word: 'goodness',
        definition: 'The quality of being morally right or virtuous.',
        exampleSentence: 'Her goodness inspired others to volunteer at the shelter.',
        partOfSpeech: 'noun',
        difficulty: 5,
        pattern: 'suffixes',
        pronunciation: 'GOOD-ness',
    },
    {
        word: 'playful',
        definition: 'Full of fun and energy; lighthearted.',
        exampleSentence: 'The playful kitten chased the ball of yarn across the room.',
        partOfSpeech: 'adjective',
        difficulty: 5,
        pattern: 'suffixes',
        pronunciation: 'PLAY-ful',
    },
    {
        word: 'eagerly',
        definition: 'In a way that shows keen interest or enthusiasm.',
        exampleSentence: 'The students eagerly raised their hands to answer the question.',
        partOfSpeech: 'adverb',
        difficulty: 5,
        pattern: 'suffixes',
        pronunciation: 'EE-gur-lee',
    },
    {
        word: 'government',
        definition: 'The group of people who make laws and run a country or state.',
        exampleSentence: 'The government passed a new law to protect the environment.',
        partOfSpeech: 'noun',
        difficulty: 5,
        pattern: 'suffixes',
        pronunciation: 'GUV-urn-ment',
    },
    {
        word: 'awareness',
        definition: 'Knowledge or understanding that something exists.',
        exampleSentence: 'The assembly raised awareness about the importance of recycling.',
        partOfSpeech: 'noun',
        difficulty: 5,
        pattern: 'suffixes',
        pronunciation: 'uh-WAIR-ness',
    },
    {
        word: 'respectful',
        definition: 'Showing admiration and regard for others.',
        exampleSentence: 'It is important to be respectful to your elders.',
        partOfSpeech: 'adjective',
        difficulty: 5,
        pattern: 'suffixes',
        pronunciation: 'ree-SPEKT-ful',
    },
    {
        word: 'gracefully',
        definition: 'In a smooth, elegant, and attractive way.',
        exampleSentence: 'The ballerina moved gracefully across the stage.',
        partOfSpeech: 'adverb',
        difficulty: 5,
        pattern: 'suffixes',
        pronunciation: 'GRAYSS-ful-ee',
    },
    {
        word: 'punishment',
        definition: 'A penalty given for breaking a rule or law.',
        exampleSentence: 'Losing screen time was the punishment for not finishing chores.',
        partOfSpeech: 'noun',
        difficulty: 5,
        pattern: 'suffixes',
        pronunciation: 'PUN-ish-ment',
    },
    {
        word: 'cleverness',
        definition: 'The quality of being quick to understand and learn.',
        exampleSentence: 'The fox is famous in stories for its cleverness.',
        partOfSpeech: 'noun',
        difficulty: 5,
        pattern: 'suffixes',
        pronunciation: 'KLEV-ur-ness',
    },
    {
        word: 'hopeful',
        definition: 'Feeling optimistic that something good will happen.',
        exampleSentence: 'She was hopeful that the weather would clear up for the picnic.',
        partOfSpeech: 'adjective',
        difficulty: 5,
        pattern: 'suffixes',
        pronunciation: 'HOHP-ful',
    },
    {
        word: 'nervously',
        definition: 'In a way that shows anxiety or worry.',
        exampleSentence: 'He nervously waited for his turn to present in front of the class.',
        partOfSpeech: 'adverb',
        difficulty: 5,
        pattern: 'suffixes',
        pronunciation: 'NUR-vus-lee',
    },
    {
        word: 'attachment',
        definition: 'A strong emotional bond, or something added to another thing.',
        exampleSentence: 'The email had an attachment with photos from the field trip.',
        partOfSpeech: 'noun',
        difficulty: 5,
        pattern: 'suffixes',
        pronunciation: 'uh-TACH-ment',
    },

    // ── Compound words (difficulty 5-6) ────────────────────────────────
    {
        word: 'butterfly',
        definition: 'A flying insect with large, colorful wings.',
        exampleSentence: 'A beautiful butterfly landed on the purple flower.',
        partOfSpeech: 'noun',
        difficulty: 5,
        pattern: 'compound',
        pronunciation: 'BUT-ur-fly',
    },
    {
        word: 'sunshine',
        definition: 'Direct light from the sun.',
        exampleSentence: 'The warm sunshine felt wonderful on our faces.',
        partOfSpeech: 'noun',
        difficulty: 5,
        pattern: 'compound',
        pronunciation: 'SUN-shyne',
    },
    {
        word: 'notebook',
        definition: 'A small book with blank pages for writing notes.',
        exampleSentence: 'She wrote her ideas in a notebook during class.',
        partOfSpeech: 'noun',
        difficulty: 5,
        pattern: 'compound',
        pronunciation: 'NOHT-book',
    },
    {
        word: 'basketball',
        definition: 'A sport played by two teams trying to throw a ball through a hoop.',
        exampleSentence: 'He practiced basketball every day after school.',
        partOfSpeech: 'noun',
        difficulty: 5,
        pattern: 'compound',
        pronunciation: 'BAS-kit-bawl',
    },
    {
        word: 'homework',
        definition: 'Schoolwork assigned to be done at home.',
        exampleSentence: 'She always finishes her homework before watching television.',
        partOfSpeech: 'noun',
        difficulty: 5,
        pattern: 'compound',
        pronunciation: 'HOHM-wurk',
    },
    {
        word: 'earthquake',
        definition: 'A sudden shaking of the ground caused by movement beneath the surface.',
        exampleSentence: 'The earthquake rattled the dishes on the shelves.',
        partOfSpeech: 'noun',
        difficulty: 5,
        pattern: 'compound',
        pronunciation: 'URTH-kwayk',
    },
    {
        word: 'thunderstorm',
        definition: 'A storm with thunder, lightning, and heavy rain.',
        exampleSentence: 'The thunderstorm knocked out the power in our neighborhood.',
        partOfSpeech: 'noun',
        difficulty: 5,
        pattern: 'compound',
        pronunciation: 'THUN-dur-storm',
    },
    {
        word: 'playground',
        definition: 'An outdoor area where children can play.',
        exampleSentence: 'The new playground has swings, slides, and monkey bars.',
        partOfSpeech: 'noun',
        difficulty: 5,
        pattern: 'compound',
        pronunciation: 'PLAY-grownd',
    },
    {
        word: 'waterfall',
        definition: 'A stream of water that falls from a high place over rocks.',
        exampleSentence: 'We hiked through the forest to see the beautiful waterfall.',
        partOfSpeech: 'noun',
        difficulty: 5,
        pattern: 'compound',
        pronunciation: 'WAW-tur-fawl',
    },
    {
        word: 'flashlight',
        definition: 'A small portable electric lamp powered by batteries.',
        exampleSentence: 'He grabbed a flashlight to explore the dark attic.',
        partOfSpeech: 'noun',
        difficulty: 5,
        pattern: 'compound',
        pronunciation: 'FLASH-lyte',
    },
    {
        word: 'fingerprint',
        definition: 'The unique pattern of lines on the tip of a finger.',
        exampleSentence: 'Every person has a different fingerprint.',
        partOfSpeech: 'noun',
        difficulty: 5,
        pattern: 'compound',
        pronunciation: 'FING-gur-print',
    },
    {
        word: 'sometimes',
        definition: 'On some occasions but not always.',
        exampleSentence: 'Sometimes we go to the park after dinner.',
        partOfSpeech: 'adverb',
        difficulty: 5,
        pattern: 'compound',
        pronunciation: 'SUM-tymz',
    },
    {
        word: 'toothbrush',
        definition: 'A small brush used for cleaning teeth.',
        exampleSentence: 'Remember to pack your toothbrush for the sleepover.',
        partOfSpeech: 'noun',
        difficulty: 5,
        pattern: 'compound',
        pronunciation: 'TOOTH-brush',
    },
    {
        word: 'scoreboard',
        definition: 'A board that shows the score during a game.',
        exampleSentence: 'The scoreboard showed that our team was winning by two points.',
        partOfSpeech: 'noun',
        difficulty: 5,
        pattern: 'compound',
        pronunciation: 'SKOR-bord',
    },
    {
        word: 'dragonfly',
        definition: 'A flying insect with a long body and two pairs of transparent wings.',
        exampleSentence: 'A dragonfly hovered over the pond in the backyard.',
        partOfSpeech: 'noun',
        difficulty: 5,
        pattern: 'compound',
        pronunciation: 'DRAG-un-fly',
    },
    {
        word: 'skateboard',
        definition: 'A short board with wheels used for riding and doing tricks.',
        exampleSentence: 'She learned how to ride a skateboard over the summer.',
        partOfSpeech: 'noun',
        difficulty: 5,
        pattern: 'compound',
        pronunciation: 'SKAYT-bord',
    },
    {
        word: 'campfire',
        definition: 'An outdoor fire used for warmth or cooking at a campsite.',
        exampleSentence: 'We roasted marshmallows over the campfire.',
        partOfSpeech: 'noun',
        difficulty: 5,
        pattern: 'compound',
        pronunciation: 'KAMP-fyr',
    },
    {
        word: 'snowflake',
        definition: 'A single crystal of snow with a unique pattern.',
        exampleSentence: 'Every snowflake has a different shape.',
        partOfSpeech: 'noun',
        difficulty: 5,
        pattern: 'compound',
        pronunciation: 'SNOH-flayk',
    },
    {
        word: 'bookshelf',
        definition: 'A shelf or piece of furniture for storing books.',
        exampleSentence: 'The bookshelf in the library was filled with adventure stories.',
        partOfSpeech: 'noun',
        difficulty: 5,
        pattern: 'compound',
        pronunciation: 'BOOK-shelf',
    },
    {
        word: 'meanwhile',
        definition: 'At the same time that something else is happening.',
        exampleSentence: 'She was cooking dinner; meanwhile, the kids set the table.',
        partOfSpeech: 'adverb',
        difficulty: 6,
        pattern: 'compound',
        pronunciation: 'MEEN-wyle',
    },
    {
        word: 'nevertheless',
        definition: 'In spite of that; however.',
        exampleSentence: 'It was raining hard; nevertheless, they continued the hike.',
        partOfSpeech: 'adverb',
        difficulty: 6,
        pattern: 'compound',
        pronunciation: 'nev-ur-thuh-LESS',
    },
    {
        word: 'furthermore',
        definition: 'In addition to what has already been said.',
        exampleSentence: 'The project was late; furthermore, it had several errors.',
        partOfSpeech: 'adverb',
        difficulty: 6,
        pattern: 'compound',
        pronunciation: 'FUR-thur-mor',
    },
    {
        word: 'widespread',
        definition: 'Found or happening over a large area or among many people.',
        exampleSentence: 'The widespread use of computers changed how we learn.',
        partOfSpeech: 'adjective',
        difficulty: 6,
        pattern: 'compound',
        pronunciation: 'WYD-spred',
    },
    {
        word: 'outstanding',
        definition: 'Exceptionally good; remarkable.',
        exampleSentence: 'She received an award for her outstanding performance in the play.',
        partOfSpeech: 'adjective',
        difficulty: 6,
        pattern: 'compound',
        pronunciation: 'owt-STAN-ding',
    },
    {
        word: 'headquarters',
        definition: 'The main office or center of an organization.',
        exampleSentence: 'The company moved its headquarters to a bigger building downtown.',
        partOfSpeech: 'noun',
        difficulty: 6,
        pattern: 'compound',
        pronunciation: 'HED-kwor-turz',
    },
    {
        word: 'handkerchief',
        definition: 'A small square of cloth used for wiping the nose or face.',
        exampleSentence: 'He pulled a handkerchief from his pocket to wipe his forehead.',
        partOfSpeech: 'noun',
        difficulty: 6,
        pattern: 'compound',
        pronunciation: 'HANG-kur-chif',
    },
    {
        word: 'neighborhood',
        definition: 'An area where people live near each other.',
        exampleSentence: 'Everyone in the neighborhood helped clean up the park.',
        partOfSpeech: 'noun',
        difficulty: 6,
        pattern: 'compound',
        pronunciation: 'NAY-bur-hood',
    },
    {
        word: 'nightingale',
        definition: 'A small bird known for its beautiful singing, especially at night.',
        exampleSentence: 'The nightingale sang sweetly in the moonlit garden.',
        partOfSpeech: 'noun',
        difficulty: 6,
        pattern: 'compound',
        pronunciation: 'NYT-in-gayl',
    },
    {
        word: 'marketplace',
        definition: 'A place where goods are bought and sold.',
        exampleSentence: 'Farmers brought fresh produce to the marketplace every Saturday.',
        partOfSpeech: 'noun',
        difficulty: 6,
        pattern: 'compound',
        pronunciation: 'MAR-kit-playss',
    },
    {
        word: 'straightforward',
        definition: 'Easy to understand; not complicated.',
        exampleSentence: 'The instructions were straightforward and easy to follow.',
        partOfSpeech: 'adjective',
        difficulty: 6,
        pattern: 'compound',
        pronunciation: 'strayt-FOR-wurd',
    },
    {
        word: 'wholesome',
        definition: 'Good for health and well-being; morally positive.',
        exampleSentence: 'Grandma always cooked wholesome meals with fresh ingredients.',
        partOfSpeech: 'adjective',
        difficulty: 6,
        pattern: 'compound',
        pronunciation: 'HOHL-sum',
    },
    {
        word: 'worthwhile',
        definition: 'Worth the time, money, or effort spent.',
        exampleSentence: 'Volunteering at the shelter was a worthwhile experience.',
        partOfSpeech: 'adjective',
        difficulty: 6,
        pattern: 'compound',
        pronunciation: 'wurth-WYL',
    },
    {
        word: 'sportsmanship',
        definition: 'Fair and respectful behavior when playing a game or sport.',
        exampleSentence: 'Good sportsmanship means congratulating the other team when they win.',
        partOfSpeech: 'noun',
        difficulty: 6,
        pattern: 'compound',
        pronunciation: 'SPORTS-mun-ship',
    },
    {
        word: 'masterpiece',
        definition: 'An outstanding work of art or skill.',
        exampleSentence: 'The painting in the museum was considered a masterpiece.',
        partOfSpeech: 'noun',
        difficulty: 6,
        pattern: 'compound',
        pronunciation: 'MAS-tur-peess',
    },

    // ── Multisyllable (difficulty 6) ───────────────────────────────────
    {
        word: 'beautiful',
        definition: 'Very pleasing to look at or listen to.',
        exampleSentence: 'The beautiful sunset painted the sky in shades of pink and orange.',
        partOfSpeech: 'adjective',
        difficulty: 6,
        pattern: 'multisyllable',
        pronunciation: 'BYOO-tuh-ful',
    },
    {
        word: 'dinosaur',
        definition: 'A large reptile that lived millions of years ago and is now extinct.',
        exampleSentence: 'The museum had a complete dinosaur skeleton on display.',
        partOfSpeech: 'noun',
        difficulty: 6,
        pattern: 'multisyllable',
        pronunciation: 'DY-nuh-sor',
    },
    {
        word: 'chocolate',
        definition: 'A sweet food made from roasted cacao beans.',
        exampleSentence: 'She picked chocolate ice cream as her favorite dessert.',
        partOfSpeech: 'noun',
        difficulty: 6,
        pattern: 'multisyllable',
        pronunciation: 'CHOK-lit',
    },
    {
        word: 'vegetable',
        definition: 'A plant or part of a plant used as food.',
        exampleSentence: 'Eating a vegetable with every meal is good for your health.',
        partOfSpeech: 'noun',
        difficulty: 6,
        pattern: 'multisyllable',
        pronunciation: 'VEJ-tuh-bul',
    },
    {
        word: 'adventure',
        definition: 'An exciting or unusual experience.',
        exampleSentence: 'Exploring the cave was the greatest adventure of the summer.',
        partOfSpeech: 'noun',
        difficulty: 6,
        pattern: 'multisyllable',
        pronunciation: 'ad-VEN-chur',
    },
    {
        word: 'temperature',
        definition: 'A measure of how hot or cold something is.',
        exampleSentence: 'The temperature dropped below freezing overnight.',
        partOfSpeech: 'noun',
        difficulty: 6,
        pattern: 'multisyllable',
        pronunciation: 'TEM-pur-uh-chur',
    },
    {
        word: 'celebrate',
        definition: 'To do something special to honor an important event.',
        exampleSentence: 'We will celebrate her birthday with a big party.',
        partOfSpeech: 'verb',
        difficulty: 6,
        pattern: 'multisyllable',
        pronunciation: 'SEL-uh-brayt',
    },
    {
        word: 'gymnasium',
        definition: 'A large room or building equipped for indoor sports and exercise.',
        exampleSentence: 'The basketball game was held in the school gymnasium.',
        partOfSpeech: 'noun',
        difficulty: 6,
        pattern: 'multisyllable',
        pronunciation: 'jim-NAY-zee-um',
    },
    {
        word: 'dictionary',
        definition: 'A book that lists words and their meanings in alphabetical order.',
        exampleSentence: 'He looked up the unfamiliar word in the dictionary.',
        partOfSpeech: 'noun',
        difficulty: 6,
        pattern: 'multisyllable',
        pronunciation: 'DIK-shuh-nair-ee',
    },
    {
        word: 'electricity',
        definition: 'A form of energy used to power lights, machines, and devices.',
        exampleSentence: 'Electricity flows through wires to power the lights in our house.',
        partOfSpeech: 'noun',
        difficulty: 6,
        pattern: 'multisyllable',
        pronunciation: 'ee-lek-TRISS-uh-tee',
    },
    {
        word: 'encyclopedia',
        definition: 'A large book or set of books with information on many subjects.',
        exampleSentence: 'She used the encyclopedia to research her science project.',
        partOfSpeech: 'noun',
        difficulty: 6,
        pattern: 'multisyllable',
        pronunciation: 'en-sy-kluh-PEE-dee-uh',
    },
    {
        word: 'particular',
        definition: 'Specific or individual rather than general.',
        exampleSentence: 'Is there a particular book you would like to read next?',
        partOfSpeech: 'adjective',
        difficulty: 6,
        pattern: 'multisyllable',
        pronunciation: 'par-TIK-yoo-lur',
    },
    {
        word: 'ridiculous',
        definition: 'Extremely silly or unreasonable.',
        exampleSentence: 'The clown wore a ridiculous hat that made everyone laugh.',
        partOfSpeech: 'adjective',
        difficulty: 6,
        pattern: 'multisyllable',
        pronunciation: 'rih-DIK-yoo-lus',
    },
    {
        word: 'appreciate',
        definition: 'To recognize the value or worth of something.',
        exampleSentence: 'I appreciate your help with the project.',
        partOfSpeech: 'verb',
        difficulty: 6,
        pattern: 'multisyllable',
        pronunciation: 'uh-PREE-shee-ayt',
    },
    {
        word: 'refrigerator',
        definition: 'An appliance that keeps food cold to preserve it.',
        exampleSentence: 'Please put the milk back in the refrigerator.',
        partOfSpeech: 'noun',
        difficulty: 6,
        pattern: 'multisyllable',
        pronunciation: 'rih-FRIJ-uh-ray-tur',
    },
    {
        word: 'literature',
        definition: 'Written works such as books, poems, and plays.',
        exampleSentence: 'We studied American literature in English class.',
        partOfSpeech: 'noun',
        difficulty: 6,
        pattern: 'multisyllable',
        pronunciation: 'LIT-ur-uh-chur',
    },
    {
        word: 'communicate',
        definition: 'To share information, thoughts, or feelings with others.',
        exampleSentence: 'Animals communicate in many different ways.',
        partOfSpeech: 'verb',
        difficulty: 6,
        pattern: 'multisyllable',
        pronunciation: 'kuh-MYOO-nih-kayt',
    },
    {
        word: 'extraordinary',
        definition: 'Very unusual or remarkable; beyond what is ordinary.',
        exampleSentence: 'The magician performed an extraordinary trick that amazed the crowd.',
        partOfSpeech: 'adjective',
        difficulty: 6,
        pattern: 'multisyllable',
        pronunciation: 'ek-STROR-dih-nair-ee',
    },
    {
        word: 'hippopotamus',
        definition: 'A large African mammal that lives in and near water.',
        exampleSentence: 'The hippopotamus spent most of the day cooling off in the river.',
        partOfSpeech: 'noun',
        difficulty: 6,
        pattern: 'multisyllable',
        pronunciation: 'hip-uh-POT-uh-mus',
    },
    {
        word: 'laboratory',
        definition: 'A room or building equipped for scientific experiments.',
        exampleSentence: 'The students conducted their experiments in the school laboratory.',
        partOfSpeech: 'noun',
        difficulty: 6,
        pattern: 'multisyllable',
        pronunciation: 'LAB-ruh-tor-ee',
    },
    {
        word: 'imagination',
        definition: 'The ability to form pictures or ideas in the mind.',
        exampleSentence: 'Her imagination helped her write the most creative stories in class.',
        partOfSpeech: 'noun',
        difficulty: 6,
        pattern: 'multisyllable',
        pronunciation: 'ih-maj-ih-NAY-shun',
    },
    {
        word: 'independent',
        definition: 'Able to do things by oneself without help from others.',
        exampleSentence: 'Learning to cook made her feel more independent.',
        partOfSpeech: 'adjective',
        difficulty: 6,
        pattern: 'multisyllable',
        pronunciation: 'in-dee-PEN-dunt',
    },
    {
        word: 'caterpillar',
        definition: 'The larval stage of a butterfly or moth, resembling a fuzzy worm.',
        exampleSentence: 'The caterpillar munched on leaves before becoming a butterfly.',
        partOfSpeech: 'noun',
        difficulty: 6,
        pattern: 'multisyllable',
        pronunciation: 'KAT-ur-pil-ur',
    },
    {
        word: 'experiment',
        definition: 'A scientific test done to learn something new.',
        exampleSentence: 'The experiment showed that plants grow faster in sunlight.',
        partOfSpeech: 'noun',
        difficulty: 6,
        pattern: 'multisyllable',
        pronunciation: 'ek-SPAIR-ih-ment',
    },
    {
        word: 'civilization',
        definition: 'An advanced society with its own culture, laws, and government.',
        exampleSentence: 'Ancient Egyptian civilization built the great pyramids.',
        partOfSpeech: 'noun',
        difficulty: 6,
        pattern: 'multisyllable',
        pronunciation: 'siv-ih-lih-ZAY-shun',
    },
    {
        word: 'opportunity',
        definition: 'A chance or favorable situation to do something.',
        exampleSentence: 'Winning the scholarship gave her the opportunity to attend college.',
        partOfSpeech: 'noun',
        difficulty: 6,
        pattern: 'multisyllable',
        pronunciation: 'op-ur-TOO-nih-tee',
    },
    {
        word: 'responsibility',
        definition: 'A duty or task you are expected to do.',
        exampleSentence: 'Taking care of the class pet was a big responsibility.',
        partOfSpeech: 'noun',
        difficulty: 6,
        pattern: 'multisyllable',
        pronunciation: 'ree-spon-suh-BIL-uh-tee',
    },
    {
        word: 'professional',
        definition: 'Relating to a job that requires special training or skill.',
        exampleSentence: 'She dreamed of becoming a professional soccer player.',
        partOfSpeech: 'adjective',
        difficulty: 6,
        pattern: 'multisyllable',
        pronunciation: 'proh-FESH-uh-nul',
    },
    {
        word: 'pronunciation',
        definition: 'The way a word is spoken aloud.',
        exampleSentence: 'The teacher helped us with the pronunciation of the new vocabulary words.',
        partOfSpeech: 'noun',
        difficulty: 6,
        pattern: 'multisyllable',
        pronunciation: 'proh-nun-see-AY-shun',
    },
    {
        word: 'information',
        definition: 'Facts or knowledge learned about something.',
        exampleSentence: 'The library is a great place to find information for your report.',
        partOfSpeech: 'noun',
        difficulty: 6,
        pattern: 'multisyllable',
        pronunciation: 'in-fur-MAY-shun',
    },
    {
        word: 'accidentally',
        definition: 'By chance or without intending to.',
        exampleSentence: 'He accidentally spilled juice on his homework.',
        partOfSpeech: 'adverb',
        difficulty: 6,
        pattern: 'multisyllable',
        pronunciation: 'ak-sih-DEN-tuh-lee',
    },
    {
        word: 'veterinarian',
        definition: 'A doctor who treats sick or injured animals.',
        exampleSentence: 'The veterinarian gave the puppy its vaccinations.',
        partOfSpeech: 'noun',
        difficulty: 6,
        pattern: 'multisyllable',
        pronunciation: 'vet-ur-ih-NAIR-ee-un',
    },
    {
        word: 'elementary',
        definition: 'Relating to the basic or beginning level of something.',
        exampleSentence: 'She teaches math at the elementary school down the street.',
        partOfSpeech: 'adjective',
        difficulty: 6,
        pattern: 'multisyllable',
        pronunciation: 'el-uh-MEN-tuh-ree',
    },
    {
        word: 'enthusiastic',
        definition: 'Showing intense and eager enjoyment or interest.',
        exampleSentence: 'The crowd was enthusiastic about the band\'s performance.',
        partOfSpeech: 'adjective',
        difficulty: 6,
        pattern: 'multisyllable',
        pronunciation: 'en-thoo-zee-AS-tik',
    },
    {
        word: 'approximately',
        definition: 'Close to an exact amount but not completely accurate.',
        exampleSentence: 'There were approximately fifty students in the auditorium.',
        partOfSpeech: 'adverb',
        difficulty: 6,
        pattern: 'multisyllable',
        pronunciation: 'uh-PROK-sih-mut-lee',
    },
];
