/**
 * words/tier5-scripps.ts
 *
 * Scripps National Spelling Bee competition words (difficulty 10).
 * Actual winning words and notable words from past Scripps competitions.
 * All entries include full etymology and source provenance.
 * ~100 curated entries.
 */
import type { SpellingWord } from './types';

export const TIER_5_SCRIPPS_WORDS: SpellingWord[] = [
    {
        word: 'knack',
        definition: 'An acquired or natural skill at performing a task.',
        exampleSentence: 'She had a knack for solving complex math problems quickly.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'irregular',
        pronunciation: 'NAK',
        etymology: 'Middle English: knakke (trick, device), possibly of imitative origin',
        source: 'scripps',
    },
    {
        word: 'chlorophyll',
        definition: 'The green pigment in plants that absorbs light for photosynthesis.',
        exampleSentence: 'Chlorophyll gives leaves their characteristic green color.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'KLOR-oh-fil',
        etymology: 'Greek: chloros (green) + phyllon (leaf)',
        source: 'scripps',
    },
    {
        word: 'incisor',
        definition: 'A narrow-edged tooth at the front of the mouth.',
        exampleSentence: 'The dentist examined the child\'s upper incisors for signs of decay.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'latin-roots',
        pronunciation: 'in-SY-zur',
        etymology: 'Latin: incisor (a cutter), from incidere (to cut into), from in (into) + caedere (to cut)',
        source: 'scripps',
    },
    {
        word: 'vouchsafe',
        definition: 'To give or grant something to someone in a gracious or condescending manner.',
        exampleSentence: 'The queen vouchsafed a rare audience to the foreign ambassador.',
        partOfSpeech: 'verb',
        difficulty: 10,
        pattern: 'french-origin',
        pronunciation: 'vowch-SAYF',
        etymology: 'Middle English: vouchen sauf (to warrant as safe), from Anglo-French: voucher (to vouch) + sauf (safe)',
        source: 'scripps',
    },
    {
        word: 'croissant',
        definition: 'A crescent-shaped roll made of rich pastry dough.',
        exampleSentence: 'She ordered a warm croissant with butter and jam for breakfast.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'french-origin',
        pronunciation: 'kwah-SAHN',
        etymology: 'French: croissant (crescent), from croitre (to grow, increase), from Latin: crescere',
        source: 'scripps',
    },
    {
        word: 'luge',
        definition: 'A light toboggan ridden in a supine position.',
        exampleSentence: 'The luge event at the Winter Olympics featured athletes reaching incredible speeds.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'french-origin',
        pronunciation: 'LOOZH',
        etymology: 'French: luge (small sled), from Medieval Latin: sludia (sled)',
        source: 'scripps',
    },
    {
        word: 'strophanthus',
        definition: 'A genus of tropical plants used in medicine and as arrow poison.',
        exampleSentence: 'The botanist identified a rare species of strophanthus during the jungle expedition.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'stroh-FAN-thus',
        etymology: 'Greek: strophos (twisted cord) + anthos (flower)',
        source: 'scripps',
    },
    {
        word: 'cambist',
        definition: 'A person who deals in foreign exchange; a manual of exchange rates.',
        exampleSentence: 'The cambist provided travelers with competitive rates for currency conversion.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'latin-roots',
        pronunciation: 'KAM-bist',
        etymology: 'Latin: cambire (to exchange), via Italian: cambista (money changer)',
        source: 'scripps',
    },
    {
        word: 'elucubrate',
        definition: 'To produce by working late at night; to compose laboriously.',
        exampleSentence: 'The scholar would elucubrate through the night to finish the manuscript.',
        partOfSpeech: 'verb',
        difficulty: 10,
        pattern: 'latin-roots',
        pronunciation: 'ih-LOO-kyoo-brayt',
        etymology: 'Latin: elucubrare (to compose by lamplight), from e (out) + lucubrare (to work by candlelight)',
        source: 'scripps',
    },
    {
        word: 'maculature',
        definition: 'Waste paper or misprinted sheets; spotted or blotched marking.',
        exampleSentence: 'The printer set aside the maculature for recycling.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'latin-roots',
        pronunciation: 'MAK-yoo-luh-chur',
        etymology: 'Latin: maculatura (a spotting), from maculare (to spot, stain), from macula (spot)',
        source: 'scripps',
    },
    {
        word: 'antediluvian',
        definition: 'Ridiculously old-fashioned; belonging to the time before the biblical flood.',
        exampleSentence: 'The museum displayed antediluvian fossils from millions of years ago.',
        partOfSpeech: 'adjective',
        difficulty: 10,
        pattern: 'latin-roots',
        pronunciation: 'an-tee-dih-LOO-vee-un',
        etymology: 'Latin: ante (before) + diluvium (flood, deluge)',
        source: 'scripps',
    },
    {
        word: 'logorrhea',
        definition: 'A tendency to extreme talkativeness or wordiness.',
        exampleSentence: 'The professor\'s logorrhea made it impossible to finish the lecture on time.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'log-oh-REE-uh',
        etymology: 'Greek: logos (word, speech) + rhoia (flow, stream)',
        source: 'scripps',
    },
    {
        word: 'appoggiatura',
        definition: 'A musical ornamental note that delays the main note.',
        exampleSentence: 'The pianist added an appoggiatura that gave the passage an expressive quality.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'latin-roots',
        pronunciation: 'uh-poj-uh-TOOR-uh',
        etymology: 'Italian: appoggiatura (a leaning), from appoggiare (to lean, support), from Latin: appodiare',
        source: 'scripps',
    },
    {
        word: 'pococurante',
        definition: 'A careless or indifferent person.',
        exampleSentence: 'The pococurante attitude of the student frustrated every teacher in the school.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'latin-roots',
        pronunciation: 'poh-koh-koo-RAN-tee',
        etymology: 'Italian: poco (little) + curante (caring), from Latin: curare (to care)',
        source: 'scripps',
    },
    {
        word: 'demarche',
        definition: 'A step or maneuver in political or diplomatic affairs.',
        exampleSentence: 'The ambassador\'s demarche signaled a new phase in the negotiations.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'french-origin',
        pronunciation: 'day-MARSH',
        etymology: 'French: demarche (step, gait), from demarcher (to march)',
        source: 'scripps',
    },
    {
        word: 'guerdon',
        definition: 'A reward or recompense.',
        exampleSentence: 'The knight received a guerdon of gold and land for his loyal service.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'french-origin',
        pronunciation: 'GUR-dun',
        etymology: 'Old French: guerdon (reward), from Medieval Latin: widerdonum, from Old High German: widarlon (repayment)',
        source: 'scripps',
    },
    {
        word: 'ursprache',
        definition: 'A hypothetical parent language, especially Proto-Indo-European.',
        exampleSentence: 'Linguists continue to debate the features of the Indo-European ursprache.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'irregular',
        pronunciation: 'OOR-shprah-kuh',
        etymology: 'German: Ursprache (original language), from ur (original, primitive) + Sprache (language)',
        source: 'scripps',
    },
    {
        word: 'guetapens',
        definition: 'An ambush or trap.',
        exampleSentence: 'The travelers were warned about the guetapens set by bandits along the mountain road.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'french-origin',
        pronunciation: 'get-ah-PAHN',
        etymology: 'French: guet-apens (ambush), from guetter (to watch) + a pense (with deliberation)',
        source: 'scripps',
    },
    {
        word: 'esquamulose',
        definition: 'Not covered with scales or scalelike structures.',
        exampleSentence: 'The biologist noted that the specimen was esquamulose, unlike related species.',
        partOfSpeech: 'adjective',
        difficulty: 10,
        pattern: 'latin-roots',
        pronunciation: 'eh-SKWAM-yoo-lohs',
        etymology: 'Latin: e (without) + squamulosus (covered with small scales), from squama (scale)',
        source: 'scripps',
    },
    {
        word: 'cymbaleer',
        definition: 'One who plays cymbals.',
        exampleSentence: 'The cymbaleer in the orchestra produced a brilliant crash at the climax of the symphony.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'sim-buh-LEER',
        etymology: 'Greek: kymbalon (cymbal), from kymbe (bowl, cup)',
        source: 'scripps',
    },
    {
        word: 'succedaneum',
        definition: 'A substitute, especially a medicine used in place of another.',
        exampleSentence: 'The pharmacist recommended a succedaneum when the prescribed medication was unavailable.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'latin-roots',
        pronunciation: 'suk-sih-DAY-nee-um',
        etymology: 'Latin: succedaneum (substitute), from succedere (to follow after), from sub (under) + cedere (to go)',
        source: 'scripps',
    },
    {
        word: 'serrefine',
        definition: 'A small spring forceps used in surgery to clamp blood vessels.',
        exampleSentence: 'The surgeon used a serrefine to control bleeding during the delicate procedure.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'french-origin',
        pronunciation: 'sair-FEEN',
        etymology: 'French: serrefine (fine clamp), from serrer (to squeeze, clamp) + fine (fine, delicate)',
        source: 'scripps',
    },
    {
        word: 'stromuhr',
        definition: 'An instrument for measuring the speed and quantity of blood flow.',
        exampleSentence: 'The researcher used a stromuhr to monitor blood flow in the experimental subject.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'irregular',
        pronunciation: 'STROHM-oor',
        etymology: 'German: Strom (stream, current) + Uhr (clock, gauge)',
        source: 'scripps',
    },
    {
        word: 'soubrette',
        definition: 'A minor female role in a comedy, typically a pert maidservant.',
        exampleSentence: 'The actress was perfectly cast as the witty soubrette in the French farce.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'french-origin',
        pronunciation: 'soo-BRET',
        etymology: 'French: soubrette (lady\'s maid), from Provencal: soubret (coy), from soubra (to set aside)',
        source: 'scripps',
    },
    {
        word: 'prospicience',
        definition: 'The act of looking forward; foresight.',
        exampleSentence: 'The CEO\'s prospicience about market trends saved the company from financial ruin.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'latin-roots',
        pronunciation: 'proh-SPISH-ee-enss',
        etymology: 'Latin: prospicere (to look forward), from pro (forward) + specere (to look)',
        source: 'scripps',
    },
    {
        word: 'autochthonous',
        definition: 'Indigenous rather than imported; native to a place.',
        exampleSentence: 'The archaeologists studied autochthonous artifacts unique to the region.',
        partOfSpeech: 'adjective',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'aw-TOK-thuh-nus',
        etymology: 'Greek: autokhthon (sprung from the land), from autos (self) + khthon (earth)',
        source: 'scripps',
    },
    {
        word: 'laodicean',
        definition: 'Lukewarm or indifferent in religion or politics.',
        exampleSentence: 'His laodicean attitude toward civic engagement frustrated community organizers.',
        partOfSpeech: 'adjective',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'lay-od-ih-SEE-un',
        etymology: 'Greek: Laodikeia (Laodicea), an ancient city in Asia Minor whose church was rebuked for lukewarmness in Revelation',
        source: 'scripps',
    },
    {
        word: 'torsade',
        definition: 'A decorative twisted braid or cord, especially in architecture.',
        exampleSentence: 'The columns featured an elegant torsade pattern carved into the marble.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'french-origin',
        pronunciation: 'tor-SAHD',
        etymology: 'French: torsade (twisted cord), from tors (twisted), from Latin: tortus (twisted)',
        source: 'scripps',
    },
    {
        word: 'stichous',
        definition: 'Arranged in rows or lines.',
        exampleSentence: 'The botanist noted the stichous arrangement of the leaves along the stem.',
        partOfSpeech: 'adjective',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'STIK-us',
        etymology: 'Greek: stikhos (a row, line of verse)',
        source: 'scripps',
    },
    {
        word: 'Feldenkrais',
        definition: 'A method of education designed to improve movement and physical functioning.',
        exampleSentence: 'The dancer practiced Feldenkrais to improve body awareness and flexibility.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'irregular',
        pronunciation: 'FEL-den-krys',
        etymology: 'Named after Moshe Feldenkrais (1904-1984), Israeli physicist and engineer who developed the method',
        source: 'scripps',
    },
    {
        word: 'euonym',
        definition: 'A name well suited to the person, place, or thing named.',
        exampleSentence: 'The word "Twitter" for a social messaging platform is considered a euonym.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'YOO-oh-nim',
        etymology: 'Greek: eu (good, well) + onyma (name)',
        source: 'scripps',
    },
    {
        word: 'feuilleton',
        definition: 'A part of a newspaper devoted to fiction, criticism, or light literature.',
        exampleSentence: 'The feuilleton section of the Parisian newspaper published serialized novels.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'french-origin',
        pronunciation: 'fuh-yuh-TOHN',
        etymology: 'French: feuilleton (little leaf), diminutive of feuille (leaf), from Latin: folium',
        source: 'scripps',
    },
    {
        word: 'chiaroscurist',
        definition: 'An artist who specializes in the use of light and shade.',
        exampleSentence: 'Rembrandt was considered one of the greatest chiaroscurists in art history.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'irregular',
        pronunciation: 'kee-ar-uh-SKYOOR-ist',
        etymology: 'Italian: chiaro (light) + scuro (dark) + -ist (one who practices)',
        source: 'scripps',
    },
    {
        word: 'coxcombical',
        definition: 'Resembling or characteristic of a vain and conceited person.',
        exampleSentence: 'His coxcombical manner of dress drew amused looks from his colleagues.',
        partOfSpeech: 'adjective',
        difficulty: 10,
        pattern: 'irregular',
        pronunciation: 'koks-KOM-ih-kul',
        etymology: 'Middle English: cokkes comb (cock\'s comb), referring to the cap of a court jester',
        source: 'scripps',
    },
    {
        word: 'ratoon',
        definition: 'A new shoot growing from the base of a crop plant, especially sugar cane.',
        exampleSentence: 'The farmer harvested the ratoon crop without having to replant the entire field.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'irregular',
        pronunciation: 'ruh-TOON',
        etymology: 'Spanish: retono (sprout), from re (again) + otonar (to grow in autumn)',
        source: 'scripps',
    },
    {
        word: 'smaragdine',
        definition: 'Of or relating to emeralds; having the color of emeralds.',
        exampleSentence: 'The smaragdine waters of the Caribbean shimmered under the tropical sun.',
        partOfSpeech: 'adjective',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'smuh-RAG-deen',
        etymology: 'Greek: smaragdinos (of emerald), from smaragdos (emerald)',
        source: 'scripps',
    },
    {
        word: 'pappardelle',
        definition: 'Large, broad flat pasta noodles.',
        exampleSentence: 'The chef served pappardelle with a rich wild boar ragu.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'latin-roots',
        pronunciation: 'pap-ar-DEL-eh',
        etymology: 'Italian: pappardelle, from pappare (to gobble up)',
        source: 'scripps',
    },
    {
        word: 'scherzo',
        definition: 'A vigorous, playful musical movement, typically in 3/4 time.',
        exampleSentence: 'The scherzo in Beethoven\'s ninth symphony is full of rhythmic energy.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'irregular',
        pronunciation: 'SKAIR-tsoh',
        etymology: 'Italian: scherzo (jest, joke), from scherzare (to joke), from Germanic skerz (to leap)',
        source: 'scripps',
    },
    {
        word: 'milieu',
        definition: 'A person\'s social environment or surroundings.',
        exampleSentence: 'The artist thrived in the bohemian milieu of 1920s Paris.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'french-origin',
        pronunciation: 'meel-YUH',
        etymology: 'French: milieu (middle, environment), from mi (middle) + lieu (place), from Latin: locus',
        source: 'scripps',
    },
    {
        word: 'nunatak',
        definition: 'An isolated peak of rock projecting above a surface of inland ice.',
        exampleSentence: 'The expedition set up camp near a nunatak visible above the vast glacier.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'irregular',
        pronunciation: 'NUN-uh-tak',
        etymology: 'Inuit (Greenlandic): nunataq (lonely peak)',
        source: 'scripps',
    },
    {
        word: 'phoresy',
        definition: 'A type of symbiosis in which one organism is carried by another.',
        exampleSentence: 'Mites that ride on beetles exhibit a form of phoresy.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'FOR-eh-see',
        etymology: 'Greek: phoresis (being carried), from pherein (to carry)',
        source: 'scripps',
    },
    {
        word: 'weissnichtwo',
        definition: 'An imaginary place; nowhere in particular.',
        exampleSentence: 'The satirical novel was set in a fictional town called Weissnichtwo.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'irregular',
        pronunciation: 'VYSS-nikht-voh',
        etymology: 'German: weiss nicht wo (know not where), coined by Thomas Carlyle in Sartor Resartus',
        source: 'scripps',
    },
    {
        word: 'seriatim',
        definition: 'Taking one subject after another in regular order; point by point.',
        exampleSentence: 'The judge addressed each count of the indictment seriatim.',
        partOfSpeech: 'adverb',
        difficulty: 10,
        pattern: 'latin-roots',
        pronunciation: 'seer-ee-AY-tim',
        etymology: 'Latin: seriatim (in sequence), from series (row, chain)',
        source: 'scripps',
    },
    {
        word: 'dulcinea',
        definition: 'A sweetheart or idealized mistress.',
        exampleSentence: 'He devoted every poem to his dulcinea, whom he worshipped from afar.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'latin-roots',
        pronunciation: 'dul-sin-EE-uh',
        etymology: 'Spanish: Dulcinea del Toboso, the idealized lady in Cervantes\' Don Quixote, from dulce (sweet)',
        source: 'scripps',
    },
    {
        word: 'propaedeutic',
        definition: 'Serving as a preliminary instruction or introductory course.',
        exampleSentence: 'The propaedeutic seminar prepared students for advanced study in philosophy.',
        partOfSpeech: 'adjective',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'proh-pee-DOO-tik',
        etymology: 'Greek: propaideuein (to teach beforehand), from pro (before) + paideuein (to teach)',
        source: 'scripps',
    },
    {
        word: 'elegiacal',
        definition: 'Relating to or characteristic of an elegy; mournfully expressive.',
        exampleSentence: 'The elegiacal tone of the symphony evoked a deep sense of loss.',
        partOfSpeech: 'adjective',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'el-uh-JY-uh-kul',
        etymology: 'Greek: elegeia (elegy), from elegos (song of mourning)',
        source: 'scripps',
    },
    {
        word: 'congelation',
        definition: 'The process of congealing or becoming frozen.',
        exampleSentence: 'The congelation of the lake surface signaled the arrival of deep winter.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'latin-roots',
        pronunciation: 'kon-jeh-LAY-shun',
        etymology: 'Latin: congelatio (a freezing), from congelare (to freeze together), from con (together) + gelare (to freeze)',
        source: 'scripps',
    },
    {
        word: 'metonymical',
        definition: 'Relating to metonymy; using the name of one thing for that of another.',
        exampleSentence: 'The phrase "the crown" used to mean the monarchy is a metonymical expression.',
        partOfSpeech: 'adjective',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'met-oh-NIM-ih-kul',
        etymology: 'Greek: metonymia (change of name), from meta (change) + onyma (name)',
        source: 'scripps',
    },
    {
        word: 'cymotrichous',
        definition: 'Having wavy hair.',
        exampleSentence: 'The anthropologist classified the population as cymotrichous based on hair texture analysis.',
        partOfSpeech: 'adjective',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'sy-MOT-rih-kus',
        etymology: 'Greek: kyma (wave) + thrix (hair)',
        source: 'scripps',
    },
    {
        word: 'droit',
        definition: 'A legal right.',
        exampleSentence: 'The treaty established the droit of neutral nations to trade freely.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'french-origin',
        pronunciation: 'DRWAH',
        etymology: 'French: droit (right, law), from Latin: directum (straight, right)',
        source: 'scripps',
    },
    {
        word: 'canaille',
        definition: 'The common people; the masses regarded contemptuously.',
        exampleSentence: 'The aristocrat sneered at the canaille gathered outside the palace gates.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'french-origin',
        pronunciation: 'kuh-NY',
        etymology: 'French: canaille (rabble), from Italian: canaglia (pack of dogs), from Latin: canis (dog)',
        source: 'scripps',
    },
    {
        word: 'kamikaze',
        definition: 'A Japanese aircraft loaded with explosives; any recklessly self-destructive act.',
        exampleSentence: 'The word kamikaze originally referred to a divine wind that saved Japan from invasion.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'irregular',
        pronunciation: 'kah-mih-KAH-zee',
        etymology: 'Japanese: kami (divine) + kaze (wind)',
        source: 'scripps',
    },
    {
        word: 'chihuahua',
        definition: 'A very small breed of dog with a smooth or long coat.',
        exampleSentence: 'The tiny chihuahua barked fearlessly at dogs ten times its size.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'irregular',
        pronunciation: 'chih-WAH-wah',
        etymology: 'Spanish: from Chihuahua, a state in northern Mexico where the breed was discovered',
        source: 'scripps',
    },
    {
        word: 'sphygmomanometer',
        definition: 'An instrument for measuring blood pressure.',
        exampleSentence: 'The nurse used a sphygmomanometer to check the patient\'s blood pressure.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'sfig-moh-muh-NOM-ih-tur',
        etymology: 'Greek: sphygmos (pulse) + manos (thin, rare) + metron (measure)',
        source: 'scripps',
    },
    {
        word: 'crustaceology',
        definition: 'The branch of zoology that deals with crustaceans.',
        exampleSentence: 'Her PhD in crustaceology focused on the behavioral patterns of deep-sea shrimp.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'latin-roots',
        pronunciation: 'krus-tay-see-OL-uh-jee',
        etymology: 'Latin: crustaceus (having a shell), from crusta (crust, shell) + Greek: logos (study)',
        source: 'scripps',
    },
    {
        word: 'paroemiology',
        definition: 'The study of proverbs.',
        exampleSentence: 'The professor of paroemiology collected folk sayings from cultures around the world.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'par-ee-mee-OL-uh-jee',
        etymology: 'Greek: paroimia (proverb, byword) + logos (study)',
        source: 'scripps',
    },
    {
        word: 'misspell',
        definition: 'To spell a word incorrectly.',
        exampleSentence: 'It is ironic to misspell the word "misspell" in a spelling competition.',
        partOfSpeech: 'verb',
        difficulty: 10,
        pattern: 'prefixes',
        pronunciation: 'mis-SPEL',
        etymology: 'Old English: mis (wrong) + spellian (to tell, relate)',
        source: 'scripps',
    },
    {
        word: 'insouciant',
        definition: 'Showing a casual lack of concern; carefree.',
        exampleSentence: 'Her insouciant attitude toward deadlines was at odds with her corporate role.',
        partOfSpeech: 'adjective',
        difficulty: 10,
        pattern: 'french-origin',
        pronunciation: 'in-SOO-see-unt',
        etymology: 'French: insouciant (careless), from in (not) + soucier (to care), from Latin: sollicitare',
        source: 'scripps',
    },
    {
        word: 'gladiolus',
        definition: 'A plant of the iris family with sword-shaped leaves and spikes of flowers.',
        exampleSentence: 'The garden was filled with colorful gladiolus blooming in midsummer.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'latin-roots',
        pronunciation: 'glad-ee-OH-lus',
        etymology: 'Latin: gladiolus (small sword), diminutive of gladius (sword)',
        source: 'scripps',
    },
    {
        word: 'narcolepsy',
        definition: 'A condition characterized by an extreme tendency to fall asleep.',
        exampleSentence: 'The patient was diagnosed with narcolepsy after experiencing sudden sleep attacks.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'NAR-koh-lep-see',
        etymology: 'Greek: narke (numbness) + lepsis (seizure, attack)',
        source: 'scripps',
    },
    {
        word: 'cnidarian',
        definition: 'An aquatic invertebrate animal of the phylum that includes jellyfish and corals.',
        exampleSentence: 'The marine biologist studied cnidarian species found in tropical reef ecosystems.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'ny-DAIR-ee-un',
        etymology: 'Greek: knide (nettle, stinging), referring to the stinging cells of these organisms',
        source: 'scripps',
    },
    {
        word: 'thamaturgy',
        definition: 'The working of wonders or miracles; magic.',
        exampleSentence: 'Medieval chronicles attributed thamaturgy to certain saints and holy figures.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'THAW-muh-tur-jee',
        etymology: 'Greek: thaumatourgia (wonder-working), from thauma (wonder) + ergon (work)',
        source: 'scripps',
    },
    {
        word: 'obeisance',
        definition: 'Deferential respect; a gesture expressing such respect, such as a bow.',
        exampleSentence: 'The courtiers made obeisance to the queen as she entered the throne room.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'french-origin',
        pronunciation: 'oh-BAY-sunss',
        etymology: 'French: obeissance (obedience), from obeir (to obey), from Latin: obedire',
        source: 'scripps',
    },
    {
        word: 'autobahn',
        definition: 'A German highway designed for high-speed traffic.',
        exampleSentence: 'They drove on the autobahn at speeds that would be illegal in most countries.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'irregular',
        pronunciation: 'OW-toh-bahn',
        etymology: 'German: Autobahn (car road), from Auto (car) + Bahn (road, path)',
        source: 'scripps',
    },
    {
        word: 'souffle',
        definition: 'A light, fluffy baked dish made with egg yolks and beaten egg whites.',
        exampleSentence: 'The chef\'s chocolate souffle was the most popular dessert on the menu.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'french-origin',
        pronunciation: 'soo-FLAY',
        etymology: 'French: souffle (puffed up), past participle of souffler (to blow), from Latin: sufflare',
        source: 'scripps',
    },
    {
        word: 'propylaea',
        definition: 'A grand entrance or gateway to a temple or group of buildings.',
        exampleSentence: 'The propylaea of the Acropolis remains one of the most impressive ancient gateways.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'prop-ih-LEE-uh',
        etymology: 'Greek: propylaia (before the gate), from pro (before) + pyle (gate)',
        source: 'scripps',
    },
    {
        word: 'myrmidon',
        definition: 'A hired ruffian; a faithful follower who carries out orders without question.',
        exampleSentence: 'The warlord dispatched his myrmidons to enforce his rule over the conquered territory.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'MUR-mih-don',
        etymology: 'Greek: Myrmidones, the warriors commanded by Achilles in Homer\'s Iliad',
        source: 'scripps',
    },
    {
        word: 'xanthosis',
        definition: 'A yellowish discoloration of the skin.',
        exampleSentence: 'The dermatologist identified the patient\'s condition as xanthosis caused by excess carotenoids.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'zan-THOH-sis',
        etymology: 'Greek: xanthos (yellow) + -osis (condition)',
        source: 'scripps',
    },
    {
        word: 'aiguillette',
        definition: 'An ornamental braided cord worn on the shoulder of a military uniform.',
        exampleSentence: 'The officer\'s aiguillette gleamed gold against the dark blue of his dress uniform.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'french-origin',
        pronunciation: 'ay-gwih-LET',
        etymology: 'French: aiguillette (small needle), diminutive of aiguille (needle), from Latin: acucula',
        source: 'scripps',
    },
    {
        word: 'duende',
        definition: 'A quality of passion and inspiration; the power to attract through personal charm.',
        exampleSentence: 'The flamenco dancer performed with a duende that moved the audience to tears.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'irregular',
        pronunciation: 'DWEN-day',
        etymology: 'Spanish: duende (spirit, fairy), contraction of dueno de casa (master of the house)',
        source: 'scripps',
    },
    {
        word: 'gesellschaft',
        definition: 'A type of social organization based on impersonal ties, as in modern industrial society.',
        exampleSentence: 'The sociologist contrasted gesellschaft with the more intimate gemeinschaft of rural communities.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'irregular',
        pronunciation: 'guh-ZEL-shahft',
        etymology: 'German: Gesellschaft (society, companionship), from Geselle (companion) + -schaft (-ship)',
        source: 'scripps',
    },
    {
        word: 'mycorrhiza',
        definition: 'A symbiotic association between a fungus and the roots of a plant.',
        exampleSentence: 'Mycorrhiza helps trees absorb nutrients and water more efficiently from the soil.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'my-koh-RY-zuh',
        etymology: 'Greek: mykes (fungus) + rhiza (root)',
        source: 'scripps',
    },
    {
        word: 'dirigible',
        definition: 'A large, elongated airship that can be steered.',
        exampleSentence: 'The dirigible floated majestically over the city during the centennial celebration.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'latin-roots',
        pronunciation: 'DIR-ij-uh-bul',
        etymology: 'Latin: dirigere (to direct, steer), from dis (apart) + regere (to guide)',
        source: 'scripps',
    },
    {
        word: 'gabbro',
        definition: 'A dark, coarse-grained plutonic rock.',
        exampleSentence: 'The geologist identified the sample as gabbro based on its mineral composition.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'irregular',
        pronunciation: 'GAB-roh',
        etymology: 'Italian: gabbro, from Gabbro, a town in Tuscany, Italy',
        source: 'scripps',
    },
    {
        word: 'consigliere',
        definition: 'An adviser, especially to a crime boss.',
        exampleSentence: 'The consigliere whispered strategy into the ear of the organization\'s leader.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'latin-roots',
        pronunciation: 'kon-seel-YAIR-eh',
        etymology: 'Italian: consigliere (counselor, adviser), from consiglio (counsel), from Latin: consilium',
        source: 'scripps',
    },
    {
        word: 'marocain',
        definition: 'A ribbed crepe fabric used in dressmaking.',
        exampleSentence: 'The designer selected a rich burgundy marocain for the evening gown.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'french-origin',
        pronunciation: 'mar-oh-KAYN',
        etymology: 'French: marocain (Moroccan), from Maroc (Morocco)',
        source: 'scripps',
    },
    {
        word: 'esquisse',
        definition: 'A first sketch or rough draft of a picture or model.',
        exampleSentence: 'The artist\'s esquisse for the mural revealed the ambitious scope of the project.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'french-origin',
        pronunciation: 'eh-SKEES',
        etymology: 'French: esquisse (sketch), from Italian: schizzo, from Latin: schedium (impromptu)',
        source: 'scripps',
    },
    {
        word: 'huisache',
        definition: 'A thorny tropical American shrub or small tree.',
        exampleSentence: 'The huisache tree bloomed with fragrant yellow flowers along the Texas roadside.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'irregular',
        pronunciation: 'WEE-sach',
        etymology: 'Nahuatl: huixachi, from huitztli (thorn) + izquitl (toasted)',
        source: 'scripps',
    },
    {
        word: 'metier',
        definition: 'A profession or forte; a field of work or activity.',
        exampleSentence: 'Teaching was clearly her metier, as she inspired every student she encountered.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'french-origin',
        pronunciation: 'may-TYAY',
        etymology: 'French: metier (trade, craft), from Latin: ministerium (service, office)',
        source: 'scripps',
    },
    {
        word: 'gaucherie',
        definition: 'Awkward or tactless behavior.',
        exampleSentence: 'His social gaucherie at the ambassador\'s dinner was the talk of the embassy.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'french-origin',
        pronunciation: 'GOH-shuh-ree',
        etymology: 'French: gaucherie (awkwardness), from gauche (left, awkward)',
        source: 'scripps',
    },
    {
        word: 'appalachian',
        definition: 'Of or relating to the Appalachian Mountains in eastern North America.',
        exampleSentence: 'The Appalachian trail stretches over two thousand miles from Georgia to Maine.',
        partOfSpeech: 'adjective',
        difficulty: 10,
        pattern: 'irregular',
        pronunciation: 'ap-uh-LATCH-un',
        etymology: 'From Apalachee, a Muskogean people of northern Florida; Spanish adaptation of the native name',
        source: 'scripps',
    },
    {
        word: 'stretto',
        definition: 'A passage in a fugue where entries come close together; a faster concluding section.',
        exampleSentence: 'The pianist built intensity through the stretto, bringing the fugue to a thrilling close.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'irregular',
        pronunciation: 'STRET-oh',
        etymology: 'Italian: stretto (narrow, tight), from Latin: strictus (drawn tight)',
        source: 'scripps',
    },
    {
        word: 'bouillon',
        definition: 'A clear, seasoned broth made by simmering meat or vegetables.',
        exampleSentence: 'The recipe called for two cups of chicken bouillon as the soup base.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'french-origin',
        pronunciation: 'BOOL-yon',
        etymology: 'French: bouillon (broth), from bouillir (to boil), from Latin: bullire',
        source: 'scripps',
    },
    {
        word: 'onychophagy',
        definition: 'The habit of biting one\'s fingernails.',
        exampleSentence: 'The therapist suggested strategies to help the anxious teenager overcome onychophagy.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'on-ih-KOF-uh-jee',
        etymology: 'Greek: onyx (nail, claw) + phagein (to eat)',
        source: 'scripps',
    },
    {
        word: 'cernuous',
        definition: 'Drooping or nodding, as in certain flowers.',
        exampleSentence: 'The cernuous blossoms of the snowdrop bent gracefully toward the ground.',
        partOfSpeech: 'adjective',
        difficulty: 10,
        pattern: 'latin-roots',
        pronunciation: 'SUR-nyoo-us',
        etymology: 'Latin: cernuus (with the face turned toward the earth, stooping forward)',
        source: 'scripps',
    },
    {
        word: 'psilosis',
        definition: 'Loss of hair; a tropical disease causing intestinal issues.',
        exampleSentence: 'The physician diagnosed the patient with psilosis after ruling out other conditions.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'sy-LOH-sis',
        etymology: 'Greek: psilosis (a stripping), from psilos (bare, smooth)',
        source: 'scripps',
    },
    {
        word: 'lachrymose',
        definition: 'Tearful or given to weeping.',
        exampleSentence: 'The lachrymose final scene of the opera left the entire audience in tears.',
        partOfSpeech: 'adjective',
        difficulty: 10,
        pattern: 'latin-roots',
        pronunciation: 'LAK-rih-mohs',
        etymology: 'Latin: lacrimosus (tearful), from lacrima (tear)',
        source: 'scripps',
    },
    {
        word: 'terraqueous',
        definition: 'Consisting of land and water.',
        exampleSentence: 'Early cartographers attempted to map the terraqueous globe with limited instruments.',
        partOfSpeech: 'adjective',
        difficulty: 10,
        pattern: 'latin-roots',
        pronunciation: 'teh-RAY-kwee-us',
        etymology: 'Latin: terra (earth, land) + aqueous (watery), from aqua (water)',
        source: 'scripps',
    },
    {
        word: 'peradventure',
        definition: 'Perhaps; by chance; a possibility of doubt.',
        exampleSentence: 'Beyond peradventure, the evidence established the defendant\'s guilt.',
        partOfSpeech: 'adverb',
        difficulty: 10,
        pattern: 'french-origin',
        pronunciation: 'pur-ad-VEN-chur',
        etymology: 'Old French: par aventure (by chance), from par (by) + aventure (adventure, chance)',
        source: 'scripps',
    },
    {
        word: 'sardoodledom',
        definition: 'Mechanically contrived plot structure in drama.',
        exampleSentence: 'The critic dismissed the play as an example of sardoodledom lacking genuine emotion.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'irregular',
        pronunciation: 'sar-DOO-dul-dum',
        etymology: 'English: coined by George Bernard Shaw, from Victorien Sardou (French dramatist) + -dom',
        source: 'scripps',
    },
    {
        word: 'deinotherium',
        definition: 'An extinct elephant-like mammal with downward-curving tusks.',
        exampleSentence: 'Fossils of a deinotherium were discovered during the archaeological excavation.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'dy-noh-THEER-ee-um',
        etymology: 'Greek: deinos (terrible) + therion (beast)',
        source: 'scripps',
    },
    {
        word: 'schwarmerei',
        definition: 'Excessive or unwholesome sentiment; extravagant enthusiasm.',
        exampleSentence: 'The literary critic accused the young poet of schwarmerei in her early works.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'irregular',
        pronunciation: 'SHVAR-muh-ry',
        etymology: 'German: Schwarmerei (fanaticism, enthusiasm), from schwarmen (to swarm, rave)',
        source: 'scripps',
    },
    {
        word: 'chiffonier',
        definition: 'A tall chest of drawers, often with a mirror.',
        exampleSentence: 'The antique chiffonier held a prominent place in the Victorian bedroom.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'french-origin',
        pronunciation: 'shif-uh-NEER',
        etymology: 'French: chiffonnier (rag-picker), from chiffon (rag, scrap)',
        source: 'scripps',
    },
    {
        word: 'glaucous',
        definition: 'Of a dull grayish-green or blue color; covered with a powdery bloom.',
        exampleSentence: 'The glaucous leaves of the eucalyptus tree glistened with morning dew.',
        partOfSpeech: 'adjective',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'GLAW-kus',
        etymology: 'Greek: glaukos (gleaming, silvery, bluish-green)',
        source: 'scripps',
    },
    {
        word: 'haussmannize',
        definition: 'To remodel a city on a grand scale, especially by demolishing older buildings.',
        exampleSentence: 'The mayor\'s plan to haussmannize the downtown district met with strong opposition.',
        partOfSpeech: 'verb',
        difficulty: 10,
        pattern: 'irregular',
        pronunciation: 'HOWS-mun-yz',
        etymology: 'French: from Baron Georges-Eugene Haussmann, who renovated Paris in the 1850s-70s',
        source: 'scripps',
    },
];
