/**
 * words/tier1.ts
 *
 * ~200 curated SpellingWord objects for Kindergarten to 1st grade (difficulty 1-2).
 *
 * Pattern distribution:
 *   - ~80 CVC words (difficulty 1)
 *   - ~60 blends words (difficulty 1-2)
 *   - ~60 digraphs words (difficulty 2)
 *
 * Difficulty distribution:
 *   - difficulty 1: simplest CVC words and basic blends (~120 words)
 *   - difficulty 2: harder CVC, all digraphs, complex blends (~80 words)
 */

import type { SpellingWord } from './types';

export const TIER_1_WORDS: SpellingWord[] = [
    // ─────────────────────────────────────────────
    // CVC WORDS (difficulty 1) - ~65 words
    // ─────────────────────────────────────────────
    {
        word: 'cat',
        definition: 'A small furry pet that purrs.',
        exampleSentence: 'The cat sat on the mat.',
        partOfSpeech: 'noun',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'kat',
        etymology: 'Old English',
    },
    {
        word: 'dog',
        definition: 'A pet animal that barks and wags its tail.',
        exampleSentence: 'My dog likes to run in the yard.',
        partOfSpeech: 'noun',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'dawg',
    },
    {
        word: 'bed',
        definition: 'A place where you sleep at night.',
        exampleSentence: 'I go to bed at eight.',
        partOfSpeech: 'noun',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'bed',
        etymology: 'Old English',
    },
    {
        word: 'cup',
        definition: 'Something you drink from.',
        exampleSentence: 'She filled her cup with milk.',
        partOfSpeech: 'noun',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'kup',
    },
    {
        word: 'net',
        definition: 'A mesh used to catch things.',
        exampleSentence: 'He caught a fish in the net.',
        partOfSpeech: 'noun',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'net',
    },
    {
        word: 'hat',
        definition: 'Something you wear on your head.',
        exampleSentence: 'She put on a red hat.',
        partOfSpeech: 'noun',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'hat',
    },
    {
        word: 'pig',
        definition: 'A pink farm animal that says oink.',
        exampleSentence: 'The pig rolled in the mud.',
        partOfSpeech: 'noun',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'pig',
    },
    {
        word: 'sun',
        definition: 'The big bright star in the sky.',
        exampleSentence: 'The sun is very hot today.',
        partOfSpeech: 'noun',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'sun',
    },
    {
        word: 'bus',
        definition: 'A big vehicle that carries many people.',
        exampleSentence: 'I ride the bus to school.',
        partOfSpeech: 'noun',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'bus',
    },
    {
        word: 'map',
        definition: 'A picture that shows where places are.',
        exampleSentence: 'We looked at the map to find the park.',
        partOfSpeech: 'noun',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'map',
    },
    {
        word: 'pen',
        definition: 'A tool you use to write with ink.',
        exampleSentence: 'She drew a picture with her pen.',
        partOfSpeech: 'noun',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'pen',
    },
    {
        word: 'rug',
        definition: 'A soft cover for the floor.',
        exampleSentence: 'The baby sat on the rug.',
        partOfSpeech: 'noun',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'rug',
    },
    {
        word: 'fox',
        definition: 'A wild animal with a bushy tail.',
        exampleSentence: 'The fox ran into the woods.',
        partOfSpeech: 'noun',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'foks',
    },
    {
        word: 'hen',
        definition: 'A female chicken.',
        exampleSentence: 'The hen laid an egg.',
        partOfSpeech: 'noun',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'hen',
    },
    {
        word: 'log',
        definition: 'A big piece of a tree trunk.',
        exampleSentence: 'The frog sat on the log.',
        partOfSpeech: 'noun',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'lawg',
    },
    {
        word: 'mug',
        definition: 'A big cup with a handle.',
        exampleSentence: 'Dad drinks coffee from a mug.',
        partOfSpeech: 'noun',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'mug',
    },
    {
        word: 'van',
        definition: 'A big car that can carry many things.',
        exampleSentence: 'We packed the van for our trip.',
        partOfSpeech: 'noun',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'van',
    },
    {
        word: 'web',
        definition: 'A net that a spider makes.',
        exampleSentence: 'The spider made a web in the corner.',
        partOfSpeech: 'noun',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'web',
    },
    {
        word: 'jam',
        definition: 'A sweet spread made from fruit.',
        exampleSentence: 'I put jam on my toast.',
        partOfSpeech: 'noun',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'jam',
    },
    {
        word: 'bib',
        definition: 'A cloth that protects a baby during meals.',
        exampleSentence: 'The baby wore a bib at lunch.',
        partOfSpeech: 'noun',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'bib',
    },
    {
        word: 'pot',
        definition: 'A container used for cooking.',
        exampleSentence: 'Mom put soup in the pot.',
        partOfSpeech: 'noun',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'pot',
    },
    {
        word: 'tub',
        definition: 'A big container you take a bath in.',
        exampleSentence: 'The baby splashed in the tub.',
        partOfSpeech: 'noun',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'tub',
    },
    {
        word: 'lid',
        definition: 'A cover that goes on top of a pot or jar.',
        exampleSentence: 'Put the lid on the box.',
        partOfSpeech: 'noun',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'lid',
    },
    {
        word: 'fin',
        definition: 'The part of a fish that helps it swim.',
        exampleSentence: 'The fish moved its fin fast.',
        partOfSpeech: 'noun',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'fin',
    },
    {
        word: 'vet',
        definition: 'A doctor who takes care of animals.',
        exampleSentence: 'We took our dog to the vet.',
        partOfSpeech: 'noun',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'vet',
    },
    {
        word: 'run',
        definition: 'To move your legs very fast.',
        exampleSentence: 'I like to run at the park.',
        partOfSpeech: 'verb',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'run',
        etymology: 'Old English',
    },
    {
        word: 'sit',
        definition: 'To rest on a chair or the ground.',
        exampleSentence: 'Please sit on the chair.',
        partOfSpeech: 'verb',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'sit',
    },
    {
        word: 'hop',
        definition: 'To jump on one foot.',
        exampleSentence: 'The bunny likes to hop.',
        partOfSpeech: 'verb',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'hop',
    },
    {
        word: 'dig',
        definition: 'To make a hole in the ground.',
        exampleSentence: 'The dog likes to dig in the sand.',
        partOfSpeech: 'verb',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'dig',
    },
    {
        word: 'hug',
        definition: 'To wrap your arms around someone.',
        exampleSentence: 'I gave Mom a big hug.',
        partOfSpeech: 'verb',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'hug',
    },
    {
        word: 'mix',
        definition: 'To stir things together.',
        exampleSentence: 'Let us mix the paint.',
        partOfSpeech: 'verb',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'miks',
    },
    {
        word: 'rip',
        definition: 'To tear something apart.',
        exampleSentence: 'Be careful not to rip the paper.',
        partOfSpeech: 'verb',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'rip',
    },
    {
        word: 'nap',
        definition: 'A short sleep during the day.',
        exampleSentence: 'The baby took a nap.',
        partOfSpeech: 'noun',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'nap',
    },
    {
        word: 'tag',
        definition: 'A game where you chase and touch someone.',
        exampleSentence: 'We played tag at recess.',
        partOfSpeech: 'noun',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'tag',
    },
    {
        word: 'gum',
        definition: 'A chewy candy you do not swallow.',
        exampleSentence: 'She chewed a piece of gum.',
        partOfSpeech: 'noun',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'gum',
    },
    {
        word: 'dip',
        definition: 'To put something into a liquid quickly.',
        exampleSentence: 'I like to dip my fries in ketchup.',
        partOfSpeech: 'verb',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'dip',
    },
    {
        word: 'bug',
        definition: 'A small crawling creature like an ant.',
        exampleSentence: 'I saw a little bug on the leaf.',
        partOfSpeech: 'noun',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'bug',
    },
    {
        word: 'hit',
        definition: 'To strike something with your hand or a bat.',
        exampleSentence: 'She hit the ball over the fence.',
        partOfSpeech: 'verb',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'hit',
    },
    {
        word: 'jog',
        definition: 'To run slowly.',
        exampleSentence: 'We jog around the track.',
        partOfSpeech: 'verb',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'jog',
    },
    {
        word: 'nod',
        definition: 'To move your head up and down to say yes.',
        exampleSentence: 'She gave a nod to say yes.',
        partOfSpeech: 'verb',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'nod',
    },
    {
        word: 'sob',
        definition: 'To cry very hard.',
        exampleSentence: 'The child began to sob.',
        partOfSpeech: 'verb',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'sob',
    },
    {
        word: 'tip',
        definition: 'The very end or top of something.',
        exampleSentence: 'The tip of the pencil broke.',
        partOfSpeech: 'noun',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'tip',
    },
    {
        word: 'zip',
        definition: 'To close something with a zipper.',
        exampleSentence: 'Please zip up your coat.',
        partOfSpeech: 'verb',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'zip',
    },
    {
        word: 'cob',
        definition: 'The middle part of corn that holds the kernels.',
        exampleSentence: 'I ate corn on the cob.',
        partOfSpeech: 'noun',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'kob',
    },
    {
        word: 'fan',
        definition: 'A thing that blows air to cool you down.',
        exampleSentence: 'Turn on the fan, it is hot.',
        partOfSpeech: 'noun',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'fan',
    },
    {
        word: 'kit',
        definition: 'A set of tools or items packed together.',
        exampleSentence: 'She opened her art kit.',
        partOfSpeech: 'noun',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'kit',
    },
    {
        word: 'lot',
        definition: 'A large amount of something.',
        exampleSentence: 'There are a lot of stars in the sky.',
        partOfSpeech: 'noun',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'lot',
    },
    {
        word: 'nut',
        definition: 'A hard-shelled seed you can eat.',
        exampleSentence: 'The squirrel found a nut.',
        partOfSpeech: 'noun',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'nut',
    },
    {
        word: 'tap',
        definition: 'To touch something lightly.',
        exampleSentence: 'She gave a tap on the door.',
        partOfSpeech: 'verb',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'tap',
    },
    {
        word: 'wet',
        definition: 'Covered with water; not dry.',
        exampleSentence: 'My shoes got wet in the rain.',
        partOfSpeech: 'adjective',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'wet',
    },
    {
        word: 'wag',
        definition: 'To move back and forth quickly.',
        exampleSentence: 'The dog likes to wag its tail.',
        partOfSpeech: 'verb',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'wag',
    },
    {
        word: 'yam',
        definition: 'A sweet orange vegetable like a potato.',
        exampleSentence: 'We ate yam for dinner.',
        partOfSpeech: 'noun',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'yam',
    },
    {
        word: 'dim',
        definition: 'Not very bright; low light.',
        exampleSentence: 'The room was dim at night.',
        partOfSpeech: 'adjective',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'dim',
    },
    {
        word: 'cub',
        definition: 'A baby bear or lion.',
        exampleSentence: 'The bear cub played in the grass.',
        partOfSpeech: 'noun',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'kub',
    },
    {
        word: 'bun',
        definition: 'A small round piece of bread.',
        exampleSentence: 'I ate a hot dog on a bun.',
        partOfSpeech: 'noun',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'bun',
    },
    {
        word: 'jug',
        definition: 'A big container for holding liquids.',
        exampleSentence: 'Pour water from the jug.',
        partOfSpeech: 'noun',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'jug',
    },
    {
        word: 'pup',
        definition: 'A baby dog.',
        exampleSentence: 'The pup chased its tail.',
        partOfSpeech: 'noun',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'pup',
    },
    {
        word: 'win',
        definition: 'To come in first place.',
        exampleSentence: 'I hope we win the game.',
        partOfSpeech: 'verb',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'win',
    },
    {
        word: 'got',
        definition: 'Received or had something.',
        exampleSentence: 'I got a new toy today.',
        partOfSpeech: 'verb',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'got',
    },
    {
        word: 'bad',
        definition: 'Not good.',
        exampleSentence: 'Eating too much candy is bad for your teeth.',
        partOfSpeech: 'adjective',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'bad',
    },
    {
        word: 'big',
        definition: 'Very large in size.',
        exampleSentence: 'The elephant is very big.',
        partOfSpeech: 'adjective',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'big',
        etymology: 'Old English',
    },
    {
        word: 'hot',
        definition: 'Very warm; high temperature.',
        exampleSentence: 'The soup is too hot to eat.',
        partOfSpeech: 'adjective',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'hot',
    },
    {
        word: 'red',
        definition: 'The color of a fire truck or an apple.',
        exampleSentence: 'I picked a red apple.',
        partOfSpeech: 'adjective',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'red',
    },
    {
        word: 'sad',
        definition: 'Feeling unhappy.',
        exampleSentence: 'He was sad when his toy broke.',
        partOfSpeech: 'adjective',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'sad',
    },
    {
        word: 'fit',
        definition: 'The right size, or to be healthy and strong.',
        exampleSentence: 'The shoe did not fit my foot.',
        partOfSpeech: 'adjective',
        difficulty: 1,
        pattern: 'cvc',
        pronunciation: 'fit',
    },
    // ─────────────────────────────────────────────
    // CVC WORDS (difficulty 2) - ~15 words
    // ─────────────────────────────────────────────
    {
        word: 'wax',
        definition: 'A soft, smooth material used to make candles.',
        exampleSentence: 'The candle is made of wax.',
        partOfSpeech: 'noun',
        difficulty: 2,
        pattern: 'cvc',
        pronunciation: 'waks',
    },
    {
        word: 'fog',
        definition: 'A thick cloud close to the ground that makes it hard to see.',
        exampleSentence: 'The fog made the road hard to see.',
        partOfSpeech: 'noun',
        difficulty: 2,
        pattern: 'cvc',
        pronunciation: 'fog',
    },
    {
        word: 'gig',
        definition: 'A short job or a show where someone plays music.',
        exampleSentence: 'The band played a fun gig.',
        partOfSpeech: 'noun',
        difficulty: 2,
        pattern: 'cvc',
        pronunciation: 'gig',
    },
    {
        word: 'jab',
        definition: 'To poke something quickly.',
        exampleSentence: 'Do not jab your finger at the cat.',
        partOfSpeech: 'verb',
        difficulty: 2,
        pattern: 'cvc',
        pronunciation: 'jab',
    },
    {
        word: 'yap',
        definition: 'When a small dog barks in a high voice.',
        exampleSentence: 'The little dog likes to yap.',
        partOfSpeech: 'verb',
        difficulty: 2,
        pattern: 'cvc',
        pronunciation: 'yap',
    },
    {
        word: 'cot',
        definition: 'A small, light bed you can fold up.',
        exampleSentence: 'He slept on a cot at camp.',
        partOfSpeech: 'noun',
        difficulty: 2,
        pattern: 'cvc',
        pronunciation: 'kot',
    },
    {
        word: 'dug',
        definition: 'Made a hole in the ground.',
        exampleSentence: 'The dog dug a hole in the yard.',
        partOfSpeech: 'verb',
        difficulty: 2,
        pattern: 'cvc',
        pronunciation: 'dug',
    },
    {
        word: 'hid',
        definition: 'Went somewhere so no one could see you.',
        exampleSentence: 'She hid behind the tree.',
        partOfSpeech: 'verb',
        difficulty: 2,
        pattern: 'cvc',
        pronunciation: 'hid',
    },
    {
        word: 'mob',
        definition: 'A large, noisy crowd of people.',
        exampleSentence: 'A mob of fans cheered at the game.',
        partOfSpeech: 'noun',
        difficulty: 2,
        pattern: 'cvc',
        pronunciation: 'mob',
    },
    {
        word: 'rim',
        definition: 'The edge or border around something round.',
        exampleSentence: 'The ball hit the rim of the basket.',
        partOfSpeech: 'noun',
        difficulty: 2,
        pattern: 'cvc',
        pronunciation: 'rim',
    },
    {
        word: 'tug',
        definition: 'To pull something hard.',
        exampleSentence: 'The dog gave a tug on the rope.',
        partOfSpeech: 'verb',
        difficulty: 2,
        pattern: 'cvc',
        pronunciation: 'tug',
    },
    {
        word: 'hem',
        definition: 'The folded edge at the bottom of a shirt or pants.',
        exampleSentence: 'Mom fixed the hem on my pants.',
        partOfSpeech: 'noun',
        difficulty: 2,
        pattern: 'cvc',
        pronunciation: 'hem',
    },
    {
        word: 'dab',
        definition: 'To touch lightly with something soft.',
        exampleSentence: 'She used a cloth to dab the spill.',
        partOfSpeech: 'verb',
        difficulty: 2,
        pattern: 'cvc',
        pronunciation: 'dab',
    },
    {
        word: 'nib',
        definition: 'The pointed tip of a pen.',
        exampleSentence: 'Write carefully with the nib of the pen.',
        partOfSpeech: 'noun',
        difficulty: 2,
        pattern: 'cvc',
        pronunciation: 'nib',
    },
    {
        word: 'cud',
        definition: 'Food that a cow chews again after swallowing.',
        exampleSentence: 'The cow chewed its cud in the field.',
        partOfSpeech: 'noun',
        difficulty: 2,
        pattern: 'cvc',
        pronunciation: 'kud',
    },
    // ─────────────────────────────────────────────
    // BLENDS WORDS (difficulty 1) - ~35 words
    // ─────────────────────────────────────────────
    {
        word: 'flag',
        definition: 'A piece of cloth with a special design that stands for something.',
        exampleSentence: 'We waved the flag on the Fourth of July.',
        partOfSpeech: 'noun',
        difficulty: 1,
        pattern: 'blends',
        pronunciation: 'flag',
        etymology: 'Old English',
    },
    {
        word: 'stop',
        definition: 'To not move anymore.',
        exampleSentence: 'The car came to a stop.',
        partOfSpeech: 'verb',
        difficulty: 1,
        pattern: 'blends',
        pronunciation: 'stop',
    },
    {
        word: 'grab',
        definition: 'To take hold of something quickly.',
        exampleSentence: 'Grab your coat before you go.',
        partOfSpeech: 'verb',
        difficulty: 1,
        pattern: 'blends',
        pronunciation: 'grab',
    },
    {
        word: 'skip',
        definition: 'To hop and step as you move forward.',
        exampleSentence: 'She likes to skip down the path.',
        partOfSpeech: 'verb',
        difficulty: 1,
        pattern: 'blends',
        pronunciation: 'skip',
    },
    {
        word: 'trip',
        definition: 'To stumble or fall, or a journey you take.',
        exampleSentence: 'We took a trip to the beach.',
        partOfSpeech: 'noun',
        difficulty: 1,
        pattern: 'blends',
        pronunciation: 'trip',
    },
    {
        word: 'clap',
        definition: 'To hit your hands together to make a sound.',
        exampleSentence: 'We clap when the song is over.',
        partOfSpeech: 'verb',
        difficulty: 1,
        pattern: 'blends',
        pronunciation: 'klap',
    },
    {
        word: 'plan',
        definition: 'An idea about what to do.',
        exampleSentence: 'We made a plan for the party.',
        partOfSpeech: 'noun',
        difficulty: 1,
        pattern: 'blends',
        pronunciation: 'plan',
    },
    {
        word: 'snap',
        definition: 'To break quickly, or the sound it makes.',
        exampleSentence: 'The twig broke with a snap.',
        partOfSpeech: 'verb',
        difficulty: 1,
        pattern: 'blends',
        pronunciation: 'snap',
    },
    {
        word: 'spot',
        definition: 'A small round mark, or a place.',
        exampleSentence: 'The dog has a black spot on its back.',
        partOfSpeech: 'noun',
        difficulty: 1,
        pattern: 'blends',
        pronunciation: 'spot',
    },
    {
        word: 'step',
        definition: 'To put one foot forward.',
        exampleSentence: 'Take one step at a time.',
        partOfSpeech: 'noun',
        difficulty: 1,
        pattern: 'blends',
        pronunciation: 'step',
    },
    {
        word: 'flat',
        definition: 'Smooth and even, not bumpy.',
        exampleSentence: 'The road is nice and flat.',
        partOfSpeech: 'adjective',
        difficulty: 1,
        pattern: 'blends',
        pronunciation: 'flat',
    },
    {
        word: 'drip',
        definition: 'When water falls one drop at a time.',
        exampleSentence: 'The faucet has a drip.',
        partOfSpeech: 'verb',
        difficulty: 1,
        pattern: 'blends',
        pronunciation: 'drip',
    },
    {
        word: 'plum',
        definition: 'A soft, round purple fruit.',
        exampleSentence: 'I ate a juicy plum for a snack.',
        partOfSpeech: 'noun',
        difficulty: 1,
        pattern: 'blends',
        pronunciation: 'plum',
    },
    {
        word: 'sled',
        definition: 'A flat board you slide on in the snow.',
        exampleSentence: 'We rode the sled down the hill.',
        partOfSpeech: 'noun',
        difficulty: 1,
        pattern: 'blends',
        pronunciation: 'sled',
    },
    {
        word: 'spin',
        definition: 'To turn around and around in a circle.',
        exampleSentence: 'Watch the top spin on the table.',
        partOfSpeech: 'verb',
        difficulty: 1,
        pattern: 'blends',
        pronunciation: 'spin',
    },
    {
        word: 'grin',
        definition: 'A big, wide smile.',
        exampleSentence: 'He had a big grin on his face.',
        partOfSpeech: 'noun',
        difficulty: 1,
        pattern: 'blends',
        pronunciation: 'grin',
    },
    {
        word: 'drop',
        definition: 'To let something fall.',
        exampleSentence: 'Do not drop the glass.',
        partOfSpeech: 'verb',
        difficulty: 1,
        pattern: 'blends',
        pronunciation: 'drop',
    },
    {
        word: 'slim',
        definition: 'Thin and narrow.',
        exampleSentence: 'The cat squeezed through a slim gap.',
        partOfSpeech: 'adjective',
        difficulty: 1,
        pattern: 'blends',
        pronunciation: 'slim',
    },
    {
        word: 'frog',
        definition: 'A small green animal that jumps and lives near water.',
        exampleSentence: 'The frog jumped into the pond.',
        partOfSpeech: 'noun',
        difficulty: 1,
        pattern: 'blends',
        pronunciation: 'frog',
    },
    {
        word: 'drum',
        definition: 'A round instrument you hit to make music.',
        exampleSentence: 'He banged on the drum.',
        partOfSpeech: 'noun',
        difficulty: 1,
        pattern: 'blends',
        pronunciation: 'drum',
    },
    {
        word: 'plug',
        definition: 'The part at the end of a cord that goes in the wall.',
        exampleSentence: 'Put the plug in the wall to turn on the lamp.',
        partOfSpeech: 'noun',
        difficulty: 1,
        pattern: 'blends',
        pronunciation: 'plug',
    },
    {
        word: 'glad',
        definition: 'Feeling happy.',
        exampleSentence: 'I am glad you came to my party.',
        partOfSpeech: 'adjective',
        difficulty: 1,
        pattern: 'blends',
        pronunciation: 'glad',
    },
    {
        word: 'swim',
        definition: 'To move through water using your arms and legs.',
        exampleSentence: 'I like to swim in the pool.',
        partOfSpeech: 'verb',
        difficulty: 1,
        pattern: 'blends',
        pronunciation: 'swim',
        etymology: 'Old English',
    },
    {
        word: 'trap',
        definition: 'Something used to catch an animal.',
        exampleSentence: 'The mouse ran into the trap.',
        partOfSpeech: 'noun',
        difficulty: 1,
        pattern: 'blends',
        pronunciation: 'trap',
    },
    {
        word: 'twin',
        definition: 'One of two children born at the same time.',
        exampleSentence: 'She and her twin look the same.',
        partOfSpeech: 'noun',
        difficulty: 1,
        pattern: 'blends',
        pronunciation: 'twin',
    },
    {
        word: 'crop',
        definition: 'Plants that a farmer grows for food.',
        exampleSentence: 'The farmer planted a corn crop.',
        partOfSpeech: 'noun',
        difficulty: 1,
        pattern: 'blends',
        pronunciation: 'krop',
    },
    {
        word: 'blob',
        definition: 'A soft lump with no clear shape.',
        exampleSentence: 'A blob of paint fell on the floor.',
        partOfSpeech: 'noun',
        difficulty: 1,
        pattern: 'blends',
        pronunciation: 'blob',
    },
    {
        word: 'crab',
        definition: 'A sea animal with a hard shell and claws.',
        exampleSentence: 'We saw a crab at the beach.',
        partOfSpeech: 'noun',
        difficulty: 1,
        pattern: 'blends',
        pronunciation: 'krab',
    },
    {
        word: 'slam',
        definition: 'To close something hard and loud.',
        exampleSentence: 'Do not slam the door.',
        partOfSpeech: 'verb',
        difficulty: 1,
        pattern: 'blends',
        pronunciation: 'slam',
    },
    {
        word: 'snip',
        definition: 'To cut with scissors in a quick way.',
        exampleSentence: 'She used scissors to snip the ribbon.',
        partOfSpeech: 'verb',
        difficulty: 1,
        pattern: 'blends',
        pronunciation: 'snip',
    },
    {
        word: 'stub',
        definition: 'A short piece left over after something is used.',
        exampleSentence: 'He kept the ticket stub.',
        partOfSpeech: 'noun',
        difficulty: 1,
        pattern: 'blends',
        pronunciation: 'stub',
    },
    {
        word: 'brim',
        definition: 'The top edge of a cup or the wide part of a hat.',
        exampleSentence: 'The cup was full to the brim.',
        partOfSpeech: 'noun',
        difficulty: 1,
        pattern: 'blends',
        pronunciation: 'brim',
    },
    {
        word: 'prop',
        definition: 'To hold something up so it does not fall.',
        exampleSentence: 'Prop the book open with a cup.',
        partOfSpeech: 'verb',
        difficulty: 1,
        pattern: 'blends',
        pronunciation: 'prop',
    },
    {
        word: 'trot',
        definition: 'To run at a slow, easy speed.',
        exampleSentence: 'The horse began to trot.',
        partOfSpeech: 'verb',
        difficulty: 1,
        pattern: 'blends',
        pronunciation: 'trot',
    },
    {
        word: 'spit',
        definition: 'To push water or food out of your mouth.',
        exampleSentence: 'Do not spit out your food.',
        partOfSpeech: 'verb',
        difficulty: 1,
        pattern: 'blends',
        pronunciation: 'spit',
    },
    // ─────────────────────────────────────────────
    // BLENDS WORDS (difficulty 2) - ~25 words
    // ─────────────────────────────────────────────
    {
        word: 'stomp',
        definition: 'To step down hard with your foot.',
        exampleSentence: 'He likes to stomp in puddles.',
        partOfSpeech: 'verb',
        difficulty: 2,
        pattern: 'blends',
        pronunciation: 'stomp',
    },
    {
        word: 'blend',
        definition: 'To mix two or more things together smoothly.',
        exampleSentence: 'Blend the fruit to make a smoothie.',
        partOfSpeech: 'verb',
        difficulty: 2,
        pattern: 'blends',
        pronunciation: 'blend',
    },
    {
        word: 'drift',
        definition: 'To move slowly without trying.',
        exampleSentence: 'The boat began to drift on the lake.',
        partOfSpeech: 'verb',
        difficulty: 2,
        pattern: 'blends',
        pronunciation: 'drift',
    },
    {
        word: 'frost',
        definition: 'A thin layer of ice on things when it is cold.',
        exampleSentence: 'There was frost on the window this morning.',
        partOfSpeech: 'noun',
        difficulty: 2,
        pattern: 'blends',
        pronunciation: 'frawst',
        etymology: 'Old English',
    },
    {
        word: 'split',
        definition: 'To break or divide into parts.',
        exampleSentence: 'Let us split the cookie in half.',
        partOfSpeech: 'verb',
        difficulty: 2,
        pattern: 'blends',
        pronunciation: 'split',
    },
    {
        word: 'stump',
        definition: 'The short part of a tree left after it is cut down.',
        exampleSentence: 'The rabbit sat on the stump.',
        partOfSpeech: 'noun',
        difficulty: 2,
        pattern: 'blends',
        pronunciation: 'stump',
    },
    {
        word: 'clamp',
        definition: 'A tool that holds two things tightly together.',
        exampleSentence: 'Use a clamp to hold the wood.',
        partOfSpeech: 'noun',
        difficulty: 2,
        pattern: 'blends',
        pronunciation: 'klamp',
    },
    {
        word: 'swift',
        definition: 'Moving very fast.',
        exampleSentence: 'The deer is a swift runner.',
        partOfSpeech: 'adjective',
        difficulty: 2,
        pattern: 'blends',
        pronunciation: 'swift',
    },
    {
        word: 'crisp',
        definition: 'Firm and crunchy.',
        exampleSentence: 'The apple was fresh and crisp.',
        partOfSpeech: 'adjective',
        difficulty: 2,
        pattern: 'blends',
        pronunciation: 'krisp',
    },
    {
        word: 'grunt',
        definition: 'A short, deep sound.',
        exampleSentence: 'The pig let out a grunt.',
        partOfSpeech: 'noun',
        difficulty: 2,
        pattern: 'blends',
        pronunciation: 'grunt',
    },
    {
        word: 'print',
        definition: 'To write neatly in separate letters, or to make copies.',
        exampleSentence: 'Please print your name on the paper.',
        partOfSpeech: 'verb',
        difficulty: 2,
        pattern: 'blends',
        pronunciation: 'print',
    },
    {
        word: 'skunk',
        definition: 'A black and white animal that can spray a bad smell.',
        exampleSentence: 'The skunk walked across the road.',
        partOfSpeech: 'noun',
        difficulty: 2,
        pattern: 'blends',
        pronunciation: 'skunk',
    },
    {
        word: 'slept',
        definition: 'Past tense of sleep; was sleeping.',
        exampleSentence: 'I slept all night long.',
        partOfSpeech: 'verb',
        difficulty: 2,
        pattern: 'blends',
        pronunciation: 'slept',
    },
    {
        word: 'plop',
        definition: 'To drop down heavily.',
        exampleSentence: 'The frog went plop into the water.',
        partOfSpeech: 'verb',
        difficulty: 2,
        pattern: 'blends',
        pronunciation: 'plop',
    },
    {
        word: 'spill',
        definition: 'When liquid falls out of a container by accident.',
        exampleSentence: 'Do not spill the juice.',
        partOfSpeech: 'verb',
        difficulty: 2,
        pattern: 'blends',
        pronunciation: 'spil',
    },
    {
        word: 'brand',
        definition: 'A type or kind of something you buy.',
        exampleSentence: 'What brand of cereal do you like?',
        partOfSpeech: 'noun',
        difficulty: 2,
        pattern: 'blends',
        pronunciation: 'brand',
    },
    {
        word: 'grump',
        definition: 'A person who is in a bad mood.',
        exampleSentence: 'Do not be a grump today.',
        partOfSpeech: 'noun',
        difficulty: 2,
        pattern: 'blends',
        pronunciation: 'grump',
    },
    {
        word: 'cleft',
        definition: 'A narrow opening or crack in something.',
        exampleSentence: 'Water ran through the cleft in the rock.',
        partOfSpeech: 'noun',
        difficulty: 2,
        pattern: 'blends',
        pronunciation: 'kleft',
    },
    {
        word: 'brisk',
        definition: 'Quick and full of energy; cool and fresh.',
        exampleSentence: 'We took a brisk walk in the cool air.',
        partOfSpeech: 'adjective',
        difficulty: 2,
        pattern: 'blends',
        pronunciation: 'brisk',
    },
    {
        word: 'clasp',
        definition: 'A small clip that holds things shut.',
        exampleSentence: 'The clasp on her bracelet came open.',
        partOfSpeech: 'noun',
        difficulty: 2,
        pattern: 'blends',
        pronunciation: 'klasp',
    },
    {
        word: 'glint',
        definition: 'A tiny flash of light.',
        exampleSentence: 'I saw a glint of light on the water.',
        partOfSpeech: 'noun',
        difficulty: 2,
        pattern: 'blends',
        pronunciation: 'glint',
    },
    {
        word: 'strut',
        definition: 'To walk in a proud way.',
        exampleSentence: 'The rooster likes to strut around the yard.',
        partOfSpeech: 'verb',
        difficulty: 2,
        pattern: 'blends',
        pronunciation: 'strut',
    },
    {
        word: 'tramp',
        definition: 'To walk with heavy steps.',
        exampleSentence: 'We heard him tramp up the stairs.',
        partOfSpeech: 'verb',
        difficulty: 2,
        pattern: 'blends',
        pronunciation: 'tramp',
    },
    {
        word: 'shrub',
        definition: 'A small bush with many leaves.',
        exampleSentence: 'A bird sat on the shrub.',
        partOfSpeech: 'noun',
        difficulty: 2,
        pattern: 'blends',
        pronunciation: 'shrub',
    },
    {
        word: 'strap',
        definition: 'A long strip used to hold things.',
        exampleSentence: 'Tighten the strap on your backpack.',
        partOfSpeech: 'noun',
        difficulty: 2,
        pattern: 'blends',
        pronunciation: 'strap',
    },
    // ─────────────────────────────────────────────
    // DIGRAPHS WORDS (difficulty 2) - ~60 words
    // ─────────────────────────────────────────────
    {
        word: 'chat',
        definition: 'To talk with someone in a friendly way.',
        exampleSentence: 'We had a nice chat after lunch.',
        partOfSpeech: 'verb',
        difficulty: 2,
        pattern: 'digraphs',
        pronunciation: 'chat',
    },
    {
        word: 'ship',
        definition: 'A big boat that sails on the ocean.',
        exampleSentence: 'The ship sailed across the sea.',
        partOfSpeech: 'noun',
        difficulty: 2,
        pattern: 'digraphs',
        pronunciation: 'ship',
        etymology: 'Old English',
    },
    {
        word: 'thin',
        definition: 'Not thick; very narrow.',
        exampleSentence: 'The paper is very thin.',
        partOfSpeech: 'adjective',
        difficulty: 2,
        pattern: 'digraphs',
        pronunciation: 'thin',
    },
    {
        word: 'when',
        definition: 'At what time.',
        exampleSentence: 'When will we go to the park?',
        partOfSpeech: 'adverb',
        difficulty: 2,
        pattern: 'digraphs',
        pronunciation: 'wen',
        etymology: 'Old English',
    },
    {
        word: 'much',
        definition: 'A large amount.',
        exampleSentence: 'Thank you so much for the gift.',
        partOfSpeech: 'adverb',
        difficulty: 2,
        pattern: 'digraphs',
        pronunciation: 'much',
    },
    {
        word: 'chop',
        definition: 'To cut into pieces.',
        exampleSentence: 'Dad helped chop the vegetables.',
        partOfSpeech: 'verb',
        difficulty: 2,
        pattern: 'digraphs',
        pronunciation: 'chop',
    },
    {
        word: 'shed',
        definition: 'A small building used to store tools or things.',
        exampleSentence: 'The rake is in the shed.',
        partOfSpeech: 'noun',
        difficulty: 2,
        pattern: 'digraphs',
        pronunciation: 'shed',
    },
    {
        word: 'whip',
        definition: 'To stir or beat very fast.',
        exampleSentence: 'Whip the cream until it is fluffy.',
        partOfSpeech: 'verb',
        difficulty: 2,
        pattern: 'digraphs',
        pronunciation: 'wip',
    },
    {
        word: 'them',
        definition: 'A word used to talk about other people or things.',
        exampleSentence: 'I gave the toys to them.',
        partOfSpeech: 'pronoun',
        difficulty: 2,
        pattern: 'digraphs',
        pronunciation: 'them',
    },
    {
        word: 'such',
        definition: 'Of that kind or to that degree.',
        exampleSentence: 'It was such a fun day.',
        partOfSpeech: 'adjective',
        difficulty: 2,
        pattern: 'digraphs',
        pronunciation: 'such',
    },
    {
        word: 'chin',
        definition: 'The bottom part of your face below your mouth.',
        exampleSentence: 'He rested his chin on his hand.',
        partOfSpeech: 'noun',
        difficulty: 2,
        pattern: 'digraphs',
        pronunciation: 'chin',
    },
    {
        word: 'shop',
        definition: 'A store where you buy things.',
        exampleSentence: 'We went to the toy shop.',
        partOfSpeech: 'noun',
        difficulty: 2,
        pattern: 'digraphs',
        pronunciation: 'shop',
    },
    {
        word: 'than',
        definition: 'A word used to compare two things.',
        exampleSentence: 'My dog is bigger than yours.',
        partOfSpeech: 'conjunction',
        difficulty: 2,
        pattern: 'digraphs',
        pronunciation: 'than',
    },
    {
        word: 'what',
        definition: 'A word used to ask about something.',
        exampleSentence: 'What is your name?',
        partOfSpeech: 'pronoun',
        difficulty: 2,
        pattern: 'digraphs',
        pronunciation: 'wut',
    },
    {
        word: 'rich',
        definition: 'Having a lot of money or being very full of flavor.',
        exampleSentence: 'The cake had a rich chocolate taste.',
        partOfSpeech: 'adjective',
        difficulty: 2,
        pattern: 'digraphs',
        pronunciation: 'rich',
    },
    {
        word: 'chap',
        definition: 'A boy or a man.',
        exampleSentence: 'He is a nice young chap.',
        partOfSpeech: 'noun',
        difficulty: 2,
        pattern: 'digraphs',
        pronunciation: 'chap',
    },
    {
        word: 'shin',
        definition: 'The front part of your leg below the knee.',
        exampleSentence: 'She bumped her shin on the table.',
        partOfSpeech: 'noun',
        difficulty: 2,
        pattern: 'digraphs',
        pronunciation: 'shin',
    },
    {
        word: 'this',
        definition: 'A word used to point out something nearby.',
        exampleSentence: 'This is my favorite book.',
        partOfSpeech: 'pronoun',
        difficulty: 2,
        pattern: 'digraphs',
        pronunciation: 'this',
    },
    {
        word: 'which',
        definition: 'A word used to ask about a choice.',
        exampleSentence: 'Which color do you like?',
        partOfSpeech: 'pronoun',
        difficulty: 2,
        pattern: 'digraphs',
        pronunciation: 'wich',
    },
    {
        word: 'each',
        definition: 'Every one in a group, one by one.',
        exampleSentence: 'Each child got a sticker.',
        partOfSpeech: 'adjective',
        difficulty: 2,
        pattern: 'digraphs',
        pronunciation: 'eech',
    },
    {
        word: 'chunk',
        definition: 'A thick piece of something.',
        exampleSentence: 'She bit off a big chunk of bread.',
        partOfSpeech: 'noun',
        difficulty: 2,
        pattern: 'digraphs',
        pronunciation: 'chunk',
    },
    {
        word: 'shelf',
        definition: 'A flat board on the wall where you put things.',
        exampleSentence: 'Put the book on the shelf.',
        partOfSpeech: 'noun',
        difficulty: 2,
        pattern: 'digraphs',
        pronunciation: 'shelf',
    },
    {
        word: 'thick',
        definition: 'Wide from one side to the other; not thin.',
        exampleSentence: 'The tree trunk is very thick.',
        partOfSpeech: 'adjective',
        difficulty: 2,
        pattern: 'digraphs',
        pronunciation: 'thik',
    },
    {
        word: 'wheel',
        definition: 'A round thing that turns to help things move.',
        exampleSentence: 'The wheel on my bike is flat.',
        partOfSpeech: 'noun',
        difficulty: 2,
        pattern: 'digraphs',
        pronunciation: 'weel',
        etymology: 'Old English',
    },
    {
        word: 'lunch',
        definition: 'The meal you eat in the middle of the day.',
        exampleSentence: 'We had pizza for lunch.',
        partOfSpeech: 'noun',
        difficulty: 2,
        pattern: 'digraphs',
        pronunciation: 'lunch',
    },
    {
        word: 'check',
        definition: 'To look at something carefully to make sure it is right.',
        exampleSentence: 'Check your work before you turn it in.',
        partOfSpeech: 'verb',
        difficulty: 2,
        pattern: 'digraphs',
        pronunciation: 'chek',
    },
    {
        word: 'shell',
        definition: 'A hard cover on the outside of an egg, nut, or sea animal.',
        exampleSentence: 'She found a pretty shell on the beach.',
        partOfSpeech: 'noun',
        difficulty: 2,
        pattern: 'digraphs',
        pronunciation: 'shel',
    },
    {
        word: 'that',
        definition: 'A word used to point out something.',
        exampleSentence: 'Look at that big tree.',
        partOfSpeech: 'pronoun',
        difficulty: 2,
        pattern: 'digraphs',
        pronunciation: 'that',
    },
    {
        word: 'where',
        definition: 'At or in what place.',
        exampleSentence: 'Where is my lunchbox?',
        partOfSpeech: 'adverb',
        difficulty: 2,
        pattern: 'digraphs',
        pronunciation: 'wair',
    },
    {
        word: 'match',
        definition: 'Something that is the same as another, or a contest.',
        exampleSentence: 'These socks do not match.',
        partOfSpeech: 'noun',
        difficulty: 2,
        pattern: 'digraphs',
        pronunciation: 'mach',
    },
    {
        word: 'chick',
        definition: 'A baby chicken.',
        exampleSentence: 'The chick was soft and yellow.',
        partOfSpeech: 'noun',
        difficulty: 2,
        pattern: 'digraphs',
        pronunciation: 'chik',
    },
    {
        word: 'shrug',
        definition: 'To lift your shoulders to show you do not know.',
        exampleSentence: 'He gave a shrug when I asked him.',
        partOfSpeech: 'verb',
        difficulty: 2,
        pattern: 'digraphs',
        pronunciation: 'shrug',
    },
    {
        word: 'thank',
        definition: 'To tell someone you are glad for what they did.',
        exampleSentence: 'I want to thank you for the present.',
        partOfSpeech: 'verb',
        difficulty: 2,
        pattern: 'digraphs',
        pronunciation: 'thangk',
    },
    {
        word: 'white',
        definition: 'The color of snow and clouds.',
        exampleSentence: 'The rabbit is soft and white.',
        partOfSpeech: 'adjective',
        difficulty: 2,
        pattern: 'digraphs',
        pronunciation: 'wyt',
    },
    {
        word: 'catch',
        definition: 'To grab something that is moving.',
        exampleSentence: 'Can you catch the ball?',
        partOfSpeech: 'verb',
        difficulty: 2,
        pattern: 'digraphs',
        pronunciation: 'kach',
    },
    {
        word: 'chill',
        definition: 'A cold feeling.',
        exampleSentence: 'There is a chill in the air.',
        partOfSpeech: 'noun',
        difficulty: 2,
        pattern: 'digraphs',
        pronunciation: 'chil',
    },
    {
        word: 'shock',
        definition: 'A big surprise that makes you jump.',
        exampleSentence: 'The loud bang gave me a shock.',
        partOfSpeech: 'noun',
        difficulty: 2,
        pattern: 'digraphs',
        pronunciation: 'shok',
    },
    {
        word: 'think',
        definition: 'To use your brain to have ideas.',
        exampleSentence: 'Let me think about the answer.',
        partOfSpeech: 'verb',
        difficulty: 2,
        pattern: 'digraphs',
        pronunciation: 'thingk',
        etymology: 'Old English',
    },
    {
        word: 'while',
        definition: 'A period of time.',
        exampleSentence: 'We waited for a while.',
        partOfSpeech: 'noun',
        difficulty: 2,
        pattern: 'digraphs',
        pronunciation: 'wyl',
    },
    {
        word: 'patch',
        definition: 'A small piece of cloth used to fix a hole.',
        exampleSentence: 'Mom sewed a patch on my jeans.',
        partOfSpeech: 'noun',
        difficulty: 2,
        pattern: 'digraphs',
        pronunciation: 'pach',
    },
    {
        word: 'chose',
        definition: 'Picked one thing from a group in the past.',
        exampleSentence: 'She chose the red crayon.',
        partOfSpeech: 'verb',
        difficulty: 2,
        pattern: 'digraphs',
        pronunciation: 'choze',
    },
    {
        word: 'shade',
        definition: 'A cool spot where the sun does not shine.',
        exampleSentence: 'We sat in the shade of the tree.',
        partOfSpeech: 'noun',
        difficulty: 2,
        pattern: 'digraphs',
        pronunciation: 'shayd',
    },
    {
        word: 'thud',
        definition: 'A heavy, dull sound.',
        exampleSentence: 'The book fell with a thud.',
        partOfSpeech: 'noun',
        difficulty: 2,
        pattern: 'digraphs',
        pronunciation: 'thud',
    },
    {
        word: 'whack',
        definition: 'To hit something hard.',
        exampleSentence: 'He gave the ball a big whack.',
        partOfSpeech: 'verb',
        difficulty: 2,
        pattern: 'digraphs',
        pronunciation: 'wak',
    },
    {
        word: 'ditch',
        definition: 'A long narrow hole dug along the side of a road.',
        exampleSentence: 'Water filled the ditch after the rain.',
        partOfSpeech: 'noun',
        difficulty: 2,
        pattern: 'digraphs',
        pronunciation: 'dich',
    },
    {
        word: 'churn',
        definition: 'To stir or shake something around and around.',
        exampleSentence: 'We watched them churn the butter.',
        partOfSpeech: 'verb',
        difficulty: 2,
        pattern: 'digraphs',
        pronunciation: 'churn',
    },
    {
        word: 'shove',
        definition: 'To push something hard.',
        exampleSentence: 'Do not shove your sister.',
        partOfSpeech: 'verb',
        difficulty: 2,
        pattern: 'digraphs',
        pronunciation: 'shuv',
    },
    {
        word: 'those',
        definition: 'A word used to point out things that are far away.',
        exampleSentence: 'Those shoes are too big for me.',
        partOfSpeech: 'pronoun',
        difficulty: 2,
        pattern: 'digraphs',
        pronunciation: 'thoze',
    },
    {
        word: 'whisk',
        definition: 'A tool used to stir eggs or cream.',
        exampleSentence: 'Use the whisk to mix the eggs.',
        partOfSpeech: 'noun',
        difficulty: 2,
        pattern: 'digraphs',
        pronunciation: 'wisk',
    },
    {
        word: 'bunch',
        definition: 'A group of things together.',
        exampleSentence: 'She picked a bunch of flowers.',
        partOfSpeech: 'noun',
        difficulty: 2,
        pattern: 'digraphs',
        pronunciation: 'bunch',
    },
    {
        word: 'chess',
        definition: 'A board game where you move pieces to win.',
        exampleSentence: 'We played a game of chess.',
        partOfSpeech: 'noun',
        difficulty: 2,
        pattern: 'digraphs',
        pronunciation: 'ches',
    },
    {
        word: 'shack',
        definition: 'A small, rough building.',
        exampleSentence: 'The old shack stood by the lake.',
        partOfSpeech: 'noun',
        difficulty: 2,
        pattern: 'digraphs',
        pronunciation: 'shak',
    },
    {
        word: 'theft',
        definition: 'The act of stealing something.',
        exampleSentence: 'The theft of the bike was reported.',
        partOfSpeech: 'noun',
        difficulty: 2,
        pattern: 'digraphs',
        pronunciation: 'theft',
    },
    {
        word: 'whiff',
        definition: 'A quick, light smell of something.',
        exampleSentence: 'I got a whiff of the cookies baking.',
        partOfSpeech: 'noun',
        difficulty: 2,
        pattern: 'digraphs',
        pronunciation: 'wif',
    },
    {
        word: 'with',
        definition: 'Together or alongside.',
        exampleSentence: 'Come play with me.',
        partOfSpeech: 'preposition',
        difficulty: 2,
        pattern: 'digraphs',
        pronunciation: 'with',
        etymology: 'Old English',
    },
    {
        word: 'then',
        definition: 'After that; next.',
        exampleSentence: 'We ate, and then we played.',
        partOfSpeech: 'adverb',
        difficulty: 2,
        pattern: 'digraphs',
        pronunciation: 'then',
    },
    {
        word: 'shut',
        definition: 'To close something.',
        exampleSentence: 'Please shut the door.',
        partOfSpeech: 'verb',
        difficulty: 2,
        pattern: 'digraphs',
        pronunciation: 'shut',
    },
    {
        word: 'thaw',
        definition: 'When ice or snow melts and becomes water.',
        exampleSentence: 'The snow will thaw in the spring.',
        partOfSpeech: 'verb',
        difficulty: 2,
        pattern: 'digraphs',
        pronunciation: 'thaw',
    },
    {
        word: 'rush',
        definition: 'To move very fast because you are in a hurry.',
        exampleSentence: 'We had to rush to catch the bus.',
        partOfSpeech: 'verb',
        difficulty: 2,
        pattern: 'digraphs',
        pronunciation: 'rush',
    },
    {
        word: 'shout',
        definition: 'To call out loudly.',
        exampleSentence: 'Do not shout in the library.',
        partOfSpeech: 'verb',
        difficulty: 2,
        pattern: 'digraphs',
        pronunciation: 'showt',
    },
];
