// Analyze natural theme clustering of all words based on definitions
var fs = require('fs');
var path = require('path');
var wordsDir = path.join(__dirname, '..', 'src', 'domains', 'spelling', 'words');
var files = ['tier1','tier2','tier3','tier4','tier5','tier5-scripps','tier5-state'];
var words = [];

for (var i = 0; i < files.length; i++) {
  var f = files[i];
  var content = fs.readFileSync(path.join(wordsDir, f + '.ts'), 'utf8');
  var lines = content.split('\n');
  var currentWord = null;
  var currentPos = null;
  for (var j = 0; j < lines.length; j++) {
    var wm = lines[j].match(/word:\s*'([^']+)'/);
    if (wm) currentWord = wm[1];
    var pm = lines[j].match(/partOfSpeech:\s*'([^']+)'/);
    if (pm) currentPos = pm[1];
    var dm = lines[j].match(/definition:\s*'(.+)'/);
    if (dm && currentWord) {
      words.push({ word: currentWord, def: dm[1], pos: currentPos || '', file: f });
      currentWord = null;
      currentPos = null;
    }
  }
}

console.log('Total words parsed: ' + words.length);

// Define theme matchers - order = priority (first match wins)
var themes = [
  ['animals', /\banimal|pet\b|creature|mammal|reptile|bird\b|birds\b|fish\b|insect|spider|snake|lizard|frog|toad\b|whale|shark|dolphin|elephant|monkey|wolf|wolves|bear\b|bears\b|deer\b|horse|donkey|chicken|duck\b|goose|geese|pig\b|pigs\b|cow\b|cows\b|sheep\b|goat\b|rabbit|mouse|mice\b|rat\b|bat\b|owl\b|eagle|hawk\b|parrot|turtle|tortoise|crab\b|lobster|butterfly|moth\b|beetle|ant\b|ants\b|bee\b|bees\b|worm|caterpillar|squid|octopus|lion|tiger|zebra|giraffe|penguin|seal\b.*animal|otter|beaver|squirrel|porcupine|rhino|hippo|chimp|gorilla|dinosaur|pterodactyl|puppy|kitten|calf\b|cub\b|foal|lamb\b|chick\b|hatchling|zoo\b|herd\b|flock|pack\b.*animal|nest\b.*bird|burrow|den\b.*animal|kennel|stable\b.*horse|aquarium|wildlife|predator|prey\b|carnivore|herbivore|omnivore|canine|feline|equine|bovine|porcine|avian|primate|arachnid|crustacean|mollusk|amphibian|nocturnal\b.*animal|venomous|staphylococc|streptococc/i],
  ['plants', /\bplant\b|plants\b|tree\b|trees\b|flower|grass\b|leaf\b|leaves\b|seed\b|seeds\b|root\b.*plant|garden|vine\b|bush\b|shrub|herb\b|moss\b|fern\b|weed\b|bloom|blossom|petal|branch\b.*tree|trunk\b.*tree|bark\b.*tree|lumber|timber|forest|orchid|chrysanthemum|botanical|pollen|photosynthesis|chlorophyll|vegetation|foliage|evergreen|deciduous|conifer|oak\b|maple|pine\b|willow|birch|cedar|elm\b|sprout|sapling|acorn|mushroom|fungus|fungi|lichen|algae|seaweed|rose\b|tulip|daisy|lily\b|sunflower|lavender|jasmine|carnation|dandelion|clover|ivy\b|bamboo|cactus|palm\b.*tree|coconut\b.*tree|flora\b/i],
  ['weather', /\bweather|rain\b|rains\b|rainy|snow\b|snowy|storm|wind\b|winds\b|windy|cloud\b|clouds\b|cloudy|thunder|lightning|fog\b|foggy|frost\b|frosty|hail\b|tornado|hurricane|typhoon|cyclone|rainbow|sunshine|sunny|climate|drought|flood\b|temperature|humid|breeze|gust\b|blizzard|monsoon|overcast|drizzle|sleet|icicle|avalanche|meteorolog/i],
  ['earth', /\bearth\b.*planet|rock\b|rocks\b|stone\b|stones\b|mountain|volcano|earthquake|mineral|crystal|fossil\b|cave\b|canyon|cliff\b|valley|river\b|lake\b|ocean|sea\b.*water|island\b|peninsula|glacier|desert\b|soil\b|sand\b|mud\b|dirt\b|continent|terrain|geology|geograph|landform|plateau|mesa\b|gorge\b|ravine|crater|geyser|stalactite|stalagmite|erosion|sediment|limestone|granite|marble\b.*stone|quartz|lava\b|magma|tectonic|coral\b.*reef|reef\b|tide\b|wave\b.*ocean|shore\b|beach\b|coast\b|bay\b|cove\b|lagoon|marsh\b|swamp|wetland|delta\b.*river|estuary|waterfall|spring\b.*water|creek\b|stream\b.*water|pond\b|brook\b|tributary/i],
  ['food', /\bfood\b|eat\b|eaten|cook\b|cooking|bake\b|baking|meal\b|fruit\b|vegetable|meat\b|bread\b|cheese|sugar\b|salt\b.*food|salt\b.*season|spice\b|flavor|taste\b|tasting|recipe|ingredient|delicious|appetite|grain\b|cereal|soup\b|stew\b|sauce\b|pastry|dessert|candy\b|chocolate|butter\b|milk\b|juice\b|tea\b.*drink|coffee|wine\b|beer\b|feast|banquet|snack|breakfast|lunch\b|dinner|supper|dine\b|dining|grill\b.*cook|roast\b|fry\b.*cook|boil\b.*cook|simmer|broth|dough|flour\b|yeast|cinnamon|vanilla|pepper\b.*spice|garlic|onion|potato|tomato|lettuce|carrot|celery|corn\b.*food|rice\b|pasta|noodle|pizza|sandwich|burger|taco|sushi|pie\b|cake\b|cookie|muffin|pancake|waffle|donut|ice cream|yogurt|honey\b|syrup|vinegar|mustard|ketchup|mayonnaise|olive\b.*food|nut\b.*food|berry|apple|banana|orange\b.*fruit|grape|lemon|lime\b.*fruit|peach|pear\b|plum\b|cherry|strawberry|blueberry|raspberry|melon|mango|pineapple|coconut\b.*fruit|avocado|cantaloupe|nutrition|vitamin|calorie|protein\b.*food|carbohydrate|fiber\b.*food|diet\b.*food|organic\b.*food|harvest\b.*crop|edible|culinary|gourmet|savory|bitter\b.*taste|sweet\b.*taste|sour\b.*taste|spicy|bland\b/i],
  ['body', /\bbody\b|organ\b|muscle|bone\b|bones\b|blood\b|heart\b.*body|brain\b|lung\b|lungs\b|liver\b|kidney|stomach\b|skin\b.*body|tooth\b|teeth\b|eye\b.*body|ear\b.*body|nose\b.*body|mouth\b|hand\b.*body|foot\b.*body|feet\b.*body|arm\b.*body|leg\b.*body|head\b.*body|neck\b|shoulder|finger|thumb\b|toe\b|knee\b|elbow|wrist\b|ankle\b|chest\b.*body|rib\b|spine\b|skull\b|jaw\b|lip\b|tongue\b|throat\b|vein\b|artery|nerve\b|cell\b.*biolog|tissue\b.*body|hair\b.*body|nail\b.*body|skeleton|anatomy|limb\b|torso|abdomen|pelvis|hip\b.*body|thigh|calf\b.*leg|shin\b|heel\b|palm\b.*hand|knuckle|eyelash|eyebrow|nostril|cheek\b.*face|chin\b|forehead|temple\b.*head|scalp|diaphragm|tendon|ligament|cartilage|joint\b.*body|gland|pupil\b.*eye|iris\b.*eye|retina|cornea|eardrum|tonsil|appendix\b.*body|intestine|colon\b.*body|esophagus|trachea|larynx|pharynx/i],
  ['health', /\bhealth|medical|medicine|disease|illness|infect|symptom|cure\b|treat\b.*medical|diagnos|prescri|surgery|surgeon|hospital|doctor\b|nurse\b.*medical|patient\b.*medical|wound\b|injury|fever\b|cough\b.*sick|sneeze|ache\b|pain\b.*body|bleed|swell\b.*body|itch\b|rash\b|scar\b|heal\b|drug\b.*medic|pill\b|vaccine|therapy|remedy|ailment|disorder|syndrome|chronic|acute\b.*medical|contagious|epidemic|pandemic|antibiotic|antiseptic|bandage|cast\b.*broken|splint|crutch|wheelchair|ambulance|emergency\b.*medical|paramedic|pharmacy|pharmacist|pharmaceutical|eczema|diphtheria|hemorrhage|asthma|allergy|diabetes|cancer\b|tumor|malaria|plague|measles|mumps|smallpox|cholera|typhoid|pneumonia|bronchitis|arthritis|osteoporosis|anemia|insomnia|nausea|vertigo|seizure|stroke\b.*medical|cardiac|respiratory|immune|antibod|patholog|tachycardia|psoriasis|stethoscope|scalpel|syringe|thermometer\b.*body/i],
  ['home', /\bhouse\b|home\b|room\b|door\b|window\b|wall\b.*build|floor\b|roof\b|ceiling|stair|basement|attic\b|garage\b|porch\b|fence\b|gate\b.*yard|yard\b|furniture|chair\b|table\b|desk\b|bed\b.*sleep|sofa\b|couch\b|shelf\b|shelves|drawer|cabinet|closet|wardrobe\b.*furniture|lamp\b|carpet\b|rug\b.*floor|curtain|drape\b|pillow\b|blanket\b|towel\b|mirror\b|clock\b|vase\b|pot\b.*cook|pan\b.*cook|cup\b.*drink|plate\b.*dish|bowl\b.*dish|fork\b|spoon\b|knife\b.*cut|container\b|bucket\b|basket\b|box\b|jar\b|lid\b|broom\b|mop\b|vacuum\b|appliance|oven\b|stove\b|refrigerator|dishwasher|washer\b|dryer\b|sink\b|faucet|bathtub|shower\b.*bath|toilet|plumbing|fireplace|chimney|balcony|hallway|corridor|foyer|lobby|patio|deck\b.*house|terrace|candle\b|chandelier|doorbell|doorknob|keyhole|hinge\b|latch\b|lock\b.*door|bolt\b.*door|nail\b.*hammer|screw\b.*tool|hammer\b|wrench|screwdriver|pliers|saw\b.*tool|drill\b.*tool|tape\b.*measure|ladder|toolbox|domestic/i],
  ['clothing', /\bcloth\b|clothes|clothing|wear\b.*body|garment|dress\b.*cloth|shirt|blouse|pants\b|trousers|jeans|skirt\b|coat\b.*wear|jacket\b|hat\b|cap\b.*wear|shoe\b|shoes\b|boot\b.*wear|sock\b|socks\b|glove\b|gloves\b|scarf\b|belt\b.*wear|button\b.*cloth|zipper|pocket\b|sleeve\b|collar\b.*shirt|fabric\b|cotton\b|silk\b|wool\b|linen\b|leather\b.*material|lace\b.*fabric|sew\b|sewing|stitch\b.*sew|thread\b.*sew|needle\b.*sew|knit\b|weave\b.*fabric|tailor\b|fashion\b|attire|wardrobe\b.*cloth|costume\b|uniform\b|outfit\b|vest\b|robe\b|cape\b.*wear|apron\b|helmet\b|ribbon\b|accessory\b.*wear|jewelry|necklace|bracelet|ring\b.*wear|earring|brooch|pendant|tiara|crown\b.*wear|tie\b.*wear|bow\b.*tie|suspender|overall|sweater|hoodie|raincoat|umbrella|sunglasses|mitten|sandal|slipper|sneaker|heel\b.*shoe|sole\b.*shoe|lace\b.*shoe|bootie|bonnet|veil\b|gown\b|tuxedo|corsage|boutonniere|decolletage|chiffon|taffeta|velvet|satin|denim|flannel|tweed|cashmere|embroid|crochet|textile/i],
  ['music', /\bmusic|musical|sing\b|singer|singing|song\b|songs\b|dance\b|dancer|dancing|melody|rhythm|harmony|harmonious|instrument\b|piano\b|guitar\b|drum\b|drums\b|violin\b|viola\b|cello\b|flute\b|trumpet\b|trombone|saxophone|clarinet|oboe\b|harp\b|organ\b.*music|banjo|ukulele|accordion|harmonica|tambourine|cymbal|xylophone|orchestra|band\b.*music|concert\b|choir\b|chorus|opera\b|symphony\b|compose\b|composer|conductor\b.*music|note\b.*music|tune\b|chord\b|lyric|hymn\b|anthem|ballad|lullaby|serenade|sonata|concerto|overture|aria\b|duet\b|solo\b.*music|quartet|ensemble|tempo|crescendo|forte\b|staccato|legato|allegro|adagio|appoggiatura|leitmotif|diapason|terpsichorean/i],
  ['art', /\bart\b|arts\b|artist|artistic|paint\b|painter|painting|draw\b.*picture|drawing|sketch\b|sculpt|sculpture|canvas\b|gallery\b|museum\b|portrait\b|photograph\b|photography|creative\b.*art|masterpiece|aesthetic|mural|mosaic|collage|pottery|ceramic|carving|engraving|illustration|calligraphy|graffiti|fresco|tapestry|lithograph|etching|watercolor|oil\b.*paint|acrylic|pigment|palette\b|easel|brush\b.*paint|chisel\b|marble\b.*sculpt|bronze\b.*sculpt|statue\b|bust\b.*sculpt|figurine|ornament\b.*decorat|beautiful\b.*creat|design\b.*visual|chiaroscurist|daguerreotype|rococo|filigree|trompe/i],
  ['performance', /\btheater|theatre|stage\b.*perform|actor\b|actress|perform\b|performance|drama\b|dramatic|comedy\b|tragic|tragedy|entertain|puppet|cinema|film\b|movie|direct\b.*film|produc\b.*film|screen\b.*film|script\b.*play|playwright|scene\b.*play|act\b.*play|role\b.*play|cast\b.*play|audience|curtain\b.*stage|spotlight|rehearsal|audition|improvise|monologue|dialogue|pantomime|vaudeville|burlesque|cabaret|recital|spectacle\b.*perform|masquerade|ventriloquist/i],
  ['sports', /\bsport|athletic|exercise|workout|game\b.*play|team\b.*play|score\b.*game|goal\b.*game|race\b.*compet|swim\b|swimmer|swimming|jump\b.*athlet|throw\b.*ball|kick\b.*ball|catch\b.*ball|hit\b.*ball|bat\b.*ball|pitch\b.*ball|field\b.*sport|court\b.*sport|gym\b|trophy\b|champion|compete|competition|tournament|match\b.*compet|wrestler|wrestling|boxing|boxer|martial|soccer|football|baseball|basketball|tennis|golf\b|golfer|hockey|volleyball|cricket\b.*sport|rugby|skating|skater|skiing|skier|surfing|surfer|cycling|cyclist|archery|archer|fencing|fencer|gymnast|marathon|sprint|relay\b.*race|hurdle|javelin|discus|shotput|decathlon|triathlon|olymp|medal\b.*sport|referee|umpire|coach\b.*sport|stadium|arena\b|rink\b|track\b.*race|lane\b.*swim|pool\b.*swim|net\b.*sport|racket|paddle\b.*sport|puck\b|goalkeeper|quarterback|pitcher\b.*base|dribble|tackle\b.*sport|punt\b|serve\b.*tennis|volley|slam\b.*sport|dunk\b|homerun|touchdown|inning|halftime|overtime|playoff|championship|league\b.*sport/i],
  ['science', /\bscien|chemi|physic\b|physicist|biolog|experiment|laboratory|microscop|telescop|molecule|atom\b|atoms\b|element\b.*chemi|compound\b.*chemi|reaction\b.*chemi|energy\b.*physic|electric|magnet\b|gravity|force\b.*physic|mass\b.*physic|velocity|acceleration|frequency|wavelength|spectrum|radiation|nuclear|quantum|genome|chromosome|evolution\b|ecosystem|organism|photosynthesis|bacteria\b|virus\b.*biolog|DNA\b|protein\b.*biolog|enzyme\b|geolog\b|astrono|planet\b|star\b.*space|galaxy|orbit\b|satellite|technology|robot\b|circuit\b|laser\b|radar\b|hypothesis|theorem|phenomenon|entropy|kinetic|thermal|celsius|fahrenheit|barometer|seismograph|centrifuge|catalyst|isotope|ion\b|electron|neutron|proton|quark|neutrino|supernova|nebula|comet\b|asteroid|meteor|eclipse\b|solstice|equinox|longitude|latitude|cartography|topography|geodesic|chromatic|ergodic|iatrogenic/i],
  ['math', /\bmath|number\b|count\b.*math|add\b.*math|subtract|multiply|divide\b.*math|equation|formula\b|calculate|geometry|angle\b.*math|triangle|circle\b.*shape|square\b.*shape|rectangle|polygon|hexagon|pentagon|octagon|diameter|radius|circumference|area\b.*math|volume\b.*math|fraction|decimal|percent|ratio|proportion|algebra|graph\b.*math|statistic|probability|measure\b.*math|metric|symmetry|parallel|perpendicular|hypotenuse|theorem\b|axiom|logarithm|exponent|coefficient|variable\b.*math|constant\b.*math|integer|prime\b.*number|factorial|fibonacci|algorithm|binary\b.*math|vector|matrix\b.*math|calculus|differential|integral\b.*math|infinity|palindrom/i],
  ['money', /\bmoney|pay\b|payment|paid\b|cost\b|price\b|buy\b|buying|sell\b|selling|purchase|trade\b.*goods|market\b|store\b.*shop|shop\b|business|company|industry|factory|manufacture|economy|economic|financial|finance|bank\b.*money|loan\b|debt\b|invest|profit\b|loss\b.*money|tax\b|budget\b|salary|wage\b|income\b|wealth|currency|coin\b.*money|dollar|merchant|commerce|commercial|auction|bargain|discount\b|receipt\b|bill\b.*pay|account\b.*money|stock\b.*market|bond\b.*financ|dividend|interest\b.*money|mortgage|insurance|pension|bankrupt|inflation|deflation|recession|surplus|deficit|revenue|expenditure|asset|liability|equity\b.*financ|portfolio|broker|entrepreneur|franchise|monopoly|subsidy|tariff|import\b.*trade|export\b.*trade|wholesale|retail|pecuniary|remuneration|emolument|peculate|malfeasant|usurious/i],
  ['language', /\bword\b|words\b|language|lingu|speak\b.*language|speech\b|pronunciation|pronounc|accent\b.*speak|dialect|translat|interpret\b.*language|vocabulary|grammar|syntax|sentence\b.*grammar|paragraph|essay\b|poem\b|poetry|poet\b|novel\b.*book|book\b.*read|read\b.*book|write\b.*text|writing|written\b|author\b|story\b.*tell|narrative|fiction\b|literary|literature|letter\b.*alphabet|alphabet|spell\b.*word|rhetoric|rhetorical|eloquen|synonym|antonym|metaphor|simile|irony\b|satire|satiric|prose\b|verse\b.*poem|manuscript|journal\b.*writ|diary\b|newspaper|magazine|publish|editor\b|library\b|dictionary|encyclopedia|thesaurus|etymology\b|onomatopoeia|tautolog|pleonasm|solecism|malapropism|neologism|colloqui|vernacular|lexicon|philolog|semantics|morpheme|phoneme|syllable|consonant|vowel\b.*sound|prefix\b.*word|suffix\b.*word|abbreviation|acronym|homonym|homophone|palindrome|anagram|epigram|epithet|euphemism|hyperbole|litotes|oxymoron|synecdoche|metonymy|alliteration|assonance|consonance|onomatopoeia|bibliophile|logodaedaly|hapax|prolegomenon|recherche|toponym|tmetic|nonfiction/i],
  ['time', /\btime\b.*concept|hour\b|minute\b.*time|second\b.*time|day\b.*time|week\b|month\b|year\b|decade\b|century\b|millennium|era\b|epoch\b|period\b.*history|age\b.*history|ancient\b|medieval|history\b|historic|past\b.*time|future\b|calendar\b|schedule\b|deadline|annual\b|daily\b|weekly|monthly|season\b|spring\b.*season|summer\b.*season|autumn|winter\b.*season|dawn\b|dusk\b|sunrise|sunset|midnight|noon\b|morning\b.*time|evening\b.*time|temporary|permanent|eternal|immortal|antique\b|vintage|archaic|obsolete|contemporary|modern\b.*time|primordial|prehistoric|dynasty|genealogy|chronolog|anachronism|antediluvian|nostalgia|posterity|precedent|prognosis|retrospect/i],
  ['people', /\bperson\b|people\b|human\b|man\b.*person|woman\b|child\b|children|baby\b|infant|toddler|boy\b|girl\b|teenager|adolescent|adult\b|elder\b|family\b|parent\b|mother\b|father\b|sister\b|brother\b|son\b.*family|daughter\b|uncle\b|aunt\b|cousin\b|grandparent|grandmother|grandfather|husband\b|wife\b|spouse|friend\b|neighbor\b|stranger\b|acquaintance|colleague|companion|ally\b|rival\b|enemy\b|opponent|king\b|queen\b|prince\b|princess\b|knight\b|soldier\b|warrior\b|chief\b|leader\b|ruler\b|governor\b|gubernatorial|president\b|mayor\b|judge\b.*law|lawyer\b|attorney|officer\b|captain\b|general\b.*military|doctor\b.*profess|teacher\b|professor\b|student\b|scholar\b|worker\b|farmer\b|carpenter\b|plumber\b|electrician\b|mechanic\b|pilot\b|sailor\b|firefighter|police\b|detective\b|spy\b|thief\b|criminal\b|prisoner\b|servant\b|citizen\b|immigrant|refugee|veteran\b|volunteer\b|celebrity|aristocrat|peasant|clergy|monk\b|nun\b|priest|bishop|pope\b|ambassador|diplomat|secretary\b.*state|senator|congressman|bureaucrat|philanthropist|misanthrope|sycophant|raconteur|dilettante|connoisseur|proletariat|bourgeoisie|cognoscente|curmudgeon|demagogue|iconoclast|polyglot|virtuoso|charlatan|martyr|heretic|oracle|sage\b.*person|mentor|apprentice|protege|disciple|patriarch|matriarch|monarch|tyrant|dictator|czar|sultan|samurai|gladiator|centurion|legionnaire|myrmidon/i],
  ['feelings', /\bfeel\b|feeling|emotion|emotional|happy\b|happiness|glad\b|sad\b|sadness|angry\b|anger\b|rage\b.*emotion|fury\b.*emotion|fear\b|afraid|scared|frighten|worry\b|worried|anxious|anxiety|nervous\b.*feel|stress\b.*feel|excite|excitement|joy\b|joyful|joyous|love\b.*feel|affection|hate\b|hatred|jealous|jealousy|envy\b|envious|proud\b.*feel|pride\b.*feel|shame\b|ashamed|guilt\b|guilty|embarrass|lonely\b|loneliness|bored\b|boredom|curious\b.*feel|curiosity|surprise\b.*feel|shock\b.*feel|disgust|hope\b.*feel|hopeful|hopeless|despair|grief\b|mourn|mourning|sorrow|sorrowful|delight|cheerful|gloomy|gloom|miserable|misery|content\b.*feel|satisfy|disappoint|frustrat|confus\b.*feel|overwhelm|calm\b.*feel|peaceful|peace\b.*feel|serene|serenity|panic\b|terror\b|horror\b|dread\b|courage|courageous|brave\b.*feel|timid|shy\b.*feel|confident|confidence|insecure|insecurity|grateful|thankful|gratitude|compassion|sympathy|empathy|pity\b|remorse|regret|resent|resentment|contempt|disdain|admiration|adore|adoration|fondness|tenderness|warmth\b.*feel|melancholy|wistful|nostalgic|euphoria|ecstasy|bliss|agony|anguish|torment\b.*feel|indifference|apathy|ambivalence|trepidation|consternation|chagrin|ennui|malaise|schadenfreude|sangfroid|insouciance|nonchalant|ebullient|effervescent\b.*enthusias|exuberant|vivacious|morose|doleful|lugubrious|lachrymose|querulous|petulant|sullen|truculent|bellicose|belligerent|acrimonious|vitriolic|caustic\b.*manner/i],
  ['mind', /\bthink\b|thinking|thought\b.*mind|idea\b|concept\b|mind\b.*think|intellig|smart\b|clever\b|wise\b|wisdom\b|knowledge\b|learn\b.*know|study\b.*academ|understand|comprehend|comprehension|reason\b.*think|logic\b|logical|rational|believe\b|belief|opinion\b|theory\b|hypothesis|conclusion\b|decision\b|choose\b.*think|judgment\b|evaluate|analyz|examine\b.*think|consider\b.*think|reflect\b.*think|ponder|contemplate|imagine\b|imagination|creative\b.*think|invent\b.*idea|memory\b|remember\b|forget\b|recognize\b|perceive\b|perception|aware\b|awareness|conscious\b|subconscious|philosophy|philosophical|psychology|psychological|mental\b|cognitive|insight\b|intuition|genius\b|ignorant|ignorance|foolish\b|naive\b|skeptic|doubt\b.*think|confus\b.*mind|puzzle\b.*think|mystery\b|enigma|paradox\b|dilemma\b|strategy|solve\b|solution|problem\b.*solv|deliberate\b.*think|discern|scrutin|astute|perspicac|sagac|erudite|esoteric|recondite|pedantic|didactic|pedagog|propaedeutic|epistem|ontolog|dialectic|syllogism|sophist|empiric|pragmatic|dogmatic|ideolog|doctrine|tenet|axiom\b.*logic|premise|postulate|corollary|theorem\b.*logic|conjecture|speculate|ruminate|cogitate|cerebral|sapient|prescient|clairvoyant|omniscient|oblivious|obtuse\b.*stupid|vacuous|fatuous|inane|asinine|sophomoric/i],
  ['character', /\bhonest|dishonest|loyal\b|loyalty|betray|faithful|unfaithful|generous|generosity|selfish|greedy|greed|humble\b|humility|arrogant|arrogance|modest\b|modesty|vain\b.*character|vanity|patient\b.*character|patience\b.*character|impatient|stubborn|obstinate|tenacious|persistent|determined|determined|lazy\b|diligent|industrious|ambitious|ambitious|coward|cowardly|heroic|valiant|noble\b.*character|villain|wicked|evil\b|cruel\b|cruelty|kind\b.*character|kindness|gentle\b.*character|harsh\b|ruthless|merciless|merciful|forgiving|vengeful|vindictive|spiteful|malicious|malevolent|benevolent|virtuous|righteous|devout|pious|sinful|immoral|ethical|unethical|corrupt\b|integrity|honor\b|dignity|respect\b.*character|disrespect|courteous|rude\b|polite|impolite|gracious|insolent|impudent|audacious\b.*bold|brazen|meek\b|docile|submissive|defiant|rebellious|obedient|disobedient|reliable|unreliable|trustworthy|deceitful|cunning\b|devious|scrupulous|unscrupulous|conscientious\b.*careful|negligent|careless|meticulous|fastidious|punctilious|cavalier\b.*attitude|nonchalant\b.*attitude|indifferent\b.*attitude|zealous|fervent|ardent|lukewarm\b.*attitude|apathetic\b.*character|stoic|ascetic|hedonist|sybarite|Machiavellian|quixotic|supercilious|obsequious|sycophantic|pusillanimous|magnanimous|imperious|haughty|condescending|patronizing|sanctimonious|hypocritical|duplicitous|perfidious|treacherous|insidious|nefarious|heinous|reprehensible|deplorable|exemplary|admirable|commendable|laudable|praiseworthy|reprobate|profligate|dissolute|licentious|abstemious|temperate|intemperate|prodigal|parsimonious|miserly|munificent|philanthropic|altruistic|egocentric|narcissistic|solipsism/i],
  ['communication', /\bspeak\b.*person|talk\b.*person|tell\b.*person|say\b.*to|convers\b|discuss|debate\b|argue\b.*speak|argument\b.*speak|persuade|convince|negotiate|agree\b|disagree|promise\b|vow\b|swear\b|oath\b|pledge\b|announce|declare|proclaim|exclaim|whisper|shout\b|yell\b|scream\b|mumble|murmur|stammer|stutter|chat\b|gossip|rumor|complain|protest\b.*voice|praise\b.*speak|criticize|compliment|insult\b|mock\b|ridicule|tease\b|taunt\b|bully\b|threaten\b|warn\b|advise\b|suggest\b|recommend|command\b|order\b.*speak|request\b|demand\b|beg\b|plead\b|implore|beseech|apologize|confess\b|admit\b|deny\b|lie\b.*untruth|exaggerat|boast\b|brag\b|flatter|preach\b|lecture\b.*speak|rant\b|rave\b|ramble\b|babble|blurt\b|garrulous|loquacious|verbose|taciturn|reticent|laconic|terse\b|succinct|eloquent|articulate\b.*speak|fluent\b|inarticulate|prevaricate|equivocate|dissembl|obfuscate|circumlocution|euphemism\b.*speak|innuendo|insinuate|allude|imply\b|infer\b|connote|denote|vociferous|stentorian|mellifluous|sonorous/i],
  ['nature', /\bnature\b|natural\b|environment|habitat|wilderness|wild\b.*nature|outdoor|landscape|scenery|pond\b|meadow|prairie|field\b.*nature|jungle|rainforest|woodland|grove\b|oasis|horizon|aurora\b|constellation\b|moon\b.*sky|star\b.*sky|sunset|sunrise|twilight|ecology|biome|tundra|savanna|steppe|taiga|ecosystem\b.*nature|biodiversity|conservation|endangered|extinct\b.*species|migrate|migration|hibernate|pollinate|symbiosis|parasite|predator\b.*nature|camouflage\b.*nature/i],
  ['actions', /\brun\b.*move|walk\b|jump\b|climb\b|crawl\b|slide\b|swing\b|push\b|pull\b|lift\b|carry\b|hold\b|grab\b|reach\b|stretch|bend\b|twist\b|turn\b.*move|spin\b|roll\b|bounce\b|skip\b.*move|gallop|trot\b|march\b|stomp|shuffle|stumble|trip\b.*fall|fall\b.*down|collapse|crash\b|smash\b|break\b.*apart|tear\b.*apart|rip\b|cut\b.*pieces|chop\b|slice\b|carve\b|scrape|scratch|dig\b.*hole|pour\b|spill\b|splash\b|spray\b|squirt|squeeze\b|crush\b|press\b|pound\b|hammer\b.*hit|knock\b|tap\b.*hit|slap\b|punch\b|clap\b|snap\b.*fingers|wave\b.*hand|point\b.*finger|nod\b|shake\b.*head|shrug\b|bow\b.*greet|kneel\b|crouch|duck\b.*avoid|dodge\b|flee\b|chase\b|escape\b|hide\b|seek\b|search\b|explore\b.*place|wander|roam\b|stroll\b|hike\b|trek\b|drift\b|float\b|sink\b|dive\b|drown\b|rescue\b|save\b.*danger|protect\b|defend\b|attack\b|fight\b|battle\b|struggle|resist\b|surrender|retreat|advance\b|charge\b.*attack|invade|conquer|capture|release\b|free\b.*captiv|imprison|arrest\b|detain/i],
  ['building', /\bbuild\b|building\b|construct\b|architecture|architect\b|structure\b.*build|tower\b|castle\b|palace\b|fortress|temple\b.*build|church\b|cathedral|mosque\b|synagogue|monument|memorial\b.*build|statue\b.*public|column\b.*build|pillar\b|arch\b.*build|dome\b|spire\b|turret|rampart|battlement|parapet|drawbridge|moat\b|courtyard|plaza\b|square\b.*public|fountain\b|amphitheater|colosseum|pyramid|obelisk|pagoda|minaret|lighthouse|windmill|barn\b|warehouse|skyscraper|bridge\b.*build|dam\b.*build|canal\b|aqueduct|pier\b|dock\b|wharf|edifice|facade|cornerstone|foundation\b.*build|scaffold|blueprint|mason|carpenter\b.*build|plaster|mortar\b.*build|brick\b|concrete|steel\b.*build|beam\b.*build|girder|truss|buttress|colonnade|portico|vestibule|rotunda|nave\b|transept|apse\b|cloister|peristyle/i],
  ['law', /\blaw\b|legal\b|court\b.*law|trial\b|jury\b|verdict\b|sentence\b.*law|guilty\b.*law|innocent\b.*law|crime\b|criminal\b.*law|felony|misdemeanor|offense\b|violat\b.*law|arrest\b.*law|prosecut|defend\b.*law|attorney|lawyer\b|barrister|solicitor|magistrate|judge\b.*law|justice\b.*law|constitution|amendment|statute|legislation|regulation|ordinance|decree|mandate|injunction|subpoena|warrant\b|bail\b|parole|probation|incarcerat|imprison|penitentiary|lawsuit|litigation|plaintiff|defendant|witness\b.*court|testimony|evidence\b|exhibit\b.*court|objection|sustain\b.*court|overrule|appeal\b.*law|acquit|convict\b|indict|arraign|plea\b|settlement\b.*law|contract\b|clause\b|provision\b.*law|liability|negligence\b.*law|tort\b|jurisprudence|precedent\b.*law|habeas|extradition|amnesty|pardon\b|clemency|sovereign|jurisdiction|emancipat/i],
  ['war', /\bwar\b|warfare|battle\b.*war|army\b|military\b|navy\b|weapon\b|sword\b|shield\b|armor\b|cannon\b|bomb\b|missile\b|rifle\b|gun\b|ammunition|siege\b|invasion|retreat\b.*war|victory\b.*war|defeat\b.*war|surrender\b.*war|truce\b|ceasefire|alliance\b.*war|enemy\b.*war|combat\b|guerrilla|infantry|cavalry|fleet\b.*navy|battalion|regiment|brigade|division\b.*military|platoon|squadron|garrison|barracks|fortress\b.*war|bunker|trench\b.*war|campaign\b.*military|strategy\b.*war|tactics\b.*war|reconnaissance|espionage|sabotage|ambush|patrol|sentry|mercenary|conscript|draft\b.*military/i],
  ['color', /\bcolor\b|colour|red\b.*color|blue\b.*color|green\b.*color|yellow\b.*color|orange\b.*color|purple\b.*color|pink\b.*color|black\b.*color|white\b.*color|brown\b.*color|gray\b.*color|grey\b.*color|golden\b|silver\b.*color|bright\b.*color|dark\b.*color|pale\b.*color|vivid|vibrant\b.*color|hue\b|shade\b.*color|tint\b|pigment|dye\b|stain\b.*color|iridescent|luminous|opaque|translucent|transparent|psychedelic|chromatic/i],
  ['light', /\blight\b.*illumin|dark\b.*absence|bright\b.*light|dim\b|glow\b|shine\b|sparkle|glitter|shimmer|gleam|glimmer|flash\b.*light|flicker|radiant|luminous\b.*light|illuminate|illuminat|shadow\b|silhouette|reflect\b.*light|refract|prism\b|beam\b.*light|ray\b.*light|spotlight\b|lantern\b|torch\b|candle\b.*light|lamp\b.*light|beacon\b|phosphorescent|fluorescent|bioluminescen|incandescent|dazzle|blind\b.*light|eclipse\b.*light|dawn\b.*light|twilight\b.*light/i],
  ['sound', /\bsound\b|noise\b|loud\b|quiet\b.*sound|silent\b|silence\b|hear\b|listen\b|echo\b|ring\b.*sound|buzz\b|hum\b.*sound|whistle\b|click\b.*sound|clang|crash\b.*sound|bang\b|boom\b|roar\b|howl\b|growl\b|bark\b.*sound|chirp|tweet\b.*bird|squeak|squeal|screech|rumble|thunder\b.*sound|rustle|crackle|sizzle|pop\b.*sound|snap\b.*sound|crack\b.*sound|splash\b.*sound|drip\b.*sound|trickle\b.*sound|murmur\b.*sound|whisper\b.*sound|acoustic|resonance|vibrat\b.*sound|pitch\b.*sound|tone\b.*sound|volume\b.*sound|amplify|mute\b|deaf\b|tinnitus|cacophony|dissonance|euphony|sonorous\b.*sound|mellifluous\b.*sound|stridulat|tintinnabulation|onomatopoeia\b.*sound/i],
  ['tools', /\btool\b|instrument\b.*tool|device\b|machine\b|equipment|apparatus|gadget|implement\b.*tool|utensil|appliance\b.*tool|mechanism|lever\b|pulley|gear\b|wheel\b.*mechan|axle\b|spring\b.*mechan|piston|valve\b|pump\b|engine\b|motor\b|generator\b.*power|turbine|conveyor|crane\b.*machine|forklift|tractor|plow\b|harrow|sickle|scythe|anvil\b|bellows|kiln\b|loom\b|spindle|compass\b.*tool|sextant|protractor|caliper|gauge\b|wrench\b|pliers\b|clamp\b|vice\b.*tool|chisel\b.*tool|file\b.*tool|rasp\b|plane\b.*tool|lathe\b|drill\b.*tool|bit\b.*drill|awl\b|gimlet|auger|stethoscope\b.*tool|scalpel\b.*tool/i],
  ['power', /\bpower\b.*authority|authority|control\b.*power|rule\b.*govern|govern\b|government|politic|republic|democracy|monarch|aristocra|oligarch|theocracy|autocra|tyrann|dictator\b.*rule|regime|parliament|congress|senate|legislat|executive\b.*govern|judicial\b|supreme\b.*court|election\b|vote\b|ballot|campaign\b.*polit|party\b.*polit|liberal|conservative|radical\b.*polit|revolution|reform\b|abolish|sovereignty|dominion|empire|colony|imperial|colonial|annex|secede|federation|confederation|constitution\b.*govern|amendment\b.*govern|veto\b|ratify|sanction\b|embargo|treaty|diplomacy|ambassador\b.*politic|hegemony/i],
  ['movement', /\bmovement\b|move\b.*direct|motion\b|speed\b|fast\b.*move|slow\b.*move|rapid\b|swift\b|flee\b|rush\b|hurry\b|hasten|accelerat|decelerat|momentum|inertia|velocity\b.*move|trajectory|orbit\b.*move|revolve|rotate|spiral|oscillat|vibrat\b.*move|undulat|fluctuat|circulate|flow\b.*move|current\b.*flow|drift\b.*move|glide\b|soar\b|hover\b|descend|ascend|rise\b.*up|sink\b.*down|plunge|plummet|surge|recede|advance\b.*move|retreat\b.*move|migrate\b.*move|disperse|converge|diverge|meander|zigzag|peripatetic/i],
  ['quantity', /\bmany\b|few\b|much\b|little\b.*amount|some\b.*amount|all\b.*every|none\b|nothing|everything|enough|plenty|abundant|scarce|rare\b.*uncommon|common\b|frequent|seldom|always\b|never\b|often\b|sometimes|usually\b|rarely|vast\b|enormous|huge\b|tiny\b|small\b.*size|large\b.*size|big\b.*size|giant\b|miniature|massive|immense|colossal|microscopic|infinite|finite|maximum|minimum|excess|surplus|deficit|shortage|overflow|empty\b|full\b.*contain|whole\b|partial|complete\b|incomplete|total\b|entire|half\b|quarter|double|triple|multiple|single\b|pair\b|couple|dozen|hundred|thousand|million|billion|myriad|innumerable|copious|profuse|scant|meager|sparse|dense\b|thick\b.*dense|thin\b.*sparse|plethora|dearth|paucity|surfeit|plentiful|ubiquitous\b.*everywhere/i],
  ['texture', /\bsmooth\b|rough\b|soft\b|hard\b.*surface|sharp\b|dull\b.*edge|flat\b|bumpy|lumpy|fuzzy|fluffy|furry|hairy|prickly|thorny|slippery|sticky|gooey|slimy|crisp\b|crunchy|brittle|fragile|delicate|sturdy|tough\b.*material|rigid|flexible|elastic|rubbery|spongy|cushion|padded|coarse\b|fine\b.*texture|grainy|sandy\b.*texture|silky|velvety|feathery|downy|woolly|glossy|matte|polished|rusty|corroded|weathered|worn\b.*surface|tattered|ragged|frayed|wrinkled|creased|crumpled/i],
  ['water', /\bwater\b|wet\b|dry\b.*water|liquid\b|fluid\b|drip\b|drop\b.*water|splash\b|spray\b.*water|stream\b|pour\b.*water|flow\b.*water|flood\b|drown\b|swim\b.*water|float\b.*water|sink\b.*water|dive\b.*water|wade\b|paddle\b.*water|sail\b|navigate|steer\b.*boat|anchor\b|dock\b.*boat|harbor\b|marina|pier\b.*water|wharf\b.*water|canal\b.*water|dam\b.*water|reservoir|well\b.*water|fountain\b.*water|hydrant|pipe\b.*water|faucet\b|tap\b.*water|drain\b|sewer|irrigation|aqueduct\b.*water|cistern|aquatic|marine|maritime|nautical|naval|seafaring|hydro|hydraulic|aquifer|watershed|estuary\b.*water|fjord|strait|channel\b.*water|gulf\b|archipelago/i],
];

var results = {};
var unmatched = [];
themes.forEach(function(t) { results[t[0]] = []; });

words.forEach(function(w) {
  var matched = false;
  var combined = (w.word + ' ' + w.def).toLowerCase();
  for (var k = 0; k < themes.length; k++) {
    if (themes[k][1].test(combined)) {
      results[themes[k][0]].push(w.word);
      matched = true;
      break;
    }
  }
  if (!matched) unmatched.push(w.word + ' [' + w.pos + ']: ' + w.def.substring(0, 70));
});

console.log('\n=== Category sizes (first-match) ===');
var sortedKeys = Object.keys(results).sort(function(a,b) { return results[b].length - results[a].length; });
var totalMatched = 0;
sortedKeys.forEach(function(c) {
  totalMatched += results[c].length;
  var flag = results[c].length < 20 ? ' << THIN' : '';
  console.log('  ' + c + ': ' + results[c].length + flag);
});
console.log('\n  MATCHED: ' + totalMatched + '/' + words.length);
console.log('  UNMATCHED: ' + unmatched.length);

console.log('\nUnmatched words (' + unmatched.length + '):');
unmatched.forEach(function(u) { console.log('  ' + u); });
