// Batch 1: Mixed etymology competition words (difficulty 9-10)
const words = [
    {
        word: 'anaphylaxis',
        definition: 'A severe, potentially life-threatening allergic reaction.',
        exampleSentence: 'The doctor treated the patient for anaphylaxis after a bee sting.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'an-uh-fih-LAK-sis',
        etymology: 'Greek: ana (against) + phylaxis (protection)',
        distractors: ['anaphilaxis', 'anaphylaxes', 'anaphylacsis'],
        theme: 'health',
    },
    {
        word: 'apotheosis',
        definition: 'The highest point of achievement or the perfect example of something.',
        exampleSentence: "The symphony was considered the apotheosis of the composer's career.",
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'uh-poth-ee-OH-sis',
        etymology: 'Greek: apotheosis (deification), from apo (from) + theos (god)',
        distractors: ['apotheoses', 'apothiosis', 'apotheocis'],
        theme: 'academic',
    },
    {
        word: 'catharsis',
        definition: 'The process of releasing strong emotions, leading to relief.',
        exampleSentence: 'Writing in her journal provided a much-needed catharsis.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'kuh-THAR-sis',
        etymology: 'Greek: katharsis (purification), from kathairein (to cleanse)',
        distractors: ['catharsus', 'catharces', 'catharcis'],
        theme: 'mind',
    },
    {
        word: 'chiropodist',
        definition: 'A person who treats ailments of the feet.',
        exampleSentence: 'The chiropodist recommended new orthotics for the runner.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'ky-ROP-uh-dist',
        etymology: 'Greek: cheir (hand) + pous (foot)',
        distractors: ['chiropodest', 'chiropidist', 'chirapodist'],
        theme: 'health',
    },
    {
        word: 'diastole',
        definition: 'The phase of the heartbeat when the heart muscle relaxes and fills with blood.',
        exampleSentence: 'During diastole, blood flows into the ventricles of the heart.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'dy-AS-tuh-lee',
        etymology: 'Greek: diastole (dilation), from dia (apart) + stellein (to send)',
        distractors: ['diastoly', 'diastolae', 'diastolle'],
        theme: 'body',
    },
    {
        word: 'dyspepsia',
        definition: 'Indigestion or difficulty digesting food.',
        exampleSentence: 'Eating too quickly can cause dyspepsia.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'dis-PEP-see-uh',
        etymology: 'Greek: dyspepsia (difficulty of digestion), from dys (bad) + pepsis (digestion)',
        distractors: ['dispepsia', 'dyspepcia', 'dyspepsha'],
        theme: 'health',
    },
    {
        word: 'ecumenical',
        definition: 'Promoting unity among different Christian churches or religions.',
        exampleSentence: 'The ecumenical council brought together leaders from many faiths.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'ek-yoo-MEN-ih-kul',
        etymology: 'Greek: oikoumenikos (of the inhabited world), from oikos (house)',
        distractors: ['ecuminical', 'ecummenical', 'ecumanical'],
        theme: 'society',
    },
    {
        word: 'ephemeron',
        definition: 'Something that lasts for a very short time.',
        exampleSentence: "The mayfly is nature's most famous ephemeron, living only a day.",
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'eh-FEM-er-on',
        etymology: 'Greek: ephemeron (lasting only a day), from epi (on) + hemera (day)',
        distractors: ['ephemaron', 'ephemiran', 'ephemeran'],
        theme: 'time',
    },
    {
        word: 'epistaxis',
        definition: 'Bleeding from the nose; a nosebleed.',
        exampleSentence: 'The dry winter air caused frequent epistaxis among the students.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'ep-ih-STAK-sis',
        etymology: 'Greek: epistazein (to drip upon), from epi (upon) + stazein (to drip)',
        distractors: ['epistaxes', 'epistaxsis', 'epistaxsis'],
        theme: 'health',
    },
    {
        word: 'eudaemonia',
        definition: 'A state of happiness and well-being; human flourishing.',
        exampleSentence: 'Aristotle believed eudaemonia was the highest human good.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'yoo-dee-MOH-nee-uh',
        etymology: 'Greek: eudaimonia (happiness), from eu (good) + daimon (spirit)',
        distractors: ['eudaimonia', 'eudemonia', 'eudaemona'],
        theme: 'mind',
    },
    {
        word: 'hagiography',
        definition: 'A biography that idealizes or idolizes its subject.',
        exampleSentence: 'The book was dismissed as hagiography rather than serious history.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'hag-ee-OG-ruh-fee',
        etymology: 'Greek: hagios (holy) + graphein (to write)',
        distractors: ['hagiografy', 'hagiographi', 'hageiography'],
        theme: 'language',
    },
    {
        word: 'hegemony',
        definition: 'Leadership or dominance, especially of one country over others.',
        exampleSentence: 'The empire maintained its hegemony over the region for centuries.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'heh-JEM-uh-nee',
        etymology: 'Greek: hegemonia (leadership), from hegemon (leader)',
        distractors: ['hegemoney', 'hegomony', 'hegeminy'],
        theme: 'society',
    },
    {
        word: 'heterodox',
        definition: 'Not conforming to accepted or orthodox standards or beliefs.',
        exampleSentence: 'His heterodox views on economics were controversial among his peers.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'HET-er-uh-doks',
        etymology: 'Greek: heterodoxos (of another opinion), from heteros (other) + doxa (opinion)',
        distractors: ['heterodocks', 'heteradox', 'hetrodox'],
        theme: 'mind',
    },
    {
        word: 'homoeopathy',
        definition: 'A system of alternative medicine based on treating like with like.',
        exampleSentence: 'She explored homoeopathy as a complementary approach to her treatment.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'hoh-mee-OP-uh-thee',
        etymology: 'Greek: homoios (like) + pathos (suffering)',
        distractors: ['homoepathy', 'homoeopathey', 'homeopothy'],
        theme: 'health',
    },
    {
        word: 'ichthyology',
        definition: 'The branch of zoology dealing with fish.',
        exampleSentence: 'Her passion for ichthyology led her to study coral reef ecosystems.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'ik-thee-OL-uh-jee',
        etymology: 'Greek: ichthys (fish) + logos (study)',
        distractors: ['icthyology', 'ichthiology', 'ichthyollogy'],
        theme: 'academic',
    },
    {
        word: 'labyrinthine',
        definition: 'Like a labyrinth; irregular and twisting.',
        exampleSentence: 'The labyrinthine corridors of the old castle confused every visitor.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'lab-uh-RIN-theen',
        etymology: 'Greek: labyrinthos (maze, large building with intricate passages)',
        distractors: ['labyrinthene', 'labyrinthiene', 'labrinthine'],
        theme: 'nature',
    },
    {
        word: 'lycanthropy',
        definition: 'The mythical transformation of a person into a wolf.',
        exampleSentence: 'Tales of lycanthropy have appeared in folklore across many cultures.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'ly-KAN-thruh-pee',
        etymology: 'Greek: lykanthropos (wolf-man), from lykos (wolf) + anthropos (human)',
        distractors: ['lycanthrapy', 'licanthropy', 'lycanthropi'],
        theme: 'nature',
    },
    {
        word: 'mnemonic',
        definition: 'A device or technique used to aid memory.',
        exampleSentence: 'ROY G BIV is a mnemonic for remembering the colors of the rainbow.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'neh-MON-ik',
        etymology: 'Greek: mnemonikos (of memory), from mnemon (mindful)',
        distractors: ['nemonic', 'mneumonic', 'mnemonik'],
        theme: 'mind',
    },
    {
        word: 'mycelium',
        definition: 'The vegetative part of a fungus, consisting of a network of fine filaments.',
        exampleSentence: 'The mycelium spread beneath the forest floor, connecting the trees.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'my-SEE-lee-um',
        etymology: 'Greek: mykes (fungus) + helos (nail, stud)',
        distractors: ['myceleum', 'mycellium', 'myscelium'],
        theme: 'plants',
    },
    {
        word: 'necropolis',
        definition: 'A large ancient cemetery with elaborate tombs.',
        exampleSentence: 'Archaeologists discovered a vast necropolis beneath the city.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'neh-KROP-uh-lis',
        etymology: 'Greek: nekropolis (city of the dead), from nekros (dead) + polis (city)',
        distractors: ['necropoles', 'necrapolis', 'necropilis'],
        theme: 'earth',
    },
    {
        word: 'oligarchy',
        definition: 'A form of government in which power is held by a small group of people.',
        exampleSentence: 'The country was effectively an oligarchy controlled by wealthy families.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'OL-ih-gar-kee',
        etymology: 'Greek: oligarkhia (government by the few), from oligos (few) + arkhein (to rule)',
        distractors: ['oligarky', 'oligarchi', 'olagarchy'],
        theme: 'society',
    },
    {
        word: 'ophthalmology',
        definition: 'The branch of medicine concerned with the study and treatment of eye disorders.',
        exampleSentence: 'She specialized in ophthalmology and performed cataract surgeries.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'of-thal-MOL-uh-jee',
        etymology: 'Greek: ophthalmos (eye) + logos (study)',
        distractors: ['opthalmology', 'ophthamology', 'opthalmollogy'],
        theme: 'health',
    },
    {
        word: 'palindrome',
        definition: 'A word, phrase, or sequence that reads the same backward as forward.',
        exampleSentence: 'The word "racecar" is a famous palindrome.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'PAL-in-drohm',
        etymology: 'Greek: palindromos (running back again), from palin (again) + dromos (running)',
        distractors: ['pallindrome', 'palindrohm', 'palendrome'],
        theme: 'language',
    },
    {
        word: 'panegyric',
        definition: 'A public speech or written text praising someone or something highly.',
        exampleSentence: 'The graduation speaker delivered a panegyric to the retiring dean.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'pan-uh-JIR-ik',
        etymology: 'Greek: panegyrikos (of a public assembly), from pan (all) + agyris (assembly)',
        distractors: ['panagyric', 'panegyrick', 'panegyrik'],
        theme: 'communication',
    },
    {
        word: 'paroxysm',
        definition: 'A sudden attack or outburst of a particular emotion or activity.',
        exampleSentence: 'A paroxysm of coughing interrupted his speech.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'PAR-ok-siz-um',
        etymology: 'Greek: paroxysmos (irritation), from para (beyond) + oxynein (to sharpen)',
        distractors: ['paroxism', 'paroxyzm', 'paroxsym'],
        theme: 'health',
    },
    {
        word: 'peripatetic',
        definition: 'Traveling from place to place, especially working in various locations.',
        exampleSentence: 'The peripatetic musician performed in a different city every night.',
        partOfSpeech: 'adjective',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'per-ih-puh-TET-ik',
        etymology: 'Greek: peripatetikos (walking about), from peripatein (to walk around)',
        distractors: ['peripatatic', 'peripetetic', 'peripatetik'],
        theme: 'travel',
    },
    {
        word: 'pharmacopoeia',
        definition: 'An official publication listing medicinal drugs with their effects and directions for use.',
        exampleSentence: 'The pharmacopoeia was updated to include new drug formulations.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'far-muh-kuh-PEE-uh',
        etymology: 'Greek: pharmakopoiia (drug-making), from pharmakon (drug) + poiein (to make)',
        distractors: ['pharmacopeia', 'pharmacopea', 'pharmacopoea'],
        theme: 'health',
    },
    {
        word: 'plethora',
        definition: 'An excessive amount of something.',
        exampleSentence: 'The garden offered a plethora of colorful flowers in spring.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'PLETH-er-uh',
        etymology: 'Greek: plethora (fullness), from plethein (to be full)',
        distractors: ['plethera', 'plethorah', 'plethura'],
        theme: 'quantity',
    },
    {
        word: 'pneumatic',
        definition: 'Operated by air or gas under pressure.',
        exampleSentence: 'The pneumatic drill made short work of breaking through the concrete.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'noo-MAT-ik',
        etymology: 'Greek: pneumatikos (of wind or breath), from pneuma (wind, breath)',
        distractors: ['neumatic', 'pnuematic', 'pneumatik'],
        theme: 'everyday',
    },
    {
        word: 'propaedeutic',
        definition: 'An introduction to or preparatory course for a subject.',
        exampleSentence: 'The propaedeutic course prepared students for advanced philosophy.',
        partOfSpeech: 'adjective',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'proh-peh-DOO-tik',
        etymology: 'Greek: propaideuein (to teach beforehand), from pro (before) + paideuein (to teach)',
        distractors: ['propedeutic', 'propaduetic', 'propeadeutic'],
        theme: 'academic',
    },
    {
        word: 'prosthesis',
        definition: 'An artificial body part, such as a limb or tooth.',
        exampleSentence: 'The advanced prosthesis allowed the athlete to compete again.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'PROS-thee-sis',
        etymology: 'Greek: prosthesis (addition), from pros (to) + tithenai (to place)',
        distractors: ['prosthisis', 'prosthecis', 'prosthasis'],
        theme: 'body',
    },
    {
        word: 'pseudepigrapha',
        definition: 'Writings falsely attributed to notable authors.',
        exampleSentence: 'The pseudepigrapha were excluded from the biblical canon.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'soo-deh-PIG-ruh-fuh',
        etymology: 'Greek: pseudepigraphos (falsely inscribed), from pseudos (false) + epigraphein (to inscribe)',
        distractors: ['pseudopigrapha', 'pseudepegrapha', 'psudepigrapha'],
        theme: 'language',
    },
    {
        word: 'ptarmigan',
        definition: 'A northern grouse with feathered feet and plumage that changes color seasonally.',
        exampleSentence: 'The ptarmigan turned white in winter to blend with the snow.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'irregular',
        pronunciation: 'TAR-mih-gun',
        etymology: "Scottish Gaelic: tarmachan; the silent P was added by false association with Greek pteron (wing)",
        distractors: ['tarmigan', 'ptarmagen', 'ptarmigon'],
        theme: 'animals',
    },
    {
        word: 'pterodactyl',
        definition: 'An extinct flying reptile with a long crest and no teeth.',
        exampleSentence: 'The museum displayed a fossil of a pterodactyl with a ten-foot wingspan.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'ter-uh-DAK-til',
        etymology: 'Greek: pteron (wing) + daktylos (finger)',
        distractors: ['teradactyl', 'pteradactyl', 'pterodactil'],
        theme: 'animals',
    },
    {
        word: 'rheumatism',
        definition: 'A condition marked by inflammation and pain in the joints or muscles.',
        exampleSentence: 'Cold weather worsened her rheumatism.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'ROO-muh-tiz-um',
        etymology: 'Greek: rheuma (stream, flow), from rhein (to flow)',
        distractors: ['rhumatism', 'rheumatizm', 'rhuematism'],
        theme: 'health',
    },
    {
        word: 'sarcophagus',
        definition: 'A stone coffin, typically adorned with sculpture or inscriptions.',
        exampleSentence: 'The ancient sarcophagus was discovered in an Egyptian tomb.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'sar-KOF-uh-gus',
        etymology: 'Greek: sarkophagos (flesh-eating), from sarx (flesh) + phagein (to eat)',
        distractors: ['sarcophogus', 'sacrophagus', 'sarcophagous'],
        theme: 'earth',
    },
    {
        word: 'schizophrenia',
        definition: 'A chronic mental disorder characterized by distorted thinking and hallucinations.',
        exampleSentence: 'Advances in treatment have greatly improved outcomes for people with schizophrenia.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'skit-soh-FREN-ee-uh',
        etymology: 'Greek: skhizein (to split) + phren (mind)',
        distractors: ['schizofrenia', 'schitzophrenia', 'skizophrenia'],
        theme: 'health',
    },
    {
        word: 'stochastic',
        definition: 'Having a random probability distribution that can be analyzed statistically.',
        exampleSentence: 'The stochastic model predicted the likely outcomes of the experiment.',
        partOfSpeech: 'adjective',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'stoh-KAS-tik',
        etymology: 'Greek: stokhastikos (able to guess), from stokhazesthai (to aim at)',
        distractors: ['stocastic', 'stochastik', 'stokastic'],
        theme: 'academic',
    },
    {
        word: 'synecdoche',
        definition: 'A figure of speech in which a part represents the whole or vice versa.',
        exampleSentence: 'Saying "all hands on deck" is a synecdoche where hands represent sailors.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'sih-NEK-duh-kee',
        etymology: 'Greek: synekdokhe (simultaneous understanding), from syn (with) + ekdekhesthai (to receive)',
        distractors: ['synecdochy', 'synecdoce', 'sinecdoche'],
        theme: 'language',
    },
    {
        word: 'tachycardia',
        definition: 'An abnormally rapid heart rate.',
        exampleSentence: 'The patient was admitted to the hospital with tachycardia after the accident.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'tak-ih-KAR-dee-uh',
        etymology: 'Greek: takhys (swift) + kardia (heart)',
        distractors: ['tackycardia', 'tachicardea', 'tachycardea'],
        theme: 'health',
    },
    {
        word: 'theocracy',
        definition: 'A system of government in which priests rule in the name of God.',
        exampleSentence: 'Ancient Egypt was governed as a theocracy with the pharaoh as divine ruler.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'thee-OK-ruh-see',
        etymology: 'Greek: theokratia (rule of God), from theos (god) + kratos (power)',
        distractors: ['theocrecy', 'theocrasy', 'theocrascy'],
        theme: 'society',
    },
    {
        word: 'topography',
        definition: 'The arrangement of the physical features of an area of land.',
        exampleSentence: 'The topography of the region included mountains, valleys, and rivers.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'tuh-POG-ruh-fee',
        etymology: 'Greek: topographia (description of a place), from topos (place) + graphein (to write)',
        distractors: ['topografy', 'topographi', 'topograffy'],
        theme: 'earth',
    },
    {
        word: 'xenophobia',
        definition: 'Intense or irrational fear or dislike of people from other countries.',
        exampleSentence: 'The organization worked to combat xenophobia through cultural exchange programs.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'greek-roots',
        pronunciation: 'zen-uh-FOH-bee-uh',
        etymology: 'Greek: xenos (stranger, foreigner) + phobos (fear)',
        distractors: ['xenephobia', 'xenophobea', 'zenophobia'],
        theme: 'society',
    },
    {
        word: 'zymurgy',
        definition: 'The branch of chemistry dealing with fermentation in brewing.',
        exampleSentence: 'He studied zymurgy to perfect his craft beer recipes.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'greek-roots',
        pronunciation: 'ZY-mur-jee',
        etymology: 'Greek: zyme (leaven) + ergon (work)',
        distractors: ['zimurgy', 'zymergy', 'zymurgi'],
        theme: 'academic',
    },
    {
        word: 'antediluvian',
        definition: 'Extremely old-fashioned or belonging to a time before the biblical flood.',
        exampleSentence: 'His antediluvian views on technology made him resistant to using email.',
        partOfSpeech: 'adjective',
        difficulty: 10,
        pattern: 'latin-roots',
        pronunciation: 'an-tee-dih-LOO-vee-un',
        etymology: 'Latin: ante (before) + diluvium (flood)',
        distractors: ['antediluvean', 'antideluvian', 'antidiluvian'],
        theme: 'time',
    },
    {
        word: 'bellicose',
        definition: 'Demonstrating aggression and willingness to fight.',
        exampleSentence: 'The bellicose leader threatened war against neighboring countries.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'BEL-ih-kohs',
        etymology: 'Latin: bellicosus (warlike), from bellum (war)',
        distractors: ['bellicoss', 'belicose', 'bellacose'],
        theme: 'character',
    },
    {
        word: 'circumlocution',
        definition: 'The use of many words where fewer would do, especially to avoid saying something directly.',
        exampleSentence: "The politician's circumlocution frustrated reporters seeking straight answers.",
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'latin-roots',
        pronunciation: 'sur-kum-loh-KYOO-shun',
        etymology: 'Latin: circumlocutio (speaking around), from circum (around) + loqui (to speak)',
        distractors: ['circumlocation', 'circumloqution', 'circumlocusion'],
        theme: 'communication',
    },
    {
        word: 'conflagration',
        definition: 'An extensive and destructive fire.',
        exampleSentence: 'The conflagration destroyed an entire block of buildings overnight.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'kon-fluh-GRAY-shun',
        etymology: 'Latin: conflagratio (burning up), from con (together) + flagrare (to blaze)',
        distractors: ['conflageration', 'conflagrasion', 'conflaguration'],
        theme: 'nature',
    },
    {
        word: 'contiguous',
        definition: 'Sharing a common border; touching.',
        exampleSentence: 'The two farms were contiguous, separated only by a fence.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'kun-TIG-yoo-us',
        etymology: 'Latin: contiguus (touching), from contingere (to touch on all sides)',
        distractors: ['contigueous', 'contigous', 'contigious'],
        theme: 'earth',
    },
    {
        word: 'defenestration',
        definition: 'The act of throwing someone or something out of a window.',
        exampleSentence: 'The Defenestration of Prague in 1618 helped trigger the Thirty Years War.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'latin-roots',
        pronunciation: 'dee-fen-eh-STRAY-shun',
        etymology: 'Latin: de (down from) + fenestra (window)',
        distractors: ['defenastration', 'defenestrasion', 'defenistration'],
        theme: 'actions',
    },
    {
        word: 'ebullient',
        definition: 'Cheerful and full of energy; enthusiastic.',
        exampleSentence: 'Her ebullient personality made every party more enjoyable.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'ih-BUL-yunt',
        etymology: 'Latin: ebulliens (boiling over), from ex (out) + bullire (to boil)',
        distractors: ['ebulliant', 'ebulient', 'ebullent'],
        theme: 'feelings',
    },
    {
        word: 'effervescent',
        definition: 'Giving off bubbles; vivacious and enthusiastic.',
        exampleSentence: 'The effervescent tablet dissolved quickly in the glass of water.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'ef-er-VES-unt',
        etymology: 'Latin: effervescere (to boil up), from ex (out) + fervescere (to begin to boil)',
        distractors: ['effervesent', 'efervescent', 'effervecent'],
        theme: 'sensory',
    },
    {
        word: 'equanimity',
        definition: 'Mental calmness and composure, especially in a difficult situation.',
        exampleSentence: 'She faced the crisis with remarkable equanimity.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'ee-kwuh-NIM-ih-tee',
        etymology: 'Latin: aequanimitas (evenness of mind), from aequus (equal) + animus (mind)',
        distractors: ['equanimmity', 'equinimity', 'equanomity'],
        theme: 'mind',
    },
    {
        word: 'grandiloquent',
        definition: 'Pompous or extravagant in language, style, or manner.',
        exampleSentence: "The senator's grandiloquent speech was full of flowery but empty rhetoric.",
        partOfSpeech: 'adjective',
        difficulty: 10,
        pattern: 'latin-roots',
        pronunciation: 'gran-DIL-oh-kwunt',
        etymology: 'Latin: grandiloquus (using lofty speech), from grandis (great) + loqui (to speak)',
        distractors: ['grandiloquant', 'grandilaquent', 'grandiloquint'],
        theme: 'communication',
    },
    {
        word: 'impecunious',
        definition: 'Having little or no money.',
        exampleSentence: 'The impecunious student relied on scholarships to attend university.',
        partOfSpeech: 'adjective',
        difficulty: 10,
        pattern: 'latin-roots',
        pronunciation: 'im-peh-KYOO-nee-us',
        etymology: 'Latin: impecuniosus (having no money), from in (not) + pecunia (money)',
        distractors: ['impecuneous', 'impecunius', 'impecuneus'],
        theme: 'money',
    },
    {
        word: 'indefatigable',
        definition: 'Persisting tirelessly; incapable of being fatigued.',
        exampleSentence: 'The indefatigable volunteer worked sixteen-hour days at the shelter.',
        partOfSpeech: 'adjective',
        difficulty: 10,
        pattern: 'latin-roots',
        pronunciation: 'in-dih-FAT-ih-guh-bul',
        etymology: 'Latin: indefatigabilis (untiring), from in (not) + defatigare (to tire out)',
        distractors: ['indefatigible', 'indefatiable', 'indifatigable'],
        theme: 'character',
    },
    {
        word: 'magnanimous',
        definition: 'Very generous or forgiving, especially toward a rival or enemy.',
        exampleSentence: 'In a magnanimous gesture, the victor pardoned all prisoners of war.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'mag-NAN-ih-mus',
        etymology: 'Latin: magnanimus (great-souled), from magnus (great) + animus (soul)',
        distractors: ['magnanimeous', 'magnanamous', 'magnannimous'],
        theme: 'character',
    },
    {
        word: 'mendacious',
        definition: 'Not telling the truth; lying.',
        exampleSentence: 'The mendacious witness was charged with perjury.',
        partOfSpeech: 'adjective',
        difficulty: 10,
        pattern: 'latin-roots',
        pronunciation: 'men-DAY-shus',
        etymology: 'Latin: mendax (lying, deceitful)',
        distractors: ['mendaceus', 'mendatious', 'mendacous'],
        theme: 'character',
    },
    {
        word: 'obsequious',
        definition: 'Excessively compliant or deferential.',
        exampleSentence: 'The obsequious assistant agreed with everything the boss said.',
        partOfSpeech: 'adjective',
        difficulty: 10,
        pattern: 'latin-roots',
        pronunciation: 'ob-SEE-kwee-us',
        etymology: 'Latin: obsequiosus (compliant), from obsequi (to follow)',
        distractors: ['obsequeus', 'obsequous', 'obsiquious'],
        theme: 'character',
    },
    {
        word: 'penultimate',
        definition: 'Second to last in a series or sequence.',
        exampleSentence: 'The penultimate chapter of the book contained the most dramatic twist.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'peh-NUL-tih-mut',
        etymology: 'Latin: paenultimus, from paene (almost) + ultimus (last)',
        distractors: ['penultimite', 'penultamate', 'penultimat'],
        theme: 'quantity',
    },
    {
        word: 'perspicacious',
        definition: 'Having a ready insight into and understanding of things.',
        exampleSentence: 'The perspicacious detective noticed a clue everyone else had missed.',
        partOfSpeech: 'adjective',
        difficulty: 10,
        pattern: 'latin-roots',
        pronunciation: 'per-spih-KAY-shus',
        etymology: 'Latin: perspicax (having keen sight), from perspicere (to look through)',
        distractors: ['perspicaceous', 'perspicatious', 'perspicasious'],
        theme: 'mind',
    },
    {
        word: 'pusillanimous',
        definition: 'Showing a lack of courage or determination; timid.',
        exampleSentence: 'His pusillanimous refusal to speak up cost them the opportunity.',
        partOfSpeech: 'adjective',
        difficulty: 10,
        pattern: 'latin-roots',
        pronunciation: 'pyoo-sih-LAN-ih-mus',
        etymology: 'Latin: pusillanimis (faint-hearted), from pusillus (very small) + animus (spirit)',
        distractors: ['pusilanimous', 'pusillanimeous', 'pusillannimous'],
        theme: 'character',
    },
    {
        word: 'recalcitrant',
        definition: 'Stubbornly resistant to authority or control.',
        exampleSentence: 'The recalcitrant student refused to follow the dress code.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'rih-KAL-sih-trunt',
        etymology: 'Latin: recalcitrare (to kick back), from re (back) + calcitrare (to kick)',
        distractors: ['recalcitrent', 'recalcetrant', 'recalcitrent'],
        theme: 'character',
    },
    {
        word: 'sanguine',
        definition: 'Optimistic or positive, especially in a difficult situation.',
        exampleSentence: 'Despite the setbacks, she remained sanguine about the project.',
        partOfSpeech: 'adjective',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'SANG-gwin',
        etymology: 'Latin: sanguineus (of blood), from sanguis (blood)',
        distractors: ['sanguin', 'sanguene', 'sangueen'],
        theme: 'feelings',
    },
    {
        word: 'soliloquy',
        definition: "An act of speaking one's thoughts aloud when alone, especially in a play.",
        exampleSentence: 'Hamlet\'s "To be or not to be" is the most famous soliloquy in theater.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'latin-roots',
        pronunciation: 'suh-LIL-oh-kwee',
        etymology: 'Latin: soliloquium (talking to oneself), from solus (alone) + loqui (to speak)',
        distractors: ['solliloquy', 'soliloquey', 'soliliquy'],
        theme: 'art',
    },
    {
        word: 'soporific',
        definition: 'Tending to induce drowsiness or sleep.',
        exampleSentence: 'The soporific lecture put half the audience to sleep.',
        partOfSpeech: 'adjective',
        difficulty: 10,
        pattern: 'latin-roots',
        pronunciation: 'sop-uh-RIF-ik',
        etymology: 'Latin: sopor (deep sleep) + facere (to make)',
        distractors: ['soparific', 'soporefic', 'soporifik'],
        theme: 'health',
    },
    {
        word: 'supernumerary',
        definition: 'Present in excess of the normal or required number.',
        exampleSentence: 'The supernumerary cast members served as extras in the crowd scenes.',
        partOfSpeech: 'adjective',
        difficulty: 10,
        pattern: 'latin-roots',
        pronunciation: 'soo-per-NOO-muh-rer-ee',
        etymology: 'Latin: supernumerarius (excess), from super (above) + numerus (number)',
        distractors: ['supernumary', 'supernumerery', 'supernumerairy'],
        theme: 'quantity',
    },
    {
        word: 'tergiversation',
        definition: 'The act of being evasive or ambiguous; equivocation.',
        exampleSentence: "The witness's tergiversation frustrated the prosecution.",
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'latin-roots',
        pronunciation: 'tur-jiv-er-SAY-shun',
        etymology: "Latin: tergiversari (to turn one's back), from tergum (back) + versare (to turn)",
        distractors: ['tergiversasion', 'tergaversation', 'tergiverstion'],
        theme: 'communication',
    },
    {
        word: 'vicissitude',
        definition: 'A change of circumstances or fortune, typically one that is unwelcome.',
        exampleSentence: 'The vicissitudes of life taught her resilience.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'latin-roots',
        pronunciation: 'vih-SIS-ih-tood',
        etymology: 'Latin: vicissitudo (change, alternation), from vicis (a turn, change)',
        distractors: ['vicissetude', 'vicissatude', 'vicissitood'],
        theme: 'time',
    },
    {
        word: 'clairvoyance',
        definition: 'The supposed ability to perceive events beyond normal sensory contact.',
        exampleSentence: 'She claimed clairvoyance allowed her to see into the future.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'french-origin',
        pronunciation: 'klair-VOY-uns',
        etymology: 'French: clairvoyance (clear-seeing), from clair (clear) + voir (to see)',
        distractors: ['clairvoyence', 'clairvoiance', 'clarevoyance'],
        theme: 'mind',
    },
    {
        word: 'connoisseur',
        definition: 'An expert judge in matters of fine art or taste.',
        exampleSentence: 'As a connoisseur of wine, she could identify the vintage by taste alone.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'french-origin',
        pronunciation: 'kon-uh-SUR',
        etymology: 'French: connaisseur (one who knows), from connaitre (to know)',
        distractors: ['connoiseur', 'connosieur', 'conoisseur'],
        theme: 'people',
    },
    {
        word: 'denouement',
        definition: 'The final outcome or resolution of a plot or situation.',
        exampleSentence: 'The denouement of the mystery novel surprised every reader.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'french-origin',
        pronunciation: 'day-noo-MAH',
        etymology: 'French: denouement (untying), from denouer (to untie)',
        distractors: ['denouament', 'denoument', 'denouemant'],
        theme: 'art',
    },
    {
        word: 'entrepreneur',
        definition: 'A person who starts and runs a business, taking on financial risk.',
        exampleSentence: 'The young entrepreneur launched her startup from a garage.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'french-origin',
        pronunciation: 'on-truh-pruh-NUR',
        etymology: 'French: entrepreneur (one who undertakes), from entreprendre (to undertake)',
        distractors: ['entrepeneur', 'entreprener', 'entreprenuer'],
        theme: 'people',
    },
    {
        word: 'nonchalance',
        definition: 'A casual lack of concern; indifference.',
        exampleSentence: 'She accepted the award with an air of nonchalance.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'french-origin',
        pronunciation: 'non-shuh-LAHNS',
        etymology: 'French: nonchalance (carelessness), from nonchaloir (to disregard)',
        distractors: ['nonchalanse', 'nonchilance', 'nonchalence'],
        theme: 'feelings',
    },
    {
        word: 'reconnaissance',
        definition: 'Military observation of an area to locate an enemy or determine strategic features.',
        exampleSentence: 'The drone was sent on a reconnaissance mission over hostile territory.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'french-origin',
        pronunciation: 'reh-KON-ih-sunss',
        etymology: 'French: reconnaissance (recognition), from reconnaitre (to recognize)',
        distractors: ['reconaissance', 'reconnaisance', 'reconnaisence'],
        theme: 'society',
    },
    {
        word: 'rendezvous',
        definition: 'A meeting at an agreed time and place.',
        exampleSentence: 'The spies arranged a secret rendezvous at midnight.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'french-origin',
        pronunciation: 'RON-day-voo',
        etymology: 'French: rendez-vous (present yourselves), from rendre (to present) + vous (yourselves)',
        distractors: ['rendevous', 'rendezvou', 'rondayvoo'],
        theme: 'actions',
    },
    {
        word: 'silhouette',
        definition: 'The dark shadow or outline of someone or something visible against a lighter background.',
        exampleSentence: 'The silhouette of the mountains was visible against the sunset.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'french-origin',
        pronunciation: 'sil-oo-ET',
        etymology: 'French: named after Etienne de Silhouette, French finance minister (1759)',
        distractors: ['silouette', 'silhouete', 'silhuette'],
        theme: 'art',
    },
    {
        word: 'souvenir',
        definition: 'A thing that is kept as a reminder of a person, place, or event.',
        exampleSentence: 'She bought a small souvenir from every country she visited.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'french-origin',
        pronunciation: 'soo-vuh-NEER',
        etymology: 'French: souvenir (to remember), from Latin subvenire (to come to mind)',
        distractors: ['souvanir', 'souvenier', 'souviner'],
        theme: 'travel',
    },
    {
        word: 'angst',
        definition: 'A feeling of deep anxiety or dread about the human condition.',
        exampleSentence: 'The existentialist novel explored themes of angst and alienation.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'irregular',
        pronunciation: 'AHNGST',
        etymology: 'German: Angst (fear, anxiety), from Old High German angust (distress)',
        distractors: ['ankst', 'anxt', 'angzt'],
        theme: 'feelings',
    },
    {
        word: 'doppelganger',
        definition: 'An apparition or double of a living person.',
        exampleSentence: 'She was startled to meet her doppelganger at the conference.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'irregular',
        pronunciation: 'DOP-ul-gang-er',
        etymology: 'German: Doppelganger (double-goer), from doppel (double) + Ganger (goer)',
        distractors: ['doppleganger', 'doppelgenger', 'dopelganger'],
        theme: 'people',
    },
    {
        word: 'leitmotif',
        definition: "A recurring theme in music, literature, or a person's life.",
        exampleSentence: 'The leitmotif of heroism runs throughout the opera.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'irregular',
        pronunciation: 'LYT-moh-teef',
        etymology: 'German: Leitmotiv (leading motif), from leiten (to lead) + Motiv (motif)',
        distractors: ['leitmotief', 'litmotif', 'leitmotiv'],
        theme: 'art',
    },
    {
        word: 'wanderlust',
        definition: 'A strong desire to travel and explore the world.',
        exampleSentence: 'Her wanderlust drove her to visit thirty countries before age thirty.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'irregular',
        pronunciation: 'WON-der-lust',
        etymology: 'German: Wanderlust (desire to hike), from wandern (to hike) + Lust (desire)',
        distractors: ['wonderlust', 'wanderlast', 'wanderlurst'],
        theme: 'travel',
    },
    {
        word: 'zeitgeist',
        definition: 'The defining spirit or mood of a particular period of history.',
        exampleSentence: 'The zeitgeist of the 1960s was one of rebellion and social change.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'irregular',
        pronunciation: 'TSYT-gyst',
        etymology: 'German: Zeitgeist (spirit of the time), from Zeit (time) + Geist (spirit)',
        distractors: ['zeitgeest', 'zietgeist', 'zeitguist'],
        theme: 'society',
    },
    {
        word: 'aficionado',
        definition: 'A person who is very enthusiastic and knowledgeable about a subject.',
        exampleSentence: 'As an aficionado of jazz, he had an impressive record collection.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'irregular',
        pronunciation: 'uh-fish-ee-uh-NAH-doh',
        etymology: 'Spanish: aficionado (amateur, fan), from aficion (affection)',
        distractors: ['afficionado', 'aficianado', 'aficianodo'],
        theme: 'people',
    },
    {
        word: 'incommunicado',
        definition: 'Not able or allowed to communicate with others.',
        exampleSentence: 'The prisoner was held incommunicado for several weeks.',
        partOfSpeech: 'adverb',
        difficulty: 10,
        pattern: 'irregular',
        pronunciation: 'in-kuh-myoo-nih-KAH-doh',
        etymology: 'Spanish: incomunicado (cut off from communication)',
        distractors: ['incomunicado', 'incommunicato', 'incommuncado'],
        theme: 'actions',
    },
    {
        word: 'imbroglio',
        definition: 'An extremely confused, complicated, or embarrassing situation.',
        exampleSentence: 'The political imbroglio threatened to bring down the government.',
        partOfSpeech: 'noun',
        difficulty: 10,
        pattern: 'irregular',
        pronunciation: 'im-BROHL-yoh',
        etymology: 'Italian: imbroglio (confusion), from imbrogliare (to embroil)',
        distractors: ['imbrolio', 'imbrogleo', 'embrolio'],
        theme: 'society',
    },
    {
        word: 'virtuoso',
        definition: 'A person highly skilled in music or another artistic pursuit.',
        exampleSentence: 'The piano virtuoso captivated the audience with a flawless performance.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'irregular',
        pronunciation: 'vur-choo-OH-soh',
        etymology: 'Italian: virtuoso (skilled), from virtu (virtue, skill)',
        distractors: ['virtuosso', 'vertioso', 'virtouso'],
        theme: 'art',
    },
    {
        word: 'beleaguer',
        definition: 'To cause persistent difficulty or problems for someone.',
        exampleSentence: 'The beleaguered company faced lawsuits from multiple directions.',
        partOfSpeech: 'verb',
        difficulty: 9,
        pattern: 'irregular',
        pronunciation: 'bih-LEE-gur',
        etymology: 'Dutch: belegeren (to besiege), from be (around) + leger (camp)',
        distractors: ['beleager', 'beleguer', 'beleagure'],
        theme: 'actions',
    },
    {
        word: 'algorithm',
        definition: 'A process or set of rules to be followed in calculations or problem-solving.',
        exampleSentence: 'The search engine uses a complex algorithm to rank web pages.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'irregular',
        pronunciation: 'AL-guh-rith-um',
        etymology: 'Arabic: al-Khwarizmi, name of the 9th-century Persian mathematician',
        distractors: ['algorithem', 'algorythm', 'algorhithm'],
        theme: 'academic',
    },
    {
        word: 'almanac',
        definition: 'An annual publication containing a calendar and other useful information.',
        exampleSentence: 'The farmer consulted the almanac for planting dates.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'irregular',
        pronunciation: 'AWL-muh-nak',
        etymology: 'Arabic: al-manakh (the climate), through Medieval Latin almanach',
        distractors: ['almanak', 'almanack', 'almenac'],
        theme: 'academic',
    },
    {
        word: 'avatar',
        definition: 'A manifestation of a deity or an icon representing a person in virtual reality.',
        exampleSentence: 'She designed a colorful avatar for her online gaming profile.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'irregular',
        pronunciation: 'AV-uh-tar',
        etymology: 'Sanskrit: avatara (descent), from ava (down) + tarati (he crosses over)',
        distractors: ['avitar', 'avataar', 'avetar'],
        theme: 'academic',
    },
    {
        word: 'juggernaut',
        definition: 'A huge, powerful, and overwhelming force or institution.',
        exampleSentence: 'The tech company became a juggernaut in the industry.',
        partOfSpeech: 'noun',
        difficulty: 9,
        pattern: 'irregular',
        pronunciation: 'JUG-er-nawt',
        etymology: 'Hindi/Sanskrit: Jagannath (Lord of the World), a title of the Hindu god Krishna',
        distractors: ['juggernaught', 'jugernaut', 'juggernot'],
        theme: 'society',
    },
];

// Check for duplicates against existing words
const fs = require('fs');
const existing = new Set(fs.readFileSync('existing-words.txt', 'utf8').trim().split('\n'));
const dupes = [];
const clean = [];
const seen = new Set();
for (const w of words) {
    const lower = w.word.toLowerCase();
    if (existing.has(lower)) {
        dupes.push(lower);
    } else if (seen.has(lower)) {
        dupes.push(lower + ' (internal dupe)');
    } else {
        // Fix: check distractors don't contain correct spelling
        if (w.distractors) {
            const hasSelf = w.distractors.some(d => d.toLowerCase() === lower);
            if (hasSelf) {
                w.distractors = w.distractors.filter(d => d.toLowerCase() !== lower);
                w.distractors.push(lower.replace(/[aeiou]/, m => m === 'a' ? 'e' : 'a'));
            }
        }
        w.word = lower;
        clean.push(w);
        seen.add(lower);
    }
}

console.log('Total generated:', words.length);
console.log('Duplicates removed:', dupes.length, dupes);
console.log('Clean new words:', clean.length);

// Generate TypeScript entries
let ts = '\n    // ── Batch 1: Mixed Etymology Competition Words ────────────────────────\n';
for (const w of clean) {
    ts += `    {\n`;
    ts += `        word: '${w.word}',\n`;
    ts += `        definition: '${w.definition.replace(/'/g, "\\'")}',\n`;
    ts += `        exampleSentence: '${w.exampleSentence.replace(/'/g, "\\'")}',\n`;
    ts += `        partOfSpeech: '${w.partOfSpeech}',\n`;
    ts += `        difficulty: ${w.difficulty},\n`;
    ts += `        pattern: '${w.pattern}',\n`;
    ts += `        pronunciation: '${w.pronunciation}',\n`;
    ts += `        etymology: '${w.etymology.replace(/'/g, "\\'")}',\n`;
    ts += `        distractors: [${w.distractors.map(d => `'${d.replace(/'/g, "\\'")}'`).join(', ')}],\n`;
    ts += `        theme: '${w.theme}',\n`;
    ts += `    },\n`;
}

fs.writeFileSync('/tmp/batch1-words.ts', ts);
console.log('\nWritten', clean.length, 'word entries to /tmp/batch1-words.ts');

// Update existing-words.txt with new words
const updatedWords = [...existing, ...clean.map(w => w.word)].sort();
fs.writeFileSync('existing-words.txt', updatedWords.join('\n'));
console.log('Updated existing-words.txt with new words');
